### ISSUE TITLE
Pickaxe Of Vein Mining doesn't works with Silk Touch

### ISSUE THREAD

**Issue by Conquerski** [Slimefun/Slimefun4#2296]
## Description (REQUIRED)

When you use a silktouch pickaxe of vein mining, trying to dig diamond ores, it will drops you diamond but not the diamond ores. It can perfectlly works with fortune but not the silktouch. 

![Pickaxe of Vein Mining doesn't work well with silktouch_2](https://user-images.githubusercontent.com/29293636/92340836-5bb9b000-f0ee-11ea-9877-e6259d7d03ff.gif)

Plugin Version:
![Slimefun Version](https://user-images.githubusercontent.com/29293636/92340474-1648b300-f0ed-11ea-92ea-bb1f1521b041.png)

## Steps to reproduce the Issue (REQUIRED)

1. Give yourselve a Pickaxe of Vein Mining.
2. Enchant the pickaxe with Silktouch.
3. Dig some ores and you'll see.

## Expected behavior (REQUIRED)

Let Silktouch works well with Pickaxe of Vein Minning.

## Environment (REQUIRED)

 - Server Software (Spigot/Paper):Paper
 - Minecraft Version:1.16.2
 - Slimefun Version:vDev - 665
 - CS-CoreLib Version:vDev -79

**Comment by LinoxGH** [comment]
@Conquerski can you please try to reproduce this eith CS-CoreLib 90?

**Comment by Conquerski** [comment]
@LinoxGH I already updated to CS-CoreLib 90, still can't work with silktouch.
![dev90](https://user-images.githubusercontent.com/29293636/92363720-87578d00-f124-11ea-97c7-71f631ce9388.png)
![silktouch](https://user-images.githubusercontent.com/29293636/92363845-b66dfe80-f124-11ea-9f73-545f255970e0.png)
