### ISSUE TITLE
Allowing the Slimefun Guide to be placed on Lecterns

### ISSUE THREAD

**Issue by TheBusyBiscuit** [Slimefun/Slimefun4#2315]
This Issue is part of [Hacktoberfest](https://hacktoberfest.digitalocean.com/) - A yearly event which encourages participation in the open-source community. [Sign up on their website](https://hacktoberfest.digitalocean.com/) and submit **four pull requests during october (Oct 1st - Oct 31st)** to any public open-source project on GitHub and earn a limited-edition T-shirt or plant a tree!

## :mag_right: Scope
The following bullet points explain what the scope of this feature should be.
It should give a general idea of what we want, you can of course deviate from this as needed.

* Allowing Players to right click a Lectern with their Slimefun guide
* "Storing" that Slimefun guide "inside" the Lectern
* Right-Clicking the Lectern should open the stored Slimefun Guide

## :anchor: Difficulty
Here is our honest estimate on how difficult (on a scale of 1-5) the implementation may be:

:large_blue_circle::large_blue_circle::large_blue_circle::white_circle::white_circle:

## :construction: Technical Challenges
These are some challenges which may need to be overcome, we wanna be as transparent as possible, so here is some guidance on what may present itself as an obstacle.

* Registering the "Slimefun Lectern" as a hidden block, it shouldn't show up in the Slimefun Guide
* Making sure the Lectern remembers the exact item that was stored and respects the chosen guide layout

## :memo: Relevant Classes or Snippets
Here are some classes or code snippets which we think might help you get a better understanding where to look for in this gigantic codebase

* [SlimefunGuide.java](https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/io/github/thebusybiscuit/slimefun4/core/guide/SlimefunGuide.java)

## :book: Useful Resources
If you need help on how to get started, maybe try looking into the following resources!

* Hacktoberfest
    * [Getting started with Hacktoberfest](https://hacktoberfest.digitalocean.com/details#get-started)
    * [Hacktoberfest FAQ](https://hacktoberfest.digitalocean.com/faq)
* GitHub/Open-Source
    * [How to contribute to Open-Source](https://opensource.guide/how-to-contribute/)
    * [Working with forks](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks)
    * [Creating a Pull Request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)
* Slimefun
    * [Contributing to Slimefun](https://github.com/Slimefun/Slimefun4/blob/master/.github/CONTRIBUTING.md)
    * [Code of Conduct](https://github.com/Slimefun/Slimefun4/blob/master/.github/CODE_OF_CONDUCT.md)

<hr>

If you want to work on this, simply comment down below and state your interests! Please also comment again if you have changed your mind. Anyone is allowed to discuss in the comments below, feel free to collaborate and work together :heart: <br>
You can always ask for help here if you get stuck.

**Comment by Seggan** [comment]
May I be assigned this?

**Comment by TheBusyBiscuit** [comment]
Sure :)

**Comment by Seggan** [comment]
Umm biscuit can you unassign me I'm more busy than expected and can't finish this.
