### ISSUE TITLE
Unit Tests for the Energy network

### ISSUE THREAD

**Issue by TheBusyBiscuit** [Slimefun/Slimefun4#2317]
This Issue is part of [Hacktoberfest](https://hacktoberfest.digitalocean.com/) - A yearly event which encourages participation in the open-source community. [Sign up on their website](https://hacktoberfest.digitalocean.com/) and submit **four pull requests during october (Oct 1st - Oct 31st)** to any public open-source project on GitHub and earn a limited-edition T-shirt or plant a tree!

## :mag_right: Scope
The following bullet points explain what the scope of this feature should be.
It should give a general idea of what we want, you can of course deviate from this as needed.

* Unit Tests should be added for the Energy network
  * We already have Unit Tests for the generic network logic, so only the energy distribution would need to be tested
  * The network itself should be mocked by specifying the capacitors, consumers and generators fields
  * The EnergyNet#tick() method (and all sub-methods) should have decent coverage
  * The energy routing should be sufficiently tested, EnergyNetComponents/EnergyNetProviders should be mocked and the passed parameters need to be tested

## :anchor: Difficulty
Here is our honest estimate on how difficult (on a scale of 1-5) the implementation may be:

:large_blue_circle::large_blue_circle::large_blue_circle::large_blue_circle::white_circle:

## :construction: Technical Challenges
These are some challenges which may need to be overcome, we wanna be as transparent as possible, so here is some guidance on what may present itself as an obstacle.

* Mocking various objects can be a challenge

## :memo: Relevant Classes or Snippets
Here are some classes or code snippets which we think might help you get a better understanding where to look for in this gigantic codebase

* [EnergyNet.java](https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/io/github/thebusybiscuit/slimefun4/core/networks/energy/EnergyNet.java)
* [EnergyNetComponent.java](https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/EnergyNetComponent.java) needs to be mocked
* [EnergyNetProvider.java](https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/EnergyNetProvider.java) needs to be mocked

## :book: Useful Resources
If you need help on how to get started, maybe try looking into the following resources!

* Hacktoberfest
    * [Getting started with Hacktoberfest](https://hacktoberfest.digitalocean.com/details#get-started)
    * [Hacktoberfest FAQ](https://hacktoberfest.digitalocean.com/faq)
* GitHub/Open-Source
    * [How to contribute to Open-Source](https://opensource.guide/how-to-contribute/)
    * [Working with forks](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks)
    * [Creating a Pull Request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)
* Slimefun
    * [Contributing to Slimefun](https://github.com/Slimefun/Slimefun4/blob/master/.github/CONTRIBUTING.md)
    * [Code of Conduct](https://github.com/Slimefun/Slimefun4/blob/master/.github/CODE_OF_CONDUCT.md)

<hr>

If you want to work on this, simply comment down below and state your interests! Please also comment again if you have changed your mind. Anyone is allowed to discuss in the comments below, feel free to collaborate and work together :heart: <br>
You can always ask for help here if you get stuck.

**Comment by NyorJa** [comment]
Hi, 

Please assign me this issue. Thanks.

**Comment by TheBusyBiscuit** [comment]
@NyorJa Thanks for looking into this :)
I assigned you to the issue and we look forward to your contributions!  ❤️

**Comment by NyorJa** [comment]
Lets rock and roll :)

**Comment by NyorJa** [comment]
Hi @TheBusyBiscuit, 

Will it be okay I can finish more likely 50%? I cannot imagine writing unit test case since I will be using mockito?

**Comment by TheBusyBiscuit** [comment]
> Hi @TheBusyBiscuit,
> 
> Will it be okay I can finish more likely 50%? I cannot imagine writing unit test case since I will be using mockito?

Any amount of Unit Tests would be beneficial to the project :)
And we are using Mockito and MockBukkit for our unit tests, feel free to have a look around some other test classes and maybe you can find something that may help you.
