### ISSUE TITLE
Hunter talisman dupe bug

### ISSUE THREAD

**Issue by andris155** [Slimefun/Slimefun4#2325]
## :round_pushpin: Description (REQUIRED)

Hunter talisman dupe bug. skeletons and zombies.
Maybe works other entities. Piglins?

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Drop items to zombie or skeleton or use dispenser.
2. The zombie or the skeleton picked up items.
3. Kill the entity with use hunter talisman.
4. If you lucky your tool or armor duplicated.

## :bulb: Expected behavior (REQUIRED)

The hunter talisman no duplicate the item which entities picked up.

## :open_file_folder: Error Reports

No error report.

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.3
 - Slimefun Version: vDEV - 676 (git 07f5687b)
 - CS-CoreLib Version: vDEV - 90 (git 9dd4a1cf)

**Comment by LinoxGH** [comment]
There is a check for this on Hunter talisman. Can you send us a video where you're reproducing this?

**Comment by andris155** [comment]
https://www.youtube.com/watch?v=Uy_EhVAp25c

**Comment by LinoxGH** [comment]
Can you also reproduce with an armor part?

**Comment by andris155** [comment]
Yes, works with armor parts.
https://www.youtube.com/watch?v=9RgouokrTUU

**Comment by andris155** [comment]
thanks

**Comment by andris155** [comment]
This fix not fixed this bug.
