### ISSUE TITLE
Adding rechargeable batteries

### ISSUE THREAD

**Issue by TheBusyBiscuit** [Slimefun/Slimefun4#2330]
This Issue is part of [Hacktoberfest](https://hacktoberfest.digitalocean.com/) - A yearly event which encourages participation in the open-source community. [Sign up on their website](https://hacktoberfest.digitalocean.com/) and submit **four pull requests during october (Oct 1st - Oct 31st)** to any public open-source project on GitHub and earn a limited-edition T-shirt or plant a tree!

## :mag_right: Scope
The following bullet points explain what the scope of this feature should be.
It should give a general idea of what we want, you can of course deviate from this as needed.

* A new Item that is `Rechargeable` called Rechargeable Battery
* A new "Generator" that de-charges rechargeable batteries

## :anchor: Difficulty
Here is our honest estimate on how difficult (on a scale of 1-5) the implementation may be:

:large_blue_circle::large_blue_circle::large_blue_circle::large_blue_circle::white_circle:

## :construction: Technical Challenges
These are some challenges which may need to be overcome, we wanna be as transparent as possible, so here is some guidance on what may present itself as an obstacle.

* You would need to create a new "Generator" which can de-charge these batteries
* You may also need to add a higher tier Carging Bench since the current one might be far too slow for such a use case

## :memo: Relevant Classes or Snippets
Here are some classes or code snippets which we think might help you get a better understanding where to look for in this gigantic codebase

* [Rechargeable.java](https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/io/github/thebusybiscuit/slimefun4/core/attributes/Rechargeable.java) (Implement this interface to mark an item as rechargeable)
* [AbstractEnergyProvider.java](https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/AbstractEnergyProvider.java) (Extend this class for the custom generator)
* [AGenerator.java](https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/me/mrCookieSlime/Slimefun/Objects/SlimefunItem/abstractItems/AGenerator.java) (You can use this as a reference on how to create the custom generator)

## :book: Useful Resources
If you need help on how to get started, maybe try looking into the following resources!

* Hacktoberfest
    * [Getting started with Hacktoberfest](https://hacktoberfest.digitalocean.com/details#get-started)
    * [Hacktoberfest FAQ](https://hacktoberfest.digitalocean.com/faq)
* GitHub/Open-Source
    * [How to contribute to Open-Source](https://opensource.guide/how-to-contribute/)
    * [Working with forks](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/working-with-forks)
    * [Creating a Pull Request](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)
* Slimefun
    * [Contributing to Slimefun](https://github.com/Slimefun/Slimefun4/blob/master/.github/CONTRIBUTING.md)
    * [Code of Conduct](https://github.com/Slimefun/Slimefun4/blob/master/.github/CODE_OF_CONDUCT.md)

<hr>

If you want to work on this, simply comment down below and state your interests! Please also comment again if you have changed your mind. Anyone is allowed to discuss in the comments below, feel free to collaborate and work together :heart: <br>
You can always ask for help here if you get stuck.

**Comment by J3fftw1** [comment]
TheBusyBiscuit told me that the Powered Crystal is based of IC2
in IC2 its called Energy Crystal and that Item Stores 100k EU that would mean it can store 1mil Joules. I would say that's a bit much for base Slimefun but the person who adds this can probably think of a correct number

**Comment by TheBusyBiscuit** [comment]
The Power Crystal is a crafting ingredient, I don't think it should store any energy and changing that would be out of scope for this issue.

**Comment by J3fftw1** [comment]
Then i take my suggestion back
