### ISSUE TITLE
Multi tool grappling hook mode sometimes bugged and not work

### ISSUE THREAD

**Issue by andris155** [Slimefun/Slimefun4#2352]
## :round_pushpin: Description (REQUIRED)

Multi tool grappling hook mode sometimes bugged and not work, and drop leads.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Give and use multi tool grappling hook mode.

https://www.youtube.com/watch?v=1zfDx7PLvEc

## :bulb: Expected behavior (REQUIRED)

Multi tool grappling hook mode always works.

## :open_file_folder: /error-reports/ Folder

none

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.3
 - Slimefun Version: vDEV - 685 (git dc551907)
 - CS-CoreLib Version: vDEV - 91 (git e42a05d1)

**Comment by LinoxGH** [comment]
Something causes the invisible bat to not die. Are there any errors on console?

**Comment by andris155** [comment]
No errors.

**Comment by LinoxGH** [comment]
@andris155 does this only happen with multitools?

**Comment by andris155** [comment]
Maybe yes. I don't tested deep the simple Grappling hook.

**Comment by LinoxGH** [comment]
Please do so if you're available, that would help us identifying the cause.

**Comment by andris155** [comment]
I successfully reproduced this bug with simple Grappling hook.

**Comment by andris155** [comment]
https://www.youtube.com/watch?v=9gxgrFLVy6k

**Comment by Volgeop** [comment]
I can confirm, hopefully someone will fix it soon

**Comment by Volgeop** [comment]
Anyone doesn't want to fix this? 😅

**Comment by 100petr** [comment]
They don't just have this problem here. And you can definitely help them through PR :D

**Comment by bobhenl** [comment]
On production server with consume-on-use: **false** it bugs sometimes even when tps are on 20, players 
 see sometimes leads in the air, then they can pick up leads + arrows (which are created by it) when it bugs and then their grappling hook change to lead too after some time https://streamable.com/aopfgn


Here is video without addons just with cscore and slimefun  + with consume-on-use: **true** - so default settings, anything changed https://streamable.com/3qhfth, here you can see the grappling hook created leads + arrows too and then it bugged into  lead (so it wasn't grappling hook anymore)

And here again cscore and slimefun without addons + consume-on-use: **false** https://streamable.com/m77p9u where you can see it's loosing leads and arrows again (19 arrows and 19 leads per one grappling hook) and also again changed into lead at the end.

**Comment by SrMonsterYT** [comment]
is there a solution for this?

**Comment by Boomer-1** [comment]
If the issue is open, no.

**Comment by JustAHuman-xD** [comment]
Does anyone have a more recent video for this? Both previous ones are unavailable
