### ISSUE TITLE
Paper items can be used in Cartography table for maps

### ISSUE THREAD

**Issue by andris155** [Slimefun/Slimefun4#2357]
## :round_pushpin: Description (REQUIRED)

Bandage, rag, Reinforced Cloth, Plastic Sheet, Steel plate, Cloth, Reinforced Plate and Magical Book Cover, Scroll of Dimensional Teleposition can be used in Cartography table for maps.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Give a Slimefun Paper item.
2. Can be craft maps in Cartography table from Paper items.

<img width="263" alt="Bandage" src="https://user-images.githubusercontent.com/8324198/94374011-85706080-0109-11eb-9c89-d595ba87adb3.PNG">
<img width="272" alt="Rag" src="https://user-images.githubusercontent.com/8324198/94374014-8903e780-0109-11eb-97c0-987a05507e30.PNG">

## :bulb: Expected behavior (REQUIRED)

Can not craft maps in Cartography table from Slimefun Paper items.

## :open_file_folder: /error-reports/ Folder

No error report.

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.3
 - Slimefun Version: vDEV - 685 (git dc551907)
 - CS-CoreLib Version: vDEV - 91 (git e42a05d1)

**Comment by poma123** [comment]
I'm going to fix this.
