### ISSUE TITLE
The refinery can be used as normal piston

### ISSUE THREAD

**Issue by andris155** [Slimefun/Slimefun4#2360]
## :round_pushpin: Description (REQUIRED)

The refinery can be used as normal piston.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Give a refinery and place.
2. Place a lever next to the refinery.
3. Use lever.

![2020-09-27_20 57 36](https://user-images.githubusercontent.com/8324198/94374287-77234400-010b-11eb-9c40-a745a7aae6bb.png)

## :bulb: Expected behavior (REQUIRED)

The refinery can not used as normal piston.

## :open_file_folder: /error-reports/ Folder

No error report.

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: 1.16.3
 - Slimefun Version: vDEV - 685 (git dc551907)
 - CS-CoreLib Version: vDEV - 91 (git e42a05d1)

**Comment by Chlorophytus** [comment]
This bug is reproducible. I'll get to it.
