### ISSUE TITLE
Update wiki.json to include new wiki pages

### ISSUE THREAD

**Issue by TheBusyBiscuit** [Slimefun/Slimefun4#2389]
This Issue is part of [Hacktoberfest](https://hacktoberfest.digitalocean.com/) - A yearly event which encourages participation in the open-source community. [Sign up on their website](https://hacktoberfest.digitalocean.com/) and submit **four pull requests during october (Oct 1st - Oct 31st)** to any public open-source project on GitHub and earn a limited-edition T-shirt or plant a tree!

## :mag_right: Scope
The following bullet points explain what the scope of this feature should be.
It should give a general idea of what we want, you can of course deviate from this as needed.

* The wiki.json is a file which maps slimefun item ids to their corresponding wiki page.
* This file hasn't been updated in a while despite there being lots of new wiki pages

## :anchor: Difficulty
Here is our honest estimate on how difficult (on a scale of 1-5) the implementation may be:

:large_blue_circle::white_circle::white_circle::white_circle::white_circle:

## :construction: Technical Challenges
These are some challenges which may need to be overcome, we wanna be as transparent as possible, so here is some guidance on what may present itself as an obstacle.

None, this is pretty straight-forward, you just gotta stick to the json format.

## :memo: Relevant Classes or Snippets
Here are some classes or code snippets which we think might help you get a better understanding where to look for in this gigantic codebase

* [Wiki: /pages/](https://github.com/Slimefun/Wiki/tree/master/pages) - This is a list of all wiki pages
* [SlimefunItems.java](https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/SlimefunItems.java) - Here you can find all Slimefun item ids, they are the first argument in the `SlimefunItemStack` constructor

## :book: Useful Resources
If you need help on how to get started, maybe try looking into the following resources!

* Hacktoberfest
    * [Getting started with Hacktoberfest](https://hacktoberfest.digitalocean.com/details#get-started)
    * [Hacktoberfest FAQ](https://hacktoberfest.digitalocean.com/faq)
* GitHub/Open-Source
    * [How to contribute to Open-Source](https://opensource.guide/how-to-contribute/)
    * [Working with forks](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/working-with-forks)
    * [Creating a Pull Request](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)
* Slimefun
    * [Contributing to Slimefun](https://github.com/Slimefun/Slimefun4/blob/master/CONTRIBUTING.md)
    * [Code of Conduct](https://github.com/Slimefun/Slimefun4/blob/master/.github/CODE_OF_CONDUCT.md)

<hr>

If you want to work on this, simply comment down below and state your interests! Please also comment again if you have changed your mind. Anyone is allowed to discuss in the comments below, feel free to collaborate and work together :heart: <br>
You can always ask for help here if you get stuck.

**Comment by comrade-om** [comment]
Hello @TheBusyBiscuit , I would be glad to contribute to this, shall I? The codebase is quite large so may take sometime to familiarize with it :smiley:

**Comment by TheBusyBiscuit** [comment]
@comrade-om Sure, you're welcome :).
By the way this particular issue does not require any coding skills at all, it's just about adding missing entries to the wiki.json file, want me to assign you to this?

**Comment by comrade-om** [comment]
Yep, I'll take this one :+1:

**Comment by comrade-om** [comment]
@TheBusyBiscuit Please review my PR :smiley:
