### ISSUE TITLE
Missing items from Coal generator guide page

### ISSUE THREAD

**Issue by andris155** [Slimefun/Slimefun4#2411]
## :round_pushpin: Description (REQUIRED)

Some items missing from Coal generator guide page.

<img width="261" alt="Capture" src="https://user-images.githubusercontent.com/8324198/95468861-3800b880-097f-11eb-8db3-5e2f9fbf7d60.PNG">

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Open coal generator guide page.

## :bulb: Expected behavior (REQUIRED)

No missing items from Coal generator guide page.

## :open_file_folder: /error-reports/ Folder

No error report.

## :compass: Environment (REQUIRED)

[16:15:18 INFO]: This Server uses the following setup of Slimefun:
[16:15:18 INFO]: Paper v1_16_R2
[16:15:18 INFO]: CS-CoreLib vDEV - 91 (git e42a05d1)
[16:15:18 INFO]: Slimefun vDEV - 707 (git 26066f2e)
[16:15:18 INFO]: Metrics build: #17
[16:15:18 INFO]:
[16:15:18 INFO]: Installed Addons: (0)

**Comment by TheBusyBiscuit** [comment]
Please always post a screenshot of `/sf versions`, it gives us all info we need.
In this case it may be an Addon messing with it.

**Comment by andris155** [comment]
I tested without addons, and same error.

**Comment by TheBusyBiscuit** [comment]
very weird...

**Comment by TheBusyBiscuit** [comment]
Not sure if it's too much to ask for, but if you could make a list of what items ARE shown, that could be pretty helpful to see which items went missing.

**Comment by andris155** [comment]
- ?
- ?
- ?
- ?
- ?
- ?
- ?
- ?
- acacia_boat
- acacia_button
- acacia_door
- acacia_fence
- acacia_log
- acacia_planks
- acacia_pressure_plate
- acacia_sign
- acacia_slab
- acacia_trapdoor
- acacia_wood
- birch_boat
- birch_button
- birch_door
- birch_fence
- birch_log
- birch_planks
- birch_pressure_plate
- birch_sign
- birch_slab
- birch_trapdoor
- birch_wood
- blaze_rod
- charcoal
- coal
- coal_block
- crimson_button
- crimson_door
- crimson_fence
- crimson_hyphae
- crimson_planks
- crimson_pressure_plate
- crimson_sign
- crimson_slab
- crimson_stem
- crimson_trapdoor
- dark_oak_boat
- dark_oak_button
- dark_oak_door
- dark_oak_fence
- dark_oak_log
- dark_oak_planks
- dark_oak_pressure_plate
- dark_oak_sign
- dark_oak_slab
- dark_oak_trapdoor
- dark_oak_wood
- dried_kelp_block
- jungle_boat
- jungle_button
- jungle_door
- jungle_fence
- jungle_log
- jungle_planks
- jungle_pressure_plate
- jungle_sign
- jungle_slab
- jungle_trapdoor
- jungle_wood
- oak_boat
- oak_button
- oak_door
- oak_fence
- oak_log
- oak_planks
- oak_pressure_plate
- oak_sign
- oak_slab
- oak_trapdoor
- oak_wood
- spruce_boat
- spruce_button
- spruce_door
- spruce_fence
- spruce_log
- spruce_planks
- spruce_pressure_plate
- spruce_sign
- spruce_slab
- spruce_trapdoor
- spruce_wood
- stripped_acacia_log
- stripped_acacia_wood
- stripped_birch_log
- stripped_birch_wood
- stripped_crimson_hyphae
- stripped_crimson_stem
- stripped_dark_oak_log
- stripped_dark_oak_wood
- stripped_jungle_log
- stripped_jungle_wood
- stripped_oak_log
- stripped_oak_wood
- stripped_spruce_log
- stripped_spruce_wood
- stripped_warped_hyphae
- stripped_warped_stem
- warped_button
- warped_door
- warped_fence
- warped_hyphae
- warped_planks
- warped_pressure_plate
- warped_sign
- warped_slab
- warped_stem
- warped_trapdoor

**Comment by CURVX** [comment]
Shouldn't there be fence gates ? Also, why not have one item of each to represent the entire set ? Clutter free :D

**Comment by andris155** [comment]
Thanks
