### ISSUE TITLE
Heavy Cream can be used as snowball

### ISSUE THREAD

**Issue by andris155** [Slimefun/Slimefun4#2422]
## :round_pushpin: Description (REQUIRED)

The Heavy Cream can be used as snowball.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Give Heavy Cream item.
2. Right click to air with Heavy Cream.

## :bulb: Expected behavior (REQUIRED)

Heavy Cream can not used as snowball.

## :open_file_folder: /error-reports/ Folder

No error report.

## :compass: Environment (REQUIRED)

[16:37:52 INFO]: This Server uses the following setup of Slimefun:
[16:37:52 INFO]: Paper v1_16_R2
[16:37:52 INFO]: CS-CoreLib vDEV - 91 (git e42a05d1)
[16:37:52 INFO]: Slimefun vDEV - 708 (git de5db265)
[16:37:52 INFO]: Metrics build: #17
[16:37:52 INFO]:
[16:37:52 INFO]: Installed Addons: (0)

**Comment by TheSilentPro** [comment]
@TheBusyBiscuit I'm thinking of changing the Heavy Cream item to a Milk Bukkit in order to avoid this issue. 
If it were still a snowball there would need to be a new class created for this in order to cancel the throwing.
Of course, i wanted to ask first if you would approve of this change.

**Comment by TheBusyBiscuit** [comment]
@TheSilentPro Well the milk bucket could still be consumed then though, which may need to be accounted for.

**Comment by TheSilentPro** [comment]
> @TheSilentPro Well the milk bucket could still be consumed then though, which may need to be accounted for.
@TheBusyBiscuit Oh that's right, i can't think of anything else that can resemble this so i guess it would need to be handled with a handler
