### ISSUE TITLE
Gold pan and Nether gold pan cannot put into item frame

### ISSUE THREAD

**Issue by andris155** [Slimefun/Slimefun4#2433]
## :round_pushpin: Description (REQUIRED)

Gold pan and Nether gold pan cannot put into item frame.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Give Gold pan or Nether gold pan.
2. Right click to item frame with Gold pan or Nether gold pan.
3. Gold pan or Nether gold pan cannot put into item frame.

![2020-10-10_15 35 20](https://user-images.githubusercontent.com/8324198/95656472-e850f700-0b0e-11eb-845b-19e1c749ff30.png)

## :bulb: Expected behavior (REQUIRED)

Gold pan and Nether gold pan can put into item frame

## :open_file_folder: /error-reports/ Folder

No error report.

## :compass: Environment (REQUIRED)

[15:39:57 INFO]: This Server uses the following setup of Slimefun:
[15:39:57 INFO]: Paper v1_16_R2
[15:39:57 INFO]: CS-CoreLib vDEV - 91 (git e42a05d1)
[15:39:57 INFO]: Slimefun vDEV - 708 (git de5db265)
[15:39:57 INFO]: Metrics build: #17
[15:39:57 INFO]:
[15:39:57 INFO]: Installed Addons: (0)

**Comment by CURVX** [comment]
Can I get assigned to this?

**Comment by TheBusyBiscuit** [comment]
@CURVX Sure :)

**Comment by andris155** [comment]
Thanks!
