### ISSUE TITLE
PyroMining and Slimefun Incompatibility

### ISSUE THREAD

**Issue by ItsSynchro** [Slimefun/Slimefun4#2439]
## :round_pushpin: Description (REQUIRED)

Whilst using the PyroMining plugin along side Slimefun's Explosive Pickaxe, it appears that players are able to mass produce the items the plugin drops from mining the ore. I've gone ahead and talked to Pyro (developer of the PyroMining plugin), and he's mentioned that he has already set the events to the highest priority so that its more than likely Slimefun overriding something.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

https://youtu.be/3wgpkvai008

## :bulb: Expected behavior (REQUIRED)

Prevent the Explosive Pickaxe from being able to override the events from other plugins.

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper):
![Capture](https://user-images.githubusercontent.com/16171807/95665027-931ae280-0b1a-11eb-8264-7800a1a2e57f.PNG)

**Comment by LinoxGH** [comment]
This can be fixed by checking if the event is cancelled.

**Comment by TheBusyBiscuit** [comment]
@LinoxGH Nope, we should change our event priority as suggested.
I just looked at the code and it seems to operate under the `MONITOR` priority which is absolutely not right at all.
It should probably run under something like `HIGH` instead.

**Comment by LinoxGH** [comment]
> @LinoxGH Nope, we should change our event priority as suggested.
> I just looked at the code and it seems to operate under the `MONITOR` priority which is absolutely not right at all.
> It should probably run under something like `HIGH` instead.

Well even then checking if event is cancelled will probably fix the dupe errors in sf addons like luckyblocks, PrivateStorage, Barrels.

**Comment by TheBusyBiscuit** [comment]
It's because of the priority.
MONITOR is only for monitoring and not for manipulating the event outcome, however our Listener does manipulate the outcome, this did not use to be the case in the past but now it is and the priority remained unchanged even though it should have been changed. Hence why we should change it by now. That would fix this issue.

**Comment by LinoxGH** [comment]
On it.
