### ISSUE TITLE
Wither creation using Necrotic Skull and dispenser

### ISSUE THREAD

**Issue by andris155** [Slimefun/Slimefun4#2448]
## :round_pushpin: Description (REQUIRED)

Wither creation using Necrotic Skull and dispenser.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Build wither body from soul sand or soul soil.
2. Place dispensers.

![2020-10-11_15 46 02](https://user-images.githubusercontent.com/8324198/95680296-e489a700-0bd8-11eb-83a2-cb2ca97cbb71.png)

3. Place Necrotic Skull to dispensers.
<img width="360" alt="Capture" src="https://user-images.githubusercontent.com/8324198/95680358-5d88fe80-0bd9-11eb-9498-944ab5df768a.PNG">
4. Use dispensers.

![2020-10-11_15 48 23](https://user-images.githubusercontent.com/8324198/95680336-37fbf500-0bd9-11eb-83f5-227cbec60d02.png)

## :bulb: Expected behavior (REQUIRED)

Wither creation not work using Necrotic Skull and dispenser

## :open_file_folder: /error-reports/ Folder

No error report.

## :compass: Environment (REQUIRED)

[15:04:52 INFO]: This Server uses the following setup of Slimefun:
[15:04:52 INFO]: Paper v1_16_R2
[15:04:52 INFO]: CS-CoreLib vDEV - 91 (git e42a05d1)
[15:04:52 INFO]: Slimefun vDEV - 712 (git 15884c65)
[15:04:52 INFO]: Metrics build: #17
[15:04:52 INFO]:
[15:04:52 INFO]: Installed Addons: (0)

**Comment by TheSilentPro** [comment]
This is with normal dispensers correct?
As far as i remember dispensers just drop the item, they dont place it?

**Comment by TheBusyBiscuit** [comment]
@TheSilentPro Well... Droppers drop items.
Dispensers "dispense" them, pretty complex but
* Shulker Boxes are placed
* Wither Skulls are placed
* Arrows are shot
* Potions are thrown
* Armor is equipped
* much more, some items are just dropped

Welcome to Minecraft.

**Comment by andris155** [comment]
Thanks!

**Comment by TheBusyBiscuit** [comment]
Before anyone asks: Yes, my solution is to just change the wither skeleton head to a player head with the wither skeleton texture XD
