### ISSUE TITLE
Unable to craft Elytra Cap without an Output Chest

### ISSUE THREAD

**Issue by GallowsDove** [Slimefun/Slimefun4#2469]
## :round_pushpin: Description
When attempting to craft Elytra Cap in an Armor Forge, it writes "Inventory full", despite the fact that the slots would clear after consuming the materials. This is fixed when you put an output chest next to it as it gives it a free slot for output.

## :bookmark_tabs: Steps to reproduce the Issue
1. Attempt to craft Elytra Cap.
2. Fail

## :bulb: Expected behavior
Materials should be consumed and the Elytra Cap should appear in the dispenser of an Armor Forge

## :scroll: Server Log
None

## :open_file_folder: /error-reports/ Folder
None

## :compass: Environment (REQUIRED)
![image](https://user-images.githubusercontent.com/71831019/95915659-c32ae580-0da7-11eb-8085-6c4db190e314.png)

**Comment by J3fftw1** [comment]
update litexpansion :)

**Comment by GallowsDove** [comment]
> update litexpansion :)

It's only my testing server and didn't need to use litexpansion for quite some time, also it has nothing to do with the bug, but yeah.

**Comment by J3fftw1** [comment]
I will take a look tomorrow see if im able to fix it

**Comment by Seggan** [comment]
Hmm when I added the elytra cap I didn't touch any of the fancy recipe stuff... It could possibly be caused by an addon.

**Comment by CURVX** [comment]
I encountered the same without any addons. Since, all slots of dispenser are used to craft the item, it fails to put the item into the dispenser. Probably needs to iron out this case in `multiblocks -> ArmorForge.java` ?

**Comment by J3fftw1** [comment]
> I encountered the same without any addons. Since, all slots of dispenser are used to craft the item, it fails to put the item into the dispenser. Probably needs to iron out this case in `multiblocks -> ArmorForge.java` ?

Imma setup my pc again in 3 hours and implement a fake inventory

**Comment by CURVX** [comment]
> Imma setup my pc again in 3 hours and implement a fake inventory

Meanwhile, I will give it a shot :D

**Comment by J3fftw1** [comment]
> > Imma setup my pc again in 3 hours and implement a fake inventory
> 
> Meanwhile, I will give it a shot :D

This is animal abuse

**Comment by CURVX** [comment]
> 
> 
> Seems to be working https://streamable.com/ujfnak but code is messy. I will draft a PR.

This doesn't make sense ... There is an output chest!
