### ISSUE TITLE
The block placer wrongly place some blocks

### ISSUE THREAD

**Issue by andris155** [Slimefun/Slimefun4#2470]
## :round_pushpin: Description (REQUIRED)

The block placer wrongly place some blocks.
The block placer allows placed blocks to the air that would otherwise break in the vanilla game.
- allium
- azure_bluet
- blue_orchid
- cornflower
- dandelion
- fern
- grass
- lily_of_the_valley
- orange_tulip
- oxeye_daisy
- pink_tulip
- poppy
- red_tulip
- seagrass
- white_tulip
- wither_rose

![2020-10-14_10 52 05](https://user-images.githubusercontent.com/8324198/95972453-c14a3c00-0e12-11eb-9d1e-95948c721770.png)

- cactus
- chorus_flower
- chorus_plant
- crimson_roots
- kelp
- ladder
- nether_sprouts
- snow
- twisting_vines
- warped_roots
- weeping_vines

![2020-10-14_10 59 59](https://user-images.githubusercontent.com/8324198/95972498-d0c98500-0e12-11eb-8cd3-b2c75dddc925.png)

- brain_coral
- brain_coral_fan
- bubble_coral
- bubble_coral_fan
- dead_brain_coral
- dead_brain_coral_fan
- dead_bubble_coral
- dead_bubble_coral_fan
- dead_fire_coral
- dead_fire_coral_fan
- dead_horn_coral
- dead_horn_coral_fan
- dead_horn_coral_fan
- dead_tube_coral
- dead_tube_coral_fan
- fire_coral
- fire_coral_fan
- horn_coral
- horn_coral_fan
- tube_coral
- tube_coral_fan

![2020-10-14_11 08 53](https://user-images.githubusercontent.com/8324198/95972567-e179fb00-0e12-11eb-871f-d8446f4f68fe.png)
![2020-10-14_11 11 43](https://user-images.githubusercontent.com/8324198/95972778-24d46980-0e13-11eb-9d4f-5a9e7f43c720.png)

- black_carpet
- blue_carpet
- brown_carpet
- cyan_carpet
- gray_carpet
- green_carpet
- light_blue_carpet
- light_gray_carpet
- lime_carpet
- magenta_carpet
- orange_carpet
- pink_carpet
- purple_carpet
- red_carpet
- white_carpet
- yellow_carpet

![2020-10-14_11 16 26](https://user-images.githubusercontent.com/8324198/95972883-459cbf00-0e13-11eb-87e5-13e04d968848.png)

- acacia_sign
- bell
- birch_sign
- crimson_sign
- dark_oak_sign
- jungle_sign
- lantern
- oak_sign
- sea_pickle
- soul_lantern
- spruce_sign
- warped_sign

![2020-10-14_11 22 22](https://user-images.githubusercontent.com/8324198/95972938-577e6200-0e13-11eb-8ae4-5e5d1a6a3c5a.png)

- black_banner
- blue_banner
- brown_banner
- cyan_banner
- gray_banner
- green_banner
- light_blue_banner
- light_gray_banner
- lime_banner
- magenta_banner
- orange_banner
- pink_banner
- purple_banner
- red_banner
- white_banner
- yellow_banner

![2020-10-14_11 25 19](https://user-images.githubusercontent.com/8324198/95973044-7aa91180-0e13-11eb-849d-49f7ed8a6c11.png)

- acacia_button
- birch_button
- crimson_button
- dark_oak_button
- jungle_button
- lever
- oak_button
- polished_blackstone_button
- polished_blackstone_pressure_plate
- repeater
- spruce_button
- stone_button
- tripwire_hook
- warped_button

![2020-10-14_11 32 24](https://user-images.githubusercontent.com/8324198/95973122-8d234b00-0e13-11eb-8f61-33f6160566c6.png)

- rail
- tall_grass
- large_fern

![2020-10-14_11 57 13](https://user-images.githubusercontent.com/8324198/95973861-77625580-0e14-11eb-9497-f416c85592dc.png)

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Give and place Block Placer.
2. Place specific blocks with Block Placer.

## :bulb: Expected behavior (REQUIRED)

The block placer follows the vanilla Minecraft block place rules.

## :open_file_folder: /error-reports/ Folder

No error report.

## :compass: Environment (REQUIRED)

[11:51:55 INFO]: This Server uses the following setup of Slimefun:
[11:51:55 INFO]: Paper v1_16_R2
[11:51:55 INFO]: CS-CoreLib vDEV - 91 (git e42a05d1)
[11:51:55 INFO]: Slimefun vDEV - 719 (git 1ffe2fd4)
[11:51:55 INFO]: Metrics build: #17
[11:51:55 INFO]:
[11:51:55 INFO]: Installed Addons: (0)

**Comment by J3fftw1** [comment]
Some blocks 😂

**Comment by TheSilentPro** [comment]
> For anyone trying to work on this, the materials simply need to be added to this JSON tag file:
> https://github.com/Slimefun/Slimefun4/blob/master/src/main/resources/tags/block_placer_ignored_materials.json
> 
> Any version-dependent materials need to be set to "required": false.

Some of these seem it would be ok to leave (ex: carpet) but it should check if the block below is an actual solid block

**Comment by J3fftw1** [comment]
Do you mind testing it again. I think i havent missed any but not 100% sure
