### ISSUE TITLE
Get damaged with ender pearls wearing ender armor

### ISSUE THREAD

**Issue by omer03** [Slimefun/Slimefun4#2478]
:round_pushpin: Description (REQUIRED)

I get damage while throwing ender pearls and magic eye of ender even though im wearing a full set of ender armor.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

Wear a full set of ender armor and throw regular ender pearls or a magic eye of ender.

## :bulb: Expected behavior (REQUIRED)

It should not damage me after throwing a pearl even though I'm at least wearing the boots

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper):
 - Minecraft Version: 1.16.3
 - Slimefun Version:
 - CS-CoreLib Version:
![image](https://user-images.githubusercontent.com/14992783/96154567-40249f00-0f0f-11eb-942c-d247f641bfa2.png)

**Comment by TheBusyBiscuit** [comment]
Do you have the ender armor unlocked and are you sure you are wearing ender boots? A screenshot would be useful.

**Comment by CURVX** [comment]
Weirdly exists in RC-16 as well but not in RC-15. 

Checked on:
Minecraft  Version: 1.16.3-R.01-SNAPSHOT
CS-CoreLib Version: DEV-91

**Comment by TheBusyBiscuit** [comment]
We don't support RC builds of Slimefun. @CURVX

**Comment by omer03** [comment]
![image](https://user-images.githubusercontent.com/14992783/96180046-247ec000-0f32-11eb-9ea6-e5d181f8c7d5.png)
![image](https://user-images.githubusercontent.com/14992783/96180068-2ba5ce00-0f32-11eb-9cde-3dbc67c4d673.png)
![image](https://user-images.githubusercontent.com/14992783/96180094-33fe0900-0f32-11eb-97ad-81189164dea0.png)

**Comment by CURVX** [comment]
I will draft a PR which resolves this one but creates another, that is, when **Enderpearl** is used with **StomperBoots** which is supposed to "negate all Fall damage" you end up taking damage. :D
