### ISSUE TITLE
The block placer wrongly place some blocks (test 3)

### ISSUE THREAD

**Issue by andris155** [Slimefun/Slimefun4#2493]
## :round_pushpin: Description (REQUIRED)

The block placer wrongly place some blocks.
The block placer allows placed blocks to the air that would otherwise break in the vanilla game.

- brain_coral
- brain_coral_fan
- bubble_coral
- bubble_coral_fan
- dead_brain_coral
- dead_brain_coral_fan
- dead_bubble_coral
- dead_bubble_coral_fan
- dead_fire_coral
- dead_fire_coral_fan
- dead_horn_coral
- dead_horn_coral_fan
- dead_horn_coral_fan
- dead_tube_coral
- dead_tube_coral_fan
- fire_coral
- fire_coral_fan
- horn_coral
- horn_coral_fan
- tube_coral
- tube_coral_fan

![2020-10-14_11 08 53](https://user-images.githubusercontent.com/8324198/95972567-e179fb00-0e12-11eb-871f-d8446f4f68fe.png)
![2020-10-14_11 11 43](https://user-images.githubusercontent.com/8324198/95972778-24d46980-0e13-11eb-9d4f-5a9e7f43c720.png)

- black_carpet
- blue_carpet
- brown_carpet
- cyan_carpet
- gray_carpet
- green_carpet
- light_blue_carpet
- light_gray_carpet
- lime_carpet
- magenta_carpet
- orange_carpet
- pink_carpet
- purple_carpet
- red_carpet
- white_carpet
- yellow_carpet

![2020-10-14_11 16 26](https://user-images.githubusercontent.com/8324198/95972883-459cbf00-0e13-11eb-87e5-13e04d968848.png)

- sea_pickle
- chorus_plant
- lantern
- bell
- soul_lantern
- vine
- chorus_flower

![2020-10-20_16 27 06](https://user-images.githubusercontent.com/8324198/96600528-5062c280-12f1-11eb-9915-35c042859961.png)

- nether_wart

![2020-10-20_16 32 54](https://user-images.githubusercontent.com/8324198/96601105-f9112200-12f1-11eb-802d-0a051d0822a0.png)

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Give and place Block Placer.
2. Place specific blocks with Block Placer.

## :bulb: Expected behavior (REQUIRED)

The block placer follows the vanilla Minecraft block place rules.

## :open_file_folder: /error-reports/ Folder

No error report.

## :compass: Environment (REQUIRED)

[16:18:16 INFO]: This Server uses the following setup of Slimefun:
[16:18:16 INFO]: Paper v1_16_R2
[16:18:16 INFO]: CS-CoreLib vDEV - 91 (git e42a05d1)
[16:18:16 INFO]: Slimefun vDEV - 727 (git c7960c29)
[16:18:16 INFO]: Metrics build: #17
[16:18:16 INFO]:
[16:18:16 INFO]: Installed Addons: (0)

**Comment by J3fftw1** [comment]
i knew i missed some

**Comment by TheBusyBiscuit** [comment]
Then why didn't you check again? :NotLikeThis:

**Comment by J3fftw1** [comment]
because i went off the text not the images and you know how many items it was it was a pain to add i wanted to make a new pr if i missed some because i wasnt sure
but you snipped me guess im gonna have to turn on watch on this repo

**Comment by andris155** [comment]
Thanks

**Comment by J3fftw1** [comment]
Thanks for checking again. This kind of issue spam we hate and love lmfao
