### ISSUE TITLE
Miner android dropped by water flow and turn into CS core-lib head

### ISSUE THREAD

**Issue by ALiangLiang** [Slimefun/Slimefun4#2496]
## :round_pushpin: Description (REQUIRED)

If miner android move and dig a block, and water is next to it. The android is dropped and change into CS core-lib head. The position also become unplaceable.
I checked the `data-storage/Slimefun/stored-blocks/world/PROGRAMMABLE_ANDROID_MINER.sfb`. The data of android is still there.
![image](https://user-images.githubusercontent.com/6974496/96755401-4336f800-1405-11eb-9f41-ed8d2ecd7f76.png)

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

https://youtu.be/UQR5B9P1Z0k

## :bulb: Expected behavior (REQUIRED)

Water should not flow and drop the miner andrioid. And also the position shoud be placeable. Idk how to recover the position now.

## :scroll: Server Log

There are no logs about it.

## :open_file_folder: /error-reports/ Folder

um..... empty forlder

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Spigot 1_16_R2
 - Minecraft Version: 1.16.3
 - Slimefun Version: vDEV - 729
 - CS-CoreLib Version: vDEV - 91

**Comment by J3fftw1** [comment]
could you show /pl to us

**Comment by ALiangLiang** [comment]
> could you show /pl to us

Sry. Only installed these plugins
![image](https://user-images.githubusercontent.com/6974496/96755946-f1db3880-1405-11eb-83e2-2419693dcee3.png)

**Comment by J3fftw1** [comment]
also there is no error in console?

**Comment by ALiangLiang** [comment]
@J3fftw1 
I'm sure no any debug information about it in console.

**Comment by J3fftw1** [comment]
imma try to reproduce rn

**Comment by J3fftw1** [comment]
i have successfully reproduced the issue this might be linked to #2111
