### ISSUE TITLE
Placing cargo nodes input/output results in unusable nodes. 

### ISSUE THREAD

**Issue by sarhatabaot** [Slimefun/Slimefun4#2517]
## :round_pushpin: Description (REQUIRED)

Placing any cargo items produces an error in the console, and doesn't allow interaction (right click) with it.
## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

Placing any cargo item - input/output/manager in versions 733,734 will bring up an error as detailed below.

## :bulb: Expected behavior (REQUIRED)

No error, right click shows the appropriate menu.
## :scroll: Server Log

https://pastebin.com/MRV9hJnj - error
https://pastebin.com/yPZryisW - server log

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper 1.15.2 build 389
 - Minecraft Version: 1.15.2
 - Slimefun Version: DEV 734
 - CS-CoreLib Version: DEV 91

![](https://puu.sh/GI2Qj/0b22729eb3.png)

**Comment by ChitterChatter** [comment]
I too am having the same issue on my server with players not being able to use some of the cargo management items, and we are getting errors on the console as well. 

![image](https://user-images.githubusercontent.com/28234726/97663601-45b5d500-1a37-11eb-83e0-71af74200f8d.png)

**Comment by sarhatabaot** [comment]
The same error appears with ancient pedestals. 
Seems to originate from [commit](b3befbda497494956d3283d4e40a62d2ea2b63ec), specifically from `PaperLib.getBlockState()`. 
Replacing `PaperLib.getBlockState()` with `block.getState()` fixes the problem, but then we lose the optimizations.

**Comment by TheBusyBiscuit** [comment]
Can you maybe try with the most recent build? The stacktrace should look a bit different

**Comment by TheBusyBiscuit** [comment]
I am still unable to reproduce this issue with the latest build of Paper.
And PersistentDataHolder#getPersistentDataContainer() is annotated as `@NotNull`, yet on some older Paper versions it appears to sometimes be null.

**Comment by sarhatabaot** [comment]
I can confirm that in the latest build of paper everything works as intended. (1.16.3)
But with paper 1.15.x/1.14.x this error comes up.

**Comment by TheBusyBiscuit** [comment]
Hmm, I added a workaround for 1.14 and 1.15, but for 1.16, they will simply get a prompt to update their server software.
