### ISSUE TITLE
Output Chest causes error and Machine to not function

### ISSUE THREAD

**Issue by RedBear47** [Slimefun/Slimefun4#2558]
## :round_pushpin: Description

 A machine (Enhanced Crafting Table, Grindstone, etc) works, however, placing an Output Chest adjacent to the dispenser causes it to stop working. A server restart seems to semi fix it until the Output Chest is broken and replaced or a new Output Chest is placed. Additionally, an error is generated on the Console.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

Construct a Multiblock machine. Test it to make sure it works. Place an Output Chest next to the dispenser. The issue on the server was first determined with one adjacent to an Enhanced Crafting Table. Previous Output Chests placed prior to updates worked and still work. Any new Output Chests or ones that are broken and replaced seem to cause the error. After a server restart, the newly placed Output Chests work (unless they are broken and replaced).
![2020-11-19_01 13 55](https://user-images.githubusercontent.com/8538404/99628668-9dc37400-2a04-11eb-988e-27928ca39cc2.png)
Picture of the Enhanced Crafting Table and GrindStone we were testing.

## :bulb: Expected behavior (REQUIRED)

The expected behavior was that the magical essence that was placed in the Enhanced Crafting Table would convert to Coal, Copper Dust, etc. and be placed in the Output Chest, however, clicking on the crafting table or the fence of the GrindStone didn't do anything. The magical essence stayed in the Enhanced Crafting Table and didn't get converted.

## :scroll: Server Log

![Error part 1](https://user-images.githubusercontent.com/8538404/99629938-f4ca4880-2a06-11eb-8733-68928f374eca.png)
![Error part 2](https://user-images.githubusercontent.com/8538404/99629952-f98efc80-2a06-11eb-9ccc-44ad314b0b09.png)
![GrindStone Error](https://user-images.githubusercontent.com/8538404/99629957-fbf15680-2a06-11eb-9ccd-055f07915f28.png)
https://pastebin.com/s7ziPsHs

## :open_file_folder: /error-reports/ Folder

![Errors Folder](https://user-images.githubusercontent.com/8538404/99630232-81750680-2a07-11eb-8b5c-3813bf878eab.png)
Errors folder is empty

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper
 - Minecraft Version: r1.16.1
 - Slimefun Version: vDEV - 744 (git 0cdd21f6)
 - CS-CoreLib Version: DEV 91 (git e42aO).jar

**Comment by TheBusyBiscuit** [comment]
I'm just gonna say it since I don't know whenever I get the chance to say something like this again:

THANKS for making such a detailed bug report ❤️ 
I rarely see people putting this much effort into their posts and it really makes a difference and saves us a lot of time, so I just wanted to say thank you :)
