### ISSUE TITLE
Breaking Infused Hoppers with a hopper limitation applied doesn't subtract them from the hopper limit.

### ISSUE THREAD

**Issue by Nekosity12** [Slimefun/Slimefun4#2560]
## :round_pushpin: Description (REQUIRED)

Placing an infused hopper down with a hopper limitation applied and then breaking said hopper will still count towards the hopper limitation. So if you for example have 1 hopper as a limit and you place down 1 infused hopper, then break the hopper, you can no longer place any other hoppers down. This only seems to happen with the infused hopper, regular hoppers and hoppers from other plugins work fine.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

Set a hopper limit (Preferably 1 for easier testing).
Get an infused hopper and place it down.
Break infused hopper.
Try to place another hopper down (any) and it will tell you it's not possible.

## :bulb: Expected behavior (REQUIRED)

Breaking the infused hopper should no longer count towards the limit.

## :scroll: Server Log

No errors but still got a link for you anyway:
https://pastebin.com/sFFGHfv3

## :open_file_folder: /error-reports/ Folder

The latest one was october 25th (Nearly a month ago) I figure you don't want those error reports
https://i.imgur.com/RPjcwgc.png

## :compass: Environment (REQUIRED)

I can't include it all in one screenshot so I split it in two with the last line being the first in the second:
https://i.imgur.com/v3IXQ2z.png
https://i.imgur.com/ODLFSO9.png

 - Server Software (Spigot/Paper): Yatopia
 - Minecraft Version: 1.16.4
 - Slimefun Version: vDEV - 744
 - CS-CoreLib Version: vDEV - 90

**Comment by TheBusyBiscuit** [comment]
What "hopper limit" are you even referring to?
Because there is definitely no such thing in Slimefun, so you should definitely state the name and version of what the software that adds it and how it applies.
Otherwise there is no chance helping you here.

**Comment by TheBusyBiscuit** [comment]
Also that error reports image isn't really useful...
When you try report an error, please post the actual error instead of just making a screenshot of the file.

**Comment by NCBPFluffyBear** [comment]
In plugins such as islands where there is /is level or other plugins (in this case, a plugin detects if hoppers next to a certain block is broken), the hoppers will register when placed but will not register when broken, likely bc of the way sf blocks break

**Comment by NCBPFluffyBear** [comment]
As for the errors, there are none. The issue is just that it doesn't pass the block break event to other plugins

**Comment by Nekosity12** [comment]
As fluffy stated, yes we are using an island plugin for a skyblock server.

This issue happens with both SuperiorSkyblock and bSkyblock.

**Comment by Skizzles** [comment]
Any update on this?

**Comment by variananora** [comment]
> As fluffy stated, yes we are using an island plugin for a skyblock server.
> 
> This issue happens with both SuperiorSkyblock and bSkyblock.

If you are using bSkyblock you can just /<gamemode> limits recalc tho?

**Comment by Skizzles** [comment]
> > As fluffy stated, yes we are using an island plugin for a skyblock server.
> > This issue happens with both SuperiorSkyblock and bSkyblock.
> 
> If you are using bSkyblock you can just /[gamemode] limits recalc tho?

Whut.... did you not read the issue? Even with a recalc it happens in numerous plugins. Biscuit even said it's an issue bro lol
