### ISSUE TITLE
ItemsAdder incompatibility

### ISSUE THREAD

**Issue by Jirsaacek** [Slimefun/Slimefun4#2575]
## :round_pushpin: Description (REQUIRED)

Well, the problem is, Slimefun isn't compatible with ItemsAdder plugin... 
That plugin adds custom blocks - Those blocks are really just an ArmorStand spawners with custom item on head, so blocks have custom texture. 
Well, when I break one of those custom blocks with Pickaxe of Containment from Slimefun, it drops 2 broken ArmorStand spawners. 

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

- Place custom block from ItemsAdder plugin I mentioned before
- Mine it with Pickaxe of Containment
- It drops 2 broken spawners

## :bulb: Expected behavior (REQUIRED)

Since it's custom block, it shouldn't drop spawners, I think there should be some kind of check for items with custom model data in spawners or something like that 

## :scroll: Server Log

No errors

## :open_file_folder: /error-reports/ Folder

No errors

## :compass: Environment (REQUIRED)

This Server uses the following setup of Slimefun:
Tuinity v1_16_R3
Minecraft version 1.16.4
CS-CoreLib vDEV - 91 (git e42a05d1)
Slimefun vDEV - 756 (git 354dd30e)
Metrics build: #17

Installed Addons: (24)
GlobalWarming vDEV - 4 (git bd8e730a)
DyedBackpacks vDEV - 11 (git b8eda0c7)
ExtraTools vDEV - 22 (git ea11f88b)
FoxyMachines vDEV - 7 (git 85598948)
SoundMuffler vDEV - 17 (git 3abf8993)
SlimefunOreChunks vDEV - 10 (git 91df3b8e)
Residence v4.9.2.1
EcoPower vDEV - 2 (git b0c0c875)
HotbarPets vDEV - 31 (git 5909202f)
ExtraGear vDEV - 12 (git 4570ea2c)
MoreTools vDEV - 8 (git db8d8814)
SlimefunLuckyBlocks vDEV - 29 (git db79cb7c)
ExoticGarden vDEV - 61 (git b5067266)
RestrictedCreative v2.4.4
InfinityExpansion vDEV - 50 (git 255cc995)
LiteXpansion vDEV - 98 (git f79eab2f)
SoulJars vDEV - 17 (git 9eedba0f)
MobCapturer vDEV - 11 (git 4edf38dd)
SlimyTreeTaps vDEV - 15 (git 205f8afc)
PrivateStorage vDEV - 15 (git a0fbc572)
TranscEndence vDEV - 21 (git f7bb1376)
ColoredEnderChests vDEV - 17 (git f9a39e70)
FluffyMachines vDEV - 47 (git 22bbdb21)
ChestTerminal vDEV - 38 (git c024be5c)

ItemsAdder version 2.1.20

I hope I did everything correctly while reporting this bug, if not, let me know and I'll edit it, thanks :)

**Comment by Jirsaacek** [comment]
Btw. LoneDev (author of ItemsAdder) said he can give you plugin for free if you need.

**Comment by TheBusyBiscuit** [comment]
> Btw. LoneDev (author of ItemsAdder) said he can give you plugin for free if you need.

Not sure if this is necessary here.
But If I end up being the one who's gonna fix it, I may contact them about it. 
Thanks for letting me know.
