### ISSUE TITLE
Null Pointer Exception in deleteLocationInfoUnsafely

### ISSUE THREAD

**Issue by matahombres** [Slimefun/Slimefun4#2576]
## :round_pushpin: Description (REQUIRED)

All day without fail, but suddenly, break plugin and spam console with NullPointerException (All plugin stop working)

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

I don't know who reproduce, because it was not connected when it happened.
I play with more people

## :bulb: Expected behavior (REQUIRED)

No spam console with NPE

## :scroll: Server Log

https://pastebin.com/YGPp1wM9

## :open_file_folder: /error-reports/ Folder

(In error-report no have errors to day)

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper): Paper v1_16_R3 Build -> 288
 - Minecraft Version: 1.16.4
 - Slimefun Version: vDEV - 756
 - CS-CoreLib Version: vDEV - 91

Addons
- FluffyMachines: vDEV - 47

**Comment by TheBusyBiscuit** [comment]
Can you please post your full `latest.log` when that happens?
There might be more than one error here.
