### ISSUE TITLE
Butcher Android Disappearing Using Fuel Interface

### ISSUE THREAD

**Issue by ItsSynchro** [Slimefun/Slimefun4#2578]
## :round_pushpin: Description (REQUIRED)

When setting a Butcher Android using the fuel interface and the script provided below, it appears to disappear. Not much else is known about it besides the steps to reproduce it and the error it throws out.

(this is the script being used)
![1](https://user-images.githubusercontent.com/16171807/100474150-f56d7980-30ad-11eb-909c-4f7c770ff8a2.png)

The image provided below is the setup. The empty space inbetween the Items and Fuel is where the android is set to go.
![thesetup](https://user-images.githubusercontent.com/16171807/100474406-847a9180-30ae-11eb-8e50-8be339a7bc9d.PNG)

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1st I placed butcher android and clicked mrscampos download script called "butcher"

2nd I edit the script to place the left & right fuel and item interfaces

3rd I started running the android and it was running perfectly until the next following day I checked on it a bit and then it disappeared

## :bulb: Expected behavior (REQUIRED)

I think the correct behavior for the butcher android if it decided to malfunction unprecedently that it should give the owner of the android when clicked on a warning that something happened during the script rather than it disappearing completely

## :open_file_folder: /error-reports/ Folder

https://pastebin.com/bLZ6h001

## :compass: Environment (REQUIRED)

![sfversions](https://user-images.githubusercontent.com/16171807/100472092-91e14d00-30a9-11eb-8835-3a8b5f8dac91.PNG)

**Comment by TheBusyBiscuit** [comment]
@ItsSynchro That error does not appear to be from Slimefun, it is caused within the `LivingEntity` class of Tuinity itself, although it also seems like a plugin called "MyPet" is interefering with it.

Not really much we can do, as the error is called within the Entity code of Blazes themselves.
I suggest you to speak to the author of MyPet and show them this error report, maybe they have an idea what caused it.

**Comment by andris155** [comment]
The MyPet not caused this error on my server, but I use the Yatopia not the Tunity.
