### ISSUE TITLE
Discord is unjoinable

### ISSUE THREAD

**Issue by GallowsDove** [Slimefun/Slimefun4#2590]
This is a bit off-topic, but since I can't join discord I don't know where to post this.

My old discord account (Thezerix) got deleted and I can't rejoin using the official invite.
My friends attempted to join as well, but get stuck at the rules unable to proceed.
When attempting to join through phone, it says "unknown network error" for a change.

Again sorry for spamming github with this, just don't know how to reach you otherwise.

**Comment by TheBusyBiscuit** [comment]
Yeah we know...
Discord knows too...

But god knows when Discord will finally fix their broken stuff...

**Comment by TheBusyBiscuit** [comment]
The issue should be fixed in the latest build of discord now.
