### ISSUE TITLE
Every recipe with "Wither Skeleton Skull" is unknown in the ancient altar

### ISSUE THREAD

**Issue by Shedopen** [Slimefun/Slimefun4#2630]
## :round_pushpin: Description (REQUIRED)

Every recipe with wither skeleton skulls isn't recognized by the ancient altar.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

Try to make a recipe with wither skeleton skulls in the ancient altar and right click the enchantment table in the middle: Recipe isn't recognized

## :bulb: Expected behavior (REQUIRED)

The recipes should work.

## :scroll: Server Log

No errors

## :open_file_folder: /error-reports/ Folder

None

## :compass: Environment (REQUIRED)

 - Server Software (Spigot/Paper):
 - Minecraft Version: 1.16.4
 - Slimefun Version: vDEV-766 (git 5aa5ca1a)
 - CS-CoreLib Version: vDEV -90 (git 9dd4a1cf)

**Comment by TheBusyBiscuit** [comment]
You didn't even specify the recipe in question, the item you wanted to craft, the item you expected, the items you used, screenshots etc..

**Comment by Shedopen** [comment]
"Essence of afterlive" and "necrotic skull" can't be crafted

**Comment by Shedopen** [comment]
![Screenshot_19](https://user-images.githubusercontent.com/53829833/102260255-82b72780-3f10-11eb-82c3-81cbb4b6cd44.png)

"Unrecognized recipe! Use the right recipe"

**Comment by WalshyDev** [comment]
Got a video?

**Comment by Shedopen** [comment]
Video here:
https://www.udrop.com/file/Jx4/2020-12-15_20-14-30.mkv

**Comment by TheBusyBiscuit** [comment]
@Shedopen As seen in the video, you are using a wrong kind of Necrotic Skull.
Look at the id, the Necrotic Skull is a `player_head`, while the one you are trying to use is just a renamed `wither_skeleton_skull`.
