### ISSUE TITLE
Can't join Discord, says "Unknown Guild"

### ISSUE THREAD

**Issue by BurrowBird** [Slimefun/Slimefun4#2638]
## :round_pushpin: Description
Can't join Discord, says "Unknown Guild".

**Comment by TheBusyBiscuit** [comment]
We know... Discord is also aware.
Discord is completely broken since over a month and they are still trying to fix it - to no success thus far.

**Comment by TheBusyBiscuit** [comment]
The issue should be fixed in the latest build of discord now.
