### ISSUE TITLE
Soulbound items do not adhere to the world settings (disabling Slimefun in a world)

### ISSUE THREAD

**Issue by andris155** [Slimefun/Slimefun4#2650]
## :round_pushpin: Description (REQUIRED)

Soulbound items do not drop out if when die in a world where disabled.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Get a soulbound item, like a chestplate and equip it.
2. Die in a world where disabled the soulbound items.
3. You will respawn with the soulbound item, despite the fact that it is disabled.

## :bulb: Expected behavior (REQUIRED)

Soulbound items drop out if when die in a world where disabled.

## :compass: Environment (REQUIRED)

[16:25:51 INFO]: This Server uses the following setup of Slimefun:
[16:25:51 INFO]: Yatopia v1_16_R3
[16:25:51 INFO]: CS-CoreLib vDEV - 92 (git e9150d72)
[16:25:51 INFO]: Slimefun vDEV - 769 (git d048f7f8)
[16:25:51 INFO]: Metrics build: #6

**Comment by svr333** [comment]
Changed the title because it was a little confusing
