### ISSUE TITLE
sf_debug_fish firing twice

### ISSUE THREAD

**Issue by J3fftw1** [Slimefun/Slimefun4#2655]
## :round_pushpin: Description (REQUIRED)

When using the sf debug fish it fires right click twice as you can see in the video.

This is really annoying when you are trying to debug 1 block but deletes/replaces 2. 
Havent really tested if it also does for shift left click.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

https://screenshots.skizzles.me/wAnA3/GUKeFAZO46.mp4
AS seen in the video you just hold shift right click on the ground and this happens.

## :bulb: Expected behavior (REQUIRED)

Not firing twice. So i can also fix my wrench :PanSmug:

## :scroll: Server Log

N/A

## :open_file_folder: /error-reports/ Folder

N/A

## :compass: Environment (REQUIRED)

[16:15:01 INFO]: Paper v1_16_R3
[16:15:01 INFO]: CS-CoreLib vDEV - 88 (git 6a39a9e7)
[16:15:01 INFO]: Slimefun vDEV - 769 (git d048f7f8)
[16:15:01 INFO]: Metrics build: #6
[16:15:01 INFO]:
[16:15:01 INFO]: Installed Addons: (1)
[16:15:01 INFO]:  LiteXpansion vDEV - 111 (git 64895074)

**Comment by WertiaCoffee** [comment]
Thanks I had the same issue
