### ISSUE TITLE
Constant 50% TPS loss at 20 TPS

### ISSUE THREAD

**Issue by DepressedMilkshake** [Slimefun/Slimefun4#2656]
## :round_pushpin: Description (REQUIRED)

Server stays at 19 - 20 TPS but entities and block placements are still delayed, as if the TPS was <15. I've already installed Clearlagg and have generated timings reports but I have no idea how the server stays at a consistent 50% TPS loss, even through restarts. Timings says "Slimefun::Task: io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask$$Lambda$5328 (Single) (SELF)" which is causing 680% tick. I have set up the startup parameters from Aikar's timings as well, but hasn't caused any noticeable differences.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

https://timings.aikar.co/?id=ee479657a0e946e7a661d5635229eac0

https://www.youtube.com/watch?v=TpPB3oknVJY&feature=youtu.be

Run Slimefun 4 on server (1.16.4) with plugins below:
Plugins (29): ClayTech, ClearLag, CS-CoreLib, EcoPower, Essentials, ExoticGarden, ExtraGear, ExtraHeads, ExtraTools, FluffyMachines, FoxyMachines, GriefPrevention, GSit, Harbor, HotbarPets, InfinityExpansion, LiteXpansion, LuckPerms, MassiveCore*, MobCapturer, MoreTools, ServerRestorer, Slimefun, SlimefunOreChunks, SlimefunWarfare, SlimyPowerSuits, SlimyTreeTaps, SoulJars, WorldEdit

## :bulb: Expected behavior (REQUIRED)

TPS Loss % not staying at 50 for entire server uptime, server shouldn't be jittering when its at 20 TPS, i don't even know how this is possible, I've never had this issue before.

## :scroll: Server Log

https://pastebin.com/ND9Pi6ma

## :open_file_folder: /error-reports/ Folder

https://pastebin.com/TFjYpECC

## :compass: Environment (REQUIRED)

 - Server Software: 
<img width="960" alt="ee" src="https://user-images.githubusercontent.com/63175510/103176500-3806ab00-4840-11eb-96b1-86a57831d704.png">

 - Minecraft Version: Java 1.16.4
 - Slimefun Version: DEV 562
 - CS-CoreLib Version: DEV 92

**Comment by TheBusyBiscuit** [comment]
Please only use the Bug Tracker for Bug Reports.

The error you posted is from InfinityExpansion, not from Slimefun.
Also read up on how to investigate lag here: https://github.com/Slimefun/Slimefun4/wiki/Server-Optimizations
