### ISSUE TITLE
Shulker within shulker in a cargo system.

### ISSUE THREAD

**Issue by sarhatabaot** [Slimefun/Slimefun4#2662]
## :round_pushpin: Description (REQUIRED)

You can place shulkers within shulkers using a cargo manager.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Create a cargo system by placing down your cargo manager.
2. Create the input by putting down a chest with a cargo note (input)
3. Create the output by putting down a shulker box with a cargo note (output)
4. Put shulker boxes into the input chest

https://puu.sh/H1Rtd/a417f1af67.png
https://puu.sh/H1Rte/f89f7fffba.png

## :bulb: Expected behavior (REQUIRED)

Shulkers should be stacked instead of placed into a shulker.

## :scroll: Server Log

N/A

## :open_file_folder: /error-reports/ Folder

N/A

## :compass: Environment (REQUIRED)

Paper v1_16_R3
CS-CoreLib vDEV - 92 (git e9150d72)
Slimefun vDEV - 769 (git d048f7f8)
Metrics build: #6
Backwards compatibility enabled!
Installed Addons: (9)
DyedBackpacks vDEV - 11 (git b8eda0c7)
SFCalc vDEV - 14 (git 8d205b67)
SlimefunOreChunks vDEV - 10 (git 91df3b8e)
SlimyTreeTaps vDEV - 16 (git 46272e92)
ExtraGear vDEV - 12 (git 4570ea2c)
SlimefunLuckyBlocks vDEV - 30 (git 26824119)
FluffyMachines vDEV - 56 (git dcefabe9)
ExoticGarden vDEV - 64 (git ef338f99)
ChestTerminal vDEV - 38 (git c024be5c)

**Comment by variananora** [comment]
Can confirm that shulker nesting is possible.

https://user-images.githubusercontent.com/34732414/104190101-27645080-544e-11eb-808a-f0dad1e8f22f.mp4

Tested on version:
![image](https://user-images.githubusercontent.com/34732414/104190024-0dc30900-544e-11eb-9c45-2d4b58bbfce5.png)
