### ISSUE TITLE
Crucible gui needs changing.

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun/Slimefun4#2667]
## :round_pushpin: Description (REQUIRED)

When setting up an electrified crucible to intake cobblestone and empty buckets to make lava it is possible that the buckets returning to the system can arrive in the crucible before cobblestone does when one slot is empty. For example, I set mine up to put buckets on the left and cobble on the right on the input side. Once there are 16 buckets on the left, if a 17th tries to enter and there is no cobblestone present in the crucible, the bucket occasionally gets in the 2nd input slot and therefore stops the crucible from receiving cobblestone and stops lava production.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. place down the crucible
2. attach input node to pull lava out
3. attach output node to receive cobblestone and buckets
4. ensure you have more than 16 buckets trying to get into the crucible
5. over time, this problem described above will happen. 

## :bulb: Expected behavior (REQUIRED)

An easy solution to this problem would be to redo the gui so the buckets have their own identified slot, the cobble will have its own spot and the output lava has its own spot. Then make it so only those items can go into those slots, preventing the crucible from having either all buckets or all cobblestone and stop working.

## :scroll: Server Log

no errors

## :open_file_folder: /error-reports/ Folder

none. I don't believe this problem is a bug, as it just wasn't forseen it could happen.

## :compass: Environment (REQUIRED)

 - Server Software: spigot 1_16_R2
 - Minecraft Version: 1.16.3
 - Slimefun Version: Dev 768
 - CS-CoreLib Version: Dev 92

**Comment by TheBusyBiscuit** [comment]
The crucible still works as intended though, doesn't it?
This doesn't really sound like a "bug" to me, more like an UX improvement.
