### ISSUE TITLE
Talisman of the Magician doesn't give extra enchantments on books, even when it says it does

### ISSUE THREAD

**Issue by j-tai** [Slimefun/Slimefun4#2679]
## :round_pushpin: Description (REQUIRED)

If you have a Talisman of the Magician in your inventory, enchanting a book in an enchanting table does not give an extra enchantment, even when the chat says "Your Talisman gave you an additional Enchantment."

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Put a Talisman of the Magician in your inventory
2. Enchant a book in an enchanting table, with no bookshelves nearby. Repeat if necessary.
    → You will receive only 1 enchantment on the book, even though the talisman said that it gave you an extra enchantment.

## :bulb: Expected behavior (REQUIRED)

Since the talisman gives an "extra" enchantment, I would expect to get at least two enchantments on the book.

If the talisman is not supposed to give extra enchantments on books, then it should not say that it gave an extra enchantment when you enchant a book.

## :scroll: Server Log

No Notable Logs

## :open_file_folder: /error-reports/ Folder

No Error Reports

## :compass: Environment (REQUIRED)

 - Server Software: Paper git-Paper-366
 - Minecraft Version: 1.16.4
 - Slimefun Version: DEV - 771 (git f2dd3a01)
 - CS-CoreLib Version: DEV - 92 (git e9150d72)

**Comment by variananora** [comment]
Can confirm using this version and plugins.

![image](https://user-images.githubusercontent.com/34732414/104162606-86629f00-5427-11eb-8943-d3b82f28c97e.png)

https://user-images.githubusercontent.com/34732414/104162618-8b275300-5427-11eb-93cb-a933f5ff03d4.mp4

**Comment by TheBusyBiscuit** [comment]
Thank you @variananora
