### ISSUE TITLE
WTF

### ISSUE THREAD

**Issue by kebufu** [Slimefun/Slimefun4#2725]
## :round_pushpin: Description (REQUIRED)

![QQ截图20210115225727](https://user-images.githubusercontent.com/31839741/104742348-4849e000-5785-11eb-84a4-845b9ee23c3d.png)

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. update MetricsModule

## :bulb: Expected behavior (REQUIRED)

null

## :compass: Environment (REQUIRED)

 - Server Software: paper
 - Minecraft Version: 1.16.3
 - Slimefun Version: 4.3-stable-200802
 - CS-CoreLib Version:1.6.3

**Comment by J3fftw1** [comment]
You are using a modified version

**Comment by kebufu** [comment]
BTW, please look this
![QQ截图20210115231305](https://user-images.githubusercontent.com/31839741/104743969-47b24900-5787-11eb-96a7-36997256960a.png)

**Comment by kebufu** [comment]
lastest Slimefun with 1.6.3 CS-CoreLib

**Comment by J3fftw1** [comment]
It downloaded metrics whats wrong with it

**Comment by TheBusyBiscuit** [comment]
> lastest Slimefun with 1.6.3 CS-CoreLib

You are not using our Slimefun...
Wrong plugin.

**Comment by WalshyDev** [comment]
![image](https://user-images.githubusercontent.com/8492901/104744140-6fcc8880-5744-11eb-8886-fc14a30f05e6.png)
This is an actual Slimefun build.

**Comment by kebufu** [comment]
MD5: 38931ECC646703E6CBCC45E7A250D642
SHA1: 29430A08A9A04AECCD15839744113AEABB90A51E
CRC32: 762043CE
IDK what's problem

**Comment by J3fftw1** [comment]
Whats your question or your issue.
You are really unclear about it

**Comment by kebufu** [comment]
> Whats your question or your issue.
> You are really unclear about it

over 100 percert
I am sorry because My English so junk.

**Comment by J3fftw1** [comment]
When something is 100 % it means it completed the download

**Comment by kebufu** [comment]
but it over 100 %,I think this is a bug

**Comment by kebufu** [comment]
![QQ截图20210115232339](https://user-images.githubusercontent.com/31839741/104745211-c9ef3d00-5788-11eb-8226-6a177e577f7f.png)
47432 bytes......

**Comment by J3fftw1** [comment]
Are you even using official slimefun version if so run /sf versions and send it

**Comment by kebufu** [comment]
![QQ截图20210115232809](https://user-images.githubusercontent.com/31839741/104745706-57cb2800-5789-11eb-9481-5b4bed84169b.png)

**Comment by J3fftw1** [comment]
We dont support rc builds

**Comment by kebufu** [comment]
I download it at https://github.com/Slimefun/Slimefun4/releases

**Comment by NCBPFluffyBear** [comment]
https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/

**Comment by kebufu** [comment]
How should i download?

**Comment by J3fftw1** [comment]
See the link @NCBPFluffyBear send and click the green text

**Comment by kebufu** [comment]
![QQ截图20210115233513](https://user-images.githubusercontent.com/31839741/104746503-551d0280-578a-11eb-993e-02b3fde994c9.png)
still

**Comment by J3fftw1** [comment]
Run /sf versions pleass

**Comment by kebufu** [comment]
![QQ截图20210115233812](https://user-images.githubusercontent.com/31839741/104746825-be047a80-578a-11eb-9562-6ef5ee6fb4c5.png)

**Comment by TheBusyBiscuit** [comment]
Alright, please make a new bug report with that version then and give detailed descriptions on what exactly the issue is and how it happened.

**Comment by kebufu** [comment]
I have a easy way to solve this problem:
```java
                if (percent != 0 && percent != lastPercentPosted.get()&&percent<=100) {
                    plugin.getLogger().info("# Downloading... " + percent + "% " + "(" + bytesWritten + "/" + totalBytes + " bytes)");
                    lastPercentPosted.set(percent);
                }```

**Comment by TheBusyBiscuit** [comment]
I mean the actual problem is the wrong file size, not necessarily the percentage.
You can either open a new issue with all the necessary details or make a pull request.
