### ISSUE TITLE
i´m must repeat block destroy 

### ISSUE THREAD

**Issue by makecodemaster** [Slimefun/Slimefun4#2736]
⚠️ error:
i must to destroy block repeat block destroying...

ℹ️  my informations:
 - my minecraft nickname: spaceX_cz
 - Server Software: unkown
 - Minecraft Version: forge 1.12.2
 - Slimefun Version: unkown
 - CS-CoreLib Version: unkown

**Comment by variananora** [comment]
You must follow the template for bug reports.
Also report this to your server's developer/owner not Slimefun.
