### ISSUE TITLE
enchantment errors with talismans

### ISSUE THREAD

**Issue by AwesomeGamer333** [Slimefun/Slimefun4#2760]
## :round_pushpin: Description (REQUIRED)

when I use the ender talisman of the wizard and/or the ender talisman of the magician, there are some bugs that occur.
it is possible to get enchantments that are unobtainable through enchantment tables, like mending and curses
sometimes it says I got an extra enchantment but I didn't (not shown in the video)
it says some enchantment levels have been lowered but they have actually been raised

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. equip the ender talisman of the wizard and/or magician
2. enchant any item via an enchantment table. it is easier to reproduce if the enchantment level is lower.
3. one of the following bugs may occur

## :bulb: Expected behavior (REQUIRED)

1. you enchant an item through an enchantment table
2. if it says u got an extra enchantment you get an extra enchantment that is not mending or curse of vanishing/binding
3. if it says some levels may be lowered then they are lowered and not raised

## :scroll: Server Log

I can't access logs from more than one day ago for some reason :/

## :open_file_folder: /error-reports/ Folder

there are no error reports

## :compass: Environment (REQUIRED)

 - Server Software: I don't know
 - Minecraft Version: optifine 1.16.4
 - Slimefun Version: vDEV - 784 (git ac590fdd)
 - 
![2021-01-24_14 22 00](https://user-images.githubusercontent.com/64745070/105640999-ae9ec480-5e4f-11eb-8671-b5dcd01fc02d.png)
https://youtu.be/sYCMY2ZAr4Y

**Comment by TheBusyBiscuit** [comment]
Your Slimefun version is pretty far behind, you should update.
