### ISSUE TITLE
Incorrect machine speeds

### ISSUE THREAD

**Issue by hex8F** [Slimefun/Slimefun4#2761]
## :round_pushpin: Description (REQUIRED)

Some electric machines instantly process their items, even when they shouldn't have.
From a quick test, it appears that affected machines are: 
Heated Pressure Chamber, Electrified Crucible, Carbon Press, Auto Drier, Refinery,
Electric Press, Electric Ingot Pulverizer (but not with every ingot), Freezer, Food Composter, Food Fabricator.
Might have missed something though.

Video here: www.youtube.com/watch?v=OKpQQupa-CE

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

Use one of the aformentioned machines.

## :bulb: Expected behavior (REQUIRED)

To machines use their normal processing time, not finishing everything in an instant.

## :scroll: Server Log

Nothing in server logs.

## :open_file_folder: /error-reports/ Folder

No error logs in folder.

## :compass: Environment (REQUIRED)

 - Server Software: Paper git-Paper-444 (MC: 1.16.5)
 - Slimefun Version: Slimefun vDEV - 796 (git 0b4c2f2e)

**Comment by TheBusyBiscuit** [comment]
What tiers were these machines?

**Comment by hex8F** [comment]
They all were tier 1's.
