### ISSUE TITLE
Woodcutter Android replant the fungus to the netherrack

### ISSUE THREAD

**Issue by andris155** [Slimefun/Slimefun4#2793]
## :round_pushpin: Description (REQUIRED)

Woodcutter Android replant the warped fungus and the crimson fungus to the netherrack.
On the vanilla Minecraft this is impassible.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

https://www.youtube.com/watch?v=zDba-_TiP_I

## :bulb: Expected behavior (REQUIRED)

Woodcutter Android no replant the fungus to the netherrack.

## :compass: Environment (REQUIRED)

[23:05:28 INFO]: Yatopia git-Yatopia-"f8c5c21" (MC: 1.16.5)
[23:05:28 INFO]: Slimefun vDEV - 806 (git fe42f6fa)
[23:05:28 INFO]: Metrics build: #21
[23:05:28 INFO]:
[23:05:28 INFO]: Installed Addons: (1)
[23:05:28 INFO]:  ExtraTools vDEV - 23 (git 9299a65c)

**Comment by variananora** [comment]
In normal circumstances it will be fine.
Video: https://youtu.be/Nvh-pAf6RwM

But if you change the block then the problem occurs.
Video: https://youtu.be/-Ze0EV3Z27E

This also works with any other tree types.
Video: https://youtu.be/L1xBYOeCHzY

**Comment by andris155** [comment]
Thanks
