### ISSUE TITLE
Cycle in the Guide Book

### ISSUE THREAD

**Issue by F-Unction** [Slimefun/Slimefun4#2811]
## :round_pushpin: Description (REQUIRED)

I don't know how to make **Blistering Ingot**.

It requires **Heated Pressure Chamber**, but make **Heated Pressure Chamber** requires **Blistering Ingot**.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Open the *Guide Book*, and find make **Heated Pressure Chamber** requires **Blistering Ingot**.
2. Find **Blistering Ingot** in the *Guide Book*, and find make it requires **Heated Pressure Chamber**.
3. FUCK!!!!!

## :bulb: Expected behavior (REQUIRED)

There is a **cycle** that make me can't make Blistering Ingot.

## :scroll: Server Log

```
[Async Chat Thread - #7/INFO]: <[world]F_Unction> FUCK
```

## :open_file_folder: /error-reports/ Folder

```
nothing
```

## :compass: Environment (REQUIRED)

 - Server Software: Spigot `git-Spigot-628435a-768d7fc (MC: 1.16.4)`
 - Minecraft Version: `1.16.4`
 - Slimefun Version: `v4.9-stable-210130`

**Comment by TheBusyBiscuit** [comment]
You are not even using an official Slimefun version, we cannot provide any support for modified versions...
