### ISSUE TITLE
After using a villager rune, villagers will not take a new workstation

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun/Slimefun4#2813]
## :round_pushpin: Description (REQUIRED)

I started by giving 5 villagers different work stations, and traded with them to lock their profession. After they were traded with, i used 5 villager runes, one on each of the 5 villagers. They instantly lost their profession and were reset to unemployed villagers. After 40 minutes of placing different work stations directly in front of them with nothing blocking their ability to access the stations they would not take any of the work stations and remained unemployed villagers. So after using the rune, they were not able to take any work station, except the one they were before the rune was applied. 

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. give a villager a profession
2. Trade with the villager to lock the profession
3. apply the villager rune
4. place down workstations after any amount of time other than the one they originally had and they will not take the new profession

## :bulb: Expected behavior (REQUIRED)

I expected them to take on any new profession as the guide says. 

## :scroll: Server Log

no errors

## :open_file_folder: /error-reports/ Folder

no errors

## :compass: Environment (REQUIRED)

 - Server Software:  paper 439
 - Minecraft Version: 1.16.5
 - Slimefun Version: Dev 815

**Comment by TheBusyBiscuit** [comment]
That's already been reported a lot of times.
Almost everytime it was due to Minecraft just being weird.
The new Villager AI and API are still not really reliable, villagers sometimes get stuck very easily.

**Comment by Boomer-1** [comment]
I found a quick workaround for now if this helps....
after hitting the villager with the rune, place the original workstation back down, then break it and any other station will then work.

**Comment by TheBusyBiscuit** [comment]
Yeah, that reinforces the thought about the Villager AI / API being funky.
They probably cache the workstation until a block update occurs.
