### ISSUE TITLE
Slimefun + EcoEnchant Incompatible 

### ISSUE THREAD

**Issue by AccioAce** [Slimefun/Slimefun4#2821]
## :round_pushpin: Description (REQUIRED)

Hello, I was told to make an report with slimefun by a plugin developer name Auxilor. I'm using this plugin call ecoenchants which I will provide the link and wiki below. This plugin allows MC servers to have custom enchantments. There is a configuration that allow us to disable players from obtaining custom enchantments which are villagers, loot chests, and enchanted table. But I have them all disabled and this took me a while figure out.

Even with the enchanted table, It looks like slimefun is interfering with it. Even if I have enchanted table disable players can use Talisman of the magician and ender talisman of the magician to get the lucky bonus enchant which allows them to get eco enchants custom enchant from the enchanted table. I was wondering is there a way for you guys to somehow fix it from happening? I would like to allow players to use the talisman but not to obtain custom enchants from eco enchants.

Eco Enchant: https://www.spigotmc.org/resources/%E2%9A%A1-1-15-1-16-5-ecoenchants-%E2%9C%A8-220-custom-enchantments-%E2%9C%85-essentials-cmi-support.79573/
Eco Enchant Wiki: https://ecoenchants.willfp.com/enchantments/obtaining

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

I explained above.

## :bulb: Expected behavior (REQUIRED)

I would like to have Talisman of the magician and ender talisman of the magician to not support eco enchants by allowing players to use it to get custom enchantments on their tools, armors, or books in any way when we disable the enchanted table section on eco enchants configuraton.

## :scroll: Server Log

I do not have any server log or console errors.

## :open_file_folder: /error-reports/ Folder

I do not have any server log or console errors.

## :compass: Environment (REQUIRED)

https://gyazo.com/eab352829db58bdd1835df76d6b8c60d

 - Server Software:  Paper
 - Minecraft Version: 1.16.5
 - Slimefun Version: vRC - 20 (git da6866ee)

**Comment by TheBusyBiscuit** [comment]
1. We do not support RC versions of Slimefun.
2. You can disable any enchantments from these talismans using Slimefun's `Items.yml` configuration file.
