### ISSUE TITLE
Search for items

### ISSUE THREAD

**Issue by SpeedCrazy** [Slimefun/Slimefun4#2825]
I would like to recommend something for slimefun in the future, every time you block an item in the guide and you click on search and write the blocked item, this item will not be invisible, I don't know if it's possible.

 - Server Software: 
 - Minecraft Version: 
 - Slimefun Version: 
![Screenshot_1](https://user-images.githubusercontent.com/33162694/107972014-fbc70f80-6f91-11eb-95fc-d81e2cde1ffd.png)

**Comment by J3fftw1** [comment]
Suggestions go on discord

**Comment by oahawhool** [comment]
I think I saw the convo you had in discord and I think what you are describing is that you don't want the users to be able to craft a particular item.
I think you said that you disabled the item sorta, and it does not show up in the guide, but, if users search for the item, it does show up in the search results and they can craft it.
Is that correct?
