### ISSUE TITLE
Auto Enchanter Enchantments Bug

### ISSUE THREAD

**Issue by Dr-Bad** [Slimefun/Slimefun4#2846]
## :round_pushpin: Description (REQUIRED)
Hi, I am a player of a server and I realized that when using Auto Enchanter, if the level of a Enchantment of a Enchanted book is lower than your tool or weapon, it will be replaced with higher level.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)
Put a book with a high-level Enchantment(Unbreaking 1) and a weapon or a tool with a low-level Enchantment(Unbreaking 3) in Auto Enchanter.

## :bulb: Expected behavior (REQUIRED)
Lower level Enchantment should not replace with higher level Enchantment.

## :compass: Environment (REQUIRED)
SlimeFun Version: Dev - 822 (git [c4be51f](https://github.com/Slimefun/Slimefun4/commit/c4be51f7bb6462b99ddaf135e518f5a3c9243690))
Minecraft Version: 1.16.4-R0.1-SNAPSHOT

Sorry for my bad English.

**Comment by TheBusyBiscuit** [comment]
That is definitely not a bug...
The Auto Enchanter will override these enchantments.
If you want this to change, make a suggestion on discord and perhaps a config option could be added.
But this is definitely not valid for a bug report.

**Comment by variananora** [comment]
Same issue with #2805 but with Book Binder.
