### ISSUE TITLE
Output chest drops nothing on break

### ISSUE THREAD

**Issue by Kbryst** [Slimefun/Slimefun4#2849]
## :round_pushpin: Description (REQUIRED)

My players have been reporting for no more than two weeks that output chests don't drop their items when they break them. When they place the chests back down they are empty (as intended). 

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Place some items in an output chest.
2. Break output chest.

## :bulb: Expected behavior (REQUIRED)

Output chest should drop the items inside it on chest break.

## :scroll: Server Log

https://pastebin.com/gAMzSYPd

## :open_file_folder: /error-reports/ Folder

Folder empty

## :compass: Environment (REQUIRED)

Paper git-Paper-486 (MC: 1.16.5)
Slimefun DEV - 822 (git c4be51f7)
Metrics-Module #21
Java 11

Installed Addons: (12)
  DyedBackpacks vDEV - 13 (git 964b2d55)
  ExtraHeads vDEV - 21 (git a2c68d59)
  EcoPower vDEV - 3 (git 18ba903d)
  HotbarPets vDEV - 35 (git 99093ddd)
  SlimyTreeTaps vDEV - 17 (git 8f3e755b)
  PrivateStorage vDEV - 16 (git f9468f23)
  ExtraGear vDEV - 12 (git 4570ea2c)
  ColoredEnderChests vDEV - 20 (git 2f2c1dfc)
  SlimefunLuckyBlocks vDEV - 31 (git 6fa9afbd)
  CMI v8.8.0.7
  ExoticGarden vDEV - 73 (git ae423e3e)
  ChestTerminal vDEV - 42 (git f4aef9ca)

**Comment by variananora** [comment]
Confirmed.

https://user-images.githubusercontent.com/34732414/109375526-fc479a80-78ef-11eb-8b35-b19c7f7b7cde.mp4
