### ISSUE TITLE
Loose handling of item NBT allows creation of fraudulent items.

### ISSUE THREAD

**Issue by MHFDoge** [Slimefun/Slimefun4#2850]
## :round_pushpin: Description (REQUIRED)

There is currently a bug involving Slimefun accepting renamed items as legitimate slimefun objects. I noticed that legitimate slimefun objects have an NBT tag applied to them which I originally thought was what the plugin used to determine whether an item is a slimefun item or not, but alas this does not appear to be the case on both a production server and locally. This appears to be present on the most recent release at the time of writing this(RC-20(da6866ee)) although, as expected, is present in past releases as well.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Ensure you have some way to rename items(essentials /irename for example) 
2. Set the name of an item of the same type to the matching contents of a slimefun item that does not have lore(ex: renaming a player head to `&4Carbon Chunk`(yes this also works with items that are present as heads))
3. Attempt to use that item in a slimefun machine for whatever the item is usable for(ex: lead dust in a smeltery turns into a lead ingot)

## :bulb: Expected behavior (REQUIRED)

Expected behavior: The item does not work, as it is lacking the proper Slimefun NBT tag and is just a renamed item.
Actual behavior: The item behaves as if it were a legitimate item.
Below: Actual slimefun item.
![image](https://user-images.githubusercontent.com/46448580/109394834-a3c3cd80-78ee-11eb-86bd-f94ef0445daa.png)

Below: Fraudulent slimefun item.
![image](https://user-images.githubusercontent.com/46448580/109394891-f1d8d100-78ee-11eb-816b-e2daae5dc4c4.png)
Both behave as proper items even though one is not.

## :scroll: Server Log

N/A

## :open_file_folder: /error-reports/ Folder

N/A

## :compass: Environment (REQUIRED)

![image](https://user-images.githubusercontent.com/46448580/109394765-43349080-78ee-11eb-87ec-5abe22acd7a4.png)

 - Server Software:  Paper build 463
 - Minecraft Version: 1.16.5
 - Slimefun Version: RC 20 (da6866ee)

**Comment by MHFDoge** [comment]
Erm, of what issue is this a duplicate of exactly?

**Comment by TheBusyBiscuit** [comment]
Duplicate of #2842 
Duplicate of #2832 
Duplicate of #2797
And also duplicate of #2582 (underlying problem is the same).

I realize that googling or searching for things might be an effort...
But I am quite tired of repeating myself over and over again at this point.
Don't allow your players to rename items with color codes, simple solution.

**Comment by MHFDoge** [comment]
If the items are handled by name and lore then what is the purpose of the applied slimefun nbt tag is if it is not functioning.?

**Comment by TheBusyBiscuit** [comment]
I linked you more than enough sources already.
I really see no point in repeating myself yet again...

Clicking a link and reading is not too much to ask for.
I am locking this thread as spam, if you have any further questions, feel free to ask them on discord - though everything has already been answered already.

**Comment by TheBusyBiscuit** [comment]
Locking this might have been a bit of an overreaction, sorry.
But like I said: if you have further questions, feel free to ask them on discord. Though every necessary info can already be found in the Issues I linked above.
