### ISSUE TITLE
Output Chest dupe glitch

### ISSUE THREAD

**Issue by eastrain07** [Slimefun/Slimefun4#2851]
## :round_pushpin: Description (REQUIRED)

When breaking output chest connected with normal chest, the chest drops item in the chest, but the item in normal chest doesn't get cleared

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Place a output chest next to normal chest
2. Open the chest and put any item in the chest
3. Break output chest

## :bulb: Expected behavior (REQUIRED)

Output chest drops itself and items in the chest and normal chest still has its item

## :compass: Environment (REQUIRED)

 - Server Software: Paper-503 MC 1.16.5
 - Minecraft Version: 1.16.5 (1.16.5-RO.1-SNAPSHOT)
 - Slimefun Version: DEV - 823 (git 84ad08be)

**Comment by variananora** [comment]
Confirmed.

https://user-images.githubusercontent.com/34732414/109450805-68f09f80-7a7e-11eb-996c-765c639a1fd3.mp4
