### ISSUE TITLE
Block Placer doesn't drop item in it when broken

### ISSUE THREAD

**Issue by eastrain07** [Slimefun/Slimefun4#2852]
## :round_pushpin: Description (REQUIRED)

Block Placer doesn't drop item in it when broken

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Place a item placer
2. Put any item in it
3. Break the placer

## :bulb: Expected behavior (REQUIRED)

Item in the placer gets deleted

## :compass: Environment (REQUIRED)

 - Server Software: Paper-503 MC 1.16.5
 - Minecraft Version: 1.16.5 (1.16.5_RO.1-SNAPSHOT)
 - Slimefun Version: DEV - 823 (git 84ad08be)

**Comment by variananora** [comment]
Confirmed.

https://user-images.githubusercontent.com/34732414/109450947-cf75bd80-7a7e-11eb-92eb-40e451cf0cba.mp4
