### ISSUE TITLE
Geo-miners leave behind holograms when broken (Seems to dupe them as well?)

### ISSUE THREAD

**Issue by Nekosity12** [Slimefun/Slimefun4#2861]
## :round_pushpin: Description (REQUIRED)

Place a geo-miner, doesn't matter if you geo-scanned or not as it will still display a hologram (I.E. "Geo-scan required!") then simply break it. The hologram remains left behind. In some areas there were even multiple holograms to kill.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Place geo-miner
2. Break geo-miner
3. Stare at the left behind hologram wondering what wrong
https://youtu.be/MB6kZ4Gr8-U

## :bulb: Expected behavior (REQUIRED)

The hologram to disappear.
I think the hologram disappearing would have been the correct behavior.

## :scroll: Server Log

No Errors

## :open_file_folder: /error-reports/ Folder

No Errors

## :compass: Environment (REQUIRED)

 - Server Software: Purpur 1.16.5
 - Minecraft Version: 1.16.5
 - Slimefun Version: DEV - 825

**Comment by variananora** [comment]
The workaround for now is to place it and break it again.
It's kinda 'common issue' (https://github.com/Slimefun/Slimefun4/wiki/Common-Issues)
Waiting for the TheBusyBiscuit to response.

**Comment by Mooy1** [comment]
Occurs for me aswell, same environment as above.

**Comment by TheBusyBiscuit** [comment]
Can confirm that this happens.
