### ISSUE TITLE
Item in android interface(fuel and item) will disappear

### ISSUE THREAD

**Issue by MrPolloo** [Slimefun/Slimefun4#2887]
## :round_pushpin: Description (REQUIRED)

Item in android interface(fuel and item) will disappear when i try to break the android interface.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Place Android Interface(Fuel or Items)
2. Place items inside the android interface
3.  Break the android interface
4.  And the item inside will disappear

## :bulb: Expected behavior (REQUIRED)

item inside android interface will drop like another machine

## :compass: Environment (REQUIRED)

- Server Software: Paper-534
- Minecraft Version: 1.16.5
- Slimefun Version: Slimefun RC - 21 (git c1fb5e12)

**Comment by variananora** [comment]
Confirmed

![image](https://user-images.githubusercontent.com/34732414/111433549-fc89c780-8730-11eb-9b5c-b0a1f8b44eb8.png)

https://user-images.githubusercontent.com/34732414/111433506-f1cf3280-8730-11eb-9953-c659238295b6.mp4

**Comment by TheBusyBiscuit** [comment]
Also for the future: We do not support RC versions of Slimefun...
