### ISSUE TITLE
Enhanced auto crafter won't craft items that override right-click functionality

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun/Slimefun4#2896]
## :round_pushpin: Description (REQUIRED)

In the enhanced auto crafter I found a number of items that when crouch clicking on it, nothing happens, or we get an error message saying there's no recipe.

Advanced Circuit Boards
Motors
Cargo Motors
Electromagnets
Heating Cools
Cooling Units
Android memory core
Tier 4 & 5 lumps
All items that the Exotic Garden essences make - a little confusing as the guide says to crouch click the item you want to craft, but you have to click with the actual essence.
All IE storage units
Carbon Chunks

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Craft any of the items above
2. Crouch Click the item on the enhanced crafter
3. 

## :bulb: Expected behavior (REQUIRED)

Given that all these items have craftable recipes in an enhanced crafting table, I thought they would be crafted in the enhanced auto crafter.

## :scroll: Server Log

no erros

## :open_file_folder: /error-reports/ Folder

no error reports

## :compass: Environment (REQUIRED)

 - Server Software: paper 552
 - Minecraft Version: 1.16.5
 - Slimefun Version: 846

**Comment by TheBusyBiscuit** [comment]
Can confirm.
It appears to affect all items which override right-click functionality. This includes unplaceable items, such as coolant cells but also items with right-click functionality like the Multimeter or Ender backpack.
