### ISSUE TITLE
Auto-crafters do not craft items even though the recipe product can fit in the chest

### ISSUE THREAD

**Issue by martinbrom** [Slimefun/Slimefun4#2901]
## :round_pushpin: Description (REQUIRED)

Autocrafters only check for a completely empty spot in the chest and disregard any spots which contain the same item as the recipe product, see screenshot below.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Fill the auto crafter chest with correct ingredients
2. Fill one chest slot with the same item as the product of the selected recipe
3. Fill the rest of the chest with other items

![SF Screenshot](https://user-images.githubusercontent.com/16322387/112024428-786e8000-8b34-11eb-871c-a451263ac3c9.png)

## :bulb: Expected behavior (REQUIRED)

The recipe is used and the product is added to the chest

I feel like AbstractAutoCrafter.java#L342 should not only check for an empty slot but rather check if the product of the recipe fits.

## :scroll: Server Log

Unfortunately do not have access

## :open_file_folder: /error-reports/ Folder

Unfortunately do not have access

## :compass: Environment (REQUIRED)

 - Server Software: not sure
 - Minecraft Version: 1.16.5-R0.1-SNAPSHOT
 - Slimefun Version: DEV 847 (git 001e7654)

**Comment by TheBusyBiscuit** [comment]
Auto Crafters require an empty slot to craft the item.
It is intended to work this way.

**Comment by LilBC** [comment]
Awww... Sad, why tho? Is it just because the auto crafter will be too op if it works like that?
