### ISSUE TITLE
Crucibles when next to each other don't make lava

### ISSUE THREAD

**Issue by Nekosity12** [Slimefun/Slimefun4#2903]
## :round_pushpin: Description (REQUIRED)

When you activate multiple crucibles beside each other they try to make lava but it cancels out and you get nothing

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Get 2 or more crucibles
2. Place them directly beside each other
3. Activate them with cobblestone to begin the lava making process
https://youtu.be/JoOVaRbo5lw
## :bulb: Expected behavior (REQUIRED)

Continue to make lava until it's finished, then the lava remains there flowing out if there's nothing to contain it.

## :scroll: Server Log

N/A

## :open_file_folder: /error-reports/ Folder

N/A

## :compass: Environment (REQUIRED)

 - Server Software: Purpur
 - Minecraft Version: 1.16.5
 - Slimefun Version: DEV 850

**Comment by variananora** [comment]
Confirmed.

![image](https://user-images.githubusercontent.com/34732414/112299009-f57f2e00-8cc9-11eb-97f5-88b259b29fd5.png)



https://user-images.githubusercontent.com/34732414/112299021-f87a1e80-8cc9-11eb-930f-e16eb13bd74d.mp4
