### ISSUE TITLE
Automated Ignition Chamber dupe items

### ISSUE THREAD

**Issue by NovaStream2030** [Slimefun/Slimefun4#2906]
## :round_pushpin: Description (REQUIRED)
When the Automated Ignition Chamber is broken, items from it are doubled

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)
https://youtu.be/6hAKlnGN41A

## :bulb: Expected behavior (REQUIRED)
Items do not multiply

## :compass: Environment (REQUIRED)
![image](https://user-images.githubusercontent.com/21084913/112472806-2336a680-8da0-11eb-805a-5aca1e8490a5.png)

**Comment by variananora** [comment]
Confirmed only happening in Spigot, but not on Paper/Tuinity.

<details>
<summary>Spigot:</summary>

![image](https://user-images.githubusercontent.com/34732414/112474653-7c073e80-8da2-11eb-8bd4-648b49af33df.png)


https://user-images.githubusercontent.com/34732414/112474715-8b868780-8da2-11eb-9eb4-4ebf0df04164.mp4


</details>


<details>
<summary>Paper:</summary>

![image](https://user-images.githubusercontent.com/34732414/112474458-3b0f2a00-8da2-11eb-9727-f66261c3e081.png)


https://user-images.githubusercontent.com/34732414/112474510-4d896380-8da2-11eb-9ee8-dd423903dfee.mp4


</details>

**Comment by variananora** [comment]
Also works with:
- Output Chest
- All Enhanced Furnace
- Block Placer

Update soon if I found out more.

**Comment by TheBusyBiscuit** [comment]
Reeee, why is Spigot always so full of bugs we need to work around...
