### ISSUE TITLE
Infinity Barrels can have the Quick Action glass pane removed

### ISSUE THREAD

**Issue by bunnkywhat** [Slimefun/Slimefun4#2910]
## :round_pushpin: Description (REQUIRED)

After update 853, Infinity Barrels can have the Quick Action glass pane removed when the barrel is empty. When the glass pane is removed and you click the empty slot, SF throws an error, reported in the pastebin below.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Place an Infinity Storage Unit (Any size works)
2. Open the Unit's GUI
3. Take the Quick Actions glass pane out like you would items in a storage container

## :bulb: Expected behavior (REQUIRED)

Nothing, the barrel is empty, it should function like the other glass panes when clicked (Except Status, now that toggles Void Excess)

## :scroll: Server Log

https://pastebin.com/JPqWV4z3

## :open_file_folder: /error-reports/ Folder

There is no file in the error-reports folder

## :compass: Environment (REQUIRED)

 - Server Software:  Paper git-Paper-487
 - Minecraft Version:  1.16.5
 - Slimefun Version: DEV-853
![Screenshot 2021-03-26 134229](https://user-images.githubusercontent.com/6545569/112671853-1f0a9780-8e39-11eb-9503-a99e33285401.png)

**Comment by WalshyDev** [comment]
This is the Slimefun issue tracker not the InfinityExpansion issue tracker. Report this there
