### ISSUE TITLE
Geo-miners leave behind holograms when broken

### ISSUE THREAD

**Issue by andris155** [Slimefun/Slimefun4#2914]
## :round_pushpin: Description (REQUIRED)

Place a geo-miner, doesn't matter if you geo-scanned or not as it will still display a hologram (I.E. "Geo-scan required!") then simply break it. The hologram remains left behind. In some areas there were even multiple holograms to kill.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Place down a geo-miner.
2. Break a geo-miner.
3. The hologram no removed.

https://www.youtube.com/watch?v=3-YlA4M9fu4

## :scroll: Server Log

The hologram to disappear when break a geo-miner.

## :open_file_folder: /error-reports/ Folder

None

## :compass: Environment (REQUIRED)

Tuinity git-Tuinity-"c303521" (MC: 1.16.5)
Slimefun DEV - 859 (git fd16306b)
Metrics-Module #21
Java 11

Installed Addons: (1)
  LiteXpansion vDEV - 138 (git 004e3c61)

**Comment by WalshyDev** [comment]
Was able to reproduce

SF b64be9827
Paper 497
MC 1.16.5
Java 14

**Comment by andris155** [comment]
Thanks
