### ISSUE TITLE
LiteXpansion UU-Matter recipes not work in Slimefun Auto-Crafter

### ISSUE THREAD

**Issue by andris155** [Slimefun/Slimefun4#2921]
## :round_pushpin: Description (REQUIRED)

LiteXpansion addon UU-Matter recipes not work in Slimefun Auto-Crafter.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Give and build Slimefun Auto-Crafters system.
2. Right click with item that can be made of UU-Matter.
3. UU-Matter recipe not selectable.

## :bulb: Expected behavior (REQUIRED)

LiteXpansion addon UU-Matter recipes works in Slimefun Auto-Crafter.

## :compass: Environment (REQUIRED)

Tuinity git-Tuinity-"c303521" (MC: 1.16.5)
Slimefun DEV - 864 (git 82366191)
Metrics-Module #21
Java 11

Installed Addons: (5)
  InfinityExpansion vDEV - 100 (git 65892de0)
  LiteXpansion vDEV - 138 (git 004e3c61)
  SlimefunFix v3.0
  FoxyMachines vDEV - 42 (git ae8d8aba)
  DynaTech vDEV - 90 (git 9f27da61)

**Comment by J3fftw1** [comment]
Wrong issue tracker

**Comment by TheBusyBiscuit** [comment]
This is the Slimefun issues tracker, not LiteXpansion.
