### ISSUE TITLE
Remove potion particle effects from Hazmat suit (Please)

### ISSUE THREAD

**Issue by Tarluin** [Slimefun/Slimefun4#2935]
## :round_pushpin: Description (REQUIRED)

Hazmat suit shows potion particle effects when worn.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Craft hazmat suit
2. wear hazmat suit
3. go crazy watching swirly particles

## :bulb: Expected behavior (REQUIRED)

No particle effects.

## :compass: Environment (REQUIRED)

![unknown](https://user-images.githubusercontent.com/10500203/113548543-51dd2a00-95b5-11eb-93a7-e0224102df6c.png)

**Comment by TheBusyBiscuit** [comment]
This is not even a bug report...
Suggestions go on discord.
