### ISSUE TITLE
Items on ancient pedastals despawn after 5 minutes

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun/Slimefun4#2939]
## :round_pushpin: Description (REQUIRED)

After building the ancient altar and pedestals, i placed an item in each pedestal. I did not finish the recipe for the final piece in the middle. 5 minutes later the items all despawned.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. PLace the ancient altar
2. place the pedastal
3. put items on each pedestal.
4. wait 5 minutes

## :bulb: Expected behavior (REQUIRED)

Items to not despawn

## :scroll: Server Log

no errors

## :open_file_folder: /error-reports/ Folder

no errors

## :compass: Environment (REQUIRED)

 - Server Software: Paper 552
 - Minecraft Version: 1.16.5
 - Slimefun Version: 869

**Comment by variananora** [comment]
Can confirm.

Video: https://youtu.be/zj70nZun_co
(Notes: Just watch for the first 30 seconds and just skip to 5 mins mark.)

<details>
<summary>/sf version</summary>


![image](https://user-images.githubusercontent.com/34732414/113651010-699ed600-96bb-11eb-9f62-b13d690c39fc.png)


</details>

**Comment by TheBusyBiscuit** [comment]
Items despawning after 5 minutes is a very normal thing in Minecraft...
This includes these items of course too.
