### ISSUE TITLE
Items on Ancient Pedestal can be burn with flowing lava or any fire from dispenser.

### ISSUE THREAD

**Issue by variananora** [Slimefun/Slimefun4#2941]
## :round_pushpin: Description (REQUIRED)

Items on Ancient Pedestal can be moved with burn with flowing lava or any fire from dispenser.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Place Ancient Pedestal
2. Put an item on it
3. Place a lava to burn the item
4. See the item burning and be unable to be picked up (or just gone)

https://user-images.githubusercontent.com/34732414/113652283-aff53480-96bd-11eb-97b7-3cf4d3a3f7c3.mp4

## :bulb: Expected behavior (REQUIRED)

Items on Ancient Pedestal should not be able to be burn with lava or fire.

## :scroll: Server Log

There is no relevant logs.

## :open_file_folder: /error-reports/ Folder

There is no error logs.

## :compass: Environment (REQUIRED)

![image](https://user-images.githubusercontent.com/34732414/113651678-a28b7a80-96bc-11eb-9e58-cedef57aba7f.png)

**Comment by TheBusyBiscuit** [comment]
To be honest... if people purposefully burn their items and then wonder why it's gone, that's on them.
