### ISSUE TITLE
[Slimefun] StrangeNetherGoo - 'STRANGE_NETHER_GOO' (Slimefun vDEV - 869 (git 18139bb5)): The Piglin Bartering chance must be between 1-99% on item: STRANGE_NETHER_GOO

### ISSUE THREAD

**Issue by TheSavior22** [Slimefun/Slimefun4#2946]
## :round_pushpin: Description (REQUIRED)

I am getting this error on the console every 10 seconds

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. 
2. 
3. 

## :scroll: Server Log

[Slimefun] StrangeNetherGoo - 'STRANGE_NETHER_GOO' (Slimefun vDEV - 869 (git 18139bb5)): The Piglin Bartering chance must be between 1-99% on item: STRANGE_NETHER_GOO
>.... [21:03:58 WARN]: [Slimefun] You can report this warning here: https://github.com/Slimefun/Slimefun4/issues

## :open_file_folder: /error-reports/ Folder

no file in error reports folder

## :compass: Environment (REQUIRED)

Metrics-Module #21
Java 11
Installed Addons: (27)
ExtraTools vDEV - 25 (git 209f9078)
FoxyMachines vDEV - 43 (git e0424fcd)
SlimefunOreChunks vDEV - 13 (git 9f7a2be3)
DynaTech vDEV - 94 (git 6d1ca164)
ExtraGear vDEV - 12 (git 4570ea2c)
ClayTech v1.2.21
InfinityExpansion vDEV - 100 (git 65892de0)
SFCalc vDEV - 18 (git e22c2127)
ElectricSpawners vDEV - 22 (git 4cb2c56b)
IllegalStack v2.2.2a
ExtraHeads vDEV - 21 (git a2c68d59)
MobCapturer vDEV - 15 (git a42c9e0c)
SlimyTreeTaps vDEV - 18 (git ab11a282)
ColoredEnderChests vDEV - 21 (git 2d3a859d)
TranscEndence vDEV - 23 (git c7ddc06a)
GeneticChickengineering vDEV - 13 (git 37cffcbb)
FluffyMachines vDEV - 74 (git 8da3ae26)
ChestTerminal vDEV - 42 (git f4aef9ca)
DyedBackpacks vDEV - 14 (git 0a051b2b)
SlimefunWarfare vDEV - 30 (git 9be48a83)
EcoPower vDEV - 3 (git 18ba903d)
HotbarPets vDEV - 36 (git 71e1a5e7)
SlimefunLuckyBlocks vDEV - 32 (git e108f086)
ExoticGarden vDEV - 75 (git 6c3e5412)
Liquid vDEV - 10 (git 2277a85b)
SimpleUtils vDEV - 3 (git ee043364)
SoulJars vDEV - 22 (git aded79dd)

 - Server Software: 
 - Minecraft Version: 
 Paper git-Paper-575 (MC: 1.16.5)
 - Slimefun Version: 
 Slimefun DEV - 869 (git 18139bb5)

**Comment by Boomer-1** [comment]
fyi - this is configurable in your items.yml file inside the Slimefun folder. By default it's set to 7%. check to see if you may have changed it.
