### ISSUE TITLE
Auto crafter still working after being disabled

### ISSUE THREAD

**Issue by J3fftw1** [Slimefun/Slimefun4#2957]
## :round_pushpin: Description (REQUIRED)
So i was also testing the enhanced auto crafter. soo it works when disabled. what works
Set a recipe in the enhanced auto crafter
stop the server
disable the auto crafter
start the server
you can open the gui.
You can also toggle of and on stuff inside the gui. 
but when the the recipe is turned of the machine breaks after a certain amount of time.
but it does display the wrong message. when trying to use the disabled auto crafter.
for example right clicking with empty hand shows 
![image](https://user-images.githubusercontent.com/44972470/114628041-8c7e4b00-9cb6-11eb-9712-c57cf3f4ac1f.png)
shift right clicking shows this message
![image](https://user-images.githubusercontent.com/44972470/114628114-a586fc00-9cb6-11eb-97aa-144e54bc5a63.png)
but when you do it with an item that shouldnt work on it like a vanilla chest it shows this
![image](https://user-images.githubusercontent.com/44972470/114628146-b59edb80-9cb6-11eb-8629-56ba33428754.png)
Another update on this when the machine is disabled and you interact with it you can steal the items inside of it
i just obtained a barrier

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)
Thanks to walshy for uploading the vid blobs.are-pretty.sexy/7FbFgdR.mp4

## :bulb: Expected behavior (REQUIRED)

To not work after being disabled

## :scroll: Server Log
N/A

## :open_file_folder: /error-reports/ Folder
N/A

## :compass: Environment (REQUIRED)
![image](https://user-images.githubusercontent.com/44972470/114578589-4fe22d80-9c7d-11eb-8245-887754851412.png)

**Comment by variananora** [comment]
Can confirm, but I can't reproduce the obtaining things from GUI part.

https://youtu.be/001nfTPj6hQ

**Comment by Boomer-1** [comment]
@J3fftw1 - with your test jar, upon following the steps above, the auto crafter stopped after disabling the autocrafter and restarting the server. while it was still in place i could set a recipe, but it would not run. once i broke it i could not place it
