### ISSUE TITLE
Carbonado edge furnace still working after being disabled

### ISSUE THREAD

**Issue by J3fftw1** [Slimefun/Slimefun4#2958]
## :round_pushpin: Description (REQUIRED)
When the carbonado edged furnace has been disabled with items still inside of it. It will still work with the speed the machine is normally it wont work on default furnace speed as you would expect.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)
Place down carbonado edged furnace with items inside of it.
Stop server
disable the furnace
start server
Furnace is still smelting at the speed of carbonado edged but it shouldnt

## :bulb: Expected behavior (REQUIRED)
Furnace to act like a normal furnace or to just being disabled and canceling the smelting

## :scroll: Server Log
N/A

## :open_file_folder: /error-reports/ Folder
N/A

## :compass: Environment (REQUIRED)
![image](https://user-images.githubusercontent.com/44972470/114578589-4fe22d80-9c7d-11eb-8245-887754851412.png)

**Comment by variananora** [comment]
Can confirm.


https://user-images.githubusercontent.com/34732414/115133782-09058680-a035-11eb-8559-2a29aa35ec7b.mp4

**Comment by Boomer-1** [comment]
@J3fftw1 with your test jar, once disabled the carbonado furnace was no longer accessible or placable. however the furnace still ran but at vanilla speeds. it is still recognized as a carbonado furnace just not accessible.
