### ISSUE TITLE
Blockplacer still functions after being disabled

### ISSUE THREAD

**Issue by J3fftw1** [Slimefun/Slimefun4#2959]
## :round_pushpin: Description (REQUIRED)
Blockplacer still functioning even when disabled if it has items inside of it

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)
Place blockplacer
place items inside of it
stop server
disable the blockplacer
start server
switch the lever to power the blockplacer
Sees blocks being placed

## :bulb: Expected behavior (REQUIRED)
Dispenser to stop working fully or to just work as a dispenser

## :scroll: Server Log
N/A

## :open_file_folder: /error-reports/ Folder
N/A

## :compass: Environment (REQUIRED)
![image](https://user-images.githubusercontent.com/44972470/114578589-4fe22d80-9c7d-11eb-8245-887754851412.png)

**Comment by variananora** [comment]
Can confirm.


https://user-images.githubusercontent.com/34732414/115134068-53880280-a037-11eb-84ac-cc21e5f012a6.mp4

**Comment by Boomer-1** [comment]
@J3fftw1 with your test jar the block placer did become disabled and acted like a vanilla dispenser. it also still recognized it as a disabled item asking how i got it.
