### ISSUE TITLE
Android Woodcutter will stuck on chopping tree if the inventory is full until the fuel ran out.

### ISSUE THREAD

**Issue by variananora** [Slimefun/Slimefun4#2964]
## :round_pushpin: Description (REQUIRED)

Android Woodcutter will stuck on chopping tree if the inventory is full until the fuel ran out.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Place Woodcutter Android
2. Plant a tree
3. Wait until the inventory is full (or just 'force' fill it)
4. See that loop on breaking the tree until the fuel ran out

<details>
<summary>Video</summary>

https://user-images.githubusercontent.com/34732414/115132937-b032ef80-a02e-11eb-9af4-01b17804d2c0.mp4

</details>

## :bulb: Expected behavior (REQUIRED)

I guess like a Farmer Android just skip past that block or kinda like Android Miner just mine the blocks but the items go missing.

## :scroll: Server Log

There is no relevant server logs.

## :open_file_folder: /error-reports/ Folder

There is no error logs.

## :compass: Environment (REQUIRED)

![image](https://user-images.githubusercontent.com/34732414/115132959-cb056400-a02e-11eb-8091-5ee32ba50597.png)

**Comment by Boomer-1** [comment]
I've had this before as well. The android will continue to attempt to chop the tree, and the wood will have the animation but it keeps using fuel
