### ISSUE TITLE
Enhanced Crafting Table and Magical Workbench Error

### ISSUE THREAD

**Issue by DimitriVasiliadis** [Slimefun/Slimefun4#2972]
## :round_pushpin: Description (REQUIRED)

The first sign of problems was when regular crafting tables started crashing people with the error Ticking screen and Rendering screen. It was hard to replicate so nothing was resolved. Now enhanced crafting tables and magical workbenches produce an error in console and do not work. The errors are: 

https://pastebin.com/47UiuAN5

I have suspicions that this might be from me removing all the crafting tables in a region with world edit. I believe this could have possibly bugged all the Slimefun machines that include a crafting table. I world edited crafting tables a couple weeks ago and just now the machines are broken. 

I also have suspicions that the world edit could be resulting in server performance issues involving Slimefun. My server uses almost max ram 10gb and it utilizes 13-30% CPU on idle when my other servers barely use 6gb and 1% CPU on idle with similar setups. It was never like this prior it just started having performance issues one day. I have tried removing Slimefun and Exotic Garden however nothing will fix the performance. It's like it bugged all the worlds.

All the other machines work that do not involve a crafting table.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Tried using enhanced crafting table and magical workbench with no recipe within the world edited region (error produced, no message)
2.  Moved to a random previously unrendered chunk and tried using enhanced crafting table and magical workbench with no recipe (error produced, no message)

## :bulb: Expected behavior (REQUIRED)

I expect that the enhanced crafting able and magical workbench would craft my item or give me a message but they produce an error in console and don't send messages to users like it normally would.

## :scroll: Server Log

https://pastebin.com/47UiuAN5

## :open_file_folder: /error-reports/ Folder

No files in error-reports.

## :compass: Environment (REQUIRED)

https://i.imgur.com/0bUhFIN.png

 - Server Version: Paper-135 - 1.16.1 
 - Minecraft version: 1.16.5
 - Slimefun version: RC- 22 (git 8c5cd7b8)
 - Addons: Exotic Garden

I am using NBT tags for retexturing items.

**Comment by TheBusyBiscuit** [comment]
Please update your Paper and Slimefun versions, we don't support RC versions of Slimefun.
