### ISSUE TITLE
Inventory Items Can be placed in the ancient alter

### ISSUE THREAD

**Issue by Brickmaster122** [Slimefun/Slimefun4#2974]
My server has an item join plugin https://www.spigotmc.org/resources/itemjoin.12661/ and there is no way to move the item. When you place things on the ancient alter though and pick it up it breaks it and the item goes into the next available slot 

Things you could do are 

1. Make a blacklist of items to place in the ancient altar Slot or item 
2. Idk really maybe make it so nonmovable items cant be placed
3. 

## :bulb: Expected behavior (REQUIRED)

I was hoping that there would be a message saying "Sorry you can't place this item here" or something else 

## :compass: Environment (REQUIRED)

Slimefun4 - RC 21  and item join v5.2.1

 - Server software: 
 paper/spigot
 - Minecraft version: 
 1.16.5
 - Slimefun version:

**Comment by WalshyDev** [comment]
I'm not sure what you mean. You say some items can be placed, what items? What shouldn't be placed? Very confused. What does it have to do with that plugin? Is it an us issue or a them issue?

Very confused. you really need to provide more detail.

Alongside that though, we don't support bugs from RC versions (and you aren't even on the latest anyway). So, try it on latest dev build and get back to us with more info. Discussing this on Discord first would be way easier.

**Comment by TheBusyBiscuit** [comment]
First off: we do not support RC versions of Slimefun.
Secondly, this doesn't really sound like a bug but rather like a missing feature.
I suggest you to request that feature from the ItemJoin developer though:
https://github.com/RockinChaos/ItemJoin

It would be much easier to implement on their end. They can also feel free to ask us for any help on it should they need it.

**Comment by Brickmaster122** [comment]
ok thanks for your feedback!
