### ISSUE TITLE
Auto-Enchanter has strict slot order

### ISSUE THREAD

**Issue by 100petr** [Slimefun/Slimefun4#2977]
## :round_pushpin: Description (REQUIRED)

The author enchanter does not work if the item is on the left (first) slot

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Place auto enchanter
2. Insert an item (such as a pickaxe) into the left (first) slot
3. Insert an enchanted book (eg unbreaking) into the right (second) slot
4. Nothing happens
If the enchanted book is placed in the left (first) slot and the item in the right (second), the auto enchanter works.
Video: https://youtu.be/NPX6k2nsg-Q

## :bulb: Expected behavior (REQUIRED)

The auto enchanter will work if there is an item in the right (first) slot and an enchanted book in the left (second) slot

## :scroll: Server Log

N/A

## :open_file_folder: /error-reports/ Folder

N/A

## :compass: Environment (REQUIRED)

![image](https://user-images.githubusercontent.com/29830635/115532225-e1f9bf80-a295-11eb-9490-1086bc46f71b.png)

**Comment by Boomer-1** [comment]
I was able to confirm and replicate the issue

**Comment by ZEROOblivious** [comment]
I'm able to replicate the issue on my server as well. 
![image](https://user-images.githubusercontent.com/32251194/115580467-18830a80-a295-11eb-8a50-e2ec11e05eae.png)

**Comment by variananora** [comment]
Confirmed.

**Comment by martinbrom** [comment]
Can confirm that it is caused by commit [cb3e9d](https://github.com/Slimefun/Slimefun4/commit/cb3e9dfbebd536ceec410f9fad060e2287e4d9a7). What happens: because `isEnchantable` now returns false instead of true, the for loop only loops once and returns null instead of checking both combinations of book and item.
