### ISSUE TITLE
Talisman of miner didn't showed up on action bar or chat when it's activated

### ISSUE THREAD

**Issue by blek-id** [Slimefun/Slimefun4#2999]
## :round_pushpin: Description (REQUIRED)
1. When talisman of the miner is being activated, no chat or action bar message is shown

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)
1. Get Talisman of the Miner
2. Break Emerald Ores

## :bulb: Expected behavior (REQUIRED)
message of the talisman working should be notified to player

## :scroll: Server Log
No error logs found

## :open_file_folder: /error-reports/ Folder
No error logs in /errror-reports/ found

## :compass: Environment (REQUIRED)
![image](https://user-images.githubusercontent.com/26654664/116526510-df394300-a903-11eb-9d6e-a208ff1f6466.png)
![image](https://user-images.githubusercontent.com/26654664/116526519-e1030680-a903-11eb-8c9b-1cd534d66e85.png)

 - Server software: PaperSpigot
 - Minecraft version:  1.16.5 Paper
 - Slimefun version: Slimefun DEV 889

**Comment by TheBusyBiscuit** [comment]
You cannot double iron or gold ore.
That's intended.

**Comment by blek-id** [comment]
Apologies about the iron/gold ore.
Can we talk about the notification not showing on either action bar / chat message?

https://user-images.githubusercontent.com/26654664/116531528-79e85080-a909-11eb-9b26-3c973b0ecb0a.mp4

**Comment by variananora** [comment]
Reopened this so I don't take #3000. Looking at you :sir_cookie:

Change title to: Talisman of miner didn't showed up on action bar or chat when it's activated.
