### ISSUE TITLE
Blocks that need another blocks below it will dropped the vanilla version of it when the block below it exploded with explosive pickaxe.

### ISSUE THREAD

**Issue by variananora** [Slimefun/Slimefun4#3009]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Elevator Plate need another blocks below it.
So when the blocks below it destroyed by explosive pickaxe it will drop a vanilla stone pressure plate.
Placing a block on destroyed Elevator Plate will give back the elevator plate.

### 📑 Reproduction Steps

1. Place Elevator Plate
2. Destroy **THE UNDERNEATH BLOCK** (Excluding the Elevator Plate) with Explosive Pickaxe
3. Dropped item will be the vanilla version
4. Place a dummy block where was the Elevator Plate
5. It will drop the original Elevator Plate

### 💡 Expected Behavior

It will just drop the Elevator Plate.

### 📷 Screenshots / Videos

https://user-images.githubusercontent.com/34732414/116788418-a94ab900-aad3-11eb-9d85-d0aaa4c48ec7.mp4

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/34732414/116788451-d8612a80-aad3-11eb-8ec0-95636b76edc4.png)

**Comment by TeamOah** [comment]
Sounds like a quick way to get some purple glazed terracotta, by exploding ultimate solar generators!

**Comment by variananora** [comment]
> Sounds like a quick way to get some purple glazed terracotta, by exploding ultimate solar generators!
> 

:NotLikeThis:

**Comment by Mooy1** [comment]
I think this could be fixed if ExposiveTool called a BlockBreakEvent for each broken block
