### ISSUE TITLE
"Withstands Explosion" items doesn't stands explosion from Explosive tools.

### ISSUE THREAD

**Issue by variananora** [Slimefun/Slimefun4#3018]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

"Withstands Explosion" items doesn't stands explosion from Explosive tools and will break them.

### 📑 Reproduction Steps

1. Place "Withstands Explosion" blocks
2. Break it with explosive tools
3. Item drops!

### 💡 Expected Behavior

Explosive tools should not explode them.

### 📷 Screenshots / Videos

Uploading 2021-05-05 12-57-19.mp4…

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/34732414/117102222-13987d80-ada2-11eb-86e5-4fb8a73e500e.png)

**Comment by TheBusyBiscuit** [comment]
I wouldn't really consider that a bug.
Pickaxes are pickaxes, it is still the player who breaks the block, the explosion is just a visual effect.
Whether or not these blocks should also be resistant against explosive pickaxes is more or less up for debate.
But I wouldn't call this a bug.
