### ISSUE TITLE
Player data is not updated immediately after the player disconnects

### ISSUE THREAD

**Issue by JinOuYongGu** [Slimefun/Slimefun4#3030]
**Thank you for looking at this issue**

## :round_pushpin: Description (REQUIRED)

After a player disconnected the server, the data file in folder **Players** will not be updated until the Slimefun autosave task runs. In my memory, the old version of Slimefun will update the files when a player offline.

The behavior actually not cause any problem like lost of items.
But I don't know if the behavior is correct. Because I want to synchronize data between servers, and it may cause lag.
![image](https://user-images.githubusercontent.com/45219386/117298939-89880c00-aeaa-11eb-9230-f0dda1413035.png)

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Unlock some sf items, or put items into slimefun backpack
2. Leave the server
3. The file in the screenshot still stores the info several mins ago.

## :bulb: Expected behavior (REQUIRED)

The data file of a player should be updated immediatlly when a player is disconnected.

## :scroll: Server Log

There is no log.

## :open_file_folder: /error-reports/ Folder

There is no error report.

## :compass: Environment (REQUIRED)

![image](https://user-images.githubusercontent.com/45219386/117298552-12527800-aeaa-11eb-9edb-7e427ad63964.png)

**Comment by WalshyDev** [comment]
You're not using the official Slimefun build. Report this to whatever Chinese fork you downloaded this from.

**Comment by TheBusyBiscuit** [comment]
1. You said "The behavior actually not cause any problem"... then why make a bug report...
2. You are not using an official Slimefun build.

**Comment by JinOuYongGu** [comment]
Sorry for my wrong report, and thanks for yours suggestion
