### ISSUE TITLE
Smelter's pickaxe bug

### ISSUE THREAD

**Issue by EpicPlayerA10** [Slimefun/Slimefun4#3046]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When you mine ancient debris by smleter's pickaxe with fortune, you will get more netherite scraps.

### 📑 Reproduction Steps

1. Get a Smelter's Pickaxe
2. Enchant to fortune
3. Mine ancient debris with this pickaxe

### 💡 Expected Behavior

I expected that I will get one scrap

### 📷 Screenshots / Videos

https://youtu.be/n4U7yLfqJSg

### 📜 Server Log

not relevant

### 📂 `/error-reports/` folder

not relevant

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

![obraz](https://user-images.githubusercontent.com/62206933/117964755-4acad980-b322-11eb-941b-ca9aae44fe55.png)

### 🧭 Other plugins

I have only slimefun plugin

**Comment by TheBusyBiscuit** [comment]
That is not a bug, that is an intended feature.
