### ISSUE TITLE
Recipe type has 'null' as a display name

### ISSUE THREAD

**Issue by martinbrom** [Slimefun/Slimefun4#3053]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When using any other language than English, some of the recipes in item detail (in the survival guide) have `null` as the item display name. The problem is probably caused by the recipe not looking for a fallback if the translation does not exist.

### 📑 Reproduction Steps

1. Open Slimefun guide
2. Change language to a different language than English (reproducible with Czech)
3. Open the recipe for Damascus Steel Helmet (for example)
4. See the display name of the anvil is `null`

### 💡 Expected Behavior

The display name is not `null`. It is either the correct translation (unavailable at the time of writing) or the fallback English name.

### 📷 Screenshots / Videos

![Screenshot from 2021-05-13 17-35-10](https://user-images.githubusercontent.com/16322387/118149172-9a3c0300-b411-11eb-9337-dc4102650380.png)

### 📜 Server Log

No errors

### 📂 `/error-reports/` folder

No errors

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

![Screenshot from 2021-05-13 17-37-06](https://user-images.githubusercontent.com/16322387/118149503-e5eeac80-b411-11eb-89e8-02f9fa8a884a.png)

**Comment by variananora** [comment]
@WalshyDev didn't you fixed this on #2956?

**Comment by martinbrom** [comment]
Seems that was for getMessage, this is a different part of the same class.

**Comment by variananora** [comment]
> Seems that was for `getMessage`, this is a different part of the same class. 

I haven't read it that much. I just remember something similar to this issue.

> I might just give the whole class a little cleanup.

Cool!
