### ISSUE TITLE
Ancient altar / Spawner Bug

### ISSUE THREAD

**Issue by pippotuttoH24** [Slimefun/Slimefun4#3057]
## :round_pushpin: Description (REQUIRED)
 

Hello, I was trying to make a reinforced spawner (With a whiter skeleton broken spawner) but when I placed 2 Ender rune, 2 Essence of aterlife and 4 filled flask of knowledge on the ancient altar it didn't work and the SF bot started saying "Unknown recipe! Use the correct recipe instead!" but the recipe was correct, a staff member also checked and it was all good (Same for the SF version)

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1. Get 4 Filled flask of knowledge, 2 Ender Rune, 2 Essence of Aterlife and 1 Broken spawner (Type wither)
2. Place the ancient altar
3. Put everything on it and then use the broken spawner on the altar, then it will start saying "Unknown recipe! Use the correct recipe instead" even thought it is correct.

## :bulb: Expected behavior (REQUIRED)

It should've craft the reinforced spawner (Wither type)

## :scroll: Server Log

[latest.log](https://github.com/Slimefun/Slimefun4/files/6474742/latest.log)

## :open_file_folder: /error-reports/ Folder

It was empty

## :compass: Environment (REQUIRED)

![sf 2](https://user-images.githubusercontent.com/84153072/118179270-f5c7ba00-b42c-11eb-8a0b-7e51dd2054ff.PNG)

 - Server software: Shockbyte
 - Minecraft version: 1.16.5
 - Slimefun version: Slimefun4 - DEV 903 (git 5194d).jar

**Comment by martinbrom** [comment]
![Screenshot from 2021-05-13 23-36-42](https://user-images.githubusercontent.com/16322387/118191129-662e0580-b444-11eb-9915-204cb3ef20bc.png)

I tried with the same setup (I cannot see the remaining 14 addons you have installed) but could not replicate the problem, could you please post a screenshot of the items on the ancient pedestals and also the broken spawner item just to be sure?

**Comment by Boomer-1** [comment]
if you check the screenshot, it says he only has 6 addons installed. 

I was able to replicate it in Dev 911. Here's the video link
https://youtu.be/PyoTfh_gVZI

**Comment by martinbrom** [comment]
That is weird, my broken spawner looks like this (different than in your video):

![Screenshot from 2021-05-14 00-27-14](https://user-images.githubusercontent.com/16322387/118195699-ff144f00-b44b-11eb-97fc-c169183a8e31.png)

**Comment by variananora** [comment]
> I was able to replicate it in Dev 911. Here's the video link
> [youtu.be/PyoTfh_gVZI](https://youtu.be/PyoTfh_gVZI)
> 
> I looked at the wrong screenshot before, sorry for any confusion. But I did reproduce it.

I think this is a different spawner (by different I mean it's not from Slimefun, but other plugin...)

@pippotuttoH24 Can we have your full `/plugins` list?

**Comment by StarWishsama** [comment]
Classic issue, just turn everything 90 degrees and try again.

**Comment by variananora** [comment]
https://youtu.be/ci1L8T0gp2c

I can't seems to reproduce it. I think this is an issue with other spawner plugin and making the spawner unreadable to Ancient Altar.
(Trying with different name spawner for confirmation: https://youtu.be/WzMypAsXvOs)

**Comment by Boomer-1** [comment]
i don't use any other plugins but slimefun. that was directly from /sf give

**Comment by variananora** [comment]
> i don't use any other plugins but slimefun. that was directly from /sf give

hmm that is weird.... lemme test that again..

**Comment by variananora** [comment]
`/sf give variananora broken_spawner` gave me this:

**Comment by Boomer-1** [comment]
https://youtu.be/BsJar2WcnEw. it did it this way everytime i ran it.

**Comment by variananora** [comment]
> [youtu.be/BsJar2WcnEw](https://youtu.be/BsJar2WcnEw). it did it this way everytime i ran it.

I don't have type of broken spawner on `/sf give`....
what addons are you using exactly?

**Comment by Boomer-1** [comment]
![image](https://user-images.githubusercontent.com/75179680/118224128-29fca400-b448-11eb-991d-c8922496f406.png)
![image](https://user-images.githubusercontent.com/75179680/118224155-341ea280-b448-11eb-88b8-d2a3522ec760.png)

**Comment by Boomer-1** [comment]
when pippo reported this initially on the discord they said it was a spawner mined from using the pickaxe of containment. I'll try testing that and see if it yields different lore.

**Comment by Boomer-1** [comment]
so when using the pickaxe of containment, i got this.

![image](https://user-images.githubusercontent.com/75179680/118224859-91ffba00-b449-11eb-888b-c96cedf0b31e.png)

Same thing pippo would have gotten with the pickaxe. My guess the reason for the two different Lore's is Soul Jars.

**Comment by Boomer-1** [comment]
There is an open issue on the Soul Jars Github as Fluffy got the same lore I originally got. 

https://github.com/TheBusyBiscuit/SoulJars/issues/23

**Comment by variananora** [comment]
Thanks Boomer!

**Comment by Boomer-1** [comment]
I reached out to pippo on discord to get a screenshot of the spawner, and confirm if it was from the pickaxe or from soul jars.

**Comment by GalaxyKat11** [comment]
Not sure if it helps, but it appears that if you use a regular ancient altar to make the broken spawner (any type) that you can use either a regular or auto ancient altar to make it a reinforced spawner. If you use the auto ancient altar to make the broken spawner, it yields a spawner that cannot be used in either the regular or auto ancient altar to make it a reinforced spawner. 
I filled 2 soul jars with wither skeleton souls and tried making the broken spawners and only the ones made in the regular ancient altar work. I do not think the problem is with soul jars, but rather something the auto ancient altar is doing to the spawner when you remove it from the machine.

**Comment by Boomer-1** [comment]
can you screenshot the spawners with your mouse hovering over them? If there's a difference between them it may show on the # of nbt tags

**Comment by GalaxyKat11** [comment]
Here is a screenshot hovering over the broken wither spawner made in a regular ancient altar.
![Screenshot (88)](https://user-images.githubusercontent.com/65092397/121107788-944dfd80-c7d6-11eb-9512-40c507d5185f.png)

And here is screenshot hovering over the broken spawner made in an Auto ancient altar.
![Screenshot (89)](https://user-images.githubusercontent.com/65092397/121107858-b6478000-c7d6-11eb-8344-93e59d18081a.png)

You can also see how the one made in Auto Ancient Altar changes and displays "Monster Spawner, Type: Pig" at top of screen when you try to move it from your inventory.
![Screenshot (90)](https://user-images.githubusercontent.com/65092397/121108121-2a822380-c7d7-11eb-9dec-c9105f05b07b.png)

**Comment by GalaxyKat11** [comment]
When you repair the broken spawner made in the Regular Ancient Altar (you can use either Ancient Altar to repair it) you get the following.
![Screenshot (91)](https://user-images.githubusercontent.com/65092397/121108618-10951080-c7d8-11eb-9aed-cb2da049efed.png)

**Comment by GalaxyKat11** [comment]
When trying to repair the broken spawner made in the Auto Ancient Altar, you get message "Unknown Recipe. Use correct recipe instead!"
![Screenshot (93)](https://user-images.githubusercontent.com/65092397/121108990-b2b4f880-c7d8-11eb-884d-dccb49c2c8a2.png)
