### ISSUE TITLE
Player can take download script button for Programmable Android

### ISSUE THREAD

**Issue by blek-id** [Slimefun/Slimefun4#3069]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Players can get the download script button from Programmable Android's memory core GUI.

### 📑 Reproduction Steps

1. Place Programmable Android Miner
2. Open and go to Memory core
3. Click and drag download script button to your inventory

### 💡 Expected Behavior

Opens Script list GUI to download

### 📷 Screenshots / Videos

![Uploading android.gif…]()

### 📜 Server Log

https://pastebin.com/sWQxNi1J

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

Paper git-Paper-575 (MC: 1.16.5)
Slimefun DEV - 913 (git f822bdd1)
Metrics-Module #21
Java 11

Installed Addons: (13)
  KGenerators v4.4.0
  DyedBackpacks vDEV - 14 (git 0a051b2b)
  SlimefunOreChunks vDEV - 13 (git 9f7a2be3)
  DynaTech vDEV - 116 (git dfb785ea)
  InfinityExpansion vDEV - 111 (git 461a3fd6)
  SlimeCustomizer vDEV - 6 (git 6c348829)
  ElectricSpawners vDEV - 22 (git 4cb2c56b)
  SFCalc vDEV - 22 (git 4e764de8)
  LiteXpansion vDEV - 151 (git e9e64576)
  IllegalStack v2.2.2a
  SlimyTreeTaps vDEV - 18 (git ab11a282)
  CMI v8.8.3.6
  FluffyMachines vDEV - 81 (git 67fa6406)

**Comment by TheBusyBiscuit** [comment]
The error indicates that you have either installed a modified or a corrupted jar file.
