### ISSUE TITLE
Breaking Backpacks

### ISSUE THREAD

**Issue by smolbrainlol** [Slimefun/Slimefun4#3070]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

If you have essentials plugin and were to use /itemlore clear on any backpack it ultimately breaks it completely rendering it to become just a head that can't be placed

### 📑 Reproduction Steps

1. Do /itemlore clear [_ Backpack}
2. and thats just it

### 💡 Expected Behavior

I only did this on accident and had accidentally broken my own backpack

### 📷 Screenshots / Videos

![image](https://user-images.githubusercontent.com/84488994/118915691-0c579f00-b960-11eb-91cf-3942c067b9c4.png)

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

DEV - 913

### 🧭 Other plugins

none

**Comment by variananora** [comment]
As a player you shouldn't be able to change the item lore of an item.
Also item naming and lore can't be changed because it will broke most of the Slimefun items.

Sidenote: You can get back your backpack with `/sf backpack`
