### ISSUE TITLE
TPS drops when crafting many items in vanilla crafting table

### ISSUE THREAD

**Issue by U5B** [Slimefun/Slimefun4#3078]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When crafting mass-crafting items using the recipe book in a vanilla crafting table, I saw the server freeze whenever I shift clicked on the output slot.

https://spark.lucko.me/Kt9YfcYNA0?hl=39,38,51,52,54,58

This is the output when ran with /spark profiler --only-ticks-over 400

### 📑 Reproduction Steps

1. Have lots of bonemeal in inventory.
2. Open crafting table.
3. Open the recipe book and shift click the bone block.
4. Shift click the bone block that appears in the output.
5. Watch as server freezes for a second, depending on how powerful your host is.

### 💡 Expected Behavior

I expected no TPS drops when crafting.

### 📷 Screenshots / Videos

https://spark.lucko.me/Kt9YfcYNA0?hl=39,38,51,52,54,58

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

will get version later

**Comment by U5B** [comment]
I am not admin on the server, but I am friends with an admin, however he is away currently. I will ask him for the Slimefun version later, through I know he is using one of the latest developer versions

**Comment by WalshyDev** [comment]
You have `backwards-compatibility` enabled which causes MUCH more expensive item checks. Disable that and you should see this go away.
**Note:** This option is needed for items older than summer 2019 to be recognised. If you don't have any of these or don't care to support them then you're fine to disable the option.

We need to check items in the crafting table as we don't want users crafting stuff with a Slimefun item. The way crafting works sucks hence this being pretty expensive.
