### ISSUE TITLE
Error with Gold Pan in my console log

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun/Slimefun4#3084]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

i just restarted my server and this error appeared in the console. I don't know what triggered it. 

### 📑 Reproduction Steps

I wish i could tell you, but I didn't do anything

### 💡 Expected Behavior

no error i guess?

### 📷 Screenshots / Videos

none

### 📜 Server Log

https://pastebin.com/Y8738A9r

### 📂 `/error-reports/` folder

https://pastebin.com/FqmHVczV

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

Dev 925

### 🧭 Other plugins

only slimefun addons are installed.

**Comment by martinbrom** [comment]
Looks like the exception is caused by ElectricGoldPan, ElectricDustWasher, ElectricSmeltery, and OilPump. These machines use sort of a "hack" where the recipes they use have no input but consume an item anyway.

**Comment by Mooy1** [comment]
https://github.com/Slimefun/Slimefun4/blob/343f47bdb6a3e64375403334930ca762e355a461/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/electric/machines/ElectricGoldPan.java#L53 for example ^

**Comment by martinbrom** [comment]
What about the dust washer? :smile:
