### ISSUE TITLE
Auto brewer disappearing 

### ISSUE THREAD

**Issue by SecretarySami** [Slimefun/Slimefun4#3093]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When putting in a potion of fire resistance(3:00) and glowstone dust into the auto brewer, the auto brewer disappears after a few seconds.

### 📑 Reproduction Steps

1. place auto brewer 
2. hook auto brewer to energy
3. place fire resistance potion (3:00) into slot one 
4. place one glowstone dust into slot 2
5. close gui and wait a few seconds 

### 💡 Expected Behavior

Placing a potion into the auto brewer with  glowstone is supposed to strengthen the potion, for example if you put a swiftness potion in with glowstone it would make it a speed 2 potion, however fire resistance does not have a stronger potion type so the auto brewer is unable to actually auto brew the stronger potion.

### 📷 Screenshots / Videos

https://youtu.be/Pego5F9QNOQ

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

https://i.imgur.com/IAW5Nsk.png
https://i.imgur.com/6ur2Hda.png

**Comment by variananora** [comment]
There should be an error log, can you get it for us?

**Comment by variananora** [comment]
Can confirm. Using Fire Resistant (3:00) + Glowstone Dust like the video did.

`/error-reports/`: https://paste.walshy.dev/isixorebus
Server logs: https://paste.walshy.dev/igiqodokah

`/sf versions`:
![image](https://user-images.githubusercontent.com/34732414/120126996-3cb4fe00-c1e8-11eb-9851-f5bcc46b1fc3.png)

**Comment by SecretarySami** [comment]
https://pastebin.com/9Jv49Qxy
let me know if this link works :)

**Comment by martinbrom** [comment]
> https://pastebin.com/9Jv49Qxy
> let me know if this link works :)

Yes it does :wink:

**Comment by SecretarySami** [comment]
Awesome, thank you. Let me know if you need anything else.
