### ISSUE TITLE
Duplication Sf + Itemsadders

### ISSUE THREAD

**Issue by istarengwa** [Slimefun/Slimefun4#3100]
## Description (Required)
Hello hello, I am explaining the current bug, which is really annoying at the time, and I do not know if the error came from you or from slimefun. 

In fact, if a player puts a slimefun object in his left hand and nothing in his right hand, that he types with the right hand empty an itemsadders block, this duplicates the slimefun object held in his left hand ad infinitum, with all his content if it is a backpack.

I created a ticket on the lonedev discord which told me:

"LoneDev — 31/05/2021
did you try contacting slimefun devs about that? i don't drop items on blocks interact
they probably are not checking if the block break event is cancelled or their blockbreak event priority is not set to MONITOR"

Video: https://cdn.discordapp.com/attachments/849633185003733023/849633251550691369/2021-05-31_01-40-41_Scene_Trim.mp4

## Steps to reproduce the Issue (Required)
i can send you the video i send to the itemsadders developer on discord if you don't mind.

## Environment (Required)

 - Minecraft Version: purpurclip-1149
 - Slimefun Version: Dev 928 (git cccf6)

**Comment by WalshyDev** [comment]
I don't understand the issue, could you please record it and show `/sf versions` in the recording.

**Comment by WalshyDev** [comment]
https://cdn.discordapp.com/attachments/849633185003733023/849633251550691369/2021-05-31_01-40-41_Scene_Trim.mp4

Video from user

**Comment by istarengwa** [comment]
https://www.casimages.com/i/21060203195761697.png.html

I updated the plugin in the meantime but it still does the same thing

**Comment by 100petr** [comment]
I can't imitate it. Does it work for all blocks? I chose random three.
righ-click (open)
https://user-images.githubusercontent.com/29830635/120889822-492dc200-c5ff-11eb-80fa-b4ade174805d.mp4
left-click (destroy)
It didn't even work with cancel-break-wrong-tool.enabled: true
https://user-images.githubusercontent.com/29830635/120889615-47afca00-c5fe-11eb-9a4a-e05a1a57b9a8.mp4
![image](https://user-images.githubusercontent.com/29830635/120889646-6d3cd380-c5fe-11eb-9fec-bbb9e1110bb4.png)
IA 2.3.9
(Sometimes I could update addons :D but it's just a test server, so I don't deal with it much)

**Comment by Rushia140** [comment]
i also got the same problem 
https://youtu.be/VLi1WgwzS2w

**Comment by istarengwa** [comment]
Hello, my problem is still there, I have slimefun dev 962 and the latest version of item adders, but now no longer need to hold in the left hand, a right click with an item slimefun on an itemadders block is enough to duplicate the item

**Comment by istarengwa** [comment]
> I can't imitate it. Does it work for all blocks? I chose random three.
> righ-click (open)
> https://user-images.githubusercontent.com/29830635/120889822-492dc200-c5ff-11eb-80fa-b4ade174805d.mp4
> left-click (destroy)
> It didn't even work with cancel-break-wrong-tool.enabled: true
> https://user-images.githubusercontent.com/29830635/120889615-47afca00-c5fe-11eb-9a4a-e05a1a57b9a8.mp4
> ![image](https://user-images.githubusercontent.com/29830635/120889646-6d3cd380-c5fe-11eb-9fec-bbb9e1110bb4.png)
> IA 2.3.9
> (Sometimes I could update addons :D but it's just a test server, so I don't deal with it much)

Hello, I'm responding a little late but there are no itemadders in your plugin list, and the duplication bug is specifically related to this plugin

**Comment by 100petr** [comment]
what? however, you can see in the video that it is an itemsadder and IA does not show in sf versions, but I'll try it again tomorrow where I'll even write about itemsadder.

**Comment by Boomer-1** [comment]
do /pl to provide the complete plugin list

**Comment by istarengwa** [comment]
> do /pl to provide the complete plugin list

I did the test only with ia + sf plugins and it always does the same duplication, here is my /pl  

https://zupimages.net/viewer.php?id=21/36/vv1h.png

**Comment by 100petr** [comment]
Thanks for the reply that this is happening on real_note. I could not duplicate the backpack, it was "destroyed", but the ingots could be duplicated.

https://user-images.githubusercontent.com/29830635/132944979-56fc2dcb-0c81-4f0d-abf8-04493799f2a9.mp4


https://user-images.githubusercontent.com/29830635/132944985-2d7ede8e-d667-441e-b1e7-4b90f64fd654.mp4

**Comment by LoneDev6** [comment]
Let me know if I can do anything to directly help Slimefun devs

**Comment by LoneDev6** [comment]
Does the problem occurs also using vanilla items?
https://user-images.githubusercontent.com/29830635/132944985-2d7ede8e-d667-441e-b1e7-4b90f64fd654.mp4

I can't find any reason why itemsadder would make this behaviour only with slimefun items, i don't even implement their api to handle their items in any way

**Comment by 100petr** [comment]
I tried goldingot and nothing happens

https://user-images.githubusercontent.com/29830635/134370493-96a5ce89-e5cb-444f-a0ae-02aaa99ce3ac.mp4

**Comment by 100petr** [comment]
so i found that it does even with normal noteblocks if IA is installed

**Comment by Sfiguz7** [comment]
@LoneDev6 looms like you might've been right about your NMS code

**Comment by LoneDev6** [comment]
> 
> 
> @LoneDev6 looks like you might've been right about your NMS code

Very good, I hope it's the issue so it's "easier" for me to fix since I've already identified the possible cause.
I'll fix this in the next days

**Comment by LoneDev6** [comment]
@Sfiguz7 
Added a check for slimefun item, now it's working fine!
```java
if(Main.hasSlimefun)
{
	NBTItem tmp = new NBTItem(itemStack);
	if(tmp.hasNBTData() && tmp.hasKey("PublicBukkitValues") 
			&& tmp.getCompound("PublicBukkitValues").hasKey("slimefun:slimefun_item"))
	{
		return;
	}
}
```

I'll release an update in the next hours

**Comment by Sfiguz7** [comment]
> I'll release an update in the next hours.
Is it fixed then? Shall we close this issue?

> Anyway I think this issue happens because Slimefun is not cancelling the PlayerInteractEvent, so ItemsAdder will process it anyway even if: `@EventHandler(ignoreCancelled = true, priority = EventPriority.MONITOR)`.
> 
> For now I'll keep this workaround
If you ignoreCancelled it should not matter whether we cancel or not, unless you check for isCancelled() and do nothing if it's true at which point you could simply remove the ignoreCancelled flag

**Comment by 100petr** [comment]
I tried it and it's fixed, thanks to both of you!

**Comment by J3fftw1** [comment]
Apparently this has been fixed since oct 4th 2021 https://github.com/Slimefun/Slimefun4/issues/3100#issuecomment-933576103
