### ISSUE TITLE
Smelter's Pickaxe with Fortune enchantment don't fully work.

### ISSUE THREAD

**Issue by variananora** [Slimefun/Slimefun4#3116]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When using Smelter's Pickaxe with Fortune enchantment to break some ores it wouldn't drop the extra drops of Fortune.
Blocks aren't working:
- Coal Ore (Deepslate)
- Diamond Ore (Deepslate)
- Emerald Ore (Deepslate)
- Nether Quartz Ore

EDIT: This also don't work in 1.16.5 as @!👑Hashir Sulaiman👑#9999 on Discord reported: https://cdn.discordapp.com/attachments/565569196218384385/853519836729573396/Minecraft__1.16.4_-_Multiplayer_3rd-party_Server_2021-06-13_11-21-16.mp4

### 📑 Reproduction Steps

1. Obtain Smelter's Pickaxe
2. Enchant Fortune on it
3. Try with the blocks above and see it won't drop the extra drops.

### 💡 Expected Behavior

Fortune enchantment should work on those blocks.

### 📷 Screenshots / Videos

https://youtu.be/OVoY_YLRQnw

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/34732414/121797844-026a4880-cc4d-11eb-8d04-5f9f76cc3d87.png)

**Comment by mantrakp** [comment]
bump itz true

**Comment by Boomer-1** [comment]
99.99% sure this is working as intended. the point of a SMELTERS pickaxe is to smelt ores that must be smelted and not obtained any other way.
