### ISSUE TITLE
Electric Gold Pan 2, Electric Dust Washer 2, Electric Furnace 3 not registering after server start.

### ISSUE THREAD

**Issue by telos954** [Slimefun/Slimefun4#3122]
## :round_pushpin: Description (REQUIRED)

After the server was working fine for several days, upon starting it back up today the Electric Gold Pan v2, Electric Dust Washer V2, and Electric Furnace 3 had stopped registering as active blocks. In attempting to get things working again, I removed the furnace and its nodes, then placed them all fresh, and it worked. Cargo nodes needed a server reboot (NOT /reload) to go active again. I was instructed in the Discord by Boomer_1 to update my java, which I have, The problem still persists with my gold pans, and dust washers which have not been manually replaced.

## :bookmark_tabs: Steps to reproduce the Issue (REQUIRED)

1.  Approach slimefun machine,
2. Attempt to interact with it,
3. Unable to be interacted with,
4. Does not preform its expected functions.

## :bulb: Expected behavior (REQUIRED)

I expected the blocks to continue doing their jobs they had been for the previous few days. Kelp was to move to the furnaces, be dried, and deposited into a chest in one section of my production facility. In another, cobble was supposed to be turned into gravel, gravel into sifted ore, sifted ore into its various dusts, then deposited into a sorting system. These two related, in close proximity, but not connected systems both experienced these issues when booting the server. They had worked long enough to fill up two double chests of the various dusts, so it's strange for them to have suddenly stopped functioning.

## :scroll: Server Log

https://pastebin.com/V5K0pzSy

## :open_file_folder: /error-reports/ Folder

Folder is empty.

## :compass: Environment (REQUIRED)

 - Server software: Spigot 1.16.5 [ **3092-Spigot-9fb885e-ebe18b9 (MC 1.16.5)** ]
 - Minecraft version: 1.16.5 [**Release**]
 - Slimefun version: DEV - 936 (git aa5a22cb)

**Comment by variananora** [comment]
Can you upload the `ELECTRIC_DUST_WASHER_2.sfb`?
it's located on `./data-storage\Slimefun\stored-blocks\world\ELECTRIC_DUST_WASHER_2.sfb`

**Comment by Boomer-1** [comment]
Just an fyi, not sure if it matters, but telos and walshy were discussing that the server telos plays on had a power outage and it didn't shut down properly, and that may have played a part in it.

**Comment by variananora** [comment]
> Just an fyi, not sure if it matters, but telos and walshy were discussing that the server telos plays on had a power outage and it didn't shut down properly, and that may have played a part in it.

yep, i saw it on discord, just want to take a look at the files.
