### ISSUE TITLE
Items processed by compressor will disappear when output chest is going to full

### ISSUE THREAD

**Issue by MrPolloo** [Slimefun/Slimefun4#3136]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When output chest is going to full(not full yet) and compressor is processing items more than output chest can store, the rest of items that processed will disappear. But if output chest already full, and compressor is processing items, the items will go to compressor instead

### 📑 Reproduction Steps

1. Fill output chest with items(in this case, example: carbon) until almost full
2. Get coal block more than enough for crafting carbon
3. Right click the compressor

### 💡 Expected Behavior

When output chest is full and the compressor is still processing, the items will go to compressor.

### 📷 Screenshots / Videos

While output chest isnt full
https://user-images.githubusercontent.com/70990197/123103125-e8f0aa00-d45f-11eb-88b0-3ab44fee5bcc.mp4

While output chest is already full
https://user-images.githubusercontent.com/70990197/123103231-fe65d400-d45f-11eb-93b0-ba87bbab056b.mp4

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

DEV- 939 (git 57f7553f)
![image](https://user-images.githubusercontent.com/70990197/123103480-4127ac00-d460-11eb-9bf6-06b2fc04cf90.png)

**Comment by variananora** [comment]
Can confirm.

Compressor will lose the processed item if the output chest is going full.
(idk how to explain it better)

**Comment by martinbrom** [comment]
Would most likely happen for a `PressureChamber`, `MagicWorkbench`, and `ArmorForge` too. These multiblocks check the output inventory before starting the crafting process and then craft the items after a certain delay. This means the output inventory has enough space for a few ticks/seconds after crafting each item.

One way to fix would be to remove the delay altogether or try to find the output inventory before & after the crafting "delay".
