### ISSUE TITLE
Mcmmo Bug with Slimefun 

### ISSUE THREAD

**Issue by GeRmAnAnToNiO124** [Slimefun/Slimefun4#3162]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

It happens that when you use the ability of the mcmmo spikes, it multiplies the efficiency x5 for a few seconds, the user takes advantage and put the spike in his second hand with control f and after this he gets the enchant in the desinchanter, this would not be a problem if it were not because you can keep repeating this method until you get efficiency ..5.

### 📑 Reproduction Steps

1. Start a server with Slimefun DEV and Mcmmo latest version
2. Activate the Peak ability and go to a deinchanter, put the peak to the secondary hand with control f and raise the peak immediately to the deinchanter.

### 💡 Expected Behavior

The peak can be disenchanted and you get efficiency 5, also if you have a peak efficiency 5 and you activate it you get efficiency 10 and so on.

### 📷 Screenshots / Videos

https://www.youtube.com/watch?v=4WGjTt3d3Mc&feature=youtu.be

### 📜 Server Log

https://pastebin.com/UMBFVtx9

### 📂 `/error-reports/` folder

https://pastebin.com/WDsF1CAP

### 💻 Server Software

Airplane

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

916

### 🧭 Other plugins

Only mcmmo

**Comment by J3fftw1** [comment]
You are 31 versions behind on slimefun

**Comment by TheBusyBiscuit** [comment]
Report that here: https://github.com/mcMMO-Dev/mcMMO/issues

**Comment by GeRmAnAnToNiO124** [comment]
The Bug Still works on the latest versions of both plugins 
https://haste.nealand.club/mimiwivago.sql

**Comment by WalshyDev** [comment]
> The Bug Still works on the latest versions of both plugins
> https://haste.nealand.club/mimiwivago.sql

Did you... read the message above...
