### ISSUE TITLE
Hologram 

### ISSUE THREAD

**Issue by OrionSys12** [Slimefun/Slimefun4#3166]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I on accident world edited our a Hologram Projector and the name for it stayed (It was edited and with color if the color portion matters) 

### 📑 Reproduction Steps

1. Placed the Hologram
2. Moved the Hologram to 2.6
3. Renamed the Hologram
4. Realized I need to move the floor
5. Forgot to break the hologram
6. did //set air in world edit
7. the edited hologram words stayed and we cant remove it

### 💡 Expected Behavior

Well I was HOPING it wouldnt have stayed as another one I had forgotten to break (non edited) was able to be removed by placing a projector in the space the previous one had been in

### 📷 Screenshots / Videos

![sf bug1](https://user-images.githubusercontent.com/87222935/125155675-654ce380-e116-11eb-943f-dc75bfcf366b.png)
![sf bug 2](https://user-images.githubusercontent.com/87222935/125155676-67af3d80-e116-11eb-8149-869204e88743.png)

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

![sf vers](https://user-images.githubusercontent.com/87222935/125155666-42baca80-e116-11eb-85b8-0a462282bd2c.png)

**Comment by J3fftw1** [comment]
You shouldn't world edit slimefun stuff but i think someone made a change for it so it can detect if someone world edited can be wrong though

**Comment by WalshyDev** [comment]
Please refer to this guide: https://github.com/Slimefun/Slimefun4/wiki/Common-Issues

**Comment by OrionSys12** [comment]
> You shouldn't world edit slimefun stuff but i think someone made a change for it so it can detect if someone world edited can be wrong though

Well yes I understand that it was a mistake, I had forgotten to remove it.

**Comment by OrionSys12** [comment]
> Please refer to this guide: https://github.com/Slimefun/Slimefun4/wiki/Common-Issues

None of that seems to be working

**Comment by J3fftw1** [comment]
/killall named 3 is to kill the hologram

**Comment by OrionSys12** [comment]
> /killall named 3 is to kill the hologram

That worked thank you
