### ISSUE TITLE
Block Placer makes blocks vanish

### ISSUE THREAD

**Issue by anonisnap** [Slimefun/Slimefun4#3182]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When placing a block, which needs to be supported (eg: Redstone Dust, Repeater, Redstone Torch) on top of a Block Placer, when the Block Placer is broken, the block on top does not drop into item form.

I only checked with Redstone Dust, Repeaters, and Redstone Torches.
I broke the block placer first using a Netherite Pickaxe, only with Vanilla Enchants

### 📑 Reproduction Steps

1. Place a Block Placer
2. Place Any of the following on top of Block Placer
    - Redstone Dust
    - Redstone Repeater
    - Redstone Torch
3. Break the Block Placer

### 💡 Expected Behavior

When the Block Placer is broken, the block on top is expected to drop as an Item, which it does not.

### 📷 Screenshots / Videos

![2021-07-27_16 19 58](https://user-images.githubusercontent.com/42655737/127170609-7527eb10-753b-4b1d-9da4-cda71faae726.png)
![2021-07-27_16 20 13](https://user-images.githubusercontent.com/42655737/127170624-b034600d-5f58-4aca-b58a-159b0b04c735.png)

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Slimefun DEV - 956

[Screenshot of Version](https://gyazo.com/815101758121ba1a5973b98ed00e90f8)

**Comment by variananora** [comment]
Can confirm. 
This works with all Slimefun machines/blocks.
Slimefun blocks will destroy the top blocks if the top blocks need a block below it. 

<details>
<summary>Details</summary>

Video: https://youtu.be/ptqw0fvPD_c

```
> sf versions
[21:38:54 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-124 (MC: 1.17.1)
Slimefun DEV - 956 (git 0262830e)
Metrics-Module #25
Java 16

Installed Addons: (2)
  CMILib v1.0.3.1
  CMI v9.0.2.1
> ver
[21:38:55 INFO]: This server is running Paper version git-Paper-124 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 170382f)
You are 9 version(s) behind
Previous version: git-Paper-104 (MC: 1.17.1)
> pl
[21:38:55 INFO]: Plugins (5): CMI, CMILib, Slimefun, Vault, VoidGenerator
```

</details>
