### ISSUE TITLE
RENAMING OF ITEM ESSENCE OF AFTERLIFE WHEN USING NORMAL ANCIENT ALTAR

### ISSUE THREAD

**Issue by Microhazard** [Slimefun/Slimefun4#3185]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

It should be fix before anyone will abuse the bug

### 📑 Reproduction Steps

1. Buy some gunpowder on a server or obtain gunpowder from the creeper.
2. Rename the item from the anvil &4Essence of Afterlife
3. Then put it in a normal ancient altar, not in auto (Auto doesn't work.)

### 💡 Expected Behavior

Players are buying gun powder and start renaming &4Essence of Afterlife from the anvil

### 📷 Screenshots / Videos

![step 1](https://user-images.githubusercontent.com/61838151/127641094-7f7f832b-c766-4b12-8f9b-215ee7a78e9d.png)
![Step 2](https://user-images.githubusercontent.com/61838151/127641100-91cbb1ff-f0af-4346-8ed1-6a57348372b8.png)
![Step 3](https://user-images.githubusercontent.com/61838151/127641101-ee585da6-9200-4046-9a55-5135fbd9546b.png)
![Step 4](https://user-images.githubusercontent.com/61838151/127641103-e32f1994-aaab-4657-ac7c-51a148b22b7f.png)
![Step 5](https://user-images.githubusercontent.com/61838151/127641108-2aa2c976-9c96-44de-8090-3219413a12f3.png)

### 💻 Server Software

Airplane

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

![SF VERSIONS](https://user-images.githubusercontent.com/61838151/127641216-4cff540b-621e-4947-9268-1aafd2820c13.png)

**Comment by J3fftw1** [comment]
Its not a default behavior that you can rename items with colors in minecraft. Not sure if this is a valid bug report

**Comment by TheBusyBiscuit** [comment]
Also buy a new keyboard, your caps key seems broken.
