### ISSUE TITLE
Raw ores not working with the luck multiplier of Slimefun Furnaces

### ISSUE THREAD

**Issue by marvjosh1** [Slimefun/Slimefun4#3190]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When raw ores (iron, gold, copper) are smelted in enhanced / reinforced / carbonado furnaces, each raw ore is smelted into 1 ingot only.

### 📑 Reproduction Steps

1. Place down an enhanced / reinforced / carbonado furnace with a luck multiplier greater than 1
2. Place some fuel in it
3. Place each kind raw ores in it
4. Watch it being smelted into 1 ingot only

### 💡 Expected Behavior

The expected behaviour is that raw ores are being multipled to give an amount of ingots around the luck multiplier when being smelted.

### 📷 Screenshots / Videos

https://youtu.be/n5gefHoJ9UI

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

https://i.imgur.com/iKtj1hl.png
https://i.imgur.com/i7ywuHv.png

**Comment by ybw0014** [comment]
Only ores benefit from the luck multiplier.

**Comment by TheBusyBiscuit** [comment]
I would argue that this should definitely apply to Raw Ores here. In 1.17 that has become the default drop.

**Comment by variananora** [comment]
> I would argue that this should definitely apply to Raw Ores here. In 1.17 that has become the default drop.

Can it be togglable? Because Iron Ore + Fortune + Furnace Luck is kinda too much?

**Comment by Skizzles** [comment]
> > I would argue that this should definitely apply to Raw Ores here. In 1.17 that has become the default drop.
> 
> Can it be togglable? Because Iron Ore + Fortune + Furnace Luck is kinda too much?

They bring up a very good point, possibly a lower fortune rate for raw ore compared to standard?

**Comment by TheBusyBiscuit** [comment]
I think a toggle would be better.
I reckon it would best to just add a toggle for all the ores (raw or not) in a follow-up build.
This way it can be tweaked to an even finer degree.
