### ISSUE TITLE
Renaming Gunpowder with anvil color to Essence of Afterlife works in Ancient Altar

### ISSUE THREAD

**Issue by FN-FAL113** [Slimefun/Slimefun4#3197]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Players with anvil color permissions are able to craft Essence of Afterlife by renaming vanilla gunpowder to &4Essence of Afterlife, then afterwards use it on ancient altar to craft soulbound runes. This only works on manual ancient altar with pedestal and doesn't work on Auto ancient altar. For now we removed the permissions for using anvil color so that players can't dupe essence of afterlife or create it in a very easy way.

### 📑 Reproduction Steps

1. Acquire vanilla gunpowder
2. Rename the gunpowder through an anvil with the same name and color as "&4Essence of Afterlife"
3. Put/Use the renamed and recolored Essence of Afterlife in the ancient pedestal to craft slimefun items like soulbound rune

### 💡 Expected Behavior

The catalyst should not detect it but it works like a crafted essence of afterlife, it tricks the catalyst that the item is infact an essence of afterlife but just renamed and recolored through an anvil.

### 💻 Server Software

Airplane

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

DEV - 960 (git 0df46)

**Comment by variananora** [comment]
Vanilla anvil can't rename items into colored ones. You should disable anvil color.
