### ISSUE TITLE
Explosive Pickaxe isn't exploding blocks and "/sf versions" don't show the Slimefun version.

### ISSUE THREAD

**Issue by lucashiagod1** [Slimefun/Slimefun4#3201]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When I try to use the explosive pickaxe it's not exploding the blocks (3x3) as it has to do. I only can mine one block per time like a normal pickaxe. I did this server to play alone using the spigot 1.14.4 and already tested different versions of the plugin to see if the problem was in the version, the last was Slimefun4 - #960. And other weird thing is when I write the command "/sf versions" a message appears saying "An internal error occurred while attempting to perform this command". And as it's my first time making a server I don't have idea how to fix that. Idk if it's a problem whit my Java (that's already updated), my computer, the way I did the server or it's a plugin problem... By the way, on the Server Log I put whats showed when I break a block whit the explosive pickaxe. Thanks for the help.

### 📑 Reproduction Steps

1. Break a block with explosive pickaxe.
2. An area (3x3) should be breaked by the explosion.
3. Only one block is breaked like a normal pickaxe.
4. When written "/sf versions" should show the Slimefun versions.
5. Instead of this, a message saying "An internal error occurred while attempting to perform this command" appears.

### 💡 Expected Behavior

I expected to see the plugin working properly, in special see the explosive pickaxe and shovel exploding stuffs!!!

### 📜 Server Log

https://pastebin.com/MXyGZ6dm

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.14.x

### ⭐ Slimefun version

Slimefun4 - #960

**Comment by Sfiguz7** [comment]
"An internal error occurred while attempting to perform this command"
This is likely caused by some issues on startup leading to Slimefun not enabling at all. Could you please attach either the full log or at least the first section with the entire startup part? From the beginning to "server online" or whatever the message is when every plugin is done loading

**Comment by lucashiagod1** [comment]
Here is... https://pastebin.com/nS6ss0Mx

**Comment by TheBusyBiscuit** [comment]
Your Spigot version is heavily outdated, that's what is causing these issues.

**Comment by lucashiagod1** [comment]
Yeah, is outdated, but the 1.16.5 is also outdated and the pickaxe works perfectly...

**Comment by TheBusyBiscuit** [comment]
You do realize that 1.16.5 came out after 1.14.4 right?

**Comment by lucashiagod1** [comment]
Man, thats not I'm talking about... https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/stable/#26 at this link has 1.14.x to 1.17.x. If 1.14.x is outdated, why show the version?

**Comment by WalshyDev** [comment]
You're using a very old 1.14 build, the build is outdated not the version. Well, the version is too but it's supported. That build isn't supported because it's so old. Use a newer build and you're fine

**Comment by lucashiagod1** [comment]
> You're using a very old 1.14 build, the build is outdated not the version. Well, the version is too but it's supported. That build isn't supported because it's so old. Use a newer build and you're fine

Oh, man, thanks a lot ^^
