### ISSUE TITLE
Plugin Incompatibility - Altar Probe when using stacker and other item plugins. Possible fixes

### ISSUE THREAD

**Issue by Skizzles** [Slimefun/Slimefun4#3203]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

This is more of a suggestion based off multiple issues found with Altar Probe items happening with multiple item based plugins like WildStacker, RoseStacker, (insert stacker name here), drop2inventory. While there are suggestions on discord, this is directly related to bug reports.

After speaking with developers of some of the plugins involved a lot of them suggested lower priority levels for these events, after speaking in the discord you guys had stated against that which is fine.

One of the devs of said plugins said:

> I think the best solution would be that they give their items the maximum possible pickup delay, which makes items to not be pickable.
> Also, they should use a lower priority, this way no other plugin will override their pickup denial. Furthermore, they should look at PlayerAttemptPickupItemEvent (or something like that), which is actually being called before PlayerPickupItemEvent, and cancel that event as well.
> I dont want to patch it on my end, because as you said it already happened with other plugins, and the best approach is that they make their plugin compatible with all the other plugins, and not force everyone to add support for their plugin
> 
> I will find the pickup delay I was talking about and will post it here later, so the Slimefun developers can chnage their code (the pickup-delay approach is much more optimizes in terms of performance as well)

If none of these options work for you guys, what would be a solution so this can be resolved for multiple plugins involved?

Thanks

### 📑 Reproduction Steps

Install WildStacker
Place an item on an ancient altar pedestal
Walk towards the item
See the item picked up

### 💡 Expected Behavior

I expected the item to not be picked up

### 📷 Screenshots / Videos

![image](https://user-images.githubusercontent.com/30563757/129658756-84bec10f-769f-40ce-b393-b95fd048c277.png)

### 📜 Server Log

N/A

### 📂 `/error-reports/` folder

None found

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Slimefun 960

### 🧭 Other plugins

WildStacker
RoseStacker
Drop2Inventory

**Comment by variananora** [comment]
Weirdly enough, I have never encountered problem with WildStacker on Ancient Altar... Will look it up later tho.

**Comment by WalshyDev** [comment]
I was actually just mentioning this the other day and said this exact thing. Other plugins check for things like not pickable as a way to know it's a custom item. I just haven't got my Java env setup yet so not been able to PR it. Fix is coming up shortly though

**Comment by Skizzles** [comment]
> Weirdly enough, I have never encountered problem with WildStacker on Ancient Altar... Will look it up later tho.

Ye only lately it has issues since 1.17, Omer said it would be a bit easier to fix on ur guys end so I came here :)

> I was actually just mentioning this the other day and said this exact thing. Other plugins check for things like not pickable as a way to know it's a custom item. I just haven't got my Java env setup yet so not been able to PR it. Fix is coming up shortly though

Thank you for the response Walshy, glad a fix is planned :)
