### ISSUE TITLE
NoSuchMethodError: org.bukkit.inventory.Inventory.isEmpty()Z

### ISSUE THREAD

**Issue by Chihsiao** [Slimefun/Slimefun4#3206]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When I attempted to do a craft with a enhanced crafting table, the exception happened.

### 📑 Reproduction Steps

1. Build a enhanced crafting table.
2. Attempt to do a craft.

### 💡 Expected Behavior

I expected that no exception would happen, and when the enhanced crafting table was empty it would notice the player that no recipe was matched. 

### 📜 Server Log

https://pastebin.com/8mi9HgZr

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.15.x

### ⭐ Slimefun version

Slimefun vDEV - 961 (git e187d878)

**Comment by variananora** [comment]
You are using outdated build of 1.15. Update it to the newest one.

**Comment by Chihsiao** [comment]
> You are using outdated build of 1.15. Update it to the newest one.

I am using paper-1.15.2-391.jar as the server jar, which is the newest one of paper 1.15.2.

I have looked up [the Javadoc of Paper-1.15](https://papermc.io/javadocs/paper/1.15/org/bukkit/inventory/Inventory.html), failing to find the method `isEmpty()`. I also looked up [the Javadoc of Paper-1.16](https://papermc.io/javadocs/paper/1.15/org/bukkit/inventory/Inventory.html) and found the method, which means that the method can used only above and at 1.16, not at 1.15 or below.
