### ISSUE TITLE
Chunk data not being saved correctly

### ISSUE THREAD

**Issue by variananora** [Slimefun/Slimefun4#3225]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

~~I'm still thinking for a better title because I'm not really sure what is happening.~~
Thanks Walshy for the new title

It seems like any world other than the defined `level-name` configured in `server.properties` will not load `chunk.sfc` correctly (even their relative nether and end world doesn't work).

<details>
<summary>Clarifications:</summary>

What I meant here is only the world defined on `level-name` configured in `server.properties` will work correctly
Examples:
Setting up `level-name=world` will only work in `world` world and will not world in other world like `world_nether` or `walshy` or `walshy_nether`

Changing it to `level-name=walshy` will only work in `walshy` world and will not world in other world like `world` or `world_nether` or `walshy_nether`

</details>

I originally found this using Multiverse for the other world, but for simplicity of this bug report I'll be testing Paper server + Slimefun only and I would test the nether world.

### 📑 Reproduction Steps

1. Install a fresh version of Paper
2. Try to GEO-Mine on the overworld and nether (Count their amounts also just for confirmation) 
3. Wait until autosaves
4. Check `./data-storage/Slimefun/stored-chunks/chunks.sfc`
5. Restart the server
6. Check the nether resources will reset on it's own and `chunks.sfc` file amount is still 0

### 💡 Expected Behavior

It should read `chunks.sfc` correctly and not reset the GEO-Scan results.

### 📷 Screenshots / Videos

It is a long video I included timestamps on the YouTube video. ~~(It still HD processing, sorry...)~~
https://youtu.be/zEcFNors-S0

### 📜 Server Log

https://haste.zneix.eu/copokiqaty.sql

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

```
> ver
[21:18:19 INFO]: Checking version, please wait...
[21:18:21 INFO]: This server is running Paper version git-Paper-238 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 7bd7b18)
You are 1 version(s) behind
> sf versions
[21:18:31 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-238 (MC: 1.17.1)
Slimefun DEV - 963 (git d6be483a)
Metrics-Module #25
Java 16

No Addons installed
> pl
[21:18:36 INFO]: Plugins (1): Slimefun
```

**Comment by WalshyDev** [comment]
Could you send the chunks.sfc you have?

**Comment by variananora** [comment]
> Could you send the chunks.sfc you have?
After server boot: nothing

<details>
<summary>After the first autosave: </summary>

```
world_nether;Chunk;-1;-1: '{"slimefun-oil":"0","slimefun-uranium":"0","slimefun-nether_ice":"0","slimefun-salt":"0"}'
world;Chunk;-1;-2: '{"slimefun-oil":"0","slimefun-uranium":"0","slimefun-nether_ice":"0","slimefun-salt":"0"}'
```

</details>

<details>
<summary>After restart: </summary>

```
world_nether;Chunk;-1;-1: '{"slimefun-oil":"0","slimefun-uranium":"0","slimefun-nether_ice":"0","slimefun-salt":"0"}'
world;Chunk;-1;-2: '{"slimefun-oil":"0","slimefun-uranium":"0","slimefun-nether_ice":"0","slimefun-salt":"0"}'
```

</details>


<details>
<summary>Autosave after restart: </summary>

```
world_nether;Chunk;-1;-1: '{"slimefun-oil":"0","slimefun-uranium":"0","slimefun-nether_ice":"0","slimefun-salt":"0"}'
world;Chunk;-1;-2: '{"slimefun-oil":"0","slimefun-uranium":"0","slimefun-nether_ice":"0","slimefun-salt":"0"}'
```

</details>

> Also, what is the world name?
`world_nether`
