### ISSUE TITLE
Robots move outside island border

### ISSUE THREAD

**Issue by exzolink** [Slimefun/Slimefun4#3231]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I'm not sure who to report this bug to, but robots can go outside the island (SuperiorSkyblock plugin)

### 📑 Reproduction Steps

Setup SuperiorSkyblock
Create island and place robot near border
Add move script and enable robot

### 💡 Expected Behavior

-

### 💻 Server Software

Airplane

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

DEV 965

### 🧭 Other plugins

SuperiorSkyblock

**Comment by variananora** [comment]
This is a protection plugin issue, please report it here
