### ISSUE TITLE
When items are locked, message displays item to unlock not category.

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun/Slimefun4#3233]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Issue #3200 was supposed to display a message to the user when trying to use something that was unlocked, what category to find it in to unlock it. Instead it only shows the item that needs to be unlocked and does not reference the category.

### 📑 Reproduction Steps

As an example, start with everything locked

1) Build a smeltery from basic machines
2) put copper dust in it
3) click the fence

The message says to unlock the Smeltery, not unlock the Smeltery in Basic Machines.

The config.yml file shows this for the not-researched message

'&4You do not have enough knowledge to understand this. &cYou will need to unlock &f"%item%&f"'

Here's the message I got in game

![image](https://user-images.githubusercontent.com/75179680/132099807-4ec8272c-f246-481b-beac-c1e0a7b30c3d.png)

### 💡 Expected Behavior

I expected to see the category where to unlock the item along with the item to unlock.

### 📜 Server Log

no error logs

### 📂 `/error-reports/` folder

no error logs

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/75179680/132099849-9911ceef-3eb5-4b06-984f-d36644077f42.png)
![image](https://user-images.githubusercontent.com/75179680/132099869-759f8a57-11b8-4097-a037-02fd51d43486.png)
![image](https://user-images.githubusercontent.com/75179680/132099883-af38e9c7-5222-470c-b555-9fa11cf62f87.png)

**Comment by TheBusyBiscuit** [comment]
The linked pull request was related to the in-guide recipe view, not the message pop up.
Sure, the category can also be added to that message. However I would consider that more of a suggestion than a bug report.

**Comment by Boomer-1** [comment]
thanks biscuit. looks like I misunderstood what it was supposed to do. 

have a great day
