### ISSUE TITLE
Infinity expansion inventory bug

### ISSUE THREAD

**Issue by dhfirmino** [Slimefun/Slimefun4#3240]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When trying to open the infinity expansion tab an inventoryclick exception on slimefun

### 📑 Reproduction Steps

open a server with slimefun, and infinityexpansion installed, try to navigate the menus, and see the exception in the console

### 💡 Expected Behavior

the internal infinity menus should open with the recipes

### 📜 Server Log

https://pastebin.com/uAZZRNWa

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Slimefun vDEV - 966 (git ab8f20f0)

### 🧭 Other plugins

ExtraTools vDEV - 29 (git 83f6db7f)
  FoxyMachines vDEV - 50 (git 2c8f23a8)
  SlimefunOreChunks vDEV - 15 (git 2520cb23)
  SensibleToolbox vDEV - 45 (git dbcee02b)
  DynaTech vDEV - 132 (git b49ee6f0)
  ExtraGear vDEV - 13 (git c62047e2)
  InfinityExpansion vDEV - 121 (git c4e42ccc)
  CMILib v1.0.3.7
  SFCalc vDEV - 34 (git 60f3c45d)
  ElectricSpawners vDEV - 23 (git 6ec96773)
  EMC2 vDEV - 11 (git 89b4400a)
  MobCapturer vDEV - 16 (git a55be0fd)
  SlimyTreeTaps vDEV - 20 (git 963f0383)
  FlowerPower vDEV - 3 (git f71e9ef8)
  PrivateStorage vDEV - 18 (git 5832db21)
  SlimeTinker vDEV - 33 (git 2b3eff04)
  TranscEndence vDEV - 35 (git b29a1a49)
  ColoredEnderChests vDEV - 23 (git 4d041832)
  FluffyMachines vDEV - 89 (git 2c269d47)
  CMI v9.0.2.5
  ChestTerminal vDEV - 44 (git 3115957d)
  DyedBackpacks vDEV - 17 (git 8b329e96)
  AlchimiaVitae vDEV - 8 (git 6d5c2f86)
  SlimefunWarfare vDEV - 63 (git 7da32599)
  EcoPower vDEV - 5 (git 5c1ecd68)
  HotbarPets vDEV - 38 (git fa6c871d)
  ExoticGarden vDEV - 77 (git a2c4b6d3)
  Liquid vDEV - 13 (git 6b71d3b3)
  LiteXpansion vDEV - 155 (git 574d551a)
  SimpleUtils vDEV - 12 (git 95769a73)
  SoulJars vDEV - 23 (git b8358a1f)
  SimpleStorage vDEV - 7 (git ef9035b3)
  SlimyRepair vDEV - 3 (git c56293bb)

**Comment by Boomer-1** [comment]
this needs to go on infinity expansions github, not slimefun

**Comment by Boomer-1** [comment]
actually just update infinity expansion. You're using an old version that is pre-game breaking update. latest is 121

**Comment by TheBusyBiscuit** [comment]
This is the Slimefun bug tracker, not InfinityExpansion. Read the checklist before you check the boxes.
