### ISSUE TITLE
AutoEnchanter overrides enchantments

### ISSUE THREAD

**Issue by variananora** [Slimefun/Slimefun4#3248]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Auto Enchanter overrides lower level on the same enchantment
Example: Pickaxe already have Unbreaking 10 and you add Unbreaking 3 book, you will get Unbreaking 3 on the final product

https://discord.com/channels/565557184348422174/565569972697301020/886602517071425637

### 📑 Reproduction Steps

1. Use auto enchanter
2. Put higher level enchantment on the main item
3. Put lower level enchantment on enchanted book
4. Lower level overrides the higher level

### 💡 Expected Behavior

Auto Enchanter should keep the highest level enchantments

### 📷 Screenshots / Videos

https://youtu.be/MXJ_LuQxJFs

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

```
> sf versions
[21:07:57 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-259 (MC: 1.17.1)
Slimefun DEV - 968 (git 79c6c139)
Metrics-Module #28
Java 16

No Addons installed
> pl
[21:07:57 INFO]: Plugins (3): Slimefun, Vault, VoidGen
> ver
[21:07:58 INFO]: Checking version, please wait...
[21:08:00 INFO]: This server is running Paper version git-Paper-259 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 810d200)
You are running the latest version
Previous version: git-Paper-250 (MC: 1.17.1)
```

**Comment by svr333** [comment]
I've tested and had the same problem

**Comment by ashton1200** [comment]
Same here I’ve tested and have had same issue
