### ISSUE TITLE
Saddle Duplication w/ Talisman of the Hunter

### ISSUE THREAD

**Issue by Azakaturan** [Slimefun/Slimefun4#3254]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When using a Talisman of the Hunter, if you kill a pig, strider (probably horse, didn't test), and the talisman procs, it will duplicate the saddle, giving you 2.

### 📑 Reproduction Steps

1. Give yourself a Talisman of the Hunter
2. Spawn in pigs or striders.
3. Put saddles on them all.
4. Kill them until the talisman procs.

### 💡 Expected Behavior

I'd expect the talisman to duplicate the mob drops, not the saddle.

### 📜 Server Log

No error

### 📂 `/error-reports/` folder

No error

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/79327162/133190397-1db9e120-27d3-492a-85c2-1fa4f5f0252c.png)

### 🧭 Other plugins

N/A

**Comment by variananora** [comment]
Confirmed with this:
https://youtu.be/mxBtHR844Gc

**Comment by brasilcraft54** [comment]
This is also happening with the wither boss if you add a nametag to it renamed from another wither boss.

**Comment by variananora** [comment]
> This is also happening with the wither boss if you add a nametag to it renamed from another wither boss.

can you clarify what you meant?

**Comment by FN-FAL113** [comment]
works with horses, tested it
