### ISSUE TITLE
AContainer Error

### ISSUE THREAD

**Issue by Seggan** [Slimefun/Slimefun4#3261]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When you place down a Galactifun Circuit Press, an NPE occurs. Since the press is an `AContainer`, I'm reporting it here. This is the base cause of Slimefun-Addon-Community/Galactifun#70. See there for more info.

### 📑 Reproduction Steps

Place down a Galactifun Circuit Press

### 💡 Expected Behavior

No error

### 📂 `/error-reports/` folder

https://pastebin.com/zmRgEx5b

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Slimefun vDEV - 968 (git 79c6c139)

### 🧭 Other plugins

Galactifun vDEV - 7 (git 770c945b)

**Comment by TheBusyBiscuit** [comment]
This is the Slimefun issues tracker.
Bugs for Galactifun, go on the Galactifun bug tracker.

**Comment by Seggan** [comment]
Yes, but the underlying issue is in AContainer. Thats why i reported it here

**Comment by TheBusyBiscuit** [comment]
I looked at the code, the underlying issue is in Galactifun/InfinityLib.
You are registering null-ingredients by bypassing the checks.
