### ISSUE TITLE
Backpack Deletion Bug

### ISSUE THREAD

**Issue by LittleGhostElvoe** [Slimefun/Slimefun4#3265]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I have encountered a bug that makes a backpack eat itself up and delete it forever.

### 📑 Reproduction Steps

1. Open a backpack in your offhand
2. Press F or your offhand key while hovering over a slot in the opened backpack
3. Close out of backpack
4. Boom the backpack is gone forever

### 💡 Expected Behavior

I didn't know what I expected to happen, I was trying to see if I could put backpacks in backpacks that way I guess

### 📷 Screenshots / Videos
![image_2021-09-17_091907](https://user-images.githubusercontent.com/76411264/133798113-8c7dbd5a-ad88-4fcf-a924-601c285915f0.png)

### 📜 Server Log

I don't have access to server logs

### 📂 `/error-reports/` folder

I don't have access to server folders

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

DEV - 937

### 🧭 Other plugins

None

**Comment by Sefiraat** [comment]
Can confirm this does indeed happen, DEV 968

https://user-images.githubusercontent.com/20646323/133805782-afe07ec5-5a94-4a23-91c3-6fd58d173205.mp4

**Comment by 100petr** [comment]
Just a temporary solution: if there are fluffy machines on the server, you can use a backpack unloader

**Comment by LittleGhostElvoe** [comment]
> Just a temporary solution: if there are fluffy machines on the server, you can use a backpack unloader

We don't got fluffy machines

**Comment by variananora** [comment]
You can ask your admin to retrieve it back using `/sf backpacks`

Can confirm this:
https://youtu.be/NseFXqircrQ
