### ISSUE TITLE
Error Disabling Metrics

### ISSUE THREAD

**Issue by ItsSynchro** [Slimefun/Slimefun4#3268]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Upon disabling Metrics, an error gets thrown.

### 📑 Reproduction Steps

1. Disable metrics

### 💡 Expected Behavior

Error not being thrown with Metrics disabled

### 📜 Server Log

https://pastebin.com/CA8m1eAh

### 💻 Server Software

Airplane

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

![sfversion](https://user-images.githubusercontent.com/16171807/133909037-3e893315-c315-4685-b33d-c99eeb4f13f7.PNG)

**Comment by variananora** [comment]
That metrics version is like 10 versions behind. Try updating it to the latest version then disabling it

**Comment by TheBusyBiscuit** [comment]
"How" or "Where" did you disable metrics?

**Comment by TheBusyBiscuit** [comment]
Nevermind, like @variananora said: You will need to manually replace your metrics jar.
