### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by WongIong** [Slimefun/Slimefun4#3271]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

https://pastebin.com/HNuJw542

### 📑 Reproduction Steps

Starting the server

### 💡 Expected Behavior

no error

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/36799194/134068339-ba4ef711-de15-4751-9b00-154dec9a6d2e.png)

**Comment by WalshyDev** [comment]
Issue in Residence, look for an update or report it there

**Comment by WongIong** [comment]
ok thank you
