### ISSUE TITLE
Basic Ore Washer bug

### ISSUE THREAD

**Issue by Disneykid93** [Slimefun/Slimefun4#3283]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

The Ore Washer doesn't work like it is shown on the wiki page with water placed in the cauldron, it worked fine on 1.16.5 and since updating only works with no water in the cauldron.

### 📑 Reproduction Steps

Build the basic ore washer that both the slimefun guide and wiki page shows and try to use sifted ore in it.
Remove the water then try to wash the sifted ore again.
Then all the resources should show up in the output chest.

### 💡 Expected Behavior

Ore washer is supposed to work when water is present in the cauldron.

### 📷 Screenshots / Videos

https://www.youtube.com/watch?v=fpRTITvaxkQ

### 📜 Server Log

https://pastebin.com/xupA8i2w (the give commands are from me testing the washer)

### 📂 `/error-reports/` folder

(No error reports show in folder)

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Slimefun version RC-28 (git 774ae8de)

**Comment by Boomer-1** [comment]
this is the ore washer. It is not meant to have water. 
![image](https://user-images.githubusercontent.com/75179680/134740986-8634001e-245f-46b5-95ab-6fc4bc2562ce.png)

**Comment by variananora** [comment]
AFAIK, this is intended behaviour.
