### ISSUE TITLE
Disabling some Slimefun items shifted some multiblocks recipe

### ISSUE THREAD

**Issue by variananora** [Slimefun/Slimefun4#3286]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

In this case I'll disable Stone Chunks from `items.yml` and try using Compressor

This also happened here: https://github.com/TheBusyBiscuit/ExoticGarden/issues/210

I think this is because when registering recipe it didn't check for the disabled items.

https://github.com/Slimefun/Slimefun4/blob/fc207b6a83866cca138e4a0b43d02e1e55a5c3b0/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/multiblocks/Compressor.java#L37-L47

I haven't tried anything else but looking at things I think I can make this work one Ore Grinder and Ore Crusher too..

### 📑 Reproduction Steps

1. Install Slimefun
2. Disable Stone Chunks from `items.yml`
3. Look at the guide, the recipe just got shifted
4. Try using the compressor just using 1 coal
5. It will output 8 coal

### 💡 Expected Behavior

The recipe should not be shifted.

### 📷 Screenshots / Videos

https://youtu.be/sgOPYilkLis

<details>
<summary>Side by side</summary>

![Untitled](https://user-images.githubusercontent.com/34732414/134792458-3d77a407-67ab-4296-be7b-c45a57179c69.png)

</details>

<details>

<summary>Normal Recipe</summary>

![image](https://user-images.githubusercontent.com/34732414/134792412-9e4bed61-5724-4701-bad1-42eae764fcf4.png)

</details>

<details>
<summary>Shifted Recipe</summary>

![image](https://user-images.githubusercontent.com/34732414/134792342-11f16b12-d860-49b2-aa25-99b615423227.png)

</details>

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

```
> sf versions
[10:34:39 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-279 (MC: 1.17.1)
Slimefun DEV - 974 (git 36c6d154)
Metrics-Module #28
Java 16

No Addons installed
```

**Comment by JustAHuman-xD** [comment]
Is this still an issue?

**Comment by variananora** [comment]
> Is this still an issue?

yes it is.

**Comment by JustAHuman-xD** [comment]
> > Is this still an issue?
> 
> 
> 
> yes it is.

Do you know if it only happens with multiblocks or if it also happens with things like machines and the ancient altar

**Comment by variananora** [comment]
just tested it and it only in multiblocks machine
it is not happening in ancient altar nor on machines.

**Comment by JustAHuman-xD** [comment]
Alright thank you, think I know what is causing it now

**Comment by JustAHuman-xD** [comment]
Alright sorry for the delay but think I made a fix for this, @variananora any chance you could test a jar? I'm not home so I can't test it and I won't be home for a couple days

**Comment by JustAHuman-xD** [comment]
> > @variananora any chance you could test a jar?
> 
> 
> 
> yeah sure just ping me at discord for this things

Got it 👍
