### ISSUE TITLE
Deluxe Combat Implementation

### ISSUE THREAD

**Issue by GeRmAnAnToNiO124** [Slimefun/Slimefun4#3317]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Basically the Slimefun plugin has an item called soulbound that makes you not lose items when you die, the pvp plugin called deluxecombat kicks and makes people drop their inventory when they die and the osulbond item is not detected and falls as well.

### 📑 Reproduction Steps

1) strikes a person
2) the person leaves the server and the punishment plugin does its job.
3) he enters the server but lost all his stuff and his inventory with soulbound items.

### 💡 Expected Behavior

Don't lose your soulbond items

### 📷 Screenshots / Videos

https://drive.google.com/file/d/1o5MmP50X8NMcFoQJVdaq5YnZRuj5BjuS/view?usp=drivesdk

### 📜 Server Log

https://mclo.gs/5XiWrCs

### 📂 `/error-reports/` folder

nothing

### 💻 Server Software

Airplane

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

Airplane git-Airplane-11 (MC: 1.16.5)
Slimefun DEV - 981 (git ee43db93)
Metrics-Module #28
Java 16

### 🧭 Other plugins

deluxe combat

**Comment by qwertyuioplkjhgfd** [comment]
According to their spigot post, the latest version (v1.30.1) has support for Slimefun, which should close the issue.

**Comment by variananora** [comment]
> According to their spigot post, the latest version (v1.30.1) has support for Slimefun, which should close the issue.

Feel free to test it and report it here, so this issue can be closed.

**Comment by WalshyDev** [comment]
Since this seems to have been fixed in the related plugin I'm gonna close. Report back if it persists.

**Comment by GeRmAnAnToNiO124** [comment]
It has not been solved, I just said that in version 1.17 of airplane it works.

**Comment by qwertyuioplkjhgfd** [comment]
> It has not been solved, I just said that in version 1.17 of airplane it works.

I doubt that Slimefun would implement a fix for another (arguably unrelated) plugin, especially for an older version where a newer version fixes it already, so the solution would just to be to update the plugin.
