### ISSUE TITLE
industrial miner small bug

### ISSUE THREAD

**Issue by VitasLoWang** [Slimefun/Slimefun4#3336]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

when you build an industrial miner, put there lava and turn it on, it can tell you that pistons should be facing up, so you fix the pistons which you accidentaly placed wrong and want to turn it on again, but you realize that the lava was already consumed!

### 📑 Reproduction Steps

see description

### 💡 Expected Behavior

lava should not be consumed if the machine is not built right

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

DEV 976

**Comment by Boomer-1** [comment]
i can confirm this has not been fixed in 985. when you build the industrial miner, the warning message does appear, but it still consumes the lava.

**Comment by Boomer-1** [comment]
https://youtu.be/fVxOQcO5N3U
here's a link to the recording to show it isn't fixed.
