### ISSUE TITLE
Industrial Miner can't mine Deepslate Ore under Y 0

### ISSUE THREAD

**Issue by EdoardLimondi** [Slimefun/Slimefun4#3338]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

This Server have Datapack Custom Heigth World

### 📑 Reproduction Steps

1- Build Industrial Miner at coordinates Y 0 or under
2- place fuel and start
3- mine 0 ores

### 💡 Expected Behavior

The industrial Miner should mine Deepslate Ore Under Y 0 

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

[11:03:15 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-338 (MC: 1.17.1)
Slimefun DEV - 937 (git 96574bed)
Metrics-Module #28
Java 16
No Addons installed

**Comment by variananora** [comment]
Update your Slimefun version. It is very outdated. The newer version already fixed this.

**Comment by EdoardLimondi** [comment]
how to update the slimefun ?

**Comment by variananora** [comment]
It should update automatically if `auto-updates` is enabled on `config.yml`. It will run on a server restart.
You can download Slimefun [here](https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/)

**Comment by EdoardLimondi** [comment]
i updated my slimefun and it's working.
thx
