### ISSUE TITLE
Uranium translation bug in Chinese

### ISSUE THREAD

**Issue by KillerSword** [Slimefun/Slimefun4#3340]
### ❗ Checklist

- [ ] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [x] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

when server is running slimefun with Chinese(China) translation,there's a text display bug on the 1-level uranium and the 2-level uranium.

### 📑 Reproduction Steps

Open the slimefun guide,click the "杂项用品” as "miscellaneous items" in english,then at the 2-5 and 2-6 uranium the chinese text is reverse.The 1-level uranium displays radiation level Medium and doesnt need Anti-chemical clothing and the 2-level uranium displays radiation level Low,and need Anti-chemical clothing.But it still causes negative effects with 2-level uranium

### 💡 Expected Behavior

The chinese translation of the two should be exchanged

### 📷 Screenshots / Videos

![91PA5~T 7Y@25B@W@RS 1OT](https://user-images.githubusercontent.com/79313771/140593794-c88c112b-f6e7-4a65-9ea5-bf6216d8664f.png
![UKQVR(RXN)20@)1LM~C(Q)M](https://user-images.githubusercontent.com/79313771/140593803-91061c1a-b8b7-4ad0-b97b-75d159bb8ee8.png)
)

### 💻 Server Software

Yatopia

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

i dont have the permission to run /sf versions so sorry
![~5EL_KJMRMU7DWAY3P}I3)P](https://user-images.githubusercontent.com/79313771/140593880-911863a9-c0d4-4bfd-ac04-fa6949fe6657.png)

**Comment by ybw0014** [comment]
请不要在官方仓库反馈汉化版内容，请前往[此处](https://github.com/StarWishSama/Slimefun4/issues)反馈。而且，改问题已在近期更新修复。
Please do not report issues with Chinese version in this repository, report [here](https://github.com/StarWishSama/Slimefun4/issues).
