### ISSUE TITLE
Soulbound not disabled when disabled in config

### ISSUE THREAD

**Issue by winnipeg21** [Slimefun/Slimefun4#3361]
### ❗ Checklist

- [x] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When I disabled soulbound items in the config already soulbound enchanted items from the ancient rune still functioned. No other config option exists for disabling already soulbound enchanted items.

### 📑 Reproduction Steps

1. Have ancient rune of soulbind enabled
2. Drop the rune with a piece of armor to enchant it
3. Disable the rune
4. Use the soulbound item

### 💡 Expected Behavior

Expected behaviour would be the soulbounded item would not function just like any SF item that is disabled.

### 📷 Screenshots / Videos

https://discord.com/channels/565557184348422174/565569972697301020/914758306130706442 <-- Related convo in the SF discord

### 📜 Server Log

Nothing in Logs

### 📂 `/error-reports/` folder

No errors

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

![Versions](https://s.pingu.ga/XSz55)

**Comment by FN-FAL113** [comment]
Tested it, still works

**Comment by variananora** [comment]
I thought I already replied to this one...

The soulbound listener still works even the item is disabled so this is why it is happening.

**Comment by winnipeg21** [comment]
It's a hit or miss bug Imo it is a bug. So disabling the rune should disable the enchant but it doesn't since the listener is still active.

One of two things needs to happen:

Disable soundbound rune would disable the listener

Add an option to toggle the listener

**Comment by winnipeg21** [comment]
> I thought I already replied to this one...
> 
> The soulbound listener still works even the item is disabled so this is why it is happening.

Lol we messed at the same time. You did in discord and I brought it to bug reports back in November.
