### ISSUE TITLE
Androids not working under y 0

### ISSUE THREAD

**Issue by DaliborTrampota** [Slimefun/Slimefun4#3385]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Androids not moving in negative Y coordinate

### 📑 Reproduction Steps

1. place android in y -50 for example
2. write script to move forward (or any other direction)
3. doesnt move. (rotating and mining works)

### 💡 Expected Behavior

Android moves

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.1

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/31895316/147154704-53e15d77-58e2-4aa2-9163-b522b0ce2729.png)

**Comment by Sfiguz7** [comment]
Confused by the tags but nevertheless, have a fix incoming

**Comment by DaliborTrampota** [comment]
> Confused by the tags but nevertheless, have a fix incoming

What tags? It's my first issue here

**Comment by Sfiguz7** [comment]
> > Confused by the tags but nevertheless, have a fix incoming
> 
> What tags? It's my first issue here

![image](https://user-images.githubusercontent.com/37039432/147161986-14acf548-b9e7-4a9a-82be-efe5bb6d9a68.png)
Me struggling with tags, don't worry your issue was perfectly fine

**Comment by DaliborTrampota** [comment]
Oh okay. It had to be automatic as I haven't add any :)

**Comment by DaliborTrampota** [comment]
And question: i see the commits that it has been fixed. Where can I download the fixed version?

**Comment by Sefiraat** [comment]
The PR has to be approved and merged before it becomes something you can actually use. When it is, this issue will close referencing the merge. Then you just need to run Slimefun and it’ll update itself :)
