### ISSUE TITLE
random people can access your waypoint even if you have a personal teleporter

### ISSUE THREAD

**Issue by teleporterisbroken** [Slimefun/Slimefun4#3389]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

random people can access your waypoint. there is no way to make your waypoint private. other poeple can access your waypoint by building another teleporter even when you're using a personal teleporter. personal teleporter is useless if peaple can access your waypoint. MAKE THE WAYPOINT PERSONAL, NOT THE TELEPORTER ITSELF.

### 📑 Reproduction Steps

1. make your own personal teleporter and waypoint
2. ask a random guy to make their own poersonal teleporter
3. and BOOM the other guy can access your waypoint 

please add a feature which makes waypoints private.

### 💡 Expected Behavior

i expect that your own waypoint to be private from everyone else if your using your own personal teleporter

### 📷 Screenshots / Videos

don't have the time.

### 📜 Server Log

can't

### 📂 `/error-reports/` folder

can't

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Slimefun vRC - 29 (git d8d037c1)

### 🧭 Other plugins

nope

**Comment by Boomer-1** [comment]
i cannot replicate this. waypoints are per player. I have two different people with different waypoints and neither can see the other in the same map. Also you did not provide all the required information, making this impossible to troubleshoot.
