### ISSUE TITLE
Auto brewer block termination issue

### ISSUE THREAD

**Issue by NewToThis3402** [Slimefun/Slimefun4#3390]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When you put a strength 2 potion and a piece of redstone on the input slot of an auto brewer, after 2-3 seconds the block gets deleted while showing an error on the console.
(this error occurred in minecraft version 1.18.1, but there is no option for selecting that yet, so I've selected 1.17x instead.)

### 📑 Reproduction Steps

Put a strength 2 potion and a piece of redstone dust on the input slot, make sure block is powered.
the block gets deleted within 2-3 seconds 

### 💡 Expected Behavior

Either nothing should happen, or it should extend the time of the potion.   

### 📷 Screenshots / Videos

![unknown](https://user-images.githubusercontent.com/96646614/147488023-195ad06b-7c47-4a91-b1db-235f052f7b16.png)
![image](https://user-images.githubusercontent.com/96646614/147488054-327a6565-3a18-42ca-932d-924a19e367df.png)

https://user-images.githubusercontent.com/96646614/147489332-1728f872-8e5a-4f52-9f44-677be8f55727.mp4

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/96646614/147489742-3a665847-5f79-4565-afab-cc32d0ec438d.png)

**Comment by TheBusyBiscuit** [comment]
Please post the corresponding error-report via pastebin, otherwise we cannot help you.

**Comment by variananora** [comment]
Yep can replicate this error
Error logs:
https://haste.zneix.eu/anitikecef.yaml

**Comment by NewToThis3402** [comment]
> Please post the corresponding error-report via pastebin, otherwise we cannot help you.

https://pastebin.com/4VKuXZqM here is the error log file

**Comment by TheBusyBiscuit** [comment]
@NewToThis3402 That's not the file, that's a message telling you where to find the file.
