### ISSUE TITLE
mfsu charging items without power

### ISSUE THREAD

**Issue by NewToThis3402** [Slimefun/Slimefun4#3391]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

The mfsu from LiteXpansion charges items without power.
in fact it doesn't even need a energy regulator.

### 📑 Reproduction Steps

place down a mfsu
don't power it
put something in which can charge, for eg. Nano blade
it starts charging without energy.

### 💡 Expected Behavior

It should not charge the item.

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Dev 987

**Comment by TheBusyBiscuit** [comment]
wrong plugin.
