### ISSUE TITLE
Cannot load configuration from stream (YAML Parsing Error)

### ISSUE THREAD

**Issue by variananora** [Slimefun/Slimefun4#3400]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Seems like some update from Spigot made errors to Slimefun while parsing a YAML files.

EDIT: this likely because of Spigot doing something on SnakeYML and updates to YamlConfiguration

### 📑 Reproduction Steps

1. Download Paper 1.18.1 (Build 120-121)  or Spigot 1.18.1 (Build 3385)
2. Install Slimefun
3. Run it
4. You get the error

### 💡 Expected Behavior

Not having errors?

### 📜 Server Log

https://haste.zneix.eu/ruqeviqafi.properties

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

```
This Server uses the following setup of Slimefun:
Paper git-Paper-121 (MC: 1.18.1)
Slimefun DEV - 992 (git 0538e345)
Metrics-Module #28
Java 17

No Addons installed
```

**Comment by WalshyDev** [comment]
Does this happen on the latest Spigot? I see quite a few commits regarding configs and snakeyaml. Wondering if the desync between Paper is what caused this

**Comment by fonkfader** [comment]
yes same issue updating on paper  git-Paper-107 (MC: 1.18.1)

**Comment by variananora** [comment]
> Does this happen on the latest Spigot?

Latest Spigot that is available is build 3385, which I also tried and having the same error.
Spigot 3385 logs: https://haste.zneix.eu/lihabohada.yaml

**Comment by qwertyuioplkjhgfd** [comment]
/languages/mk/messages.yml is not a valid yaml for example
