### ISSUE TITLE
Block Placer not denying spawners

### ISSUE THREAD

**Issue by bunnkywhat** [Slimefun/Slimefun4#3412]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Block Placer still places spawners despite it being configured not to.

### 📑 Reproduction Steps

1. Add Spawner to Block Placer's unplaceable-blocks config in items.yml
2. Added MOB_SPAWNER as well, for good measure
3. Load up server, get a spawner and put it in the Block Placer
4. Activate the block placer with a button and read console
5. Error log I posted is the result after pressing button

### 💡 Expected Behavior

The Block Placer shouldn't place the spawner at all, and should only show a black smoke animation

### 📜 Server Log

https://pastebin.com/f5wWwz6J

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/6545569/148627775-358f1fad-e94d-4be8-a0d9-9fc04b8e9702.png)

**Comment by variananora** [comment]
Spawner Item ID is `spawner` `mob_spawner` is the ID for older Minecraft versions.
