### ISSUE TITLE
Wither breaking blocks doesn't clear BlockStorage data.

### ISSUE THREAD

**Issue by variananora** [Slimefun/Slimefun4#3414]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Wither when breaking blocks (not the explosive projectile one or the first exploding one when spawned) doesn't clear BlockStorage data.

### 📑 Reproduction Steps

1. Spawn wither
2. Wait until the first explosion
3. Place blocks 
4. Bring the wither to that block for them to destroy.

### 💡 Expected Behavior

It does clear BlockStorage when destroyed like the explosion did.

### 📷 Screenshots / Videos

https://youtu.be/u80h35cXH3Y

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

```
This Server uses the following setup of Slimefun:
Paper git-Paper-141 (MC: 1.18.1)
Slimefun DEV - 994 (git eac32ac9)
Metrics-Module #28
Java 17

Installed Addons: (2)
  CMILib v1.1.0.7
  CMI v9.1.0.3
```

### 🧭 Other plugins

```
Plugins (6): CMI, CMILib, Slimefun, Vault, VoidGen, WorldEdit
```

**Comment by Boomer-1** [comment]
i'm testing shortly

**Comment by Boomer-1** [comment]
After testing Panda's test jar, I was able to confirm it is working correctly by removing the data out of the stored-blocks folder.
