### ISSUE TITLE
Problem with explosive tools (pick, shovel) in the protections in the "lands"

### ISSUE THREAD

**Issue by ArrozElManko** [Slimefun/Slimefun4#3422]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Hello, a few days ago I was getting problems with these 2 items the explosive shovel and explosive pick.

The problem I have is that if you break a block with those 2 items on the edge of the protected area, that crack penetrates

### 📑 Reproduction Steps

Explosive elements penetrate protected areas

### 💡 Expected Behavior

Not to penetrate or break the protected area

### 📷 Screenshots / Videos

https://www.youtube.com/watch?v=Fn8YBkQCAUQ

### 📜 Server Log

nothing

### 📂 `/error-reports/` folder

nothing

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

https://imgur.com/a/ZNI0ZOC

### 🧭 Other plugins

https://imgur.com/a/ZNI0ZOC

**Comment by variananora** [comment]
Any protection plugins related is handled by dough, please report it there https://github.com/baked-libs/dough.

**Comment by Sfiguz7** [comment]
Post closure, but I would check if you have `call-explosion-event` set to true in your items.yml under all explosive items.
