### ISSUE TITLE
Advanced Programmable Androids not working.

### ISSUE THREAD

**Issue by pericahuten** [Slimefun/Slimefun4#3436]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Advanced Programmable Androids (Every variant) isn't executing any scripts and consuming fuel given to it.

### 📑 Reproduction Steps

1. Place down any Advanced Programmable Android
2. Place fuel in it (feel free to do any other custom script, default turn to the left works too.)
3. Run the Android.

### 💡 Expected Behavior

Expected behaviour would be for android to execute its script just like other non advanced androids.

### 📷 Screenshots / Videos

https://www.youtube.com/watch?v=NLhmgw5FG3o

### 📜 Server Log

No response

### 📂 `/error-reports/` folder

No response

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/80347019/150534329-a6590fc8-16bc-4703-8707-357640bf3b34.png)

### 🧭 Other plugins

![image](https://user-images.githubusercontent.com/80347019/150534364-c498cd37-ed33-469c-983a-e30269384133.png)

**Comment by variananora** [comment]
Advanced Android require different type of fuel to work.
IIRC it's lava or oil. You can check it on the guide.
