### ISSUE TITLE
EcoEnchants & Auto Enchanter -> Exceeding amount of enchantments

### ISSUE THREAD

**Issue by AlternativeSoap** [Slimefun/Slimefun4#3447]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [x] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

AlternativeSoap — i dag kl. 06:19
Need some help here...
Does Auto Enchanter got an enchantment limiter? I know it got it inside "items" config, but if I set it to 8 my players can still get over 8 enchantments.

[...]

AlternativeSoap — i dag kl. 06:24
I've got ecoenchants, so they can get like really many enchantments at the same time

BOOMER_1 — i dag kl. 06:25
iirc, you can limit the # of those enchants in their config

variananora — i dag kl. 06:25
it will be bypassed by sf

AlternativeSoap — i dag kl. 06:25
I know, but it doesn't work with the auto enchanter...

variananora — i dag kl. 06:25
using auto enchanter

AlternativeSoap — i dag kl. 06:26
They said I should try to contact you if you got any ideas or workaround

BOOMER_1 — i dag kl. 06:26
ecoenchants shouldn't work in the enchanter should they?  they aren't actual enchants 

variananora — i dag kl. 06:26
hmm
can you show us a vid or smth
i'm a little bit lost
and just open an issue on github

variananora — i dag kl. 06:27
so we can track it properly

BOOMER_1 — i dag kl. 06:27
alternativesoap, are you saying players are able to apply ecoenchantments via the auto enchanter

AlternativeSoap — i dag kl. 06:27
No, I am saying they can apply more enchantments than the hard-cap.

BOOMER_1 — i dag kl. 06:27
of eco enchants or vanilla enchants

AlternativeSoap — i dag kl. 06:27
both

variananora — i dag kl. 06:28
yes, to a degree 

BOOMER_1 — i dag kl. 06:28
he's not saying that

variananora — i dag kl. 06:28
apply to item A
disenchant it
then enchant it on item B

BOOMER_1 — i dag kl. 06:28
he's saying the quantity of both are over limits

AlternativeSoap — i dag kl. 06:28
Or just use "auto enchanter" constant with a enchanted book everytime 

variananora — i dag kl. 06:29
item B exceed the max cap of enchantment configured by eco enchants

BOOMER_1 — i dag kl. 06:29
but ecoenchants should not work in the disenchanter. that's what i'm trying to find out
or the enchanter

AlternativeSoap — i dag kl. 06:29
No, not the disenchanter... Only the auto enchanter

variananora — i dag kl. 06:29
amount of enchantments. not the level of enchantments

BOOMER_1 — i dag kl. 06:29
correct
quantity

AlternativeSoap — i dag kl. 06:30
Yup correct

variananora — i dag kl. 06:30
eco enchanter is one of plugins that register itself as a 'proper' enchantment
it's not like sf 'life steal'
alternativesoap can you open the issue on github?
so we can track it?

Removed some text, but I am too tired and too lazy to explain it on point.

### 📑 Reproduction Steps

Use ecoenchants, use hard-cap quantity of enchantments on one tool at a time example 4, use an auto enchanter, go over the limit with that.

### 💡 Expected Behavior

Not to exceed the limit, everything else work but not the auto enchanter...

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

![2022-01-27_06 41 00](https://user-images.githubusercontent.com/86206216/151298729-d6818c6b-9055-4b53-8c51-a56182ff3b06.png)
![2022-01-27_06 40 58](https://user-images.githubusercontent.com/86206216/151298732-21cac940-1a6e-4000-b8dc-49d6d19dffba.png)

### 🧭 Other plugins

EcoEnchants

**Comment by variananora** [comment]
Better description:

EcoEnchants has a hard cap limit on how many enchantments a tool may have. AutoEnchanter bypassed this hard cap limit. Is there a way to block AutoEnchanter to bypass that hard cap limit

AlternativeSoap said that they already asked EcoEnchants about this and EcoEnchant said that to ask Slimefun to discuss about an idea how to fix this, or a workaround to disable it.

https://discord.com/channels/565557184348422174/565569972697301020/936128219923480616

Is it possible to add max amount of enchantment on AutoEnchanter config?

**Comment by WalshyDev** [comment]
So, I see 2 ways to probably solve this:

1. EcoEnchants simply hooks into SF and listens to our event + cancels 
2. We fire an enchant event for other plugins to handle
    1. We need to consider what the side effect of this is and if it should be an option.

**Comment by Texbio** [comment]
Bum

**Comment by AlternativeSoap** [comment]
I hope they fix it soon so I can enable auto enchanter again.

**Comment by Phoenix-Starlight** [comment]
This is a free and open-source plugin. People do this on a volunteer basis, if you'd like this to be resolved faster, consider learning how to program. Otherwise you need to give time.

**Comment by AlternativeSoap** [comment]
Trust me, I would like to learn to program, but like you say time is the real enemy. 
But thanks for this answer!

**Comment by Texbio** [comment]
bumpp

**Comment by Boomer-1** [comment]
when a fix is ready it will be released. there are bigger projects being worked on that will make larger impacts at the moment. please understand those are a greater priority. this will be addressed, just be patient.

**Comment by lvanko** [comment]
Please keep this issue in mind, many of us are reading and waiting hoping there will be some sort of solution. Out of impatience, I decided to write - please accept my suggestion to add a setting to the enchanter for the maximum number of enchanters per item. A lot of servers use different types of custom enchants, we wonder what spells to do exactly so that they don't all get 50 enchants on a sword to kill their opponent with just a look.

**Comment by J3fftw1** [comment]
> Please keep this issue in mind, many of us are reading and waiting hoping there will be some sort of solution. Out of impatience, I decided to write - please accept my suggestion to add a setting to the enchanter for the maximum number of enchanters per item. A lot of servers use different types of custom enchants, we wonder what spells to do exactly so that they don't all get 50 enchants on a sword to kill their opponent with just a look.

I see EcoEnchants marked your issue as completed.
Not exactly sure what they changed but there are 2 ways of fixing it like @WalshyDev said before.

> So, I see 2 ways to probably solve this:
> 
>     1. EcoEnchants simply hooks into SF and listens to our event + cancels
> 
>     2. We fire an enchant event for other plugins to handle
>        
>        1. We need to consider what the side effect of this is and if it should be an option.

I do wonder what EcoEnchants specifically did to mark your issue as resolved.
I can also see a third option to solve this.
To make a config option of the max enchants we let on a tool.
That could easily be done without hooking into other plugins.

**Comment by Boomer-1** [comment]
I like the config option. The only downside i can see is if the enchantment doesn't register as an actual enchant (lore). but that's not anything we could address i'd think.

**Comment by J3fftw1** [comment]
> I like the config option. The only downside i can see is if the enchantment doesn't register as an actual enchant (lore). but that's not anything we could address i'd think.

yea thats outside our reach at all. 
We do not know which lore is an enchant.

**Comment by lvanko** [comment]
The option in the config will help, no matter if the enchants are considered lore lines, everyone will be able to choose an appropriate number depending on the specifics of their server. Players will just avoid tools with more than one or two lore lines :)
