### ISSUE TITLE
Skulls missing Owner Details when in BlockMenu

### ISSUE THREAD

**Issue by Sefiraat** [Slimefun/Slimefun4#3449]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When getting a Player Head ItemStack using `BlockMenu#getItemInSlot()` the given ItemStack's SkullMeta does not have the owner details available.

### 📑 Reproduction Steps

![image](https://user-images.githubusercontent.com/20646323/151538840-d11927c8-b974-407c-b644-66dc1f9a4105.png)
In the above shot, `instanceOne` is derived from `SlimfunItem#getRecipeOutput` and has the owner details (for reference, it's a Cargo node). 'instanceTwo' is the ItemStack via `BlockMenu#getItemInSlot` and is the correct ItemStack in all bar this one element. The Skull meta has all details (including GameProfile with the correct UUID) but no owner name in the profile and thus 'getOwningPlayer()` is retuning null.

![image](https://user-images.githubusercontent.com/20646323/151539241-8d0532a6-01fd-45cb-8536-078e648f57e8.png)
When pulling the ItemStack out by hand and checking the meta then, you get the above screenshot with the correct owner information within.

### 💡 Expected Behavior

The ItemStacks should match each other perfectly - at least with the correct owner details.

### 📷 Screenshots / Videos

![image](https://user-images.githubusercontent.com/20646323/151539699-207bae8d-579f-43d2-b5cc-11cd9ec6bd2e.png)

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Dev 999

**Comment by TheBusyBiscuit** [comment]
Player Heads are handled by dough (https://github.com/baked-libs/dough)
This seems like a missing method override on dough's part
