### ISSUE TITLE
Hercules Pickaxe duplication on 1.17 ores

### ISSUE THREAD

**Issue by variananora** [Slimefun/Slimefun4#3455]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When breaking new 1.17 ores that can be converted to Slimefun dust using Hercules Pickaxe it will drop their dust and raw ore version at the same time.

List of working ores:
  - Copper Ore
  - Deepslate Copper Ore
  - Deepslate Iron Ore
  - Deepslate Gold Ore

I believe this is cause by
https://github.com/Slimefun/Slimefun4/blob/008090cc6f50b15a503ef1f151cea20931016cd0/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/HerculesPickaxe.java#L33-L47

When adding those item it doesn't break until it's over and will add their natural drop in 
https://github.com/Slimefun/Slimefun4/blob/008090cc6f50b15a503ef1f151cea20931016cd0/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/items/tools/HerculesPickaxe.java#L58-L60

Side note: Not sure why those are `* 2` tho. Destroying other ores with Hercules Pickaxe can give you twice their drop, also works with fortune enchantment. (Should I create other bug report on this? or is this intended behaviour?)

### 📑 Reproduction Steps

1. Get Hercules Pickaxe
2. Mine blocks listed above
3. They will drop dust and raw ore at the same time.

### 💡 Expected Behavior

The raw ore should not be dropped.

### 📷 Screenshots / Videos

https://youtu.be/tweHnXMhICY

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

```
This Server uses the following setup of Slimefun:
Paper git-Paper-181 (MC: 1.18.1)
Slimefun DEV - 999 (git e02eedd9)
Metrics-Module #28
Java 17

Installed Addons: (2)
  CMILib v1.1.1.0
  CMI v9.1.0.6
```

**Comment by FN-FAL113** [comment]
I wonder if this is confirmed bug, might test it later and try a fix if it is a bug

**Comment by FN-FAL113** [comment]
are the double drops even intentional, I think the fallback should not do double drops

**Comment by TheBusyBiscuit** [comment]
Hmm, yeah somehow this slipped through our code review in #3253 
Obviously any `break;` in the first switch/case can still trigger the `default:` block in the second switch/case.
It would be best to have a `boolean hasDoubledDrops` here to fix this.

Pull requests are welcome, as I am still very busy with my thesis for university.

But again... why exactly does this pickaxe exist in the first place?

**Comment by Boomer-1** [comment]
given the number of ways to turn vanilla iron, gold and copper ores into slimefun dust, it does seem unnecessary. Considering you have to be somewhat into building your slimefun system to have the materials to craft this hammer, you probably are getting into some automation at this point. if that's the case, then the hammer probably never is needed. I would agree with Biscuit that this seems unnecessary to keep in the game.

**Comment by FN-FAL113** [comment]
Yeah would also agree its unnecessary to have it ingame anymore

**Comment by TheBusyBiscuit** [comment]
The Hercules pickaxe has been deprecated for 3 months now and will now be removed.
We can consider this "resolved" then.
