### ISSUE TITLE
Not able to pick up / open Android (NullPointerException)

### ISSUE THREAD

**Issue by siaynoq** [Slimefun/Slimefun4#3462]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I have a home server - today after logging in, I was not able to destroy/pick up my miner android - nor open the interface.
On top of that, I got a NPE in the server logs. (https://pastebin.com/vX6H6w80)

I made sure I'm using the latest Slimefun lib. I have ExoticGarden and Galactifun installed.
While trying to "debug/resolve" the issue, I made myself an operator and was able to successfully remove the miner... treid to place the miner back with both op/deop rights, but I am not able to reproduce this bug anymore :(

Upon checking the code for a few mins, I have no idea how this can happen, as `me.mrCookieSlime.Slimefun.api.BlockStorage.getLocationInfo()` seems to have a proper NPE-proof implementation, but I wasn't digging into this too much... 

### 📑 Reproduction Steps

1. Place Android miner
2. ???
3. Try to open the android
4. ... or destroy the miner
 

### 💡 Expected Behavior

3. Miner opens
4. ... or picked up when destroyed.

### 📜 Server Log

https://pastebin.com/vX6H6w80

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

DEV - 999

### 🧭 Other plugins

- Galactifun
- ExoticGarden

**Comment by variananora** [comment]
> has this happened since?

not that we know of, no one seems to report it lately.

**Comment by JustAHuman-xD** [comment]
> > has this happened since?
> 
> 
> 
> not that we know of, no one seems to report it lately.

Alright I can add a quick null check to the class but yeah looks like this is related to blockstorage
