### ISSUE TITLE
Could not deserialize object

### ISSUE THREAD

**Issue by Bettanation** [Slimefun/Slimefun4#3465]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Could not deserialize object
Player was interacting with auto breeder and growth accelerator and food fabricator
For some reason they said elevator plate also turned into a normal stone plate?

### 📑 Reproduction Steps

Use latest dev 999 version.

Player was interacting with auto breeder and growth accelerator and food fabricator

### 💡 Expected Behavior

Not to throw the error

### 📷 Screenshots / Videos

n/a

### 📜 Server Log

https://pastebin.com/rsLrvS7f

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

https://ibb.co/s9ZH21g

### 🧭 Other plugins

n/a

**Comment by Boomer-1** [comment]
just an fyi - you have 2 cmi jar files in your plugins folder.

**Comment by Bettanation** [comment]
> just an fyi - you have 2 cmi jar files in your plugins folder.

Cmi lib jars, They get auto installed, not my fault. Seems like this is a paper error

**Comment by Bettanation** [comment]
This has completely broken my server. If this cant get fixed i guess im removing slimefun and resetting my map.

**Comment by WalshyDev** [comment]
First off, calm the hell down. It hasn't been an hour and you're being impatient. 

Secondly, be patient.

**Comment by Bettanation** [comment]
> First off, calm the hell down. It hasn't been an hour and you're being impatient.
> 
> Secondly, be patient.

Great response. My server is completely broken and players cant do anything. If this cant be fixed im done with slimefun, just stating the truth.

**Comment by WalshyDev** [comment]
Ok, goodbye
