### ISSUE TITLE
Explosive Shovel doesn't recognize Rooted_Dirt

### ISSUE THREAD

**Issue by Azakaturan** [Slimefun/Slimefun4#3469]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

The explosive shovel doesn't recognize rooted_dirt as a valid shovel material and doesn't explode it.

### 📑 Reproduction Steps

1- Give yourself an Explosive Shovel
2- Set an area as rooted_dirt
3- Break a block with the shovel

### 💡 Expected Behavior

It should probably break the 3x3 of rooted_dirt.

### 📷 Screenshots / Videos

https://gyazo.com/877623c86cd56818113ed75e6d320230

### 📜 Server Log

N/A

### 📂 `/error-reports/` folder

N/A

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/79327162/154863309-36be2eaa-58b5-4eb4-9fee-fc7fe78f4fae.png)

### 🧭 Other plugins

N/A

**Comment by Boomer-1** [comment]
Confirmed. Looks like panda is already at the heart of it.
