### ISSUE TITLE
Creative mode error

### ISSUE THREAD

**Issue by LozoTrioxide** [Slimefun/Slimefun4#3483]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When in creative mode, error occurs when moving things in inventory

### 📑 Reproduction Steps

Load server
move items in creative mode
error

### 💡 Expected Behavior

No error

### 📷 Screenshots / Videos

N/A

### 📜 Server Log

https://pastebin.com/fFa7fTWs

### 📂 `/error-reports/` folder

N/A

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

Paper git-Paper-237 (MC: 1.18.2)
Slimefun DEV - 1002 (git dc35bda5)
Java 17

Installed Addons: (5)
  CMILib v1.1.2.0
  RedProtect v7.7.3
  EcoPower vDEV - 5 (git 5c1ecd68)
  ItemsAdder v3.0.2
  ExoticGarden vDEV - 78 (git 7f9a5f63)

### 🧭 Other plugins

N/A

**Comment by J3fftw1** [comment]
I just repro'd it.
Checking for a fix right now

**Comment by Sefiraat** [comment]
@J3fftw1 https://github.com/Slimefun/Slimefun4/blob/7668a786caf56d96dcc146eded815882fef5a55a/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/MiddleClickListener.java#L49

**Comment by J3fftw1** [comment]
> @J3fftw1
> 
> https://github.com/Slimefun/Slimefun4/blob/7668a786caf56d96dcc146eded815882fef5a55a/src/main/java/io/github/thebusybiscuit/slimefun4/implementation/listeners/MiddleClickListener.java#L49

slow
