### ISSUE TITLE
Infused Magnet - Magical Gadgets

### ISSUE THREAD

**Issue by Rudraar78** [Slimefun/Slimefun4#3495]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

According to the description of this item ' Infused Magnet ' in the ' Magical Gadgets' Section it picks up items in a radius as long as the item is in your inventory. So to pick up blaze rods you would need to have at least one blaze rod in your inventory BUT it picks up every items in the radius  I am Aware that It could be an issue with the lore of the item.Also this bug makes the item a bit annoying because it also picks up items which are going in a hopper . Also I am playing on server with Minecraft Bedrock Edition I know that slimefun is made for Java Edition of Minecraft I am able to play on the server because of another plugin called 'GeyserMC' which provides crossplay between Java And Bedrock Edition of Minecraft I am sure that GeyserMC has nothing to do with other plugins 

> 
![Screenshot_2022-03-15-18-58-10-189_com mojang minecraftpe](https://user-images.githubusercontent.com/101646444/158390122-638b051c-84d1-453f-bf47-8b19b6923e67.jpg)

### 📑 Reproduction Steps

You can see it by 
1. Opening Slimefun Guide
2. Going in 'Magical Gadgets ' Section which has elytra item on it
3. Hover over 'Infused Magnet'

### 💡 Expected Behavior

I expected that this item would only pick up items that were already in your inventory and it would not pick up items that hoppers are sucking up

### 📷 Screenshots / Videos

![Screenshot_2022-03-15-18-58-10-189_com mojang minecraftpe](https://user-images.githubusercontent.com/101646444/158391690-f5a0d052-20c0-4075-a71e-f4bfad0c3500.jpg)

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

Slimefun Version 995

### 🧭 Other plugins

It is not related to other plugins Because Magical Gadgets Comes by itself when Slimefun is added

**Comment by Sefiraat** [comment]
The meaning here is that the MAGNET is somewhere in your inventory, not a matching item to be picked up
