### ISSUE TITLE
Flask of knowledge bug

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [Slimefun/Slimefun4#3501]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When you right click an empty flask of knowledge it takes the whole level.
Example when you right click an empty flash of knowledge when you are at level 10 it sends you back to level 9.
However when you right click a filled flask of knowledge you do not get the whole xp back and only get like a tiny portion of it.
Example when you right click a filled flask of knowledge at level 9 you stay at level 9.

### 📑 Reproduction Steps

Add some xp to yourself [Example 30 levels]
Right click an empty flask of knowledge [You should now be at level 29]
Now right click the filled flask of knowledge [You still stay at level 29 and do not get the whole xp back]

### 💡 Expected Behavior

Expected to get the whole level back instead of a tiny portion of it

### 📷 Screenshots / Videos

![image](https://user-images.githubusercontent.com/97077949/159223480-04f0c04e-adac-4dfe-aaff-cfcc2d976a46.png)

Before using empty flask of knowledge ^

![image](https://user-images.githubusercontent.com/97077949/159223521-32075015-f51f-485b-ae2b-ac8eb3d5af2c.png)

After using 1 empty flask of knowledge ^

![image](https://user-images.githubusercontent.com/97077949/159223580-c9744a5f-cc11-4fdd-b60a-b685484ef5a2.png)

After using the one filled flask of knowledge ^

### 📜 Server Log

N/A

### 📂 `/error-reports/` folder

N/A

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

[07:48:16 INFO]: This Server uses the following setup of Slimefun:
Paper git-Paper-216 (MC: 1.18.1)
Slimefun DEV - 1006 (git 114de629)
Metrics-Module #28
Java 17

Installed Addons: (34)
  GlobalWarming vDEV - 11 (git 73ff77d4)
  SlimeBot v1.1.0
  Networks vDEV - 32 (git aaff3aac)
  CrystamaeHistoria vDEV - 59 (git d9361aae)
  ExtraTools vDEV - 33 (git 46d26e49)
  AureliumSkills vBeta 1.2.10
  FoxyMachines vDEV - 55 (git c1b69ec7)
  FNAmplifications vDEV - 54 (git b26bd8f8)
  SimpleMaterialGenerators vDEV - 4 (git 5543cc8f)
  DynaTech vDEV - 160 (git e1075a1c)
  ExtraGear vDEV - 13 (git c62047e2)
  SFAdvancements vDEV - 9 (git e90d0f72)
  CMILib v1.1.2.3
  InfinityExpansion vDEV - 137 (git 4b326e08)
  SFCalc vDEV - 37 (git dfc0fc41)
  ElectricSpawners vDEV - 23 (git 6ec96773)
  MobCapturer vDEV - 17 (git c21b00a5)
  SlimyTreeTaps vDEV - 20 (git 963f0383)
  FlowerPower vDEV - 13 (git 06ad45dc)
  SlimeTinker vDEV - 71 (git a226bf46)
  TranscEndence vDEV - 40 (git cfc98363)
  FluffyMachines vDEV - 106 (git 38aa2740)
  DyedBackpacks vDEV - 17 (git 8b329e96)
  HotbarPets vDEV - 38 (git fa6c871d)
  SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
  ExoticGarden vDEV - 78 (git 7f9a5f63)
  DankTech2 vDEV - 4 (git 803760fb)
  Liquid vDEV - 14 (git 0f5346bf)
  SlimeCustomizer vDEV - 24 (git f6aa53e9)
  LiteXpansion vDEV - 174 (git e36d509d)
  ElementManipulation vDEV - 9 (git 4d3ceae6)
  SoulJars vDEV - 23 (git b8358a1f)
  EquivalencyTech v${project.version}
  PotionExpansion vDEV - 5 (git e2cfcd8a)

### 🧭 Other plugins

N/A

**Comment by TheBusyBiscuit** [comment]
That is intended.
