### ISSUE TITLE
Cargo doesnt exist

### ISSUE THREAD

**Issue by ReformedHooper** [Slimefun/Slimefun4#3504]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

There is no cargo in the latest version of slimefun, the only error I have in the console is in the paste, I do not have more errors.: https://paste.walshy.dev/TT5xl96pZ6FV

### 📑 Reproduction Steps

----------

### 💡 Expected Behavior

Not working after update

### 📜 Server Log

https://paste.walshy.dev/TT5xl96pZ6FV

### 📂 `/error-reports/` folder

https://paste.walshy.dev/TT5xl96pZ6FV

### 💻 Server Software

Airplane

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

Slimefun DEV - 1008 (git 020094e0)

**Comment by variananora** [comment]
Some categories are missing because of this commit https://github.com/Slimefun/Slimefun4/commit/d3cf518f7472c5b4e63a7df6d75b4db8672bd430

![image](https://user-images.githubusercontent.com/34732414/159472941-2ea4b41e-56bd-4d83-96a7-42cd4d8a04c6.png)

**Comment by qwertyuioplkjhgfd** [comment]
I can't access the paste, it looks like it got auto-deleted? Can you re-upload it?
