### ISSUE TITLE
Skull Texture Not Loding

### ISSUE THREAD

**Issue by Zsomi** [Slimefun/Slimefun4#3508]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

It did not fill the head texture of the slimefun objects.

### 📑 Reproduction Steps

1. Upload the SlimeFun plguin to server.
2. Restart the server.
3. Use the /sf open_guide

### 💡 Expected Behavior

When I open the menu and use the SlimeFun object, the texture of the head does not load.

### 📷 Screenshots / Videos

![Képernyőkép 2022-03-27 190301](https://user-images.githubusercontent.com/31018282/160292372-abdde7b3-ef64-48ab-8f82-57caf60a0833.png)

### 📜 Server Log

https://pastebin.com/6CQHskkd

### 📂 `/error-reports/` folder

Empty

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

Slimefun4 - DEV 1008 (git 02009)

**Comment by Boomer-1** [comment]
this is probably due to a slow internet connection.

**Comment by Boomer-1** [comment]
my guide shows no issues. Will leave this open for 24 hours to see if you can provide any additional information. Try running a speed test to see your speeds.

**Comment by Zsomi** [comment]
PING ms
10
 DOWNLOAD Mbps
203.00
 UPLOAD Mbps
21.96

**Comment by Boomer-1** [comment]
thanks for getting back. are other people having this happen on your server?

**Comment by Zsomi** [comment]
I tested it with 10 people.

**Comment by Boomer-1** [comment]
are any other players experiencing the heads in the guide

**Comment by Zsomi** [comment]
Yes.

**Comment by Boomer-1** [comment]
that would lead me to believe that for whatever reason the server just doesn't have a good connection with the head database. it's not happening across the board and there hasn't been an update to slimefun in a while. I'd check after your next scheduled restart and see if it still persists. if so, let us know

**Comment by Phoenix-Starlight** [comment]
Is the server in offline mode?

**Comment by Zsomi** [comment]
The textures of the other heads are displayed in the Headdatabase, Deluxemenus plugin
