### ISSUE TITLE
Bucket of oil,Geo Miner,GPS scanner and oil pump wont work.

### ISSUE THREAD

**Issue by Karezzzzz** [Slimefun/Slimefun4#3512]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When I try to use oil pump or geo miner I place it but for some reason, it just says CS Core libs head can you fix this bug I will appreciate it Thank you forward I removed 2 items but I will send you the picture of GEO Miner 

### 📑 Reproduction Steps

So I placed it down and it doesn't work 

### 💡 Expected Behavior

Hmm i dont know

### 📷 Screenshots / Videos

![Base Profile Screenshot 2022 03 31 - 20 05 00 93](https://user-images.githubusercontent.com/102758293/161121197-1b084383-ef94-4ec3-a8c1-14499ac4ac7c.png)

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.16.x

### ⭐ Slimefun version

DEV - 1008

**Comment by ybw0014** [comment]
downgrade to 1006 and disable auto update for now

**Comment by Boomer-1** [comment]
please provide a /pl screenshot as well

**Comment by Karezzzzz** [comment]
> downgrade to 1006 and disable auto update for now
Wdym to downgrade and how can I do that?

**Comment by Boomer-1** [comment]
delete the 1008 dev jar, download the 1006 dev jar, and turn off auto updates in the config

**Comment by Karezzzzz** [comment]
> delete the 1008 dev jar, download the 1006 dev jar, and turn off auto updates in the config

Sure ill try that

**Comment by Karezzzzz** [comment]
> delete the 1008 dev jar, download the 1006 dev jar, and turn off auto updates in the config

The problem is that I am using aternos and there is no such a version like that

**Comment by Karezzzzz** [comment]
> delete the 1008 dev jar, download the 1006 dev jar, and turn off auto updates in the config

These are the versions:
<html>
<body>


Slimefun4-1008  

Slimefun4-986 
Slimefun4-935
Slimefun4-723  
Slimefun4-559
Slimefun4-489 
Slimefun4-365 
Slimefun4-559 
Slimefun4-489 
Slimefun4-365 
Slimefun4-559
Slimefun4-489
Slimefun4-365 
Slimefun4-559 
Slimefun4-365 | 1.14.41.14.31.14.21.14.1 |  1.13.1 |  
Slimefun4-559 | 1.15.21.15.11.14.41.14.31.14.21.14.11.13.21.13.1 |  
Slimefun4-489 | 1.15.21.15.11.14.41.14.31.14.21.14.1 |  
Slimefun4-365 | 1.14.41.14.31.14.21.14.1 |  
Slimefun4-95 | 1.13.21.13.1 |  
Slimefun4-52

Slimefun4-365 | 1.14.41.14.31.14.21.14.1 |  1.13.1 |  
Slimefun4-559 | 1.15.21.15.11.14.41.14.31.14.21.14.11.13.21.13.1 |  
Slimefun4-489 | 1.15.21.15.11.14.41.14.31.14.21.14.1 |  
Slimefun4-365 | 1.14.41.14.31.14.21.14.1 |  
Slimefun4-95 | 1.13.21.13.1 |  
Slimefun4-52

Slimefun4-489 | 1.15.21.15.11.14.41.14.31.14.21.14.1 |  
Slimefun4-365 | 1.14.41.14.31.14.21.14.1 |  1.13.1 |  
Slimefun4-559 | 1.15.21.15.11.14.41.14.31.14.21.14.11.13.21.13.1 |  
Slimefun4-489 | 1.15.21.15.11.14.41.14.31.14.21.14.1 |  
Slimefun4-365 | 1.14.41.14.31.14.21.14.1 |  
Slimefun4-95 | 1.13.21.13.1 |  
Slimefun4-52


</body>
</html>

**Comment by Boomer-1** [comment]
You're on aternos? Not much we can do there. they don't let you upload files.

**Comment by Boomer-1** [comment]
also please upload the screenshot of /pl

**Comment by Karezzzzz** [comment]
> type /pl in game and take a screenshot of it

Here
![Base Profile Screenshot 2022 03 31 - 21 59 50 36](https://user-images.githubusercontent.com/102758293/161139508-625af92d-5e54-47b0-bac2-9f86d545b6a2.png)

**Comment by Karezzzzz** [comment]
> 

Sure but will anything delete from slimefun??

**Comment by Karezzzzz** [comment]
> so if dev 986 is the only other recent option you have, you can downgrade to that for now.

well I gotta say is THANK YOU SO MUCH EVERY THING IN THIS SLIMEFUN WORKS!!! you are a life saveeer
