### ISSUE TITLE
Colored an item with anvil, can make a slimefun item

### ISSUE THREAD

**Issue by TheWylot** [Slimefun/Slimefun4#3515]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

i get a stick made it bold light blue and renamed it to iron alloy ingot like slimefun item name, and it gived me an slimefun item with NBT tag of 1

### 📑 Reproduction Steps

place an anvil
rename a item like an name of slimefun tiems

### 💡 Expected Behavior

it should cancel that event

### 📜 Server Log

no errors

### 📂 `/error-reports/` folder

no errors

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Purpur git-Purpur-1428 (MC: 1.17.1)
Slimefun RC - 31 (git 0ea16bd1)

Installed Addons: (8)
  LiteXpansion vDEV - 174 (git e36d509d)
  LocketteX v1.7.5
  ExtraHeads vDEV - 23 (git 0b59a770)
  MobCapturer vDEV - 17 (git c21b00a5)
  HotbarPets vDEV - 38 (git fa6c871d)
  ExtraGear vDEV - 13 (git c62047e2)
  ChestTerminal vDEV - 44 (git 3115957d)
  ExoticGarden vDEV - 78 (git 7f9a5f63)

### 🧭 Other plugins

ColoredAnvils https://www.spigotmc.org/resources/coloredanvils.2216/ v 2.0.0

**Comment by variananora** [comment]
1. We don't support RC versions.
2. Vanilla anvil can't rename items into colored ones. You should disable anvil color.

Addition: This will be addressed in the recipe rewrite stated here https://github.com/Slimefun/Slimefun4/issues/3170
