### ISSUE TITLE
Multitool lead dupe

### ISSUE THREAD

**Issue by manul694** [Slimefun/Slimefun4#3516]
### ❗ Checklist

- [x] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Multitool can dupe leads

### 📑 Reproduction Steps

Multitool spawning a bat with lead, so if you kill the bat the lead will drop

### 💡 Expected Behavior

I used multitool and killaura

### 📷 Screenshots / Videos

https://youtu.be/WDfiK4okr8c

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/48861382/161380116-eb2bcebb-4f0d-40a8-b592-360d66edee30.png)
I am modded only for translate slimefun to russian language, the game mechanics were not affected.

**Comment by Boomer-1** [comment]
we do not support modified versions. Item names cannot be translated only lore and language. Please use the official version with the Russian translation. if you can replicate the issue with the official version, open a new report.

**Comment by variananora** [comment]
Duplicate of #2352 anyways
