### ISSUE TITLE
Flask of Knowledge can fill up water

### ISSUE THREAD

**Issue by xMikux** [Slimefun/Slimefun4#3524]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

If you don't have any exp level, you can use Flask of Knowledge like normal bottle can do.
Fill up water.

### 📑 Reproduction Steps

1. Don't have any exp level on you.
2. Take the Flask of Knowledge, right click on water.
3. See it fill with water.

### 💡 Expected Behavior

Don't fill up water.

### 📷 Screenshots / Videos

https://user-images.githubusercontent.com/26039249/162515971-6b177d52-9fae-4bc9-a7da-23d5d0279c24.mp4

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/26039249/162513799-779ea737-c6a7-4231-9d0a-549911da409b.png)

**Comment by FN-FAL113** [comment]
is this really a bug

**Comment by variananora** [comment]
> is this really a bug or filling should be canceled
yes.
