### ISSUE TITLE
Heads Displaying Textureless

### ISSUE THREAD

**Issue by kirin-3** [Slimefun/Slimefun4#3532]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

All of the head-sized blocks such as generators, cargo nodes, energy connectors, etc. are displayed as white/black no texture blocks. When you move around the textures pop-in and pop-out, one moment they are white and then displayed correctly same as placing the same kind of blocks.

### 📑 Reproduction Steps

I am honestly not sure when did this start happening so it's hard for me to tell how to reproduce properly. Right now placing any kind of Slimefun head blocks causes this issue but not with Head database heads or vanilla heads.

### 💡 Expected Behavior

Head blocks to display texture

### 📷 Screenshots / Videos

![Screenshot_20220414_180052](https://user-images.githubusercontent.com/85101965/163421395-ef39e147-1a3b-4fad-88a5-6c0488a213ec.png)

### 📜 Server Log

https://privatebin.net/?e5f524ae98c1b88a#4ftnsfsGz7B51w2VF2ycKkpfrD4aFFnoJKpNSEHUAzUG

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

![Screenshot_20220414_182025](https://user-images.githubusercontent.com/85101965/163421546-205a5786-e1a9-489f-a11f-f1b0fc71e6a2.png)

### 🧭 Other plugins

I am also using ItemsAdder and Head Database and also have Exotic Garden, Simple Storage, Fluffy Machines and SfCalc addons.

**Comment by Boomer-1** [comment]
not that this is related, but you can turn backwards compatibility off if nothing on your server is before mid 2019.

**Comment by kirin-3** [comment]
> not that this is related, but you can turn backwards compatibility off if nothing on your server is before mid 2019.

Yeah, I've realized that today when I was looking for answers. I've turned that off, which will apply after next restart.

**Comment by kirin-3** [comment]
The issue also happens with Exotic Garden's fruits as they are head blocks as well. Just found it easy to display the texture pop with it.

![Peek 2022-04-14 18-56](https://user-images.githubusercontent.com/85101965/163427817-f54ace8d-d73e-499d-b6cb-69c0f1ab5334.gif)

**Comment by kirin-3** [comment]
Okay, this seems to be a ItemsAdder issue. When no resource pack is applied they display correctly when the resource pack is on they become bugged again. I've also tried with default slimefun and ItemsAdder configurations, same issue.
