### ISSUE TITLE
Auto Enchanter Deletes Items

### ISSUE THREAD

**Issue by purpleskier1** [Slimefun/Slimefun4#3534]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When placing an auto enchanter on the ground unconnected to an energy network, placing an item to enchant and an enchant book just deletes both items and they phase out of existence. There is nothing processing in the center where it normally says there is a minute left etc. It literally just deletes the tool and book.

### 📑 Reproduction Steps

1. Place auto enchanter on the ground unconnected to an energy network.
2. Put a tool and a book in the auto enchanter slot, that is the left side surround by the blue panes of glass.
3. Be super pissed off that your items just got deleted and complain the the server admin.

### 💡 Expected Behavior

I expected nothing to happen and for the items to just sit there if they are not connected to power. The correct behavior if the enchanter is not connected to an energy network would be to place the tool and book in and have them not phase from existence.

### 📜 Server Log

No error message

### 📂 `/error-reports/` folder

No error report

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/100005820/163484915-37efde99-5014-4395-a2f7-31f48ca1b570.png)

**Comment by Boomer-1** [comment]
once you power it the items will complete the process

**Comment by Boomer-1** [comment]
the correct behavior would be to put it in when it's powered from a network, not to input them when it's not

**Comment by purpleskier1** [comment]
Yeah I am aware you are supposed to have it powered for it to work but I did not know that if you added power to it after the fact that it will still work. I appreciate it. I still feel as if this is an issue that should be fixed though because new players don't know that and end up mining it up and losing the items anyway.

**Comment by Boomer-1** [comment]
It may be possible. let's see what the dev's can do with it.

**Comment by TheBusyBiscuit** [comment]
Not really a "bug" but I can see why the lack of an indicator can cause confusion here.
I can add the indicator a tick earlier which should make it appear in cases where the machine is not powered.
I think we should have an "Missing power" indicator specifically but since localization is not supported by our inventories yet, it couldn't be translated.
