### ISSUE TITLE
Bio Reactor can't be crafted

### ISSUE THREAD

**Issue by StarRibbon** [Slimefun/Slimefun4#3535]
PLS delete the issue:
I can't read
Brass =!= Bronze

**Comment by StarRibbon** [comment]
Forgot plugins:
![2022-04-15_22 38 56](https://user-images.githubusercontent.com/103781795/163629236-536fae90-c239-4f43-9011-fa648e3f1db9.png)
(Can't get version info)

**Comment by ybw0014** [comment]
why dont you close it youself
