### ISSUE TITLE
Disappering Gold Pans

### ISSUE THREAD

**Issue by kirin-3** [Slimefun/Slimefun4#3538]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Electric gold pans are disappearing if you interact with them too much.

### 📑 Reproduction Steps

1. Make an electric gold pan 3 process 
2. spam right click and ESC on it.

### 💡 Expected Behavior

Not to disappear.

### 📷 Screenshots / Videos

https://user-images.githubusercontent.com/85101965/164281649-2eb8e575-87a5-4139-b0a7-4e4c87607373.mp4

[Error Report 2](https://privatebin.net/?3fd0180b9d95cd98#7SGkpFZx5BSRDucviKhLHsZFeyiwb4bubgD2h78DHjFx)
[Error Report 3 - Different stacktrace](https://privatebin.net/?edcc64e2b376a177#HxkXrYJfP9mpzS1ZpNcKmbcprqyDhCDh9Lk4DGB7KuRB)

### 📜 Server Log

https://privatebin.net/?8ed346065e73474b#QniTSpzbUqcWtSNkEUuKgdZQ49yJwhZrVvEjTR5xHn7

### 📂 `/error-reports/` folder

https://privatebin.net/?3deb9cba446fd7fd#12i9wb6HDbwKwEfEfau7moK6STyvigPbpKs2e4SbKGT6

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

![Screenshot_20220420_194851](https://user-images.githubusercontent.com/85101965/164282196-e32bbc3a-6410-4405-bbff-000e67ac39fc.png)

**Comment by Boomer-1** [comment]
for now, downgrade to 1009

**Comment by LevyLucas** [comment]
I would like to add that this bug is occurring with any electrical machine.. it is happening a lot on my server with more than one machine

**Comment by Boomer-1** [comment]
downgrade to dev 1009
