### ISSUE TITLE
Can't Place Cargo Nodes to Machines

### ISSUE THREAD

**Issue by kirin-3** [Slimefun/Slimefun4#3544]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I can not place cargo nodes input/output onto slimefun machines. I can onto chests and if you place a chest and put nodes onto it then break the chest and put a machine in its place, the machine works as expected.

I had a problem yesterday with paper's update folder patch which was discussed in the discord. I believe that might be the cause of this as well, although I did rollback my server, I still had the issue for a brief time period afterwaards.

### 📑 Reproduction Steps

I'm not sure but as i said I think its related to update folder patch so;
1.run a server with slimefun latest and place some machines and nodes.
2.stop the server and put older slimefun version into plugins/update folder.
3.start server and stop when it loads.
4.remove the old slimefun jar from both updates folder and plugins folder and upload the latest slimefun jar
5.run the server
6.try placing nodes on the machines

### 💡 Expected Behavior

To be able to place nodes on machines.

### 📷 Screenshots / Videos

https://user-images.githubusercontent.com/85101965/164507067-2e934b7d-c6b6-4475-8ee4-b5dcb6f7300e.mp4

### 📜 Server Log

https://privatebin.net/?4bc6fd15de6b3236#3jyRt2yJKCsLhe3oPFwb9uDwhheHmSH5gt1dpwSgdng7

### 📂 `/error-reports/` folder

No errors anywhere.

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

![Screenshot_20220421_192846](https://user-images.githubusercontent.com/85101965/164507447-da40ece0-53ee-46fe-8acb-80d73d502b9a.png)

I'm using 1009 because of #3538

**Comment by J3fftw1** [comment]
tested this issue in 1.18.2 
paper version 299
and slimefun version 1010
i dont seem to have this issue, try changing your server build to paper since we dont support purpur. The recent changes that they pulled in could have broken this.

**Comment by Boomer-1** [comment]
I'm not having issues in paper 1.18.2 on dev 1009

**Comment by kirin-3** [comment]
I still get the same issue paper299 and dev 1009 SF :( I've also tried with one version lower purpur which doesn't have most of the recent paper patches, still the same.

**Comment by Boomer-1** [comment]
gotta ask, you're not trying to put them on top of the machines, are you?

**Comment by kirin-3** [comment]
I'm trying every side? There is a video above as well

**Comment by NIKIBG12** [comment]
I have the same issue, and I tracked it down to advancedenchantments latest updates, 8.9.14 is the latest that works for me without this error

**Comment by Boomer-1** [comment]
kirin, please try removing the advanced enchantments plugin to confirm if that fixes it for you.

**Comment by FN-FAL113** [comment]
This is a known bug with AE, it affects all heads and it also auto rotates it to the south. Downgrading the version is a temp fix

**Comment by Boomer-1** [comment]
has an issue been opened with AE?

**Comment by kirin-3** [comment]
Can confirm its AE bug.
