### ISSUE TITLE
 Placing a block above a crucible causes the recipe to fail and lose the items entirely

### ISSUE THREAD

**Issue by soolarr** [Slimefun/Slimefun4#3559]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When placing a block above a crucible that is actively turning cobble into lava, the recipe will fail and you will lose the cobble permanently, even if the block was removed quickly and instantly after placing the block.

### 📑 Reproduction Steps

1. Place A Crucible
2. Right Click The Crucible With 16 Cobblestone
3. Place A Block Over The Crucible
4. Remove The Block Instantly

### 💡 Expected Behavior

The lava to be generated correctly & not to fail the recipe.

### 📷 Screenshots / Videos

https://youtu.be/UGEGgWSK2g8

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

https://i.imgur.com/kSqwomZ.png
https://i.imgur.com/jloPfs2.png

**Comment by Boomer-1** [comment]
I guess I don't know what you expect when you deliberately stop it from working. I'll leave this open only to see if a dev wants to chime in, but to me this is invalid.

**Comment by TheBusyBiscuit** [comment]
This is intentational, to prevent various glitches and ways in which the crucible could be abused.
