### ISSUE TITLE
Can't use any machines in any worldguard region, Anyone help?

### ISSUE THREAD

**Issue by dgaming152** [Slimefun/Slimefun4#3569]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Basically I cant use any machines in any WorldGuard protected region & I cant solve this anywhere please help all the machines work outside of the region but when built inside the region they dont work even on my OP account

### 📑 Reproduction Steps

Create a protected region with the World Guard plugin Then try and place a basic machine in that region & it wont let you use it 

### 💡 Expected Behavior

I thought it was going to work :D 

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

DEV - 1-14 (git f431aa6d) Metrics-module #28

### 🧭 Other plugins

WorldGuard 7.0.7

**Comment by Boomer-1** [comment]
As was told to you in the discord, you must correct your settings in worldguard. this is not a slimefun issue.
