### ISSUE TITLE
TeleporterManager throwing an ArithmeticException

### ISSUE THREAD

**Issue by TheRealEzCoins** [Slimefun/Slimefun4#3573]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When teleporting between 2 Matrix teleport devices it would throw an ArithmeticException upon clicking the waypoint of the other teleporter. Whenever you click on the waypoint it'll throw you out of the menu and not let you open it up again. on restart it would also throw this error and not be-able to load the thread requiring a full reboot again (Server is running Pufferfish (Velocity))
![unknown](https://user-images.githubusercontent.com/82239215/170864401-4be32265-8752-4d60-be36-4b1ab63f41ef.png)

### 📑 Reproduction Steps

1. Place 3 energized transmitters at y320
2. Try teleporting 
3. breaks
![image_2022-05-29_131852111](https://user-images.githubusercontent.com/82239215/170865311-898e8b6a-49cb-4b56-bfcc-2cbd41ffc7fe.png)

### 💡 Expected Behavior

I expected it to just normally teleport you to the other waypoint like it does with any other waypoint.

### 📷 Screenshots / Videos

https://youtu.be/qosbtApavRw

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

Slimefun4 - DEV 1014

**Comment by Phoenix-Starlight** [comment]
Have you verified the problem exists on Paper?

**Comment by TheRealEzCoins** [comment]
> Have you verified the problem exists on Paper?

Yep, seems like it also works on Paper from my testing

**Comment by variananora** [comment]
Sorry for late reply, I can't seems to replicate this, I think this is fixed has been fixed on dough or something. Is this still an issue on your server?
