### ISSUE TITLE
Swift Sneak In Auto Enchanter

### ISSUE THREAD

**Issue by DeLorean1355** [Slimefun/Slimefun4#3600]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When I put netherite boots (Prot 4, mending, unbreaking 3, depth strider 3) and a swift sneak 3 enchanted book into an auto enchanter, it would not enchant the item. Nothing happened. There was adequate power connected to the enchanter. I believe it didn’t recognize it as a valid enchant as it’s a new one from 1.19.

### 📑 Reproduction Steps

When I put netherite boots (Prot 4, mending, unbreaking 3, depth strider 3) and a swift sneak 3 enchanted book into an auto enchanter, it would not enchant the item. Nothing happened. There was adequate power connected to the enchanter. I believe it didn’t recognize it as a valid enchant as it’s a new one from 1.19.

### 💡 Expected Behavior

I expected the process of auto enchanting to begin and the timer to start. Afterwards I expected the boots to be enchanted with swift sneak 3.

### 📷 Screenshots / Videos

https://cdn.discordapp.com/attachments/565569196218384385/992476885114179634/Lunar_Client_1.19-9f9eccb_master_2022-07-01_12-06-54.mp4

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

DEV 1015

### 🧭 Other plugins

Not related to another plugin

**Comment by ybw0014** [comment]
swift sneak is a enchantment for leggings, not boots, as we already talked about it in discord

**Comment by DeLorean1355** [comment]
Oh, my bad!

**Comment by Boomer-1** [comment]
As noted, working as intended. Enchant goes on leggings
