### ISSUE TITLE
Auto Drier cannot Crafted

### ISSUE THREAD

**Issue by MegalithOffical** [Slimefun/Slimefun4#3604]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Im putting Auto Drier companents into Enchanted Crafter but its not working

### 📑 Reproduction Steps

Try to do Auto Drier crafting

### 💡 Expected Behavior

I expected to Craft Auto Drier

### 📷 Screenshots / Videos

![javaw_siVYlksViV](https://user-images.githubusercontent.com/74655120/177036632-c4315a6c-bab5-4aab-94ca-fcfd57e2b4ca.gif)
![image](https://user-images.githubusercontent.com/74655120/177036656-e23343f6-007c-4243-b284-dac12a0b5183.png)

### 📜 Server Log

https://paste.ee/p/LY08j

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Slimefun4 - DEV 1015 (git 2c4f8)
Metrics-Module #28
Java 17

### 🧭 Other plugins

Installed Addons: (5)
  InfinityExpansion vDEV - 140 (git 0098d2fb)
  LiteXpansion vDEV - 178 (git 1f81893c)
  EcoPower vDEV - 5 (git 5c1ecd68)
  ItemsAdder v3.2.0
  ExoticGarden vDEV - 78 (git 7f9a5f63)

**Comment by variananora** [comment]
I think that campfire can't have an NBT Tag, try to craft fresh campfire and try again.

**Comment by Boomer-1** [comment]
99% sure var is right.

**Comment by Boomer-1** [comment]
@TheSidOffical have you any further info? did you try it with a campfire that had no nbt data?
