### ISSUE TITLE
Windstick Dupe Bug

### ISSUE THREAD

**Issue by GitNuck** [Slimefun/Slimefun4#3618]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Using a Windstick collide twice with a painting and a duplicate Windstick will drop.  Tried colliding with a wall to test and no dupe, also tested with players on the Server that are not OP and they too can dupe, so not a permission or group related issue.

### 📑 Reproduction Steps

Face  a painting, use the Windstick twice colliding with the painting.

### 💡 Expected Behavior

Not being able to dupe a Windstick

### 📷 Screenshots / Videos

https://user-images.githubusercontent.com/88690764/178918782-090e802b-f025-4dd6-b7c0-b59ae303d985.mp4

### 📜 Server Log

No errors

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

![2022-07-14_00 48 19](https://user-images.githubusercontent.com/88690764/178919239-26b0ded7-9ec0-491f-90c8-d85705317950.png)
![2022-07-14_00 49 47](https://user-images.githubusercontent.com/88690764/178919487-4b0a6378-63b0-421b-bad5-b7bcf9e8fb94.png)

**Comment by Sefiraat** [comment]
Messages about editing a painting are being sent, can you confirm which of your plugins all this behaviour?

**Comment by GitNuck** [comment]
CraftBook

**Comment by Sefiraat** [comment]
If you have a test server, please try to recreate this without craftbook to see if the issue still persists. Thanks

**Comment by GitNuck** [comment]
> If you have a test server, please try to recreate this without craftbook to see if the issue still persists. Thanks

100% CraftBook is the culprit, thanks for the help!
