### ISSUE TITLE
Progammable Android miner not working

### ISSUE THREAD

**Issue by TrainingBear** [Slimefun/Slimefun4#3636]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When android Running, Suddenly stop for a moment.

### 📑 Reproduction Steps

https://user-images.githubusercontent.com/77871999/182125197-179fc87f-d833-4ab4-a1ab-3159a667e0fc.mp4

### 💡 Expected Behavior

I hope this is fixed as soon as possible

### 📷 Screenshots / Videos

https://user-images.githubusercontent.com/77871999/182120314-3830edb5-87c6-4826-922c-e205b85926d5.mp4
![2022-08-01_16 17 18](https://user-images.githubusercontent.com/77871999/182120883-763a5f98-b342-4cb7-9f7b-d55983009839.png)

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

Slimefun4 - DEV 1026 (git 85e8f)
![2022-08-01_16 56 05](https://user-images.githubusercontent.com/77871999/182124495-e1032ce5-3504-4bb5-bac6-cbfd8671774b.png)

### 🧭 Other plugins

  + SkinsRestorer 14.2.1
  + WorldEdit 7.2.10+1742f98
  + PlaceholderAPI 2.11.1
  + Slimefun4 - DEV 1026 (git 85e8f)
  + HardcoreSlimefun 1.0
  + Galactifun DEV - 63 (git 364ecbf5)
  + FluffyMachines DEV - 121 (git efca037f)
  + ExoticGarden DEV - 78 (git 7f9a5f63)
  + LiteXpansion DEV - 180 (git d574b154)
  + InfinityExpansion DEV - 140 (git 0098d2fb)

**Comment by J3fftw1** [comment]
This is not an issue. You got hardcore slimefun installed this will make androids malfunction 1 in x chance

**Comment by Sefiraat** [comment]
As Jeff said, this is not Slimefun causing this and in an intended effect of the addon you have installed :) Will close now.
