### ISSUE TITLE
Textures not showing up through GeyserMC

### ISSUE THREAD

**Issue by JoshLoecker** [Slimefun/Slimefun4#3638]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When using SlimeFun with GeyserMC, textures in the slimefun guide (such as "Useful Items", "Resoures", and "Technical Components") show up as player heads in the bedrock version.

This may be a limitation with using GeyerMC and SlimeFun - I was wondering if there is any method to resolve the missing textures?

Thanks for any help!

(Note: If this is an issue related to GeyserMC, please let me know and I will direct my question to their issue page! I wasn't sure which to start with)

### 📑 Reproduction Steps

1. Start a server with SlimeFun and GeyserMC
2. Join the server using a bedrock client (Windows, Console, or Mobile)
3. Execute the command `/sf guide`
4. Open the book given to you
5. View the missing textures, which show up as player heads
6. In Java these show up as textures

### 💡 Expected Behavior

I would like to see the modified/new textures as present in the java version when using bedrock

### 📷 Screenshots / Videos

This is what I see on mobile (bedrock)
![IMG_B8167BD688CE-1](https://user-images.githubusercontent.com/47901540/182895918-0ba0ee6d-8fea-4a1a-a9f4-b9d33989524d.jpeg)

This is what I see on Java
![Screen Shot 2022-08-04 at 11 12 50 AM](https://user-images.githubusercontent.com/47901540/182896545-323f10c1-db48-4dd4-8508-b850f3677b20.png)

### 📜 Server Log

No server errors occur

### 📂 `/error-reports/` folder

No errors are present

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

![Screen Shot 2022-08-04 at 11 14 16 AM](https://user-images.githubusercontent.com/47901540/182897103-02697251-6bb1-4d8c-b4e5-de757477246a.png)

### 🧭 Other plugins

This is the version of GeyserMC I am running
![Screen Shot 2022-08-04 at 11 14 39 AM](https://user-images.githubusercontent.com/47901540/182897248-652d7311-12d2-48b8-a149-efaf5ec8912c.png)

**Comment by WalshyDev** [comment]
This is a Geyser limitation, not a bug in Slimefun.
