### ISSUE TITLE
 Missing recipes

### ISSUE THREAD

**Issue by GonxaMS** [Slimefun/Slimefun4#3651]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I just installed the plugin on my minecraft server and recipes are missing, supposedly the logs only have 228 items and 258 researchs

### 📑 Reproduction Steps

When starting the server I get the error
"[18:02:42] [Server thread/ERROR]: [Slimefun] Item "STAFF_ELEMENTAL_STORM" from Slimefun vDEV - 1027 (git 96c873bd) has caused an Error!"

### 💡 Expected Behavior

-

### 📜 Server Log

https://pastebin.com/QPtZZ77C

### 📂 `/error-reports/` folder

https://pastebin.com/3ryP8Xv2

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Slimefun DEV - 1027 (git 96c873bd)

### 🧭 Other plugins

CMILib v1.2.3.3

**Comment by variananora** [comment]
Try to redownload your Slimefun jar and your Paper jar (and remove the cache folder too), because I can't replicate this problem.

**Comment by Boomer-1** [comment]
any updates?

**Comment by Boomer-1** [comment]
specifically did you clear the cache folder then restart the server?

**Comment by VanillaChan6571** [comment]
I solved this issue but not sure it’s a bug for Slimefun. 

for whatever reason Slimefun doesn’t like datapacks, so if you have any datapacks installed on the server like I did (I had custom world gen datapacks) You must remove them all otherwise the recipes do not load correctly. I don’t know if this a bug or not. Although it’s recommended that Slimefun devs should look into why datapacks cannot be used with Slimefun or some recipes don’t load like GPS category etc.

**Comment by variananora** [comment]
What datapacks are you using btw? I'll look into it later when available.

**Comment by VanillaChan6571** [comment]
> What datapacks are you using btw? I'll look into it later when available.

![3FDC4F30-0117-470B-B1E5-E3BDE2E49C65](https://user-images.githubusercontent.com/39040261/188079491-0b123838-dd18-4f8a-890d-94d42128cf25.png)

**Comment by VanillaChan6571** [comment]
[Datapacks.zip](https://github.com/Slimefun/Slimefun4/files/9475804/Datapacks.zip)

So you dont have to go searching for them, i will just upload a zip here for faster results.

**Comment by variananora** [comment]
I dont want to download a random zip files tho tbh, do you have the source link or smth?

**Comment by VanillaChan6571** [comment]
Slimefun dislikes https://www.planetminecraft.com/data-pack/william-wythers-overhauled-overworld/ (william-wythers-overhauled-overworld datapack) for those who are using it, I dont know if its been worked on it or not but if you do come across this post, remove this datapack or similar datapack and it should resolve itself. Not sure why 5 recipes/categories are missing and not the whole plugin killing itself. Something to do with "biomes" which is weird but okay.

**Comment by TheBusyBiscuit** [comment]
I resolved the issue found within the error report.
It should now spit out a warning instead of failing to load items and recipes.
