### ISSUE TITLE
Various addon drops are not disabled when world file sets items to false.

### ISSUE THREAD

**Issue by roracle** [Slimefun/Slimefun4#3660]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When disabling Slimefun in a world (./plugins/Slimefun/world-settings/worldname.yml) drops are still enabled.  If Slimefun is disabled, drops should not occur, but they do.

### 📑 Reproduction Steps

Set everything in a world file to "false".
Notice how Slimefun Warfare and Exotic Garden drops still occur.  Interestingly, Iron Golems do not drop circuit boards (and the "item is disabled in this world" message shows up.  That functionality should be reflected on all item drops if the world has them disabled.

### 💡 Expected Behavior

If an item is disabled in the world file, it should never drop.

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Slimefun DEV - 1027 (git 96c873bd)

### 🧭 Other plugins

Exotic Garden and Slimefun Warfare are the immediate ones. Other drops from other addons may occur as well, but I haven't tested everything (because I don't know how to get a comprehensive list of all dropped items Slimefun and addons are creating).

**Comment by Sefiraat** [comment]
This report needs to be made on the addon's GitHub pages respectively. Slimefun provides addon developers the tools to *know* when an item is disabled but it's up to us as developers to check and ensure these things still do not occur. A report should only be made on the Slimefun repo if a Slimefun core item is behaving in the manner you suggest here.

As addons have many varied and wonderful ways of providing/dropping items to players, it cannot be handled from beginning to end by Slimefun.

**Comment by roracle** [comment]
> This report needs to be made on the addon's GitHub pages respectively. Slimefun provides addon developers the tools to *know* when an item is disabled but it's up to us as developers to check and ensure these things still do not occur. A report should only be made on the Slimefun repo if a Slimefun core item is behaving in the manner you suggest here.
> 
> As addons have many varied and wonderful ways of providing/dropping items to players, it cannot be handled from beginning to end by Slimefun.

I presumed since core Slimefun controlled the world list to enable or disable items, it was handled by core. 

How do I find which addons are dropping items?

**Comment by Sefiraat** [comment]
You've identified two above?

**Comment by roracle** [comment]
> You've identified two above?

Immediately found while experimenting in the vanilla world
