### ISSUE TITLE
SlimefunAddon bug

### ISSUE THREAD

**Issue by JWJUN233233** [Slimefun/Slimefun4#3663]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I'm a Chinese developer , my plugin's name is DTech ,I meet a strange problrm
I make a SlimefunAddon plugin ,the plugin can add custom item to Slimefun.
you can change file "Blocks.yml" to add your items/blocks.
I add a recipe to a item ,the guide show the recipe ,but I cannot craft it

### 📑 Reproduction Steps

I load Slimefun and my plugin
Blocks.yml:
`DTECH_TEST:
  id: DTECH_TEST
  name: 测试
  lore: 测试物品
  useTexture: false
  texture: ''
  material: CHEST
  cannotPlace: false
  useLore: true
  recipe:
    '1': CHEST
    '2': CHEST
    '3': CHEST
    '4': CHEST
    '5': DIAMOND
    '6': CHEST
    '7': CHEST
    '8': CHEST
    '9': CHEST
  ItemUse:
  - tellraw [playerName] {"text":"你使用了物品"}
  BlockUse:
  - tellraw [playerName] {"text":"你使用了方块"}
PORTABLE_TNT:
  id: PORTABLE_TNT
  name: '&e手持式TNT'
  lore: '&f右键它将点燃'
  useTexture: false
  texture: ''
  material: TNT
  cannotPlace: true
  useLore: true
  recipe:
    '1': TNT
    '2': TNT
    '3': TNT
    '4': TNT
    '5': REDSTONE
    '6': TNT
    '7': TNT
    '8': TNT
    '9': TNT
  ItemUse:
  - takeitem [playerName]
  - tellraw [playerName] {"text":"快跑!","color":"red"}
  - summon PRIMED_TNT [playerLocation] [playerWorld]
TEXTURE:
  id: TEXTURE
  name: '&e材质测试物品'
  lore: ''
  useTexture: true
  texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTYyYzQ5MWUyNDIzNjMzZDlhZTc5ODdlZjg2NjFlZmQ0ZTY4M2ZjODdkNzVjODkwMzNkYjIyN2FmZjVhMDk3MCJ9fX0=
  material: TNT
  cannotPlace: false
  useLore: false
  recipe:
    '1': AIR
    '2': AIR
    '3': AIR
    '4': AIR
    '5': AIR
    '6': AIR
    '7': AIR
    '8': AIR
    '9': AIR
CESHI:
  id: CESHI
  material: TNT
  name: '&e测试物品'
  lore: 'null'
  useTexture: true
  useLore: false
  recipe:
    '1': AIR
    '2': AIR
    '3': AIR
    '4': AIR
    '5': AIR
    '6': AIR
    '7': AIR
    '8': AIR
    '9': AIR
  texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmI1ZjQyZTU3MzAwM2U2ODllNzc1ZTM2MTI4NWFlMDA4YjExNjdlNjg0YjJiy2MzMGE5OWRkM2Q0ZjZmYzNmJ9fX0=
DIAMOND_BLOCK:
  id: DIAMOND_BLOCK
  material: DIAMOND_BLOCK
  name: '&b钻石块'
  lore: 'null'
  useTexture: true
  useLore: false
  recipe:
    '1': DIAMOND
    '2': DIAMOND
    '3': DIAMOND
    '4': DIAMOND
    '5': DIAMOND
    '6': DIAMOND
    '7': DIAMOND
    '8': DIAMOND
    '9': DIAMOND
  texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWVhOThlOGQ2YzU2NDJlMzJhYjU2OWRhYmY5M2NkNjkwNDYwYzQ5NDc3Y2E5YjlkYmY3MjU5YjM3OTUxZjJhZCJ9fX0=
`
then you found my plugin's item cannot be crafted
my plugin : https://github.com/JWJUN233233/DTech

### 💡 Expected Behavior

I craft the item is right

### 📷 Screenshots / Videos

https://user-images.githubusercontent.com/66861021/186549690-2dc15ff7-8b4a-4d1a-8606-1c48484ac8a5.mp4

### 📜 Server Log

https://pastebin.com/XPLyQwib

### 📂 `/error-reports/` folder

there are nothing

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Slimefun-v2022.07-release

### 🧭 Other plugins

![无标题](https://user-images.githubusercontent.com/66861021/186553226-ccdd7280-8193-493b-b0e9-912d72db7092.png)

**Comment by JWJUN233233** [comment]
Slimefun version is Slimefun-v8c1a744-canary

**Comment by Boomer-1** [comment]
This is not a problem with Slimefun. This is an issue with your addon.

**Comment by JWJUN233233** [comment]
I make a test again ,I don't think it's a bug of my plugin
![image](https://user-images.githubusercontent.com/66861021/186620690-735190ce-7412-4074-8d51-145ac6703335.png)
I copy the code of develop guide ,but it cannot be crafted 

https://user-images.githubusercontent.com/66861021/186623973-d6423009-4e02-498a-be14-18902bcf2cf9.mp4

**Comment by Sefiraat** [comment]
The version of Slimefun you have quoted is not one I recognise and is, unfortunately, not supported. This is due to the fact that changed in this custom version *could* be what is causing you issues here. Please try the same against a stock dev build of Slimefun and see if you still have the issue

**Comment by JWJUN233233** [comment]
https://user-images.githubusercontent.com/66861021/186652246-39a27986-880b-44fc-8ba9-2c9f43dd52a4.mp4

I stil have the issue
I can't download dev build of Slimefun,maybe I need VPN,but I don't have VPN
I use the newest version

**Comment by Boomer-1** [comment]
if you aren't using an official version, there is nothing we can do. additionally, if your add-on is not working, that has nothing to do with slimefun. here is the link to the official version.

https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/

**Comment by JWJUN233233** [comment]
:(
![image](https://user-images.githubusercontent.com/66861021/186677260-9ceb1f3b-46c9-47ca-8809-4d2ca112c460.png)

**Comment by JWJUN233233** [comment]
![image](https://user-images.githubusercontent.com/66861021/186677631-4b5b6da7-ccfc-402e-85b7-db513a9cbbeb.png)
I download this version

**Comment by Boomer-1** [comment]
Use the dev version. however, the issue still resides with your addon.

**Comment by Boomer-1** [comment]
the download link works for me fine. so either your computer lost connection, or something / someone has blocked your access

**Comment by DongShaoNB** [comment]
you are not using the official version of Slimefun, please go to the corresponding version to submit issue or use official version of Slimefun
you using version of Slimefun: https://github.com/StarWishsama/Slimefun4/

**Comment by JWJUN233233** [comment]
I cannot download , either

**Comment by Sefiraat** [comment]
Please note this issue is closed and seemingly has no reason to be reopened based on the current information. 
If you need further help it may be beneficial for you to communicate on the Slimefun Discord under #ProgrammingHelp where you may be able to find out what exactly you're doing wrong.
