### ISSUE TITLE
Backpack dupe items

### ISSUE THREAD

**Issue by ybw0014** [Slimefun/Slimefun4#3664]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Backpacks can be used to dupe items.

Two players, a backpack, and backpack upgrade materials are needed.

### 📑 Reproduction Steps

1. Player A holds a backpack in main hand, and a portable crafting table in off hand.
2. Player A opens a backpack, and put items that need to be duped (e.g. 64x diamonds).
3. Player A press F to switch backpack & portable, and switch back. (Not closing backpack)
4. Player A drops the backpack, without closing the backpack.
5. Player B picks up the backpack from Player A, upgrade it in enhanced crafting table.
6. Player B opens the backpack, gets the 64x diamonds.
7. Player A gets 64x diamonds, in total, 128x diamonds.

### 💡 Expected Behavior

The opened backpacks are closed.

### 📷 Screenshots / Videos

https://youtu.be/IFFCafxr7bQ

### 📜 Server Log

N/A

### 📂 `/error-reports/` folder

N/A

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

DEV - 1027

### 🧭 Other plugins

No

**Comment by TheBusyBiscuit** [comment]
Thanks for the detailed bug report!

The issue should be fixed within the latest commit.
Players should no longer be able to swap the backpack from hand to another while having the backpack open.
Additionally, a safeguard was added to close the backpack inventory before upgrading its size.

**Comment by SrMonsterYT** [comment]
bug continues in version  DEV - 1033 (git 5455fb08)

**Comment by pump61** [comment]
dupe is still working I can do it right now if I need to, in the video I show that I'm using version 1033

**Comment by SrMonsterYT** [comment]
please fix this, people are abusing it, and if I remove it from my server I will lose a lot of items.

**Comment by J3fftw1** [comment]
You could temporarily disable it

**Comment by Phoenix-Starlight** [comment]
Patience. This is an open-source project contributed to by volunteers.

**Comment by Phoenix-Starlight** [comment]
Also you will not lose backpack data if you were to disable usage. The
data will remain but no one can make backpacks or use them.

**Comment by SrMonsterYT** [comment]
> You could temporarily disable it

ok thanks and sorry

**Comment by TheBusyBiscuit** [comment]
I hope it is fixed now, haven't tested it yet. Let me know if the next build will have this issue fixed.
I suspect the reason the previous fix wasn't working was due to a threading issue.

**Comment by ybw0014** [comment]
Just tested in Slimefun 1035 and looks like it is fixed.
