### ISSUE TITLE
android miner griefs other bases

### ISSUE THREAD

**Issue by RIPISDRAD** [Slimefun/Slimefun4#3665]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

there is a bug with android miner that when u put it outside of the claim and program it to dig and move forward it gonna dig into other claims and grief them !!!
it works with grief prevention and landlords I tried them both but not other claiming system

### 📑 Reproduction Steps

put an android miner outside of a claiming area
do script dig forward and move forward again and again
put fuel
turn it on
watch it destryoing everything

### 💡 Expected Behavior

i expected for it to dont happen? or at least stop when it enters other claims or even claiming area

### 📷 Screenshots / Videos

---

### 📂 `/error-reports/` folder

nothing 

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

1027

### 🧭 Other plugins

grief prevention / landlords with world guard

**Comment by Boomer-1** [comment]
I believe this is related to dough, not slimefun, but I'll let an admin confirm.

**Comment by variananora** [comment]
Yep, please create an issue on [dough](https://github.com/baked-libs/dough/issues)
