### ISSUE TITLE
floating holograms

### ISSUE THREAD

**Issue by SrMonsterYT** [Slimefun/Slimefun4#3666]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

the holograms are getting airborne

### 📑 Reproduction Steps

just by putting any machine or power generator that uses holograms

### 💡 Expected Behavior

the hologram does not stay in the air

### 📷 Screenshots / Videos

1° https://prnt.sc/thXqHnV0m0Ad
2° https://prnt.sc/_h52cpQMHXtg

### 📜 Server Log

no

### 📂 `/error-reports/` folder

no

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Slimefun4 - DEV 1027 (git 96c87).jar

### 🧭 Other plugins

server and addons: https://prnt.sc/bmAXPr4VynJd

**Comment by ybw0014** [comment]
Isn't this duplication of #3176?

**Comment by Boomer-1** [comment]
yes it is. closing. also follow the instructions in the common issues on the wiki to remove. First, start by placing the item back, and rebreaking it. if that doesn't work, use another item that generates a hologram. for example, if  your power regulator left it, put it back and rebreak it. if it still stays, use a cargo manager. If it is still there follow the wiki instructions.
