### ISSUE TITLE
NOT a BUG How can I make 3d plants with itemsadder for slimefun?

### ISSUE THREAD

**Issue by mitchngwen** [Slimefun/Slimefun4#3670]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

How can I change the way the plants look with itemsadder for slimefun? where is the custom model data for each plant stored?

### 📑 Reproduction Steps

nada

### 💡 Expected Behavior

nada

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

not pertinent

**Comment by ybw0014** [comment]
Issue tracker is used to report BUGS only, for other questions, ask in discord.

**Comment by mitchngwen** [comment]
You took the time to write back to me you could have just answered my
question. Lol

**Comment by Sefiraat** [comment]
> You took the time to write back to me you could have just answered my question. Lol
> […](#)

Your question was answered though by signposting you to the correct channel for these requests. This is important not just for the question you have now but will redirect any questions you may have in the future. By answering you directly here would infer that you should use this method again in the future?
