### ISSUE TITLE
Iron dust wrong item

### ISSUE THREAD

**Issue by Distoupia** [Slimefun/Slimefun4#3674]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Some time ago i have a minecraft server in 1.16.x, all working fine and progressing in the slimefun guide. But actually, iron dust for be created, need iron ore, an ore that you just can get it with silk touch. Some time ago, SlimeFun was a little fast for progress, but actually, you need silk touch for get one of the first items, and this is something you don't changed, please, fix it 🙏🏻

### 📑 Reproduction Steps

1. Open SlimeFun Guide.
2. Look for Iron Dust.
3. Unlocked.
4. And see his craft.

### 💡 Expected Behavior

Crush raw iron in the ore crusher instead of a iron ore.

### 📷 Screenshots / Videos

![imagen](https://user-images.githubusercontent.com/106001914/190730480-d725ddf2-c9cd-4635-878d-27c7baa7aa36.png)

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Dev 1027 (git 96c87)

**Comment by Boomer-1** [comment]
you have not reported any actual problem. You can already turn raw iron into iron dust.

**Comment by Boomer-1** [comment]
you also get iron dust from sifted ore, so you have 3 different ways of obtaining it.
