### ISSUE TITLE
error report on energy regulator

### ISSUE THREAD

**Issue by threlief** [Slimefun/Slimefun4#3680]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

someone places a energy regulator gives error in console and then disappears 

### 📑 Reproduction Steps

get energy regulator 
place on ground 
it will give error in console 
then the regulator will disappear

### 💡 Expected Behavior

regulator to stay where placed

### 📜 Server Log

https://pastebin.com/BDf3xD0Q

### 📂 `/error-reports/` folder

https://pastebin.com/PqFGmgsr

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Paper git-Paper-135 (MC: 1.19.2)
Slimefun DEV - 1033 (git 5455fb08)
Metrics-Module #28
Java 17
Installed Addons: (17)
  Networks vDEV - 45 (git ade6fbd0)
  DyedBackpacks vDEV - 17 (git 8b329e96)
  ExtraTools vDEV - 36 (git 922c0324)
  ShopGUIPlus v1.78.0
  FoxyMachines vDEV - 59 (git c3ed4f8a)
  SlimefunOreChunks vDEV - 15 (git 2520cb23)
  DynaTech vDEV - 172 (git 81955fc0)
  AdvancedEnchantments v8.15.5
  SlimefunLuckyBlocks vDEV - 36 (git 60f0c8dc)
  InfinityExpansion vDEV - 140 (git 0098d2fb)
  CMILib v1.2.3.6
  ElectricSpawners vDEV - 23 (git 6ec96773)
  ExtraHeads vDEV - 23 (git 0b59a770)
  SoulJars vDEV - 23 (git b8358a1f)
  MobCapturer vDEV - 21 (git f82c20fc)
  SlimyTreeTaps vDEV - 20 (git 963f0383)
  FluffyMachines vDEV - 127 (git cf047dcf)

**Comment by J3fftw1** [comment]
https://pastebin.com/PqFGmgsr
in this pastebin it says this has to do with DynaTech not a slimefun issue
Nothing has changed on this code for ages aswell soo
Please report it there
