### ISSUE TITLE
backpack dupe

### ISSUE THREAD

**Issue by pump61** [Slimefun/Slimefun4#3682]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

**Recently you released a fix to the dupe related here in the issues but the dupe is still working, I'm using version 1033 and I can still reproduce the duplication using the same way as before**

### 📑 Reproduction Steps

put the backpack in the left hand and the sf book in the right

when you open or open the sf book the backpack ends up opening on top

then you put the items you want to duplicate

press f to release the left hand backpack

and drop it to a friend

so your friend goes there and upgrades
 example: small to medium

note: while your friend is upgrading the backpack you keep the inventory open and when he does you take the items you want to dupe from the menu that will remain open

then he will open the backpack and the items will be in his inventory and inside the backpack

### 💡 Expected Behavior

The upgraded backpack retains the items that were inside it even though they were removed in the procedure

### 📷 Screenshots / Videos

https://streamable.com/yzib9s

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/61327951/193577093-8bad0e8d-75e7-4640-be61-3c8c9a8c9759.png)

**Comment by variananora** [comment]
closing this because of reopening of #3664
