### ISSUE TITLE
ancient altar isnt working

### ISSUE THREAD

**Issue by Aggvel** [Slimefun/Slimefun4#3687]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

i was trying to craft ancient rune [fire] but the ancient altar stoped working i have crafted items before with it and havent made modifications to it since i look at the website if i was doing something wrong nothing.I checked 10 times if i had the recepie wrong answer is i didnt idk why but it just stoped working please tell me if im doing something wrong .Server was running on minehut

### 📑 Reproduction Steps

idk what happened

### 💡 Expected Behavior

the rune should have been crafted but it didnt

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

DEV - 937 (git 96754bed)

**Comment by variananora** [comment]
1. You dont have the latest version of Slimefun, update it. We have a checklist for a reason. 
2. 'idk what happened' is not useful, we can't figure out what you were doing thus can't help you
3. You probably have an NBT tag in your vanilla item. Make sure you use brand new crafted item. In this case is: `flint and steel`, `fire charges`, and `blaze powder`
4. If you need any help, [Slimefun's Discord Server](https://discord.gg/slimefun) is the way to go, not here.
