### ISSUE TITLE
Slimefun container problem

### ISSUE THREAD

**Issue by DeadBoy2537** [Slimefun/Slimefun4#3688]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [ ] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [x] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

(I'm sorry but my version 1.14.4 server does not work with the DEV version of Slimefun)
When I put items into a Slimefun container (such as the Automatic Ignition Chamber) and then destroy the container, the items inside the container will double drop.

### 📑 Reproduction Steps

1. Put some items in the Slimefun container (such as Automatic Ignition Chambe)
2. Close the container, and then destroy it, the items will double drop

### 💡 Expected Behavior

Not asking for a fix, but hoping to give a solution

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.14.x

### ⭐ Slimefun version

Slimefun vRC - 32 (git e13d157a)

**Comment by J3fftw1** [comment]
We sadly dont support rc versions we only support dev versions since these issues can be already fixed in those versions

**Comment by variananora** [comment]
side note: you can use dev version in 1.14.4, you just need java 16. if you use spigot there is a java version limit (iirc is 15?), so try using paper. or just update to the newer minecraft versions.

**Comment by DeadBoy2537** [comment]
> side note: you can use dev version in 1.14.4, you just need java 16. if you use spigot there is a java version limit (iirc is 15?), so try using paper. or just update to the newer minecraft versions.

I tried to start the server with Java 16 (server version is paper-1.14.4-245), but it just tells me "Unsupported Java detected (60.0). Only up to Java 13 is supported." (I'm using Adoptium OpenJDK)

**Comment by J3fftw1** [comment]
That will be an issue with your hosting service then
