### ISSUE TITLE
Error Spam / Book dupe

### ISSUE THREAD

**Issue by PhoenixCodingStuff** [Slimefun/Slimefun4#3699]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Console is filled with errors mentioned below.
People can get Books which they are not supposed to get

### 📑 Reproduction Steps

Open the Slimefun setting menu <- Crouch and spam click with Slimefun Guide.
Click on Back icon

### 💡 Expected Behavior

No error in console. 
No (<-- Back) book received.

### 📷 Screenshots / Videos

![image](https://user-images.githubusercontent.com/97077949/196427300-8f9d0ec4-d613-462c-b0f5-cd36bb0f92b8.png)
![image](https://user-images.githubusercontent.com/97077949/196427392-a693f604-e7ce-4101-8108-b2a473d76a1b.png)

### 📜 Server Log

https://paste.walshy.dev/W0dhQv6SVILp

### 📂 `/error-reports/` folder

N/A

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

[Tue 08:16:42 INFO ] This Server uses the following setup of Slimefun:
Paper git-Paper-206 (MC: 1.19.2)
Slimefun DEV - 1034 (git 7b9d769b)
Metrics-Module #28
Java 17
Installed Addons: (26)
  Networks vDEV - 45 (git ade6fbd0)
  CrystamaeHistoria vDEV - 78 (git 340f1a94)
  AureliumSkills vBeta 1.3.9
  FoxyMachines vDEV - 60 (git b0ae0062)
  RelicsOfCthonia vDEV - 7 (git 5e498434)
  SlimefunOreChunks vDEV - 15 (git 2520cb23)
  FNAmplifications vDEV - 79 (git 220e6eb2)
  SimpleMaterialGenerators vDEV - 4 (git 5543cc8f)
  DynaTech v1.0.0
  SFAdvancements vDEV - 21 (git e6f6cf10)
  SlimeHUD vDEV - 7 (git fd655730)
  CMILib v1.2.3.6
  InfinityExpansion vSlimeCraft
  ElectricSpawners vDEV - 23 (git 6ec96773)
  MobCapturer vDEV - 21 (git f82c20fc)
  SlimyTreeTaps vDEV - 20 (git 963f0383)
  SlimeTinker vDEV - 77 (git 99a520b9)
  TranscEndence vDEV - 41 (git 98d7d47e)
  FluffyMachines vSlimeCraft
  AlchimiaVitae vDEV - 22 (git 09618c12)
  HeadLimiter vDEV - 14 (git 0a02e2fd)
  ExoticGarden vDEV - 78 (git 7f9a5f63)
  DankTech2 vDEV - 8 (git f2a8ab1f)
  SlimeCustomizer vDEV - 27 (git 3d8b02e5)
  LiteXpansion vDEV - 182 (git d3800398)
  SoulJars vDEV - 23 (git b8358a1f)

### 🧭 Other plugins

N/A

**Comment by TheBusyBiscuit** [comment]
This issue does not make any sense to me.
Not only am I unable to reproduce this, the error seems completely unrelated too.

The error would suggest that this is caused by a broken addons item. I added some additional logging, so try on the latest build again and post the new error. Then we will know what addon caused this error message.

**Comment by J3fftw1** [comment]
https://github.com/ProfElements/DynaTech/commit/333c2e7a3059d983d3326c56c062b5474e045f9c

This might be the cause

**Comment by TheBusyBiscuit** [comment]
Yep, that should be the cause!
