### ISSUE TITLE
Golden Apple Juice not applied absorption effect

### ISSUE THREAD

**Issue by xMikux** [Slimefun/Slimefun4#3701]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When drinking ``Golden Apple Juice``, normally will apply Absorption effect, but after drinking it, it is not applied.

### 📑 Reproduction Steps

1. Make a Golden Apple Juice
2. Drink it
3. And look it applied Absorption effect or not

### 💡 Expected Behavior

After drink it, it will apply Absorption effect.

### 📷 Screenshots / Videos

https://user-images.githubusercontent.com/26039249/196673306-69edeea3-4a48-497a-8ece-b5aeb9a5cab1.mp4

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/26039249/196672660-393d4165-a839-4d1f-82d2-8e7e77c8ab24.png)

**Comment by Boomer-1** [comment]
was able to duplicate this.
