### ISSUE TITLE
Subcategories are still visible in the guide despite everything inside being disabled and hidden.

### ISSUE THREAD

**Issue by VoltroXP** [Slimefun/Slimefun4#3705]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When everything in a subcategory is disabled and hidden from the guide, the subcategory doesn't go away and can still be opened, revealing it is empty inside. Normal Slimefun categories are hidden from the guide when they are empty, like if you were to disable everything in the android category. This does not appear to function for subcategories though.

This primarily affects Slimefun add-ons, such as ExoticGarden and FluffyMachines, since Slimefun itself doesn't really have any sub-categories. However, according to the developer of the latter, the issue is with Slimefun, so I am reporting it here.

### 📑 Reproduction Steps

1. Since Slimefun doesn't really have any subcategories, install any Slimefun add-on (such as ExoticGarden or FluffyMachines).
2. Disable everything in one of the subcategories (such as Magical Plants or Portable Chargers), and hide them from the guide.
3. Restart the plugin/server.
4. The subcategories are still visible in the guide, and are empty upon opening them. 

### 💡 Expected Behavior

I expected that upon disabling everything in a subcategory, the subcategory would no longer be visible in the guide like normal categories.

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Slimefun DEV - 1035

### 🧭 Other plugins

FluffyMachines vDEV - 127
ExoticGarden vDEV - 78

**Comment by Boomer-1** [comment]
this would be an issue with each specific addon. please open an issue with the addon you are questioning if this should be the case.

**Comment by VoltroXP** [comment]
> this would be an issue with each specific addon. please open an issue with the addon you are questioning if this should be the case.

I stated in the report that it's not an issue with each plugin though, the developer of FlufflyMachines said so. Given that the issue is prevalent in BOTH FlufflyMachines and ExoticGarden, I am inclined to agree with them.

**Comment by VoltroXP** [comment]
https://github.com/NCBPFluffyBear/FluffyMachines/issues/129#issuecomment-1287638682

**Comment by Boomer-1** [comment]
core slimefun doesn't have any sub categories. they are only in addons, but I'll reopen this in case I'm misunderstanding how the sub categories are setup.
