### ISSUE TITLE
Some receipts are missing and PICKAXE_OF_CONTAINMENT doesn't drop the broken spawner when breaking the spawner 

### ISSUE THREAD

**Issue by GoodDay360** [Slimefun/Slimefun4#3712]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Some receipts are missing and PICKAXE_OF_CONTAINMENT doesn't drop the broken spawner when breaking the spawner 

### 📑 Reproduction Steps

1. craft PICKAXE_OF_CONTAINMENT
2. mine spawner
3. drop nothing and give an error in console 

### 💡 Expected Behavior

fix missing receipts and fix PICKAXE_OF_CONTAINMENT so it drops broken spawner

### 📷 Screenshots / Videos

![2022-11-14_21 03 54](https://user-images.githubusercontent.com/59399625/201679915-5b11355e-363a-4e2e-a646-2500efd06c8d.png)

### 📜 Server Log

https://mclo.gs/AVSoNpP

### 📂 `/error-reports/` folder

Folder is empty.

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

[Slimefun4 - DEV 1035 (git 0b7c6).jar](https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/Slimefun4-1035.jar)

### 🧭 Other plugins

![image](https://user-images.githubusercontent.com/59399625/201679259-4b8b0798-df1f-445b-bfd9-8763145bc23e.png)

**Comment by Boomer-1** [comment]
how about some more information. What recipes are missing? 

also a video showing the pickaxe not working correctly. it is working perfectly for me

**Comment by J3fftw1** [comment]
in the error it shows its missing recipes. thats why im wondering about datapacks since we have had these issues before with datapacks

**Comment by Boomer-1** [comment]
ah, I missed the log. yeah, remove that datapack. also we don't support offline mode.

**Comment by Boomer-1** [comment]
remove datapack. if after it is removed you still have an issue, you can reopen this.

**Comment by ybw0014** [comment]
linking to #3651, if u are using same datapacks

**Comment by J3fftw1** [comment]
I would like to know what datapacks he is using since they shouldnt cause an issue
even tho we dont support offline offline isnt bricking the server.
