### ISSUE TITLE
Error 429 occurance

### ISSUE THREAD

**Issue by RazihelYT** [Slimefun/Slimefun4#3719]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Ive been getting this printout in my console log since the installation of Slimefun. Im currently running version Slimefun DEV (git 0b7c656d) and have ExoticGardens version ExoticGarden vDEV (git 7f9a5f63) installed as well. Ive tried searching everywhere on google relating to rate-limiting and the skin listed in the dough error associated with Slimefun. Ive come up empty handed and would like to fix this error accordingly. Thank you for your time.

[08.12 12:07:02] [Server] [ERROR] [dough: skins] Exception while requesting skin: https://api.mojang.com/users/profiles/minecraft/st392

[08.12 12:07:02] [Server] [WARN] [Slimefun] Attempted to refresh skin cache, got this response: ExecutionException: java.io.IOException: Server returned HTTP response code: 429 for URL: https://api.mojang.com/users/profiles/minecraft/st392

[08.12 12:07:02] [Server] [WARN] [Slimefun] This usually means mojang.com is temporarily down or started to rate-limit this connection, nothing to worry about!

### 📑 Reproduction Steps

Install SlimeFun4 and ExoticGardens most recent releases for 1.19.2
Start server
Check server console for errors

### 💡 Expected Behavior

Ive noticed that this error and I havent noticed any issues with slimefun, I just get spammed with an error notification often and would like to resolve the issue.

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

[08.12 12:07:19] [Server] [INFO] This Server uses the following setup of Slimefun:
[08.12 12:07:19] [Server] Paper git-Paper-(MC: 1.19.2)
[08.12 12:07:19] [Server] Slimefun DEV (git 0b7c656d)
[08.12 12:07:19] [Server] Metrics-Module #28
[08.12 12:07:19] [Server] Java 17
[08.12 12:07:19] [Server] Installed Addons(3)
[08.12 12:07:19] [Server]   Brewery v3.1.1
[08.12 12:07:19] [Server]   CMILib v1.2.3.7
[08.12 12:07:19] [Server]   ExoticGarden vDEV (git 7f9a5f63)

**Comment by WalshyDev** [comment]
> This usually means mojang.com is temporarily down or started to rate-limit this connection, nothing to worry about!

**Comment by RazihelYT** [comment]
> > This usually means mojang.com is temporarily down or started to rate-limit this connection, nothing to worry about!

This has been going on for over 2 months.

**Comment by Boomer-1** [comment]
well, we can't control what Mojang does with their servers. they have been rate limiting a lot of servers lately.

**Comment by ConaII** [comment]
This isn't caused by Mojang's servers.

```
{
  "path" : "/users/profiles/minecraft/st392",
  "errorMessage" : "Couldn't find any profile with that name"
}
```

This is caused by one of the contributors inside of:
`/plugins/Slimefun/cache/github/code2_contributors.json`

1. That account doens't exist or changed their name.

**Comment by Boomer-1** [comment]
it isn't happening across the board. if it was the above, every server would see it

**Comment by ConaII** [comment]
It happens in my server too

**Comment by Boomer-1** [comment]
So far only 2 people have reported it. if a few more do, then it may be. however, it's not a slimefun error, it's an error under dough, which would be reported there

**Comment by Boomer-1** [comment]
it's also not a big deal, as it only would appear on the server starting and doesn't affect anything.

**Comment by ybw0014** [comment]
This is due to a contributor named *st392* no longer being a valid Minecraft username, so mojang will return 429. His only contribution is [#12](https://github.com/Slimefun/Slimefun4/pull/12) that was made in 2016
