### ISSUE TITLE
Soul jars mobs error

### ISSUE THREAD

**Issue by AzCreep** [Slimefun/Slimefun4#3722]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

when i launch the plugin it all loads fine exept for soul jars that spams an error when launching

### 📑 Reproduction Steps

1. literally just launching the server it should show somewhere on console

### 💡 Expected Behavior

Launch fine?

### 📷 Screenshots / Videos

![image](https://user-images.githubusercontent.com/49355027/206931162-5e79e07b-afa6-4368-848d-05bb559f7b5b.png)

### 📜 Server Log

https://paste.denizenscript.com/View/103889

### 📂 `/error-reports/` folder

Empty folder

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Slimefun Dev 1035

### 🧭 Other plugins

SoulsJars Dev 23

**Comment by ybw0014** [comment]
This is not Slimefun.

**Comment by Boomer-1** [comment]
please report this on the soul jars github.
