### ISSUE TITLE
Could not pass event FurnaceSmeltEvent

### ISSUE THREAD

**Issue by LcyDev** [Slimefun/Slimefun4#3741]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

N/A

### 📑 Reproduction Steps

Unknown

### 💡 Expected Behavior

N/A

### 📜 Server Log

https://paste.gg/p/ConaII_/ce0b4a7588a34a96a7b233f099e54ec7

### 💻 Server Software

git-Purpur-1892

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

DEV - 1039 (git 3ae41d59)

**Comment by Phoenix-Starlight** [comment]
Ignore the issue most likely.

**Comment by J3fftw1** [comment]
This doesnt seem like a slimefun issue more a paper issue.
What version of paper do you run?

**Comment by Boomer-1** [comment]
looks like purpur 1892

**Comment by J3fftw1** [comment]
Nice catch boomer.
Try latest version of Purpur if that doesnt work try latest of papermc.
if that doesnt work report back

**Comment by LcyDev** [comment]
I think it's not happening anymore (purpur 1.19.3 build 1900)

**Comment by LcyDev** [comment]
At least i can't replicate it (I'm guessing it was by smelting in the Enhanced Furnace?)
I tried all 10 levels

**Comment by LcyDev** [comment]
Can confirm, keeps happening.
I will try paper i guess

**Comment by LcyDev** [comment]
https://paste.gg/p/ConaII_/ba285dbaa2654c33a3544a0e8b714ba9

**Comment by LcyDev** [comment]
[01:00:42] [Server thread/ERROR]: Could not pass event FurnaceSmeltEvent to Slimefun vDEV - 1040 (git ec3ce731)
java.lang.NullPointerException: null

**Comment by J3fftw1** [comment]
Okay looking at the code i might have found the problem. 
Do you have anything that is giving a minus luck value. 
Thats the only thing i can see right now causing an issue

**Comment by J3fftw1** [comment]
@LcyDev If you have discord please join the slimefun discord server and ping me in #offtopic
Slimefun server https://discord.gg/slimefun
My discord `J3fftw#0806`

**Comment by Boomer-1** [comment]
LcyDev - we are going to do a test on a build, but we need the steps that caused the error to begin with. can you please provide those?

**Comment by LcyDev** [comment]
Ok, one admin suggested what could be the cause of this and he was in fact, correct.

It has to do with custom recipes with furnaces. I confirmed it with [CustomCrafting](https://github.com/WolfyScript/CustomCrafting) but i don't know if it happens with datapack recipes too

**Comment by J3fftw1** [comment]
So i narrowed it down to luck.
Your error points to some line of code where we calculate luck for items that are smelted to give multiplied output.
But it can also be customcrafting for other blocks.
Im not sure how its calculated.
But feel free to send your custom crafting config on here so we can do some testing

**Comment by LcyDev** [comment]
https://paste.gg/p/ConaII_/940c849daff745d2acdf93719aafcf55

**Comment by Boomer-1** [comment]
without knowing what created it, not sure how i can test for it, or the potential fix

**Comment by J3fftw1** [comment]
With the files you provided i cant reproduce the issue.
Could you send the whole folder of plugins/CustomCrafting/

**Comment by LcyDev** [comment]
Can you try the latest source of CustomCrafting?
The plugin config shouldn't matter

Both plugin folder and plugin here
https://www.mediafire.com/file/3c6w4rf6cuscivi/CustomCraft.zip/file
