### ISSUE TITLE
https://paste.walshy.dev/drHYrYn7KiIF

### ISSUE THREAD

**Issue by FaiqGaming** [Slimefun/Slimefun4#3747]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

https://paste.walshy.dev/drHYrYn7KiIF

### 📑 Reproduction Steps

fix it!

### 💡 Expected Behavior

I hope this problem got fixed

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

latest slimefun dev 1039

**Comment by variananora** [comment]
closing this issue since there is not real information

**Comment by FaiqGaming** [comment]
I received a bug report that the PortableGeoScanner item cannot be used like the example in this video "https://youtu.be/5bb5Qq5M3dM" and when I told my members to re-click an error appeared in the console like the text in this link "https:// paste.walshy.dev/drHYrYn7KiIF"

**Comment by TheBusyBiscuit** [comment]
The error you posted is from DynaTech, not from Slimefun though: https://github.com/ProfElements/DynaTech
So please post the issue on their bug tracker, not ours and write a more descriptive issue.

Instructions like "fix it!" really don't help any of us.

**Comment by Boomer-1** [comment]
also dynatech requires 1.19 now so to run it you will have to upgrade to 1.19. there is no error to fix if you run the correct version
