### ISSUE TITLE
Error when click PortableGeoScanner

### ISSUE THREAD

**Issue by FaiqGaming** [Slimefun/Slimefun4#3748]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I received a bug report that the PortableGeoScanner item cannot be used like the example in this video "https://youtu.be/5bb5Qq5M3dM" and when I told my members to re-click an error appeared in the console like the text in this link "https://paste.walshy.dev/drHYrYn7KiIF"
Server Version > Pufferfish 1.17.1

### 📑 Reproduction Steps

I don't understand this kind of problem so I'm just reporting it here

### 💡 Expected Behavior

I hope this problem is resolved soon so that there are no more problems like this in the future

### 📷 Screenshots / Videos

https://youtu.be/5bb5Qq5M3dM

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Pufferfish git-Pufferfish-22 (MC: 1.17.1)
Slimefun DEV - 1039 (git 3ae41d59)
Metrics-Module #28
Java 17

**Comment by ybw0014** [comment]
This is nothing to do with Slimefun, it is DynaTech's issue.
Also, DynaTech only supports latest version, which is 1.19.x. If you want a version that supports 1.17, find an old version from builds history.
