### ISSUE TITLE
Elytra Cap doesn't negate damage when crashing to ground or walls using elytra

### ISSUE THREAD

**Issue by variananora** [Slimefun/Slimefun4#3759]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Elytra Cap doesn't negate damage when crashing to ground or walls using elytra, while the description of the item said otherwise

### 📑 Reproduction Steps

1. Equip an elytra cap
2. Equip an elytra
3. Fly using elytra
4. Crash into walls or ground
5. See that you got damaged

### 💡 Expected Behavior

It should negate the damage

### 📷 Screenshots / Videos

https://youtu.be/TjE_2hCBhRw

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

```
This Server uses the following setup of Slimefun:
Paper git-Paper-386 (MC: 1.19.3)
Slimefun DEV - 1043 (git 4bfc4f06)
Metrics-Module #28
Java 17

No Addons installed
```

**Comment by J3fftw1** [comment]
It seems like it doesnt always detect the player gliding. Which makes me think this is a spigot issue.
A way to fix it is to wear the boots of stomper.
