### ISSUE TITLE
Skin cache issue

### ISSUE THREAD

**Issue by anthonykour** [Slimefun/Slimefun4#3761]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

`[19:52:59 ERROR]: [dough: skins] Exception while requesting skin: https://api.mojang.com/users/profiles/minecraft/st392
[19:52:59 WARN]: [Slimefun] Attempted to refresh skin cache, got this response: ExecutionException: java.io.FileNotFoundException: https://api.mojang.com/users/profiles/minecraft/st392
[19:52:59 WARN]: [Slimefun] This usually means mojang.com is temporarily down or started to rate-limit this connection, nothing to worry about!`

### 📑 Reproduction Steps

Every time I restart the server.

### 💡 Expected Behavior

Load appropriate skin. 

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Slimefun vDEV - 1043 (git 4bfc4f06)

**Comment by Boomer-1** [comment]
this is a known issue on dough, not a slimefun issue.

**Comment by Texbio** [comment]
Is it possible to suppress this error since its a bit annoying to see when nothing is wrong?

**Comment by Phoenix-Starlight** [comment]
Silencing exceptions is generally bad to do.
