### ISSUE TITLE
Could not pass event InventoryClickEvent to Slimefun vDEV

### ISSUE THREAD

**Issue by SrMonsterYT** [Slimefun/Slimefun4#3762]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

error console: https://pastebin.com/v74RajSV

server version: https://prnt.sc/lZj6K9YogjKj

### 📑 Reproduction Steps

I don't know how this is happening

### 💡 Expected Behavior

this error does not happen

### 📜 Server Log

this error does not happen

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Pufferfish git-Pufferfish-47 (MC: 1.19.2)

**Comment by J3fftw1** [comment]
This is not slimefun. Report this on the networks repo

**Comment by SrMonsterYT** [comment]
@Sefiraat

**Comment by Boomer-1** [comment]
you were told to report this on the Networks Github. it is not a slimefun issue.
