### ISSUE TITLE
Issue with plugin Vehicles and probably more

### ISSUE THREAD

**Issue by Rokysek** [Slimefun/Slimefun4#3767]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

In Vehicles plugin, you can plant seeds using tractor. If you have Slimefun item that is placable (+more, tried it with machines, cargo, solar panels, backpacks) in your main hand, it plants a seed which after destroying drops the item that was in your hand. I asked Vehicles support and they found out that the error causing it is probably line 80. I am sending some messages from him:
![image](https://user-images.githubusercontent.com/19331474/218342787-f9cf8547-8f93-4959-80eb-c95802684c0c.png)
![image](https://user-images.githubusercontent.com/19331474/218342790-c80efdfa-cc01-4c27-b1b0-7468d9eac6c2.png)
![image](https://user-images.githubusercontent.com/19331474/218342799-2b04763a-0e3a-4cbe-b8e5-3f058abae69f.png)
![image](https://user-images.githubusercontent.com/19331474/218342803-e8a56951-59bb-4bc9-9e46-d71a83d96bee.png)

(Server is running on Waterfall - Yatopia)

### 📑 Reproduction Steps

1. Ride a tractor
2. Put in seeds
3. Put the Slimefun item in your main hand
4. Ride over farmland
5. Destroy the seed (doesn’t have to be grown)

### 💡 Expected Behavior

It shouldn’t interfere with what you are planting, it should plant the item that is in the vehicle trunk.

### 📷 Screenshots / Videos

https://medal.tv/games/minecraft/clips/UYm6TSvGIMsVI/d1337wv7pVSz?invite=cr-MSxwTEIsMjc4MTU2MzIs

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/19331474/218342712-797531a4-a52c-4cb5-b1b4-084b185da4c8.png)

### 🧭 Other plugins

Vehicles - https://www.spigotmc.org/resources/%E2%9C%88%EF%B8%8Fvehicles-no-resourcepacks-needed.12446/

**Comment by Roky67** [comment]
No, it has not> Has this been fixed in the meantime?

**Comment by Roky67** [comment]
> Has this been fixed in the meantime?

No, it hasn't.

**Comment by J3fftw1** [comment]
It will be fixed

**Comment by JustAHuman-xD** [comment]
I can look into a fix

**Comment by Roky67** [comment]
> I can look into a fix

Thanks, I would really appreciate it

**Comment by Mtuart** [comment]
Would love to see an update on this, given that it seems quite simple to fix =D

**Comment by J3fftw1** [comment]
> Would love to see an update on this, given that it seems quite simple to fix =D

If it is simple feel free to make a Pull request solving the issue. 😉

**Comment by PanHaskins** [comment]
This duplication bug also works without the Vehicles plugin. You just need to harvest it manually.

**Comment by Boomer-1** [comment]
since vehicles has stated to Alessio that this bug will not be able to be fixed, do we need to keep this open? is there any chance we are able to fix the issue?

**Comment by J3fftw1** [comment]
We should be able to fix it from our side so yes keep it open it’s still a bug

**Comment by JustAHuman-xD** [comment]
> We should be able to fix it from our side so yes keep it open it’s still a bug

We can't

**Comment by JustAHuman-xD** [comment]
Message 7 for the full run down we went over a numerous amount of things, the issue was on their side, idk if they've pushed the patch that was figured out or not

**Comment by J3fftw1** [comment]
There is still a bug, even if its a non fix from our side we should keep it open to link future reports to

**Comment by JustAHuman-xD** [comment]
Oh for sure! Not against keeping the issue open, we tested a fix (and it worked) sometime in January, going to assume they haven't pushed it yet?

**Comment by Boomer-1** [comment]
when Alessio was working with them, it was a fundamental difference in how certain parts of the code was handled, and neither side could change, iirc. the solution he came up with was to disable tractors in vehicles

**Comment by JustAHuman-xD** [comment]
> when Alessio was working with them, it was a fundamental difference in how certain parts of the code was handled, and neither side could change, iirc. the solution he came up with was to disable tractors in vehicles
> 
> 

I was working with him on it, we did find a proper fix, they were handling an event incorrectly.

**Comment by Boomer-1** [comment]
lets hope they push out the fix then

**Comment by ShiftSad** [comment]
I've made a fork for my server, and fixed this duplication glitch by simply ignoring the event if the player is in a vehicle. Worked flawlessly.
The only issue is that I had to add their premium plugin jar in my source to build, since they don't provide an api. Really easy to fix if I just use reflection. I can prob push it if needed.

**Comment by ShiftSad** [comment]
I've made a simple fix for it in my fork. Simply ignore the event if the player is in a vehicle and the plugin is enabled.

https://github.com/Slimefun/Slimefun4/commit/a4032bc0bb7a6cbb44b6e9f680a761a8b0e2532a

**Comment by Sfiguz7** [comment]
The fix is ready and they have been notified, they just went radio silence on their end for a bit. Apparently soon :tm: it will be out
![image](https://github.com/Slimefun/Slimefun4/assets/37039432/e6fd7fd5-4470-4709-ac3d-c884b671c24e)

**Comment by Sfiguz7** [comment]
Cool ty, will close this then
