### ISSUE TITLE
sf stats counting disabled items in the list of unlocked items, making us unable to achieve 100% 

### ISSUE THREAD

**Issue by Ritwik-main** [Slimefun/Slimefun4#3782]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

sf stats has a place where it shows total researches, and its counting the disabled ones as  a part of it

### 📑 Reproduction Steps

disable a item in sf and then unlock everything else, then check sf stats but you wont have 100% researches

### 💡 Expected Behavior

sf stats should not include disabled items into calculating % of  research done by player

### 📷 Screenshots / Videos

![image](https://user-images.githubusercontent.com/116669493/221359602-79ea42fa-a3fd-41e0-b57f-83209b5ebad6.png)
everything has been unlocked but still due to disabled items player is unable to reach 100% 

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Sf version 1043 

### 🧭 Other plugins

this bug is not related to a plugin.

**Comment by JustAHuman-xD** [comment]
Is this caused by disabled items or disabled researches?

**Comment by JustAHuman-xD** [comment]
Just did some testing, it is caused by disabled items and can confirm this is a problem
