### ISSUE TITLE
Nuclear Reactor randomly stops working.

### ISSUE THREAD

**Issue by Kivviss** [Slimefun/Slimefun4#3789]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Issue is that nuclear reactors randomly stops taking any items from acess port and even if you put them manualy into reactor, they will not product anything until you broke them a place them on another spot. Time until they stop working is randomly, sometimes it takes longer.

### 📑 Reproduction Steps

Just place reactor and after some time of production, they will stop working.

### 💡 Expected Behavior

It would be good to fix this, so you do not need them to move them constantly.

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

DEV - 1046

**Comment by Boomer-1** [comment]
I can do some testing later but this sounds more like block storage

**Comment by Boomer-1** [comment]
as a follow up I've not been able to duplicate this issue at all. do you have a video or something to show this happening?

**Comment by Kivviss** [comment]
Sorry, can't provide that, I'm no longer part of project where i was slaving anymore.

**Comment by Kivviss** [comment]
Sorry, can't provide that, I'm no longer part of project where anymore.
