### ISSUE TITLE
Ore Crusher Bug

### ISSUE THREAD

**Issue by imanwastaken** [Slimefun/Slimefun4#3790]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Basically, if I use an Ore Crusher in the plugin certain blocks don't work (The ones that I have tested so far are all iron, gold, diamond, coal,lapis,emerald, and copper blocks and their raw versions.)(You can't double the drops to the ores and no access to iron and gold dust apart from sifted ore)
Im using Aternos 1.19.3(3669) Spigot with the 3 plugins below.

### 📑 Reproduction Steps

Im using Aternos
1.19.3(3669) 
Spigot with the 3 plugins below.

### 💡 Expected Behavior

I expected nothing much.

### 📷 Screenshots / Videos

It basically says this when im trying to put the ore.
![image](https://user-images.githubusercontent.com/127206252/223623458-c985d6cc-781f-45f8-8517-e92f968d3a42.png)
![image](https://user-images.githubusercontent.com/127206252/223623749-4981dc8b-a727-4d88-bff8-6aae95e4060c.png)
![image](https://user-images.githubusercontent.com/127206252/223623842-9be790f5-a662-4943-af01-123411c568a3.png)

### 📜 Server Log

?

### 📂 `/error-reports/` folder

?

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

![image](https://user-images.githubusercontent.com/127206252/223622126-8b37b7ff-6aaf-4373-8f7f-715d8a75219d.png)

### 🧭 Other plugins

GodItems 2
SpawnerSilk
Death Chest

**Comment by Boomer-1** [comment]
closing this as invalid. you did not build an ore crusher. remove oak fence, replace with netherbrick fence.
