### ISSUE TITLE
Synthetic meralds

### ISSUE THREAD

**Issue by TheDivineCombos** [Slimefun/Slimefun4#3814]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

You can use synthetic emeralds to craft regular emerald blocks, while not being able to do that with other ingots, I hope it's a not intended to make emerald blocks with them as it makes it even more op for villager trading and selling if you play with it on a server

### 📑 Reproduction Steps

Make 9 synthetic emeralds, place them into a 3x3 crafting grid in the shape of an emerald block recipe and you can make an emerald block

### 💡 Expected Behavior

I was expecting to not be able to make emerald blocks

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Slimefun4 - DEV 1050 (git 22a7f).jar

**Comment by Boomer-1** [comment]
that is intended behavior, to use synthetic emeralds and diamonds in a vanilla crafting table. it even tells you in the lore that they can be used to trade with a villager.
