### ISSUE TITLE
Talisman of the Hunter = Ender Talisman of the Hunter

### ISSUE THREAD

**Issue by sensun00** [Slimefun/Slimefun4#3818]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [x] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [x] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I was crafting Talisman of the Hunter and was looking at tier 1 and then at tier2 but they have exactly same bonus 

### 📑 Reproduction Steps

boost bonus on tier 2 amulet.

### 💡 Expected Behavior

boost tier 2 amulet bonus.

### 📷 Screenshots / Videos

![12313](https://user-images.githubusercontent.com/131488082/233718766-9fc5dff2-8dd0-4675-a7c8-0f8179e4f2ee.png)

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

RC - 33(git 083fc6d)

**Comment by ybw0014** [comment]
this is not a bug report but rather a feature request, so it should not be here.

**Comment by sensun00** [comment]
ohh then im sorry

**Comment by Boomer-1** [comment]
it is not a different tier, it allows you to use it in your enderchest. the additional craft gives you that abiity
