### ISSUE TITLE
Breaking a connector when the energy network is too large can temporarily render the energy network unusable

### ISSUE THREAD

**Issue by xiecraftoffical** [Slimefun/Slimefun4#3819]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Placing a huge energy network and disrupting a connector will temporarily prevent remote machines from connecting to the energy network.

### 📑 Reproduction Steps

1. Placing a huge energy network
2. disrupting a connector

### 💡 Expected Behavior

After performing the above operation, the remote machine can still operate normally

### 📷 Screenshots / Videos

https://user-images.githubusercontent.com/108851959/233761291-02499cbc-a8a1-4ce2-bfca-c838b6274fdc.mp4

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.18.x

### ⭐ Slimefun version

DEV 1050

### 🧭 Other plugins

slimefunHUD

**Comment by JustAHuman-xD** [comment]
Not sure this is really a bug, It's just the energy network re-connecting everything

**Comment by Boomer-1** [comment]
pretty sure Human is right. since it detected a broken connector, it should reestabish that it is connected to a network. additionally the example of placing 1000 connectors like that isn't a realistic build, i don't see this as an issue either, but I'll let an admin close it if they wish

**Comment by Sefiraat** [comment]
I've played around with this and I'm happy enough with the behaviour, you've broken one of the earliest nodes in the tree and it's just re-propagating itself, and doesn't exactly take an age ;)
