### ISSUE TITLE
/sf <argument>

### ISSUE THREAD

**Issue by freddymbatten** [Slimefun/Slimefun4#3823]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

when i loaded in and tested the /slimefun cmd or ./slimefun guide it always said /sf <argument>

### 📑 Reproduction Steps

idk what to do please help

### 💡 Expected Behavior

i want it to be correct and work for my players

### 📷 Screenshots / Videos

![image](https://user-images.githubusercontent.com/132191272/235342486-3ef3a9b1-0c7c-44e6-ba74-27029bebdfce.png)

### 📜 Server Log

30.04 07:58:45 [Server] ERROR Ambiguous plugin name 'Towny' for files 'plugins/Towny-0.99.0.0.jar' and 'plugins/Towny-0.88.0.0.jar' in 'plugins' 30.04 07:58:45 [Server] ERROR Ambiguous plugin name 'TownyChat' for files 'plugins/TownyChat-0.88.0.0.jar' and 'plugins/TownyChat-0.103.jar' in 'plugins' 30.04 07:58:47 [Server] WARN Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug! 30.04 07:58:59 [Server] WARN Legacy plugin TownyChat v0.4 does not specify an api-version. 30.04 07:58:59 [Server] WARN Legacy plugin Slimefun vv4.1.15 does not specify an api-version. 30.04 07:58:59 [Server] INFO Loading server plugin LuckPerms v5.4.71 30.04 07:58:59 [Server] INFO Loading server plugin Vault v1.7.3-b131 30.04 07:58:59 [Server] INFO Loading server plugin Essentials v2.20.0-dev+56-fd49b70 30.04 07:58:59 [Server] INFO Loading server plugin dynmap v3.5-beta-3-866 30.04 07:59:00 [Server] INFO version=git-Paper-448 (MC: 1.19.3) 30.04 07:59:00 [Server] INFO Mod Support API available 30.04 07:59:00 [Server] INFO Loading server plugin Towny v0.99.0.0 30.04 07:59:00 [Server] INFO Loading server plugin UberEnchant v8.9.12 30.04 07:59:00 [Server] INFO Loading server plugin TownyChat v0.4 30.04 07:59:00 [Server] INFO Loading server plugin NyxArmorPlugin v1.2.0 30.04 07:59:00 [Server] INFO Loading server plugin MinecraftGPT v1.2.6

### 📂 `/error-reports/` folder

?

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

slimefun version 4

### 🧭 Other plugins

noope

**Comment by ybw0014** [comment]
Please send a full log via pastebin, the log you provides contains nothing useful for investigating your issue.

**Comment by freddymbatten** [comment]
okay
0.04 07:59:26 [Server] INFO Initialized - Took 1034ms to complete
30.04 07:59:26 [Server] INFO Enabling Slimefun vv4.1.15*
30.04 07:59:26 [Server] ERROR [STDERR]  
30.04 07:59:26 [Server] WARN Nag author(s): '[The Slimefun 4 Community]' of 'Slimefun' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
30.04 07:59:26 [Server] ERROR [STDERR] #################### - INFO - ####################
30.04 07:59:26 [Server] ERROR [STDERR]  
30.04 07:59:26 [Server] ERROR [STDERR] Slimefun could not be loaded.
30.04 07:59:26 [Server] ERROR [STDERR] It appears that you have not installed CS-CoreLib
30.04 07:59:26 [Server] ERROR [STDERR] Your Server will now try to download and install
30.04 07:59:26 [Server] ERROR [STDERR] CS-CoreLib for you.
30.04 07:59:26 [Server] ERROR [STDERR] You will be asked to restart your Server when it's finished.
30.04 07:59:26 [Server] ERROR [STDERR] If this somehow fails, please download and install CS-CoreLib manually:
30.04 07:59:26 [Server] ERROR [STDERR] https://dev.bukkit.org/projects/cs-corelib
30.04 07:59:26 [Server] ERROR [STDERR]  
30.04 07:59:26 [Server] ERROR [STDERR] #################### - INFO - ####################
30.04 07:59:26 [Server] ERROR [STDERR]  
30.04 07:59:27 [Server] INFO Running delayed init tasks
30.04 07:59:27 [Server] INFO Essentials found a compatible payment resolution method: Vault Compatibility Layer (v1.7.3-b131)!
30.04 07:59:27 [Server] INFO Fetching version information...
30.04 07:59:27 [Server] INFO Time until a New Day: 4 hours, 33 seconds
30.04 07:59:27 [Server] INFO Checking for updates...
30.04 07:59:27 [Server] Startup Done (43.102s)! For help, type "help"
30.04 07:59:27 [Server] INFO Timings Reset
30.04 07:59:27 [Server] INFO Checking for Updates ... 
30.04 07:59:27 [Server] INFO No new version available
30.04 07:59:27 [Server] WARN You're 2 EssentialsX dev build(s) out of date!
30.04 07:59:27 [Server] WARN Download it here: https://essentialsx.net/downloads.html
30.04 07:59:27 [Server] INFO New update available: 0.99.0.5 | Current version: 0.99.0.0
30.04 07:59:27 [Server] INFO Download it here: https://github.com/TownyAdvanced/Towny/releases/tag/0.99.0.5
30.04 07:59:29 [Server] WARN Exception in thread "Thread-40" java.lang.Error: java.util.zip.ZipException: zip END header not found
30.04 07:59:29 [Server] WARN at Armor+.jar//Updater.a(:144)
30.04 07:59:29 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
30.04 07:59:29 [Server] WARN Caused by: java.util.zip.ZipException: zip END header not found
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
30.04 07:59:29 [Server] WARN at Armor+.jar//Updater.a(:82)
30.04 07:59:29 [Server] WARN ... 1 more
30.04 07:59:29 [Server] WARN Exception in thread "Thread-39" java.lang.Error: java.util.zip.ZipException: zip END header not found
30.04 07:59:29 [Server] WARN at TownyChat-0.88.0.0.jar//Updater.a(:144)
30.04 07:59:29 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
30.04 07:59:29 [Server] WARN Caused by: java.util.zip.ZipException: zip END header not found
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
30.04 07:59:29 [Server] WARN at TownyChat-0.88.0.0.jar//Updater.a(:82)
30.04 07:59:29 [Server] WARN ... 1 more
30.04 07:59:29 [Server] WARN Exception in thread "Thread-41" java.lang.Error: java.util.zip.ZipException: zip END header not found
30.04 07:59:29 [Server] WARN at AuctionHouse-1.18.2-3.2.3.jar//Updater.a(:144)
30.04 07:59:29 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
30.04 07:59:29 [Server] WARN Caused by: java.util.zip.ZipException: zip END header not found
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1315)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:709)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
30.04 07:59:29 [Server] WARN at AuctionHouse-1.18.2-3.2.3.jar//Updater.a(:82)
30.04 07:59:29 [Server] WARN ... 1 more
30.04 07:59:32 [Server] ERROR [STDERR]  
30.04 07:59:32 [Server] ERROR [STDERR] #################### - WARNING - ####################
30.04 07:59:32 [Server] ERROR [STDERR]  
30.04 07:59:32 [Server] ERROR [STDERR] Could not connect to BukkitDev.
30.04 07:59:32 [Server] ERROR [STDERR] Please download & install CS-CoreLib manually:
30.04 07:59:32 [Server] ERROR [STDERR] https://dev.bukkit.org/projects/cs-corelib
30.04 07:59:32 [Server] ERROR [STDERR]  
30.04 07:59:32 [Server] ERROR [STDERR] #################### - WARNING - ####################
30.04 07:59:32 [Server] ERROR [STDERR]  
30.04 07:59:32 [Server] WARN Can't keep up! Is the server overloaded? Running 5317ms or 106 ticks behind
30.04 08:00:21 [Server] INFO CONSOLE issued server command: /list 
30.04 08:00:21 [Server] INFO There are 0 out of maximum 20 players online.
30.04 08:01:14 [Server] INFO CONSOLE issued server command: /list 
30.04 08:01:14 [Server] INFO There are 0 out of maximum 20 players online.
30.04 08:01:46 [Server] INFO UUID of player sir_snake is 827decbe-37aa-405c-b183-21628abfa415
30.04 08:01:46 [Server] INFO sir_snake joined the game

**Comment by Sefiraat** [comment]
> okay
> 0.04 07:59:26 [Server] INFO Initialized - Took 1034ms to complete
> 30.04 07:59:26 [Server] INFO Enabling Slimefun vv4.1.15*
> 30.04 07:59:26 [Server] ERROR [STDERR]
> 30.04 07:59:26 [Server] WARN Nag author(s): '[The Slimefun 4 Community]' of 'Slimefun' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
> 30.04 07:59:26 [Server] ERROR [STDERR] #################### - INFO - ####################
> 30.04 07:59:26 [Server] ERROR [STDERR]
> 30.04 07:59:26 [Server] ERROR [STDERR] Slimefun could not be loaded.
> 30.04 07:59:26 [Server] ERROR [STDERR] It appears that you have not installed CS-CoreLib
> 30.04 07:59:26 [Server] ERROR [STDERR] Your Server will now try to download and install
> 30.04 07:59:26 [Server] ERROR [STDERR] CS-CoreLib for you.
> 30.04 07:59:26 [Server] ERROR [STDERR] You will be asked to restart your Server when it's finished.
> 30.04 07:59:26 [Server] ERROR [STDERR] If this somehow fails, please download and install CS-CoreLib manually:
> 30.04 07:59:26 [Server] ERROR [STDERR] https://dev.bukkit.org/projects/cs-corelib
> 30.04 07:59:26 [Server] ERROR [STDERR]
> 30.04 07:59:26 [Server] ERROR [STDERR] #################### - INFO - ####################
> 30.04 07:59:26 [Server] ERROR [STDERR]
> 30.04 07:59:27 [Server] INFO Running delayed init tasks
> 30.04 07:59:27 [Server] INFO Essentials found a compatible payment resolution method: Vault Compatibility Layer (v1.7.3-b131)!
> 30.04 07:59:27 [Server] INFO Fetching version information...
> 30.04 07:59:27 [Server] INFO Time until a New Day: 4 hours, 33 seconds
> 30.04 07:59:27 [Server] INFO Checking for updates...
> 30.04 07:59:27 [Server] Startup Done (43.102s)! For help, type "help"
> 30.04 07:59:27 [Server] INFO Timings Reset
> 30.04 07:59:27 [Server] INFO Checking for Updates ...
> 30.04 07:59:27 [Server] INFO No new version available
> 30.04 07:59:27 [Server] WARN You're 2 EssentialsX dev build(s) out of date!
> 30.04 07:59:27 [Server] WARN Download it here: https://essentialsx.net/downloads.html
> 30.04 07:59:27 [Server] INFO New update available: 0.99.0.5 | Current version: 0.99.0.0
> 30.04 07:59:27 [Server] INFO Download it here: https://github.com/TownyAdvanced/Towny/releases/tag/0.99.0.5
> 30.04 07:59:29 [Server] WARN Exception in thread "Thread-40" java.lang.Error: java.util.zip.ZipException: zip END header not found
> 30.04 07:59:29 [Server] WARN at Armor+.jar//Updater.a(:144)
> 30.04 07:59:29 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
> 30.04 07:59:29 [Server] WARN Caused by: java.util.zip.ZipException: zip END header not found
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.(ZipFile.java:1315)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$CleanableResource.(ZipFile.java:709)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile.(ZipFile.java:243)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile.(ZipFile.java:172)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile.(ZipFile.java:186)
> 30.04 07:59:29 [Server] WARN at Armor+.jar//Updater.a(:82)
> 30.04 07:59:29 [Server] WARN ... 1 more
> 30.04 07:59:29 [Server] WARN Exception in thread "Thread-39" java.lang.Error: java.util.zip.ZipException: zip END header not found
> 30.04 07:59:29 [Server] WARN at TownyChat-0.88.0.0.jar//Updater.a(:144)
> 30.04 07:59:29 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
> 30.04 07:59:29 [Server] WARN Caused by: java.util.zip.ZipException: zip END header not found
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.(ZipFile.java:1315)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$CleanableResource.(ZipFile.java:709)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile.(ZipFile.java:243)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile.(ZipFile.java:172)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile.(ZipFile.java:186)
> 30.04 07:59:29 [Server] WARN at TownyChat-0.88.0.0.jar//Updater.a(:82)
> 30.04 07:59:29 [Server] WARN ... 1 more
> 30.04 07:59:29 [Server] WARN Exception in thread "Thread-41" java.lang.Error: java.util.zip.ZipException: zip END header not found
> 30.04 07:59:29 [Server] WARN at AuctionHouse-1.18.2-3.2.3.jar//Updater.a(:144)
> 30.04 07:59:29 [Server] WARN at java.base/java.lang.Thread.run(Thread.java:833)
> 30.04 07:59:29 [Server] WARN Caused by: java.util.zip.ZipException: zip END header not found
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1469)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1477)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.(ZipFile.java:1315)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1277)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile$CleanableResource.(ZipFile.java:709)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile.(ZipFile.java:243)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile.(ZipFile.java:172)
> 30.04 07:59:29 [Server] WARN at java.base/java.util.zip.ZipFile.(ZipFile.java:186)
> 30.04 07:59:29 [Server] WARN at AuctionHouse-1.18.2-3.2.3.jar//Updater.a(:82)
> 30.04 07:59:29 [Server] WARN ... 1 more
> 30.04 07:59:32 [Server] ERROR [STDERR]
> 30.04 07:59:32 [Server] ERROR [STDERR] #################### - WARNING - ####################
> 30.04 07:59:32 [Server] ERROR [STDERR]
> 30.04 07:59:32 [Server] ERROR [STDERR] Could not connect to BukkitDev.
> 30.04 07:59:32 [Server] ERROR [STDERR] Please download & install CS-CoreLib manually:
> 30.04 07:59:32 [Server] ERROR [STDERR] https://dev.bukkit.org/projects/cs-corelib
> 30.04 07:59:32 [Server] ERROR [STDERR]
> 30.04 07:59:32 [Server] ERROR [STDERR] #################### - WARNING - ####################
> 30.04 07:59:32 [Server] ERROR [STDERR]
> 30.04 07:59:32 [Server] WARN Can't keep up! Is the server overloaded? Running 5317ms or 106 ticks behind
> 30.04 08:00:21 [Server] INFO CONSOLE issued server command: /list
> 30.04 08:00:21 [Server] INFO There are 0 out of maximum 20 players online.
> 30.04 08:01:14 [Server] INFO CONSOLE issued server command: /list
> 30.04 08:01:14 [Server] INFO There are 0 out of maximum 20 players online.
> 30.04 08:01:46 [Server] INFO UUID of player sir_snake is 827decbe-37aa-405c-b183-21628abfa415
> 30.04 08:01:46 [Server] INFO sir_snake joined the game
You’re using a very outdated version of slimefun. Please download the latest < https://thebusybiscuit.github.io/builds/>

**Comment by freddymbatten** [comment]
which one do i download?

**Comment by freddymbatten** [comment]
![image](https://user-images.githubusercontent.com/132191272/235343718-6d176e4f-3257-41bf-998b-038082c22fc4.png)
now its not working at all

**Comment by Sefiraat** [comment]
Remove cs-corelib

**Comment by Sefiraat** [comment]
I'll assume you're sorted now then - you're more than welcome to reopen the issue if not with further details including a new screenshot of your /pl, a screenshot of your /sf versions (if possible) and a startup log once more.
