### ISSUE TITLE
[SlimeTinker] Task #8880 for SlimeTinker vDEV - 79 (git fe7ea82b) generated an exception java.lang.IllegalArgumentException: Health must be between 0 and 60.0, but was 72.0. (attribute base value: 20.0, player: )

### ISSUE THREAD

**Issue by BluishBlueMoon** [Slimefun/Slimefun4#3824]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

- using full armor made of Damascus steel that gives the player a health boost of 10.
- Elite mobs plugin is installed and the player has permanent 4 extra hearts provided by this plugin.

* Slimefun DEV - 1050 (git 22a7f422)
** SlimeTinker vDev - 79 (git fe7ea82b)

*** How to tweak/solve that issue so that SlimeTinker doesn't spam the console?

thanks in advance :)

### 📑 Reproduction Steps

1- Use SlimeTinker to craft a complete set of armor made of (Damascus steel "plates") = to get a health boost of 10
2- Use EliteMobs plugin and prestige 2 times = to get an extra health boost

### 💡 Expected Behavior

[00:06:23 WARN]: [SlimeTinker] Task #8880 for SlimeTinker vDEV - 79 (git fe7ea82b) generated an exception
java.lang.IllegalArgumentException: Health must be between 0 and 60.0, but was 72.0. (attribute base value: 20.0, player: )

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Slimefun DEV - 1050 (git 22a7f422)

**Comment by Sefiraat** [comment]
Good morning!

You’ve reported this issue in the wrong repo I am sorry to say! Please raise your issue here: https://github.com/Sefiraat/SlimeTinker and I’ll be sure to take a look asap :). 

Thanks!
