### ISSUE TITLE
Signs attached to custom blocks don't drop

### ISSUE THREAD

**Issue by ghost** [Slimefun/Slimefun4#3831]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When placing a sign on an output chest or edged/reinforced furnace. if you subsequently break the block the sign will not drop.

### 📑 Reproduction Steps

1. Place down an output chest
2. Place a sign on it
3. Break the output chest

### 💡 Expected Behavior

I expect the sign to drop.

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

DEV 1050

**Comment by WalshyDev** [comment]
Did this break in 1.19.x or was this always an issue @Boomer-1 ?

**Comment by Boomer-1** [comment]
i'm pretty sure it's been mentioned in the past, but this was the first time i think it got reported here

**Comment by WalshyDev** [comment]
Interesting, thanks!

**Comment by J3fftw1** [comment]
This is most likely the same as with vines buttons paintings etc.
I have seen this being reported on discord.
We even speculated a fix but it’s really vaguely in my mind.

I think we were talking about sending a block update on block break
