### ISSUE TITLE
Disabling 'Cutter' from Excellent Enchants breaks auto disenchanter and enchanter

### ISSUE THREAD

**Issue by CarterMane** [Slimefun/Slimefun4#3842]
### ❗ Checklist

- [x] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When disabling the cutter enchant from excellent enchants, it breaks the auto enchanter and disenchanter. I tried to re-enable cutter, but it still didn't work. There also weren't any error messages in the logs, which made it weirder.

### 📑 Reproduction Steps

1: Have slimefun and excellent enchants
2: Disable Cutter from the config files

### 💡 Expected Behavior

It should still work, as only cutter was disabled from an entirely different config folder

### 📷 Screenshots / Videos

https://github.com/Slimefun/Slimefun4/assets/131935346/fea9bcb3-1257-4f2c-90cd-456a3acbf926

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

![image](https://github.com/Slimefun/Slimefun4/assets/131935346/0aa6e3db-f92a-4221-93c8-32bd24fc2dbc)

### 🧭 Other plugins

Excellent Enchants

**Comment by variananora** [comment]
Can we see `items.yml` on Slimefun's folder, especially on `AUTO_ENCHANTER` and `AUTO_DISENCHANTER`?

**Comment by CarterMane** [comment]
![image](https://github.com/Slimefun/Slimefun4/assets/131935346/885d296f-5530-4fe2-8fdb-8db73f6fed5c)
![image](https://github.com/Slimefun/Slimefun4/assets/131935346/10bd37b2-11de-4ddc-bffe-84bbe4386aaf)
I can't send the file over, so here are some screenshots of the auto enchanter and disenchanter tiers 1 and 2

**Comment by CarterMane** [comment]
okay, i'll try that

**Comment by CarterMane** [comment]
nope

**Comment by CarterMane** [comment]
latest version also doesn't work

**Comment by variananora** [comment]
> latest version also doesn't work

what version are you testing on? version 1060 should fixed it. can you confirm this?

**Comment by JustAHuman-xD** [comment]
Try with the latest build

**Comment by variananora** [comment]
I can't replicate it on the latest version, closing this assuming this was fixed.
