### ISSUE TITLE
Allows Illegal Enchants With Runes

### ISSUE THREAD

**Issue by MaxwellRose101** [Slimefun/Slimefun4#3843]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Basically, Lopobia uses this plugin. On the server, you can only get one blue and one pink enchant. However, with slimefun you can get much more than just one. This is illegal on Lopobia. Apparently, I asked one of the people that knew how to do it. They said that it  involves SlimeFun and runes or something. Could you fix this?

P.S. If you know how to do this please tell me, I'm begging you.

### 📑 Reproduction Steps

1. Make a sword or tools or armor or something.
2. Enchant it.
3. Use a rune or something to make it have illegal enchants.
4. You're done.

### 💡 Expected Behavior

I didn't even know that this was possible.

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

Slimefun vDev - 1057 (git 39886fc0)

### 🧭 Other plugins

Maybe the Enchant GUI plugin

**Comment by J3fftw1** [comment]
There are a lot of maybes and other stuff in the incident. You don’t even know how to reproduce this how would we verify the issue or let a lone fix it

**Comment by Sefiraat** [comment]
Heya, please include details about what a ‘pink enchant’ is, what plug-in it comes from. What version of said plug-in. It sounds like the auto enchanter is the likely cause which, if it is, just disable that on a server level if it causes such an impact on your eco? But if not, we need way more information here.

**Comment by MaxwellRose101** [comment]
Never mind, I figured it out.
