### ISSUE TITLE
1.20 support

### ISSUE THREAD

**Issue by Bayanicool** [Slimefun/Slimefun4#3850]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

1.20 needs supporting

### 📑 Reproduction Steps

asdasdasdasdads

### 💡 Expected Behavior

asd

### 📷 Screenshots / Videos

asd

### 📜 Server Log

asd

### 📂 `/error-reports/` folder

asd

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

asd

### 🧭 Other plugins

asd

**Comment by J3fftw1** [comment]
We do already support it

**Comment by Boomer-1** [comment]
this is for actual issues with slimefun not requests that have already been implemented.
