### ISSUE TITLE
language

### ISSUE THREAD

**Issue by 164ebr** [Slimefun/Slimefun4#3854]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Why is it that after I chose zh-CN, only some of the content has been translated into Chinese, but the composition table of the item is still in English?

After looking through the source code, I found that there are indeed Chinese translations of all items under resources/languages/zh-CN/recipes.yml. Why cannot I view them in the game?

### 📑 Reproduction Steps

none

### 💡 Expected Behavior

none

### 📷 Screenshots / Videos

![image](https://github.com/Slimefun/Slimefun4/assets/86980013/dd01f414-475c-47c6-9b2a-e4f31ede6442)
![image](https://github.com/Slimefun/Slimefun4/assets/86980013/19b3ef51-7648-4d2c-ad93-9f0b4d740a8e)
![image](https://github.com/Slimefun/Slimefun4/assets/86980013/2acbf0c9-e5e3-423f-98b1-b55e6b0fb816)

why

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

DEV-1060

**Comment by ybw0014** [comment]
Items are not translatable for now.

**Comment by zwtdj** [comment]
他的物品全部写在SlimefunItems，我从18年开始修改这个文件里面的名称为中文，到现在了，这个文件还是没有做成汉化的，但是实现了通过id识别，不会因为名称改变而无法使用。
