### ISSUE TITLE
Smeltery not working

### ISSUE THREAD

**Issue by Von27** [Slimefun/Slimefun4#3856]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

We are trying to add the backpacks from Slimefun to our server, and we are having troubles using the Smeltery. Not all objects are set as enable but the Smeltery is. Please refer to our screenshots and information and provide us with assistance. 

Slimefun vDEV - 1061 (git 79e057d2)
papermc-1.19.4-549

### 📑 Reproduction Steps

We currently have activated: Weapons: Grandma's Walking Stick, Grandpa's Walking Stick, Sword of Beheading, Seismic Axe, Explosive Bow, Icy Bow
Useful Items: Small/Medium/Large Backpack
Tools: Gold Pan/Nether Pan
Food: Fortune Cookie
Private Storage: Oak Safe/Birch Safe/Spruce Safe/Acacia Safe/Jungle Safe/Dark Oak Safe/Iron Safe
Basic Machines: Enhanced Crafting Table, Grind Stone, Magic Workbench, Ore Cruster, Smeltery
Magical Items - Magical Lump 1, 2, 3, magical book cover, lava crystal, ancient rune (fire), ancient rune (earth), blank rune
Resources - gold dust, gold ingot 4....14 carat (4,6,8,10,12,14)

### 💡 Expected Behavior

After adding gold dust to the smeltery - it is not giving us ingots. 

### 📷 Screenshots / Videos

![2image](https://github.com/Slimefun/Slimefun4/assets/20481767/6aaf9a33-bedc-4527-87d4-1c26aa2e5be9)
![3image](https://github.com/Slimefun/Slimefun4/assets/20481767/bd6b0ad3-01af-4e0e-a636-7946df48b2a9)
![1image](https://github.com/Slimefun/Slimefun4/assets/20481767/90dcc11b-5906-4942-854f-3f9f8dda6c40)

### 📜 Server Log

https://pastebin.com/2NP8FFnW

### 📂 `/error-reports/` folder

N/a

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Slimefun vDEV - 1061 (git 79e057d2)

### 🧭 Other plugins

No

**Comment by ybw0014** [comment]
Related to #3286

**Comment by Von27** [comment]
@ybw0014 We updated the MultiBlockMachine.java with https://github.com/Slimefun/Slimefun4/blob/da9f84925ab7547b02405e5f6dee57eb022f4c1d/src/main/java/io/github/thebusybiscuit/slimefun4/core/multiblocks/MultiBlockMachine.java
However, the problem still persists. The dust is below the ingots, the smeltery is yet not working

**Comment by variananora** [comment]
I think this should be fixed on DEV-1072 or higher. If your issue still persist feel free to comment back on this issue or report it on our [Discord Server](https://discord.gg/slimefun).
