### ISSUE TITLE
Item Dupe From Industrial Miner

### ISSUE THREAD

**Issue by ShimieShimie** [Slimefun/Slimefun4#3872]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

There is a bug with the Industrial Miner where any items within the output chest will dupe during mining when someone with no permission to break the chest tries to break it. This may be because of another plugin where some blocks require permission from the player who set it down to be able to be used by someone else.
List of plugins:
   blockprot
   essentials
   spark 
   vault

### 📑 Reproduction Steps

set miner up 
put items that want to be duped in output chest
activate the miner with fuel
have someone that has no permission to access the chest break the chest
the items will fly out of the chest as if broken but the chest will come back with the items inside

### 💡 Expected Behavior

i found this when my friend tried to break the process of the miner to troll me
i expected it to stop the miner and explode my items everywhere

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

rc 34

**Comment by Sefiraat** [comment]
Hi there! 

Thanks for the report.
You can find the list of supported protection plugins here: <https://github.com/Slimefun/Slimefun4/wiki/Protection-Plugins>

Support for BlockProt would need to be added to Dough as has been done with the other plugins in the list for this to work as expected here.

I would advise you to either:
* Move to another protection plugin that is supported 
* Request that BlockProt adds itself as a protection module within Dough.
