### ISSUE TITLE
Slimefun Items turn into normal Heads when Places

### ISSUE THREAD

**Issue by IranMine123** [Slimefun/Slimefun4#3877]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Hello, when i use some items like "Energy Regulator" it just turn into normal Head when I place them and no more it will be slimefun item
that's just happening for me. items work for other players
here is some screenshots

### 📑 Reproduction Steps

Placing them

### 💡 Expected Behavior

they work 

### 📷 Screenshots / Videos

![image](https://github.com/Slimefun/Slimefun4/assets/74745380/5646bddf-751a-47ba-9dd0-926ed18b8e03)
![image](https://github.com/Slimefun/Slimefun4/assets/74745380/34b23219-7c29-446d-bdff-f078bda60388)

### 📜 Server Log

no any errors

### 📂 `/error-reports/` folder

empty

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

DEV - 1068 (git cab97b1a)

**Comment by J3fftw1** [comment]
If you have viaversion installed please update and try again

**Comment by Sefiraat** [comment]
There was an issue with ViaVersion where having the armor-toggle-fix set to true, machines would sometimes lose data when placed. This has been resolved in the most recent development build of ViaVersion.

Download the most up-to-date version and the issue should be resolved.

Their development builds can be found here: https://ci.viaversion.com/job/ViaVersion/lastSuccessfulBuild/
