### ISSUE TITLE
BASIC MACHINES NOT WORKING FOR ME IN 1.20.x PLS HELP

### ISSUE THREAD

**Issue by MustangPro5377** [Slimefun/Slimefun4#3885]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I installed slimefun from aternos on paper/bukkit 1.20.1 , when i try to build basic machines and make recipes on any of them, it doesnt work

### 📑 Reproduction Steps

nil

### 💡 Expected Behavior

i was expecting that the recipe would be done

### 📷 Screenshots / Videos

nil

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

slimefun 4

### 🧭 Other plugins

nil

**Comment by Sefiraat** [comment]
Hello and good morning! 

Please could you provide more information? You mention basic recipes aren’t working but what recipes, what are you trying to do that doesn’t work? Really the reproduction steps part of the issue is key here and you have left it blank intentionally. Without more there isn’t a huge amount we can do to help, and we would love to :) <3

**Comment by Boomer-1** [comment]
additionally slimefun does not work on bukkit. it must be spigot based. paper is preferred. provide a screenshot of /sf versions in addition to everything Sefiraat asked for

**Comment by MustangPro5377** [comment]
> Please could you provide more information? You mention basic recipes aren’t working but what recipes, what are you trying to do that doesn’t work? Really the reproduction steps part of the issue is key here and you have left it blank intentionally. Without

i tried doing grandpa sticks and grandmas sticks , not working
i researched them too

**Comment by WalshyDev** [comment]
More info is needed than "not working"

Please go to Discord and someone can help. We need things like:
* What is happening
* Any errors
* Versions
* Server log

Sadly, no one can help with just "not working", we cannot read minds and cannot see what's happening on your server.

**Comment by MustangPro5377** [comment]
wait im sending it

**Comment by MustangPro5377** [comment]
![Minecraft_ 1 20 - Multiplayer (3rd-party Server) 7_2_2023 12_29_30 PM](https://github.com/Slimefun/Slimefun4/assets/98084618/1038b0ba-9c09-475d-ac73-8a5052bc762d)

**Comment by MustangPro5377** [comment]
Uploading Minecraft_ 1.20 - Multiplayer (3rd-party Server) 2023-07-02 12-32-40.mp4…

**Comment by MustangPro5377** [comment]
https://github.com/Slimefun/Slimefun4/assets/98084618/c3436ccb-7e91-4f2b-8bcd-76fa6e29f6f7

**Comment by MustangPro5377** [comment]
please see this

**Comment by MustangPro5377** [comment]
![BASIC MACHINES NOT WORKING FOR ME IN 1 20 x PLS HELP · Issue #3885 · Slimefun_Slimefun4 and 3 more pages - Personal - Microsoft​ Edge 7_2_2023 12_36_11 PM](https://github.com/Slimefun/Slimefun4/assets/98084618/c811709c-73d5-4495-bee5-3e83f0d8fcc4)

**Comment by MustangPro5377** [comment]
> More info is needed than "not working"
> 
> Please go to Discord and someone can help. We need things like:
> 
> * What is happening
> * Any errors
> * Versions
> * Server log
> 
> Sadly, no one can help with just "not working", we cannot read minds and cannot see what's happening on your server.

i have sent screenshots and videos
pls look into it
