### ISSUE TITLE
basic machines not working in 1.20 (sent screenshots this time)

### ISSUE THREAD

**Issue by MustangPro5377** [Slimefun/Slimefun4#3886]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

While i try to put any recipes on basic machines it does not work. As said before, i used paper/bukkit on aternos and installed it. is it neccessary to uninstall bukkit and only put paper software?

### 📑 Reproduction Steps

1) research any stuff that needs to be crafted using enhanced crafting table or any basic machine (pls install paper/bukkit on aternos)
2) build the basic machine and use it by the given recipe
3) and then the recipe may not be able to be crafted if its an error

### 💡 Expected Behavior

I expected that it would work

### 📷 Screenshots / Videos

![Minecraft_ 1 20 - Multiplayer (3rd-party Server) 7_2_2023 12_29_30 PM](https://github.com/Slimefun/Slimefun4/assets/98084618/21fcace3-0a04-4a9f-bc9f-1c8cfae02362)

https://github.com/Slimefun/Slimefun4/assets/98084618/4dc000ec-1879-44ff-8a58-ec57c573f22e

![BASIC MACHINES NOT WORKING FOR ME IN 1 20 x PLS HELP · Issue #3885 · Slimefun_Slimefun4 and 3 more pages - Personal - Microsoft​ Edge 7_2_2023 12_36_11 PM](https://github.com/Slimefun/Slimefun4/assets/98084618/de172d49-23e7-4acd-9873-5328a4a6e1d2)

### 📜 Server Log

given above in screenshots

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

![Minecraft_ 1 20 - Multiplayer (3rd-party Server) 7_2_2023 12_29_30 PM](https://github.com/Slimefun/Slimefun4/assets/98084618/6f012bda-8f6d-4577-907e-8b2edd1d82b5)

**Comment by variananora** [comment]
Your slimefun version is cut off. Send a full list on it.

It looks like there is problem with a protection plugin or permissions issue. Check your protection plugin and make sure you have permission/access in that region, or try "wilderness" region.

Please don't spam this in here, if you have a problem we have a [Discord server](https://discord.gg/slimefun) and we will help you.

**Comment by variananora** [comment]
I'm closing this because there is no response back, and if you still have a problem feel free to join our [Discord Server](https://discord.gg/slimefun) and discuss it there.
