### ISSUE TITLE
An exception thrown while executing sql: INSERT OR IGNORE INTO block_data (loc, data_val, data_key) VALUES ('world;9814:105:8851', 'MjY2MTk=', 'stored');

### ISSUE THREAD

**Issue by aesopcmc** [Slimefun/Slimefun4#3889]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

The console keeps reporting errors and warnings after an item is used
：
java.lang.IllegalStateException: An exception thrown while executing sql: INSERT OR IGNORE INTO block_data (loc, data_val, data_key) VALUES ('world;9814:105:8851', 'MjY2MTk=', 'stored');
[09:04:06 WARN]:        at Slimefun-v2023.06-release.jar//com.xzavier0722.mc.plugin.slimefun4.storage.adapter.sqlite.SqliteAdapter.executeSql(SqliteAdapter.java:261)

### 📑 Reproduction Steps

It should be that after using a certain item, the error has been reported repeatedly, and the log is increasing and occupying a lot of disk space

### 💡 Expected Behavior

dont't print warn error

### 📜 Server Log

https://pastebin.com/SEcEx5RR

### 📂 `/error-reports/` folder

https://pastebin.com/rCUtuGyK

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

  Slimefun v2023.06-release

**Comment by variananora** [comment]
You are not running the official version of Slimefun. Slimefun does not support SQL Databases.
