### ISSUE TITLE
backpack and cooler bug

### ISSUE THREAD

**Issue by SrMonsterYT** [Slimefun/Slimefun4#3903]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

one question had some change in slimefun, now all backpacks are coming with ID without ever having been opened this is normal? and also the cooler

slimefun and addons version:  https://prnt.sc/5IMRJfnPx076

### 📑 Reproduction Steps

video: https://youtu.be/x_3yTFNs8F4

### 💡 Expected Behavior

not come with ID, in /sf cheat if I take them comes normal see: https://prnt.sc/u1UHH8ajLVhw

### 📷 Screenshots / Videos

Description

### 📜 Server Log

no logs

### 📂 `/error-reports/` folder

no error

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

 Slimefun vDEV - 1079 (git 5b458f16)

**Comment by Boomer-1** [comment]
if they are manually crafted they have always come with an id. if they are done via autocrafting in core slimefun or networks they will not have an id. this is nothing new. I'll leave this open for the dev team to determine if this is something to look at or if they want to close it.

**Comment by SrMonsterYT** [comment]
no way, and since it has some craft that need the cooler, it cannot have ID 
photo: https://prnt.sc/d6MkUZut6L-Q

**Comment by Boomer-1** [comment]
it can have an id as people have crafted it for years

**Comment by SrMonsterYT** [comment]
> it can have an id as people have crafted it for years

you do not understand yet this did not happen before in 1.19.4, some items need the cooler without ID

photo: https://prnt.sc/NEoKrcj-eDrP

**Comment by SrMonsterYT** [comment]
> 

and how do I create a cooler without ID?

**Comment by Sefiraat** [comment]
Autocraft it
