### ISSUE TITLE
ExpCollector tick 19.49%

### ISSUE THREAD

**Issue by SrMonsterYT** [Slimefun/Slimefun4#3904]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

cpu increase in slimefun version #79 

spark lag: https://spark.lucko.me/8VyzUYO33o

slimefun and addons version: https://prnt.sc/fUoukhWGWEsI

timings slimefun: https://prnt.sc/t6NXi__V-13s

### 📑 Reproduction Steps

ExpCollector

### 💡 Expected Behavior

no 19%

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Slimefun DEV - 1079 (git 5b458f16)

**Comment by Phoenix-Starlight** [comment]
Checking the code reveals it uses code that will be changed in the inventory system rewrite.

**Comment by SrMonsterYT** [comment]
> Checking the code reveals it uses code that will be changed in the inventory system rewrite.

sorry I didn't understand, so is it a problem that will be solved?

**Comment by Phoenix-Starlight** [comment]
It will be solved, but no ETAs or time estimate. See #3170

**Comment by WalshyDev** [comment]
I'd recommend focusing on your entity/tick issues as the primary concern, 19% of this is bad but not terrible compared to ticking:
![image](https://github.com/Slimefun/Slimefun4/assets/8492901/7edc7087-0b4a-4ba4-8496-ee1ad9fd0ffa)

Obviously, this is still taking ages so we need to look into it but it's worth noting.

Now, 1079 was PR https://github.com/Slimefun/Slimefun4/pull/3892 however, this did not touch ExpCollector or related code. Can you please confirm what build this actually happened on?

**Comment by SrMonsterYT** [comment]
> I'd recommend focusing on your entity/tick issues as the primary concern, 19% of this is bad but not terrible compared to ticking: ![image](https://user-images.githubusercontent.com/8492901/252525129-7edc7087-0b4a-4ba4-8496-ee1ad9fd0ffa.png)
> 
> Obviously, this is still taking ages so we need to look into it but it's worth noting.
> 
> Now, 1079 was PR #3892 however, this did not touch ExpCollector or related code. Can you please confirm what build this actually happened on?

#79

**Comment by J3fftw1** [comment]
> > I'd recommend focusing on your entity/tick issues as the primary concern, 19% of this is bad but not terrible compared to ticking: ![image](https://user-images.githubusercontent.com/8492901/252525129-7edc7087-0b4a-4ba4-8496-ee1ad9fd0ffa.png)
> > Obviously, this is still taking ages so we need to look into it but it's worth noting.
> > Now, 1079 was PR #3892 however, this did not touch ExpCollector or related code. Can you please confirm what build this actually happened on?
> 
> #79

The PR you are linking is 7 years old

**Comment by Sefiraat** [comment]
He means Dev 1079 I think which, as Walshy pointed out, should have any impact here, what so ever. Given we have had sight of Sr's timings reports a few times over the last few weeks, I'm fairy happy this is a new occurance in terms of his experience within his server, but not likely due to recent updates. I'll do some tests locally during my lunch to see if I can get the same result(s).

**Comment by Sefiraat** [comment]
@SrMonsterYT Can you please try to find the exp collectors you have on the server and send a video of the setup?

I have managed to recreate this but only after pumping SO much EXP into the system, this report was spawning 10k worth of exp orbs per tick into 4 collectors with unlimited deep storage keeping 12k flasks over the duration of a small 60 second profile. 

<img width="888" alt="image" src="https://github.com/Slimefun/Slimefun4/assets/20646323/9b0bd84b-1120-48a1-af3a-28198ea7d38e">

**Comment by SrMonsterYT** [comment]
> 

it's a simple farm the skeleton wither dies and the exp collector collects and is the only player who has it on the whole server, I asked other players of the 100 online and no one had only 1 player, the server has about 2 weeks only because I reset and increased his processor, so I think this is a slimefun bug, is there any way to increase this exp collector tick?

photo: https://prnt.sc/YR_qmuXScDmc

video: https://youtu.be/irmzlTM8AkE

**Comment by Sefiraat** [comment]
It's not the version, nothing in this code has changed.

Your timings showed 2 exp collectors and the one you just showed seems very tame and is likely the reason for the lower usage. If you can find the 2nd one it's possible the setup there is more intense and would give you something to mitigate.

To be clear, this is on Slimefun, not yourself, but it's not something that can be resolved with ease so we need to give you the tools to self-regulate this.

**Comment by SrMonsterYT** [comment]
> It's not the version, nothing in this code has changed.
> 
> Your timings showed 2 exp collectors and the one you just showed seems very tame and is likely the reason for the lower usage. If you can find the 2nd one it's possible the setup there is more intense and would give you something to mitigate.
> 
> To be clear, this is on Slimefun, not yourself, but it's not something that can be resolved with ease so we need to give you the tools to self-regulate this.

now yes i hadn't done spark correctly it seems the problem still has and this happens only with 1 exp collector from 1 player 

spark: https://spark.lucko.me/5zHrVkp9PI

I spent 5 minutes killing like I did in the video and turned on the spark

**Comment by Sefiraat** [comment]
Hmm, ok this is great - thanks!

**Comment by SrMonsterYT** [comment]
> Hmm, ok this is great - thanks!

sorry to bother you again but here is the second exp collector from another player

photo: https://prnt.sc/rYYeGAXA-7Eo

is there anything I can do other than wait for it to be fixed?

**Comment by Sefiraat** [comment]
Short of disabling the blocks/removing them from the world, you'll need to await a resolution.

**Comment by SrMonsterYT** [comment]
> Short of disabling the blocks/removing them from the world, you'll need to await a resolution.

ok i will wait for a correction, thank you very much

**Comment by SrMonsterYT** [comment]
> > Short of disabling the blocks/removing them from the world, you'll need to await a resolution.
> 
> ok i will wait for a correction, thank you very much

sorry to comment here, but is version 83 the fix for this?

**Comment by Sefiraat** [comment]
> 

Version 1084. Please type the full version number in btw, its minor but it caused a little confusion up above you'll notice :)
