### ISSUE TITLE
All Slimefun Items can be interacted with even when claimed

### ISSUE THREAD

**Issue by CarterMane** [Slimefun/Slimefun4#3910]
### ❗ Checklist

- [x] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

The faction plugin i'm using allows other people to interact with all slimefun machines, even though they shouldn't be interacted with. (Faction Plugin: https://www.spigotmc.org/resources/medieval-factions.79941/)

Using pufferfish as server software (Allows bukkit, spigot, and paper plugins to be run all together)

Note: Although I am using a modded client, the other players who are using vanilla still can perform this

### 📑 Reproduction Steps

Download slimefun and the faction plugin
Create a faction and place some slimefun machines inside the chunks you claim
Have another person join and attempt to interact with those machines

### 💡 Expected Behavior

The machines shouldn't be able to be interacted with

### 📷 Screenshots / Videos

https://github.com/Slimefun/Slimefun4/assets/131935346/7b434b3c-6628-47fb-9d17-07c460423f15

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Slimefun #1087

### 🧭 Other plugins

https://www.spigotmc.org/resources/medieval-factions.79941/
Factions plugin used on our server

**Comment by Boomer-1** [comment]
this sounds like an issue with your protection plugin. which specifically are you using

**Comment by CarterMane** [comment]
i included the plugin in the report

**Comment by Boomer-1** [comment]
Here's the list of protection plugins that are supported.

https://github.com/Slimefun/Slimefun4/wiki/protection-plugins

I'll let a dev confirm, but I believe they have to hook into dough.

**Comment by Boomer-1** [comment]
i'd open an issue on their github

**Comment by CarterMane** [comment]
I'll try and get the owner to switch to one of these plugins, hopefully everything goes well

**Comment by CarterMane** [comment]
do these plugins also prevent other players to interact with machines?

**Comment by CarterMane** [comment]
ok i submitted a bug report on their gitbub
the server owner also wants to know if these plugins also prevent players from interacting with slimefun machines

**Comment by Phoenix-Starlight** [comment]
They should provided configuration is done properly.

**Comment by Sefiraat** [comment]
As said above, it looks like you aren’t using a supported protection plugin which means there isn’t much we can do currently. Good luck having your owner switch/getting the protection dev to hook :). <3
