### ISSUE TITLE
Crafting Soulbound Backpack giving an error from upgrading in Magic Workebench

### ISSUE THREAD

**Issue by XaosKoltron** [Slimefun/Slimefun4#3939]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When I was crafting a Soulbound backpack, it was giving issues that the crafting recipe was wrong. I checked the crafting recipe and it was 100% correct materials in the Magic Workbench. I crafted the Woven Backpack in the Enhanced Crafting Table, only machine I have currently since automation is not possible yet. 

I did some research that in 2018 there was a similar issue and assumed that was fixed but seems like it broke again.
Some suggest using the Old Automated Crafting Chamber and one also suggested changing the method of crafting type from Magic Workbench to Enchanced Crafting Table since the ID was giving the issue.
I cannot modify any game files since I play on a server that's hosted else where.

Slimefun Version : DEV - 1093
Minecraft Version: 1.20.1
Server Software: Paper

### 📑 Reproduction Steps

Craft Small Backpack and upgrade it to Woven Backpack in Enhanced Crafting Table
Then
Upgrade Woven Backpack in Magic Workbench

### 💡 Expected Behavior

When crafting the Soulbound Backpack it suppose to give the Soulbound backpack since I am able to craft Radiant Backpacks without any issues

### 📷 Screenshots / Videos

![2023-08-08_00 11 53](https://github.com/Slimefun/Slimefun4/assets/38610136/16fd1de8-bd7d-4154-8213-ba3103049680)
![2023-08-08_00 11 57](https://github.com/Slimefun/Slimefun4/assets/38610136/e892c0b5-d542-4789-bad3-50f6a4488c74)
![2023-08-08_00 12 01](https://github.com/Slimefun/Slimefun4/assets/38610136/ce0ce45b-dffd-408e-ac87-20f4ea70e9ba)
![2023-08-08_07 19 29](https://github.com/Slimefun/Slimefun4/assets/38610136/10514064-09d0-4753-9384-026e5c3ce6e0)
![2023-08-08_07 19 32](https://github.com/Slimefun/Slimefun4/assets/38610136/cfed36bf-d28d-4b28-8f85-4df31459caf3)
![2023-08-08_07 19 35](https://github.com/Slimefun/Slimefun4/assets/38610136/588c04c4-b2a7-48ea-a496-a6b338927c03)

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

DEV - 1093

**Comment by JustAHuman-xD** [comment]
> im pretty sure the backpack cant have an ID

You’re right but wouldn’t it be better if we changed it so it _could_. It’s rather unintuitive to not be able to have one.

**Comment by J3fftw1** [comment]
you are 100% right, it would be better but that will have to be changed with the recipe rewrite.
This is the same reason why items cant have different meta then vanilla

**Comment by Sefiraat** [comment]
If DistinctiveItem is implemented and the correct isItemSimiler overload is invoked this should be doable within the current code base without to much issue? I think at least. I’ve looked at 0 lines of code for this supposition so I may be talking trash.
