### ISSUE TITLE
i get harmed since the new radiation update

### ISSUE THREAD

**Issue by Dexter411** [Slimefun/Slimefun4#3945]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Hello, since a few days each time i login from the /hub to the   survival server, i get radiated. my countdown get less and less and i guess at one point i will die. but: i dont have any blistering, uranium, neptunium, plutonium in inventory, i dont run any nuclear reactors. i wear infinity gear. i also tested it to change gear to a new craftet hazmaz suite... i still  get radiated....

### 📑 Reproduction Steps

i dont know how to reproduce this.

i am only a player on the server, so no admin or stuff or developer. i cant provide any more data.

### 💡 Expected Behavior

i am only a player on the server, so no admin or stuff or developer. i cant provide any more data.

### 📷 Screenshots / Videos

![47v](https://github.com/Slimefun/Slimefun4/assets/142180177/a2c53285-06e0-4840-97c7-ee8e41a5eb6f)

https://github.com/Slimefun/Slimefun4/assets/142180177/ec1ce64e-506a-42e1-bfb9-4e525c9b229e

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

00000.0

### 🧭 Other plugins

i am only a player on the server, so no admin or stuff or developer. i cant provide any more data.

**Comment by iTwins** [comment]
Does this happen every time you join? Is the radiation level the same every time you join? Did you have any radioactive materials in your inventory before and left while still radiated? Does it last the same amount of time every time (4 or 5 seconds in the video you sent)? Is it always gone within 10 seconds? Are there any addons that could be messing with radiation? Have you asked a developer of the server if they know anything? Can you provide the ``config.yml``? Do you have any information that could help with reproducing?

**Comment by Dexter411** [comment]
Hello, i think i understand it now: sometimes the server is a bit laggy. so, i had indeed uran in my inventory when i rearanged some stuff and i guess at a lag, the system didnt recognize the infinity gear instant, so it  puts my radiation level up to 100. after several logins, the radiation level goes more and more down, when it was zero, it never happend again.
