### ISSUE TITLE
Block tickers task 

### ISSUE THREAD

**Issue by SemperAmici** [Slimefun/Slimefun4#3947]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Players have reported that wither skeletons,villagers and blazes are not spawning from seeds in netheopiosis but other mobs are. 

I am using the following settings:
spawning:
  player-cap-water-ambient: 10
  player-cap-water-animal: 10
  player-cap-water-hostile: 15
  player-cap-land-ambient: 15
  player-cap-land-animal: 15
  player-cap-land-hostile: 30
  player-cap-villager: 5
  player-cap-piglin-trader: 4
  player-cap-wandering-trader: 4

### 📑 Reproduction Steps

Do not know how to reproduce as only the three mentioned mobs are the only ones I was told that did not spawn. It isn’t server difficulty as it is on hard.

### 💡 Expected Behavior

Having wither skeletons,villagers and blazes spawn from seeds.

### 📜 Server Log

https://pastebin.com/nbBJE1fP

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

https://pastebin.com/hTFtRvUB

**Comment by JustAHuman-xD** [comment]
This should be opened in netheopsis not Slimefun probably

**Comment by Sefiraat** [comment]
As per the above, pop this in Netheopoiesis’ repository issues :). Thanks!
