### ISSUE TITLE
Feature Request - "Stack" and "Item" pull modes for Input Nodes

### ISSUE THREAD

**Issue by praetoras** [Slimefun/Slimefun4#3952]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When using input nodes on nodes like Round Robin, the system pulls entire stacks from slots and round-robins them to accepting output nodes.

When attempting to slow the progress by feeding inventory through a hopper, this appears to interrupt the system's round-robin counting and causes it to reset, resulting in only a portion of the accepting inventories getting the items, resulting in "clumping" and very uneven distribution.

### 📑 Reproduction Steps

Set up a chest with an input node to blacklist-pull all items put into the chest. Attach a hopper feeding into the chest and (optionally) another chest above the hopper as an inventory source.

Have the cargo network output to a line of 10 chests, each filtered with advanced cargo output nodes to accept a specific identical item (in my case it was gold dusts). Set the input node to round robin.

Put several stacks of the test item into the hopper (or the chest above it).

### 💡 Expected Behavior

There are many, many use-cases for needing to round-robin cargo per-item rather than per-stack. I propose adding a new setting that causes the input node to purposefully pull only one item at a time.

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

https://i.gyazo.com/7857b9ccfc6a34b359664fbfb5acf080.png

**Comment by Boomer-1** [comment]
this isn't really a bug but a suggestion which goes on the #suggestions channel on the discord.
