### ISSUE TITLE
bug with synthetic emerald

### ISSUE THREAD

**Issue by exeedavid** [Slimefun/Slimefun4#3979]
### ❗ Checklist

- [x] I am using the official english version of Slimefun and did not modify the jar.
- [ ] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [ ] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [x] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

when doing a synthetic emerald on the smeltery, it makes the aluminium dust into aluminium ingot, instead of emerald

### 📑 Reproduction Steps

1. go to the smeltery to make a synthetic emerald
2. put the materials there just like guide says
3. it gives me aluminium ingot in place synthetic emerald

### 💡 Expected Behavior

I hope the synthetic emerald is made instead of the aluminum ingot.

### 📷 Screenshots / Videos

![image](https://github.com/Slimefun/Slimefun4/assets/145595185/afcb565f-fb12-4a02-a823-4b96d39d78bc)
![image](https://github.com/Slimefun/Slimefun4/assets/145595185/c0354f13-3fb2-4336-af3c-81df32b948f5)
![image](https://github.com/Slimefun/Slimefun4/assets/145595185/6ca723a9-fce3-4c54-94e7-913293aa06a4)

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

![image](https://github.com/Slimefun/Slimefun4/assets/145595185/0be0756c-d942-4724-99a2-d75eab9da47c)

**Comment by Boomer-1** [comment]
you are missing one ingredient in the smeltery. the glass pane. closing as invalid.
