### ISSUE TITLE
When using unresearched pickaxes, you are able to dupe any item in the enhanced, reinforced or carbonado furnaces

### ISSUE THREAD

**Issue by Boomer-1** [Slimefun/Slimefun4#3983]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

You can dupe any item in any of the enhanced or the carbonado or reinforced furnace. it will also work with any slimefun machine that has a vanilla interface, such as the android item or fuel interfaces.

### 📑 Reproduction Steps

1. Unlock the research for any of the enhanced, reinforced or carbonado furnaces, android interfaces or any sf machine with a vanilla interface
2. obtain any tool such as the cobalt pickaxe from a player but you have not unlocked the research for that pickaxe
3. Place any item in the furnace or machine
4. attempt to break the furnace with the pickaxe
5. you'll get that item duped with every attempt to break the machine

### 💡 Expected Behavior

the item should not drop and duplicate when breaking the machine

### 📷 Screenshots / Videos

https://youtu.be/o-z6EFDtO0g

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

dev 1101

**Comment by Boomer-1** [comment]
this was initially reported by someone on discord and I was able to confirm

**Comment by ybw0014** [comment]
it should be fixed in 1102 but build was failed

**Comment by iTwins** [comment]
build 1103 was successful, so this is now fixed.
