### ISSUE TITLE
Creating reinforced spawner and it changed to pig spawner

### ISSUE THREAD

**Issue by condblock** [Slimefun/Slimefun4#3984]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When I fixing a spawner, it becames to pig spawner.

### 📑 Reproduction Steps

1. Get a broken spawner(blaze)
2. Fix it on ancient alter

### 💡 Expected Behavior

I expected to get a blaze spawner

### 📷 Screenshots / Videos

![2023-09-30_18 45 57](https://github.com/Slimefun/Slimefun4/assets/72214833/0121b60d-6cb1-4700-83db-a40cbf916ab9)
![2023-09-30_18 32 01](https://github.com/Slimefun/Slimefun4/assets/72214833/25c904c1-a412-44e1-a200-333fa17c169e)
![2023-09-30_18 32 09](https://github.com/Slimefun/Slimefun4/assets/72214833/b32e7864-b5b7-4449-b567-0d7bc22e81b3)

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

This Server uses the following setup of Slimefun:                                                                                                                           [18:36:15 INFO]: Purpur git-Purpur-2014 (MC: 1.20.1)                                                                                                                                         [18:36:15 INFO]: Slimefun DEV - 1100                                                                                                                                            [18:36:15 INFO]: Metrics-Module #29                                                                                                                                                          [18:36:15 INFO]: Java 17                                                                                                                                                                     [18:36:15 INFO]:                                                                                                                                                                             [18:36:15 INFO]: Installed Addons: (26)                                                                                                                                                      [18:36:15 INFO]:   ExtraTools vDEV - 36 (git 922c0324)                                                                                                                                       [18:36:15 INFO]:   Quaptics vDEV - 4 (git cbc2e78e)                                                                                                                                          [18:36:15 INFO]:   SlimefunOreChunks vDEV - 15 (git 2520cb23)                                                                                                                                [18:36:15 INFO]:   SfChunkInfo vDEV - 8 (git b1b94abb)                                                                                                                                       [18:36:15 INFO]:   DynaTech vDEV - 201 (git 0feb2ee0)                                                                                                                                        [18:36:15 INFO]:   ExtraGear vDEV - 13 (git c62047e2)                                                                                                                                        [18:36:15 INFO]:   SlimeHUD vDEV - 10 (git 7d1c666b)                                                                                                                                         [18:36:15 INFO]:   InfinityExpansion vDEV - 144 (git 9da37202)                                                                                                                               [18:36:15 INFO]:   SFCalc vDEV - 37 (git dfc0fc41)                                                                                                                                           [18:36:15 INFO]:   ElectricSpawners vDEV - 23 (git 6ec96773)                                                                                                                                 [18:36:15 INFO]:   BetterReactor vDEV - 11 (git 88a98d28)                                                                                                                                    [18:36:15 INFO]:   WhatIsThis v5.3                                                                                                                                                           [18:36:15 INFO]:   SlimeTinker vDEV - 84 (git 2c9f6155)                                                                                                                                      [18:36:15 INFO]:   PrivateStorage vDEV - 18 (git 5832db21)                                                                                                                                   [18:36:15 INFO]:   Galactifun vDEV - 76 (git aa6414a8)                                                                                                                                       [18:36:15 INFO]:   TranscEndence vDEV - 41 (git 98d7d47e)                                                                                                                                    [18:36:15 INFO]:   ColoredEnderChests vDEV - 23 (git 4d041832)                                                                                                                               [18:36:15 INFO]:   FluffyMachines vDEV - 130 (git 01c839cc)                                                                                                                                  [18:36:15 INFO]:   DyedBackpacks vDEV - 17 (git 8b329e96)                                                                                                                                    [18:36:15 INFO]:   Cultivation vDEV - 11 (git 3e25165d)                                                                                                                                      [18:36:15 INFO]:   SoundMuffler vDEV - 24 (git ae8e2bf7)                                                                                                                                     [18:36:15 INFO]:   HardcoreSlimefun v1.0                                                                                                                                                     [18:36:15 INFO]:   Liquid vDEV - 14 (git 0f5346bf)                                                                                                                                           [18:36:15 INFO]:   SlimeCustomizer vDEV - 30 (git 6f0bf930)                                                                                                                                  [18:36:15 INFO]:   SimpleUtils vDEV - 15 (git 4250fd5e)                                                                                                                                      [18:36:15 INFO]:   SoulJars vDEV - 24 (git 78d1c6fa)

**Comment by variananora** [comment]
Hey, sorry for the late reply. I can't seems to reproduce this on my test server. I also found that your sf item name and lores are translated to Korean, are you sure you are using the official version? Since sf can't do that.

**Comment by condblock** [comment]
> Hey, sorry for the late reply. I can't seems to reproduce this on my test server. I also found that your sf item name and lores are translated to Korean, are you sure you are using the official version? Since sf can't do that.

I also tested it on the official version.

**Comment by Boomer-1** [comment]
can you record a video of it with the official version as I am unable to create it either after multiple attempts on the official version. please show /sf versions in game

**Comment by variananora** [comment]
Can you also include your `/plugins`? So I can check and test if you have any spawner plugins that could caused this.

**Comment by condblock** [comment]
i tested again, and it is problem of soul jar.

**Comment by Boomer-1** [comment]
additionally, if you already had a broken spawner, then that's not soul jars. soul jars has no spawners. this seems to be isolated to your non official version
