### ISSUE TITLE
Could not call method 

### ISSUE THREAD

**Issue by 100petr** [Slimefun/Slimefun4#3992]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I updated the server to 1.20.2 and it gives an error when loading (sf is updated)

### 📑 Reproduction Steps

Start the server with version 1.20.2

### 💡 Expected Behavior

It won't write an error

### 📷 Screenshots / Videos

![image](https://github.com/Slimefun/Slimefun4/assets/29830635/a9d3e22d-a558-4ee0-839a-d909bbc30379)

### 📜 Server Log

https://pastebin.com/kqci1apN

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

1104

**Comment by iTwins** [comment]
Your error says that you're using DEV 1090

**Comment by JustAHuman-xD** [comment]
If you verified can you put those screenshots on the main message?

**Comment by JustAHuman-xD** [comment]
Can you give a screenshot of the output of /sf versions

**Comment by TheBusyBiscuit** [comment]
The error shows that it's a purpur/paper issue with deserializing honey block data.
I had a look and found the corresponding issue: https://github.com/PaperMC/Paper/issues/9823

It is supposed to be fixed soon-ish, have a look for purpur updates.
