### ISSUE TITLE
Command /sf stats doesnt work in some cases

### ISSUE THREAD

**Issue by EagL3-GIT** [Slimefun/Slimefun4#3995]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Some of the items cant be disabled because then when you unlock every single reasearch its giving an error after using command /sf stats.

### 📑 Reproduction Steps

1. Disable particular items in items.yml
   (For example disable every single piece of REINFORCED ALLOY armor.)
2. Give yourself all the researches.
3. Run command /sf stats,

### 💡 Expected Behavior

It should show stats as normal without error.

### 📷 Screenshots / Videos

![image](https://github.com/Slimefun/Slimefun4/assets/63203158/e081057a-d165-4fa8-a155-6b2d93fd7761)

### 📜 Server Log

https://pastebin.com/H6K4Cp7C

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Paper git-Paper-233 (MC: 1.20.2)
Slimefun DEV - 1104 (git c977454e)
Metrics-Module #29
Java 17
 
Installed Addons: (12)
Networks vDEV - 50 (git 3de3c9d6)
InfinityExpansion vDEV - 144 (git 9da37202)
AureliumSkills vBeta 1.3.23
ShopGUIPlus v1.92.0
LiteXpansion vDEV - 192 (git 661862ed)
IllegalStack v2.9.8
aquacore v1.4-SNAPSHOT
Residence v5.1.3.0
CMI v9.6.5.3
FluffyMachines vDEV - 132 (git ccf029ba)
ItemsAdder v3.6.0
HeadLimiter vDEV - 15 (git 66d18f52)

**Comment by JustAHuman-xD** [comment]
Ah should be a straightforward fix lemme see what I can do

**Comment by JustAHuman-xD** [comment]
(Nvm iTwins is on it lol)
