### ISSUE TITLE
Slimefun items shows as player heads (texture bug)

### ISSUE THREAD

**Issue by RamsTwii** [Slimefun/Slimefun4#4004]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

The first time i played with slimefun the textures worked perfectky, the following day when i restarted the server all items that uses player heads showed as steve, alex, etc
(items that i crafted the first day when it was working still shows the right textures)
How can i solve this ?

### 📑 Reproduction Steps

1. Start your server
2. Panic because the backpack you just crafted is now a human head

### 💡 Expected Behavior

I expected the textures to work i guess ?

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

![Minecraft 1 20 2 - Multiplayer (3rd-party Server) 22_10_2023 22_35_40](https://github.com/Slimefun/Slimefun4/assets/148721520/420e4bae-a6e5-4b24-a9f8-b810c78796d9)

**Comment by RamsTwii** [comment]
Also the items are still working they did not turn into cs-core heads the bug is just the textures

**Comment by Boomer-1** [comment]
confirmed from server log mojang servers were unable to be reached
