### ISSUE TITLE
Head item textures turning into default mojang skins

### ISSUE THREAD

**Issue by CluelessSlayer** [Slimefun/Slimefun4#4013]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

All head items turn into default head skins, normal SlimeFun and addons. They work correctly its just the texture.

### 📑 Reproduction Steps

1. get any head item

### 💡 Expected Behavior

The items are displayed with usual textures

### 📷 Screenshots / Videos

![image](https://github.com/Slimefun/Slimefun4/assets/146643651/90b38933-410d-43c6-84d5-0b48560c748c)
![image](https://github.com/Slimefun/Slimefun4/assets/146643651/13b19e45-04de-45fa-a925-e29cb61c44ee)

### 📜 Server Log

https://pastebin.com/BsrDwBme

### 📂 `/error-reports/` folder

empty

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

![image](https://github.com/Slimefun/Slimefun4/assets/146643651/c595e998-af9b-4727-b1bf-4a5a135cdb2f)

### 🧭 Other plugins

![image](https://github.com/Slimefun/Slimefun4/assets/146643651/bde6ad53-4825-4158-923b-656bc81379a0)

**Comment by Boomer-1** [comment]
if you look in your server log, this is addressed. either your server cannot connect to the mojang head database, or mojang is rate limiting your server. every 10 minutes the server reattempts to connect to it. all you can currently do is wait, closing as invalid.
