### ISSUE TITLE
simple duplication based on backpack

### ISSUE THREAD

**Issue by m1919810** [Slimefun/Slimefun4#4031]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

while playing in 'paper1.20' server I find a backpack duplication.
I successfully repeat this duplication in several 1.20 and 1.19.2 paper servers
now me and my friend are running a 1.19.2 paper server with slimefun "Slimefun 2023.10.20-release" ,"Paper git-Paper-365 (MC: 1.19.3)" and addons.
I d like to know  how to fix this bug

### 📑 Reproduction Steps

1.download a fastclick tool such as tweakeroo (fastrightclick speed 6 available)
2.put item in a backpack
3.close the backpack
4.open fastclick and open the backpack,take out items in backpack
5.quit the game
6.back to the game

### 💡 Expected Behavior

you will find items duplicated in your backpack

### 📷 Screenshots / Videos

too lazy to get one

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Paper git-Paper-365 (MC: 1.19.3)
Slimefun 2023.10.20-release
Metrics-组件 #29
Java 17
安装的附属插件: (35)

**Comment by WalshyDev** [comment]
>  slimefun "Slimefun 2023.10.20-release"

This is not an official version therefore we cannot provide any support.

**Comment by m1919810** [comment]
> > slimefun "Slimefun 2023.10.20-release"
> 
> This is not an official version therefore we cannot provide any support.

bro，I think that's universal . Wait for me ,I'll prove it

**Comment by Boomer-1** [comment]
if you can demonstrate it on the official version, dev 1104 then we can look into it

**Comment by m1919810** [comment]
> if you can demonstrate it on the official version, dev 1104 then we can look into it

ok,I'm trying to build a server

**Comment by m1919810** [comment]
> if you can demonstrate it on the official version, dev 1104 then we can look into it

sorry my mistake.
I just realized that none of the servers I played in use official versions
so I’m considering changing my sf version into official one?

**Comment by m1919810** [comment]
> if you can demonstrate it on the official version, dev 1104 then we can look into it

so if I want my present version of sf bugfix,where should I get help。
There are errors while loading previous addons in official versions

**Comment by J3fftw1** [comment]
I think you should join the Slimefun discord and ask in there
https://discord.gg/slimefun

**Comment by ybw0014** [comment]
https://github.com/StarWishsama/Slimefun4
He completely ignores and wiped the warning messages in sf versions output. We have told users not to report to official issue tracker.

**Comment by m1919810** [comment]
> https://github.com/StarWishsama/Slimefun4/issues He completely ignores and wiped the warning messages in sf versions output. We have told users not to report to official issue tracker directly with this version info.

sorry about that .I havn't been there before. My friend download our sf version
