### ISSUE TITLE
over a few 100 warns

### ISSUE THREAD

**Issue by pro9code** [Slimefun/Slimefun4#4034]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

i just started the server

### 📑 Reproduction Steps

tried the plugin on canvasmc

### 💡 Expected Behavior

not 100 errors

### 📜 Server Log

https://justpaste.it/2gyq6

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

1104 git c9774

**Comment by Boomer-1** [comment]
update to the latest slimefun version. then if you still have the issue, come back with updated info. you can download the latest version at https://blob.build

**Comment by ybw0014** [comment]
why you even run Slimefun on a mod server? just use mods

**Comment by pro9code** [comment]
it dosn't have any mods and is focused on compatibility.

**Comment by Boomer-1** [comment]
then why have a mod launcher if no mods?

either way, until you're on the latest version there's nothing we can do
