### ISSUE TITLE
Advanced Enchants - Multiplication Dupe

### ISSUE THREAD

**Issue by PirateBeowolf** [Slimefun/Slimefun4#4038]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Advanced Enchants - Multiplication 
Dupes any SF block

Chance to multiply ore drops. Costs 5 souls

### 📑 Reproduction Steps

add level 1-5, 5 is best and dupe

### 💡 Expected Behavior

You click any SF block or machine even power or cargo and get more 

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

https://ae.advancedplugins.net

**Comment by Boomer-1** [comment]
did you open an issue with advanced enchants as this doesn't happen without their enchant
