### ISSUE TITLE
Advance Enchants and Slimefun Dupe

### ISSUE THREAD

**Issue by Pascual75** [Slimefun/Slimefun4#4041]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

You can dupe with the enchants replant several peaks of the slimefun

### 📑 Reproduction Steps

1. Take a hoe and enchant it with replanting
2. Pick up example carrot and instead of carrot you will harvest peaks of the slimefun

### 💡 Expected Behavior

Don't pick spikes

### 📷 Screenshots / Videos

https://www.youtube.com/watch?v=5dX2oPHWkzs

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

Slimefun 4 DEV 1104 (git c9774)

### 🧭 Other plugins

Advance Enchants

**Comment by J3fftw1** [comment]
Please report this to Advance Enchants 
dupe https://github.com/Slimefun/Slimefun4/issues/4038
dupe https://github.com/Slimefun/Slimefun4/issues/4033
