### ISSUE TITLE
Exception while requesting skin jphipps3

### ISSUE THREAD

**Issue by Zyhriz** [Slimefun/Slimefun4#4046]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I've noticed this on a few servers (all 1.19.4, one hosted by Minehut, another running on Pufferpanel and a third on Pterodactyl), but occasionally when Slimefun attempts to cache skins for the custom heads, it runs into an issue where it can't find jphipps3's skin. This is the error:

```
[01:00:29 ERROR]: [dough: skins] Exception while requesting skin: https://api.mojang.com/users/profiles/minecraft/jphipps3
[01:00:29 WARN]: [Slimefun] Attempted to refresh skin cache, got this response: ExecutionException: java.io.FileNotFoundException: https://api.mojang.com/users/profiles/minecraft/jphipps3
[01:00:29 WARN]: [Slimefun] This usually means mojang.com is temporarily down or started to rate-limit this connection, nothing to worry about!
```

This error probably happens because the user doesn't exist.

### 📑 Reproduction Steps

1. Install Slimefun and addons (I don't think it's an addon issue, but I'm mentioning it just incase)
2. Restart server
3. Wait ~2 minutes
4. Look at console

### 💡 Expected Behavior

No errors put in console.

### 📂 `/error-reports/` folder

None

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

![IMG_3029](https://github.com/Slimefun/Slimefun4/assets/122718003/f99050e3-91ea-41e2-be5d-809f859443db)

### 🧭 Other plugins

There's a chance it's one of the addons that are creating the issue, but it would say that addon's name instead of just Slimefun, right?

**Comment by ybw0014** [comment]
you are using an outdated version, update to latest version on https://blob.buid/

**Comment by Zyhriz** [comment]
Oops, sorry, didn't notice. I'll update and see if that fixes it.

**Comment by Zyhriz** [comment]
...the issue isn't resolved. i have the most up to date version

**Comment by Boomer-1** [comment]
1104 is not the latest on the build site. 1104 is the most recent on the discord, but not blob build

**Comment by JustAHuman-xD** [comment]
> Oops, sorry, didn't notice. I'll update and see if that fixes it.
> 
> Edit: Yeah I am? DEV 1104, and the commit number is the same as is on the download site. https://blob.build/ isn't a site, either. 😐

that is a site

**Comment by Zyhriz** [comment]
> > Oops, sorry, didn't notice. I'll update and see if that fixes it.
> > Edit: Yeah I am? DEV 1104, and the commit number is the same as is on the download site. https://blob.build/ isn't a site, either. 😐
> 
> that is a site

Safari's bugging I guess. Said server not found.

And I got my version off https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/ . Is that not where I'm supposed to be downloading it from? That's what the github links to.

I'll edit once I try the new version.

**Comment by Boomer-1** [comment]
1112 is the latest on https://blob.build

**Comment by Zyhriz** [comment]
> > > Oops, sorry, didn't notice. I'll update and see if that fixes it.
> > > Edit: Yeah I am? DEV 1104, and the commit number is the same as is on the download site. https://blob.build/ isn't a site, either. 😐
> > 
> > 
> > that is a site
> 
> Safari's bugging I guess. Said server not found.
> 
> And I got my version off https://thebusybiscuit.github.io/builds/TheBusyBiscuit/Slimefun4/master/ . Is that not where I'm supposed to be downloading it from? That's what the github links to.
> 
> I'll edit once I try the new version.

Looks like it was fixed after updating to the version on https://blob.build/ , sorry for the confusion.
And I think I got the error on Safari after clicking the link before the typo was fixed. I should've noticed.
