### ISSUE TITLE
 head items have the player head texture

### ISSUE THREAD

**Issue by TerrariaMinecraftFan44** [Slimefun/Slimefun4#4052]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

All the heads are just player heads without texture (I'm on a premium account and my server is online)

### 📑 Reproduction Steps

Use a player head mechanic 

### 💡 Expected Behavior

Player heads with the texture 

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Slimefun - DEV 1104
![prueba slimefun](https://github.com/Slimefun/Slimefun4/assets/152024790/1560e408-6a07-4540-a522-1bc671ce798d)

### 🧭 Other plugins

Not in another plugin but it happens in the ExoticGarden addon

**Comment by TerrariaMinecraftFan44** [comment]
A user posted something similar on the exotic garden addon and no one answered him

**Comment by Sfiguz7** [comment]
There was an issue due to a Spigot change, this has since been fixed. You can download the latest build here: https://blob.build/

**Comment by TerrariaMinecraftFan44** [comment]
Thanks, it worked.
