### ISSUE TITLE
Custom player heards are broken on 1.20.2.

### ISSUE THREAD

**Issue by MagmaBro123** [Slimefun/Slimefun4#4058]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Title. All player heads from Slimefun and all addons are broken.

Pufferfish fork is being used.

### 📑 Reproduction Steps

Use the plugin and any addons on a 1.20.2 server.

### 💡 Expected Behavior

Everything to work correctly.

### 📷 Screenshots / Videos

![2023-12-13_19 12 42](https://github.com/Slimefun/Slimefun4/assets/51277766/69338f11-7d29-4ec4-af41-bd435ba637b6)

### 📜 Server Log

N/A.

### 📂 `/error-reports/` folder

N/A.

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

![2023-12-13_19 08 28](https://github.com/Slimefun/Slimefun4/assets/51277766/49496b95-bf89-4068-b571-b1fd797aeee8)
![2023-12-13_19 08 30](https://github.com/Slimefun/Slimefun4/assets/51277766/2f774c18-3545-4c0f-beb9-db25dd65bf01)

### 🧭 Other plugins

None.

**Comment by ybw0014** [comment]
you didnt search existing issues... why you tick that

**Comment by variananora** [comment]
Slimefun already fixed this and moved the builds page to the new https://blob.build/
Version 1104 or lower won't automatically update to the new builds page, you need to update your Slimefun manually.

**Comment by MagmaBro123** [comment]
> Slimefun already fixed this and moved the builds page to the new https://blob.build/ Version 1104 or lower won't automatically update to the new builds page, you need to update your Slimefun manually.

I wasn't made aware of this new page. No announcement, ping, etc. was ever made, but thanks.

**Comment by ybw0014** [comment]
There was an @everyone announcement on discord server. https://discord.com/channels/565557184348422174/565569425210867715/1181501726516318218
