### ISSUE TITLE
sensitive blocks server crashes

### ISSUE THREAD

**Issue by 100petr** [Slimefun/Slimefun4#4069]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Server crashes with error about sensitive blocks (last thing about it I found this PR https://github.com/Slimefun/Slimefun4/pull/4050)

### 📑 Reproduction Steps

it specifically happened to me when I was destroying a custom tree from itemsadder
to someone else when harvesting wines in bulk https://discord.com/channels/565557184348422174/565569196218384385/1187986406484750406

### 💡 Expected Behavior

the server will not be overloaded and will not crash

### 📷 Screenshots / Videos

https://www.youtube.com/watch?v=pqGNxOiH5N0

### 📜 Server Log

https://pastebin.com/pjg05cMU

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Slimefun version Dev - 1117

**Comment by WalshyDev** [comment]
Related: https://github.com/Slimefun/Slimefun4/pull/3966 & https://github.com/Slimefun/Slimefun4/pull/4048 & https://github.com/Slimefun/Slimefun4/pull/4050

cc: @iTwins @JustAHuman-xD @Sfiguz7 

We've had a few reports of this now hanging servers, I haven't dug into this code much or the situations around it but want to highlight for y'all

**Comment by JustAHuman-xD** [comment]
To fix this there are a couple things we could do, I'll talk to the others about it, I get home in a couple days so I can make a PR then

**Comment by WalshyDev** [comment]
This code was disabled in build 1121, we'll figure out a better path forward (and probably config option) for next time.
