### ISSUE TITLE
Backpacks don't increment number

### ISSUE THREAD

**Issue by SchnTgaiSpock** [Slimefun/Slimefun4#4080]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Crafting new backpacks does not increment its number, and it just gives another copy of an existing backpack. The number only increments when the server is restarted.

### 📑 Reproduction Steps

Craft several Small Backpacks in an Enhanced Crafting Table

### 💡 Expected Behavior

For the backpack number to increment

### 📷 Screenshots / Videos

https://github.com/Slimefun/Slimefun4/assets/101147426/391ec1e1-c56a-4bbf-9c69-a4104a90538f

(Sorry about the quality)

### 📜 Server Log

No error messages

### 📂 `/error-reports/` folder

No errors generated

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Dev 1122

**Comment by JustAHuman-xD** [comment]
Sounds like something was missed with the new storage api
