### ISSUE TITLE
Could not pass event PlayerRightClickEvent to Slimefun vDev - 1131

### ISSUE THREAD

**Issue by kubus1472** [Slimefun/Slimefun4#4103]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When trying to place anything on an ancient pedestal, the item disappears and the following error appears in the console: Could not pass event PlayerRightClickEvent to Slimefun vDev - 1131

### 📑 Reproduction Steps

1. try to place anything on the ancient pedestal
2. the item disappears and is not placed on the pedestal

### 💡 Expected Behavior

i expected the item to stay on the altar instead of disappearing.

### 📷 Screenshots / Videos

https://github.com/Slimefun/Slimefun4/assets/46248811/acff546d-bf60-4d9a-9f52-ffd0f5c1fb9a

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

This Server uses the following setup of Slimefun:
Paper git-Paper-196 (MC: 1.20.1)
Slimefun Dev - 1131
Metrics-Module #29
Java 17

Installed Addons: (17)
  DyedBackpacks vDEV - 17 (git 8b329e96)
  AureliumSkills vBeta 1.3.24
  ExtraTools vDEV - 36 (git 922c0324)
  SoundMuffler vDEV - 24 (git ae8e2bf7)
  SlimefunOreChunks vDEV - 15 (git 2520cb23)
  EcoPower vDEV - 5 (git 5c1ecd68)
  ExtraGear vDEV - 13 (git c62047e2)
  ExoticGarden vDEV - 78 (git 7f9a5f63)
  InfinityExpansion vDEV - 144 (git 9da37202)
  LiteXpansion vDEV - 192 (git 661862ed)
  SFCalc vDEV - 37 (git dfc0fc41)
  ExtraHeads vDEV - 25 (git 8c29f73a)
  SoulJars vDEV - 24 (git 78d1c6fa)
  SlimyTreeTaps vDEV - 20 (git 963f0383)
  MobCapturer vDEV - 33 (git 6fc26c35)
  Galactifun vDEV - 76 (git aa6414a8)
  Kingdoms v1.16.20.1

**Comment by WalshyDev** [comment]
Please provide the log, right now we have no info to go on.

**Comment by WalshyDev** [comment]
Fixed in build 1132
