### ISSUE TITLE
Output Chest n non researched tools item bug dupe

### ISSUE THREAD

**Issue by HeadsShot** [Slimefun/Slimefun4#4110]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I found a bug about how to dupe an item on slimefun and it's very OP and how to reproduce the bug is

### 📑 Reproduction Steps

First you need to research Output Chest and then you need to place the chest
Second You need to put some item any item works 
Third you or your friend need to give an unresearched tools given to you or your friend  to do the bug
Fourth all you need is to destroy the chest with the unresearched tools

### 💡 Expected Behavior

It'll dupe everything you put in that chest

### 📷 Screenshots / Videos

![WhatsApp Image 2024-01-24 at 21 20 12_4adc85ef](https://github.com/Slimefun/Slimefun4/assets/41201881/a214c93d-6b46-4f8c-bca9-592f685e7630)

### 📜 Server Log

https://drive.google.com/file/d/1FLo5brK8TwSRoOVZ7aQal5afpsht3Qis/view?usp=sharing the log is too big to put onto pastebin

### 📂 `/error-reports/` folder

none

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

RC - 35 (git 5e901972)
metric modules 29

### 🧭 Other plugins

None

**Comment by ybw0014** [comment]
we dont support rc versions, also it is not a latest rc.

**Comment by JustAHuman-xD** [comment]
Yes

**Comment by JustAHuman-xD** [comment]
We also definitely need what other plugins are on the server and such

**Comment by HeadsShot** [comment]
alright

**Comment by HeadsShot** [comment]
fixed

**Comment by ybw0014** [comment]
this should be closed
