### ISSUE TITLE
griefPrevention and slimefun ( Claim#allowContainers )

### ISSUE THREAD

**Issue by SrMonsterYT** [Slimefun/Slimefun4#4117]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

slimefun is conflicting with griefPrevention, I reported it to griefPrevention and they pointed me to slimefun

image: https://prnt.sc/39yg_jPj5djv

### 📑 Reproduction Steps

have griefPrevention and slimefun, and it starts to lag the server

### 💡 Expected Behavior

no lag

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

https://prnt.sc/PnU70Fb6nTaT

**Comment by J3fftw1** [comment]
This is something they should handle.
We do not know their code thats why we leave it to them to update the dough protection module but since they gave clear instructions i will see if i can change this.

**Comment by SrMonsterYT** [comment]
has this been resolved or does it need testing?

**Comment by J3fftw1** [comment]
This issue is still open so it’s not resolved

**Comment by J3fftw1** [comment]
Solved in #4165
