### ISSUE TITLE
SlimeFun is not compatible with the Mohist side, and the freight node cannot be placed

### ISSUE THREAD

**Issue by wuyf2011** [Slimefun/Slimefun4#4121]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Placing a shipping node on a box still pops up the "Freight node must be placed on a box" prompt, which I think is an incompatibility with the mohist side, and I hope the dev team can fix this

### 📑 Reproduction Steps

1、Place the freight node on the box
2、Cannot be placed, it says "Freight node must be placed on the box"

### 💡 Expected Behavior

Normal should be that the node can be placed normally and function normally

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Slimefun-50f52a2-Beta

**Comment by variananora** [comment]
First of all we don't have that version, use official version and we don't support hybrid servers.

**Comment by wuyf2011** [comment]
> 是的，我们不支持

OK thank you
