### ISSUE TITLE
When researching coal generator, if you leave and rejoin after save, coal generator is un-researched

### ISSUE THREAD

**Issue by yenseo7009** [Slimefun/Slimefun4#4123]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [x] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

when researched coal generator and leave and rejoin, coal generator un-researched

### 📑 Reproduction Steps

1. see coal generator researched
2. leave and rejoin after few minutes
3. you can see coal generator un-researched

### 💡 Expected Behavior

boris expected coal generator research progress loaded properly after rejoining server

### 📷 Screenshots / Videos

![2024-02-08_22 31 54](https://github.com/Slimefun/Slimefun4/assets/97831742/534e4113-33e0-4a5a-a63b-8adc285c473f)
![2024-02-08_22 14 52](https://github.com/Slimefun/Slimefun4/assets/97831742/53dfae7a-68d9-4906-9408-07fd4dd24559)

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

dev-1133

**Comment by yenseo7009** [comment]
up: after
down: before

**Comment by J3fftw1** [comment]
This is the second report of this.

**Comment by WalshyDev** [comment]
Could you provide your plugin list and also logs?

**Comment by yenseo7009** [comment]
Boris not server staff, boris sorry

**Comment by yenseo7009** [comment]
So boris will wait until staffs provide that

**Comment by yenseo7009** [comment]
![image-1](https://github.com/Slimefun/Slimefun4/assets/97831742/7a95459c-8e3a-471f-aa02-32feb9b41184)
![image-2](https://github.com/Slimefun/Slimefun4/assets/97831742/92a0d791-f1b8-4c63-813d-17f8344a09fb)
Here's the plugin list
