### ISSUE TITLE
Item dupe with backpacks and a big player profile

### ISSUE THREAD

**Issue by TwinkleToes777** [Slimefun/Slimefun4#4130]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

An item dupe bug that can be done by opening backpack that was given by another player who has a huge player file (10.1MB), with hundreds of backpacks (599 to be exact)

### 📑 Reproduction Steps

Step 0: Restart server, ensures that other player's backpacks will be unloaded prior to starting the dupe process
Step 1: Open up a backpack of a person who has made a ton of backpacks with possibly a ton of items in them
Step 2: Server lags, after which the backpack will open
Step 3: Take items out of the backpack somewhat quickly, then close the interface or wait for it to refresh on its own
Step 4: Open the backpack again, which opens instantly without any lag assuming the interface was closed
Step 5: The original items that were taken out are both still in the backpack and your inventory, which means that the items were duped

### 💡 Expected Behavior

I expected items to not get duped

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

 This Server uses the following setup of Slimefun:
 Purpur git-Purpur-1985 (MC: 1.19.4)
 Slimefun Dev - 1136
 Metrics-Module #29
 Java 17
 Installed Addons: (8)
   Networks vDEV - 50 (git 3de3c9d6)
   InfinityExpansion vDEV - 144 (git 9da37202)
   SFCalc vDev - 38
   MobCapturer vDEV - 33 (git 6fc26c35)
   HotbarPets vDEV - 38 (git fa6c871d)
   EcoPower vDEV - 5 (git 5c1ecd68)
   FluffyMachines vDEV - 132 (git ccf029ba)
   ExoticGarden vDEV - 78 (git 7f9a5f63)

**Comment by Boomer-1** [comment]
there were some fixes today that could possibly stop this, as you had reported a lag issue. once that new dev version rolls out, please retest on the newer dev version

**Comment by J3fftw1** [comment]
They are on the new build

**Comment by Boomer-1** [comment]
didn't think it had reached blob.builds yet, thanks

**Comment by J3fftw1** [comment]
I can repro this bug very conisitently now.
