### ISSUE TITLE
Slimefun Bugs backpack

### ISSUE THREAD

**Issue by SrMonsterYT** [Slimefun/Slimefun4#4146]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

my server is synchronized by huskSync, there are 2 synchronized servers, the problem is that when I open a backpack on server 1 and come to server 2 and open another backpack I can get the same ID as the backpacks and if someone takes this duplicate backpack or gives it to someone else, you can wait for them to put the items inside and take the items out.

video: https://youtu.be/ytbwYkKDH8M

### 📑 Reproduction Steps

take 2 backpacks
open a backpack on server 1
open another backpack on server 2
and you'll have 2 backpacks with the same ID

### 💡 Expected Behavior

the ID shouldn't just be #1, #2, #3, but codes like #DKAWK3-aD@%6az236

### 📷 Screenshots / Videos

1° https://prnt.sc/5uQ8xTu652oP
2° https://prnt.sc/ZTaEDYRisxEL

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

slimefun and server version: https://prnt.sc/VTGCjLugZ0a6

**Comment by WalshyDev** [comment]
Yeah, this is expected. The data won't be synced. You will need to see if HunkSync can do that. If not, sounds like a Feature Request for HunkSync where you can specify directories.

Storage rewrite will eventually lead to this probably being possible but not near term.

**Comment by SrMonsterYT** [comment]
> Yeah, this is expected. The data won't be synced. You will need to see if HunkSync can do that. If not, sounds like a Feature Request for HunkSync where you can specify directories.
> 
> Storage rewrite will eventually lead to this probably being possible but not near term.

this could be fixed if slimefun had a mysql option
