### ISSUE TITLE
Un-stackable Items

### ISSUE THREAD

**Issue by ghost** [Slimefun/Slimefun4#4152]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

All items prior to updating to 1.20.4 are not stackable with items after updating to 1.20.4.
The only way to fix it that I have found is to either get an admin to replace it for you which is not feasible replacing millions of items.
The other way I have found is that you can place and break head items to fix it, but again it is not feasible placing millions of items.

**There was no resource pack added during this time period**

### 📑 Reproduction Steps

Make 1.20.2 [or any older version] server.
Get few items.
Update server to 1.20.4.
Get the SAME items and figure out those do not stack.

### 💡 Expected Behavior

Items should stack and older items should automatically update.

### 📷 Screenshots / Videos

60 of the old connectors
![image](https://github.com/Slimefun/Slimefun4/assets/97077949/fa74e8b8-cf89-4f38-8201-390ffbd95c3b)
place one of the old items
![image](https://github.com/Slimefun/Slimefun4/assets/97077949/f142986f-6b34-40cc-8e5a-b717c83a48b0)
old item nbt
https://paste.gg/p/anonymous/5021362fa1a74fed8a129c05adb58e16 

new item on breaking
![image](https://github.com/Slimefun/Slimefun4/assets/97077949/7645a3fb-4485-4805-bf17-25bea79340c6)
new item nbt
https://paste.gg/p/anonymous/7b13ded39cd04244a0c41dfe34c3eb3e

### 📜 Server Log

N/A

### 📂 `/error-reports/` folder

N/A

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

This Server uses the following setup of Slimefun:
Purpur git-Purpur-2151 (MC: 1.20.4)
Slimefun Dev - 1141
Metrics-Module #29
Java 18
Installed Addons: (16)
  Networks vDEV - 50 (git 3de3c9d6)
  CrystamaeHistoria vDEV - 81 (git 0c0efa95)
  Gastronomicon vDev - 3
  FastMachines vDev - 9
  FoxyMachines vDEV - 67 (git 0028aa93)
  Quaptics vDEV - 4 (git cbc2e78e)
  SlimeCraft v4.0.0
  SFAdvancements vDev - 5
  HeadLimiter vDev - 19
  SlimeHUD vDEV - 11 (git b6dc2d53)
  SFCalc vDev - 38
  DracFun v2.0.7
  MobCapturer vDEV - 33 (git 6fc26c35)
  SpiritsUnchained vDev - 24
  TranscEndence vDEV - 41 (git 98d7d47e)
  FluffyMachines vDev - 4

### 🧭 Other plugins

N/A

**Comment by J3fftw1** [comment]
Have you not made any changes to plugins in the update?

**Comment by J3fftw1** [comment]
This is due to a change in nbt order in the 1.20.4 update we can’t really do anything about this.
