### ISSUE TITLE
Slimefun furnance giving "Netherite Scrap" after smelting. ItemsAdder

### ISSUE THREAD

**Issue by DarrienZ** [Slimefun/Slimefun4#4161]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

**Slimefun Carbonado Edged Furnance** giving "Netherite Scrap" after smelting custom ore (Vibranium Ore [Using Ancient Debris Material.). Vibranium Ore will spawn at Nether world.

### 📑 Reproduction Steps

Slimefun Carbonado Edged will smelt custom ore into Netherite Scrap.

### 💡 Expected Behavior

It should return back "Vibranium Ore" like other customs ore. Got video.

### 📷 Screenshots / Videos

https://github.com/Slimefun/Slimefun4/assets/108975040/b7e929a8-9748-464a-92dc-4f653068186a

### 📜 Server Log

No Error

### 📂 `/error-reports/` folder

No Error

### 💻 Server Software

Purpur

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Slimefun Dev - 1142

### 🧭 Other plugins

ItemsAdder 3.6.3-beta-13

**Comment by J3fftw1** [comment]
This seems to be an items adder issue.
We didnt change anything about furnaces.
We just modify speed/luck/effeciency
