### ISSUE TITLE
Got banned from discord By BOOMER1 because i used Discord's reply functionality

### ISSUE THREAD

**Issue by mirddes** [Slimefun/Slimefun4#4174]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

honestly it was the most bizarre experience ive had on a discord server.

i tried reaching out to BOOMER1 to appeal to logic and reason, i was ignored and ultimately blocked without consideration.

![image](https://github.com/Slimefun/Slimefun4/assets/13982888/b578b193-f3f6-4b9e-82af-76030dd1d603)

https://www.reddit.com/r/discordapp/comments/xs03ep/you_can_disable_people_from_pinging_you_with_the/

becoming irrate because someone used discord's reply functionality and demanding every single user reconfigure their clients not not ping on reply instead of using documented discord functionality to adequately configure your server in completely unacceptable.

picking fights with autistic users because they didn't ping, they replied.... SMH.... smh...smh....

Love and peace is in my heart; i conducted myself in a respectful manner.

i even left when BOOMER1 started becoming belligerent and warned/muted me, but seemingly got banned for leaving the discord.

i have no words for my lack of comprehension for why this series of events took place.

i dont know what to do in this situation so im submitting a bug report because this is clearly a bug, and not an intended feature.

Slimefun is an amazing mod, works great on bedrock, we're loving it.

Are we chill?

### 📑 Reproduction Steps

hopefully i don't simply get banned for saying "wtf"

### 💡 Expected Behavior

certainly wasn't expecting that behaviour.

was expecting something WAY MORE CHILL.

i certainly did not join slimefun for a battle of egos over some minor detail.

### 📷 Screenshots / Videos

![image](https://github.com/Slimefun/Slimefun4/assets/13982888/ef9cd553-4989-4cae-bf57-1a2b667604da)

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Slimefun4-RC

### 🧭 Other plugins

Love and peace is in my heart; i conducted myself in a respectful manner.

i even left when BOOMER1 started becoming belligerent and warned/muted me, but seemingly got banned for leaving the discord.

**Comment by SchnTgaiSpock** [comment]
💀

**Comment by J3fftw1** [comment]
I have locked this issue.
This is not the place to appeal bans, please contact one of the admins on discord.

you got banned because of pinging a staff member multiple times.
We have discord rules which everyone should follow. By saying that we demand every user to change their discord configuration you are already telling me you will ping people again when it’s against the rules. You can follow the rules of the server or you get banned it’s that easy. We don’t have to welcome every single person.

if you do feel like appealing please contact:
Walshydev 
Or
sfiguz7
