### ISSUE TITLE
The soulbound rune does not work due to an interference with the soulbound of advanced enchantments.

### ISSUE THREAD

**Issue by AlexLG2908** [Slimefun/Slimefun4#4176]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [x] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When I use the soulbound rune on an item, it doesn't work, it just stays on the ground along with the item. I have asked in other places about what it could be and they mention that it is a problem with the soulbound of the Advanced Enchantments.

### 📑 Reproduction Steps

.

### 💡 Expected Behavior

The rune must be applied when casting it together with the item

### 📷 Screenshots / Videos

https://youtu.be/Fi467M1q_NY

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.17.x

### ⭐ Slimefun version

![image](https://github.com/Slimefun/Slimefun4/assets/167010522/7bfa86c4-9e55-4f46-be30-7c3f031c45e9)

### 🧭 Other plugins

Advanced Enchantments v9.6.17

**Comment by Boomer-1** [comment]
this has been brought up a couple times with AE. 
https://github.com/GC-spigot/AdvancedEnchantments/issues/4196
https://github.com/GC-spigot/AdvancedEnchantments/issues/3794

**Comment by Boomer-1** [comment]
According to AE this has been fixed.

https://github.com/GC-spigot/AdvancedEnchantments/issues/4196
