### ISSUE TITLE
ChargingBench can recharge muliple stackable items.

### ISSUE THREAD

**Issue by Intybyte** [Slimefun/Slimefun4#4183]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

To test this out I created a simple addon with a stackable item as the tool that needs to be recharged, I put a stack into the ChargingBench and it recharged them.

### 📑 Reproduction Steps

1. Get yourself a stack of stackable rechargable items
2. Throw them into the charging bench
3. A stack worth of these items will recharge, effectively making charging bench +3200% more efficient

### 💡 Expected Behavior

1. Don't recharge the ItemStack

### 📷 Screenshots / Videos

https://github.com/Slimefun/Slimefun4/assets/61906290/10dfdf62-072e-43a4-b7b9-3ebbb829916a

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Dev - 1145

### 🧭 Other plugins

Any addon, fixing this may allow addon creators more freedom over their Rechargeable items

**Comment by Boomer-1** [comment]
confirmed

**Comment by Boomer-1** [comment]
could be tied to #4212

**Comment by mcchampions** [comment]
> could be tied to #4212

No.and you may add "?"
