### ISSUE TITLE
Soulbound items are wiped out of inventory when you die and leave server without respawn .

### ISSUE THREAD

**Issue by rabin69** [Slimefun/Slimefun4#4192]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

when i soulbound my items and i was fighting for pvp and my lights went off oviously i died  and i didnt open the game that day when lights came ,thought my items are soulbound it will remain in my inventory but when i open the game next day server restarted and whole inventory wiped out . 

### 📑 Reproduction Steps

1.join server 
2.make items soulbound 
3.just do /kill  yourself 
4.kick yourself from server without pressing respawn
5.restart the server 
6. you will find that ur inventory is wiped with your soulbound items .

### 💡 Expected Behavior

The expected behaviour is that it should not wipe out the inventory so to prevent it you should add something that should store the payers soulbound items data and even if the server restart the data shouldd be there to prevent the loss of soulbound inventory .

### 📷 Screenshots / Videos

![image](https://github.com/Slimefun/Slimefun4/assets/109132686/110c946b-0b54-4aa5-b5b1-eb23387f2575)

### 📜 Server Log

no such problem with logs

### 📂 `/error-reports/` folder

no such error 

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

recent version 

### 🧭 Other plugins

no other plugins

**Comment by JustAHuman-xD** [comment]
Duplicate #3774
