### ISSUE TITLE
You can disenchant items such as the reinforced armor and move the enchantments from it onto netherite armor.

### ISSUE THREAD

**Issue by RadiantUwU** [Slimefun/Slimefun4#4201]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I have seen others use this to get completely broken armor which cannot be fixed without modifying the plugin itself.
This bug involves the disenchanting table and auto enchanter.
I'm a server operator on a public minecraft server and having prot 9 netherite armor shouldn't be acceptable.

### 📑 Reproduction Steps

Disenchant Reinforced armor
Enchant netherite armor

### 💡 Expected Behavior

Disallow disenchanting any slimefun items.

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

![image](https://github.com/Slimefun/Slimefun4/assets/69520693/dd398093-915b-48a6-8044-041c8965dca5)

**Comment by ybw0014** [comment]
either disable them or alter the config. not a bug

**Comment by RadiantUwU** [comment]
This issue is resolved by disabling the "allow disenchanting" here
![image](https://github.com/Slimefun/Slimefun4/assets/69520693/8c987a5d-e2e0-4fe9-aeb0-b96c9ccc3017)
