### ISSUE TITLE
Multitools don't work

### ISSUE THREAD

**Issue by jasonhmtang** [Slimefun/Slimefun4#4203]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Multitools cannot switch their mode and do not perform their functions

### 📑 Reproduction Steps

1. Acquire a multitool (I've tested Duralium and Carbanado so far)
2. Charge it (I used a charging bench)
3. Attempt to use it by shift right clicking and right clicking (Doesn't work)

### 💡 Expected Behavior

I expected for it to work as intended

### 📷 Screenshots / Videos

https://github.com/Slimefun/Slimefun4/assets/36118691/982d5236-c91c-4b09-99c5-96a16fcc2445

I am attempting to right click in this video (my right click button does work)

### 📜 Server Log

https://pastebin.com/CBW4KZHm#google_vignette

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

![Screenshot 2024-06-08 130357](https://github.com/Slimefun/Slimefun4/assets/36118691/3b4a1ac6-86e8-4b28-b755-1a3a55d31288)

**Comment by Boomer-1** [comment]
it works fine thru Slimefun dev 1145. something in the last 2 updates may have broken it

**Comment by Boomer-1** [comment]
looks like #4122 broke it

**Comment by jasonhmtang** [comment]
So what exactly do I do to fix the problem?

**Comment by Boomer-1** [comment]
download version 1148 that just pushed out
