### ISSUE TITLE
WDFKISTHAT!

### ISSUE THREAD

**Issue by good344654** [Slimefun/Slimefun4#4204]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

we can change name to clean nbt,then we can use "雷电法杖",it's good

### 📑 Reproduction Steps

we can change name to clean nbt,then we can use "雷电法杖",it's good

### 💡 Expected Behavior

we can change name to clean nbt,then we can use "雷电法杖",it's good

### 📷 Screenshots / Videos

nothing

### 📜 Server Log

https://idon'thave!/

### 📂 `/error-reports/` folder

https://idon'thave!/

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

new version

### 🧭 Other plugins

idk

**Comment by Boomer-1** [comment]
you've not really said anything, nor provided any actual bug issue. closing as invalid
