### ISSUE TITLE
Slimefun Items can be renamed in the anvil,And no longer limited by the listener

### ISSUE THREAD

**Issue by pingguomc** [Slimefun/Slimefun4#4205]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Use the quick click device to click on the anvil and set the name to "$#% y # # # $_% # yy # $_ # $_c # $_% _c% _% c% c% c% _% c% c% c% c"
After a series of errors, there is a probability that the item has been renamed, and similar usage restrictions are no longer in effect.
But for example, lightning can still be used.you can see the video

 https://www.bilibili.com/video/BV1Ei421i7B6/?share_source=copy_web&vd_source=0c579ca481e99907fda9d05eb4ec333b

### 📑 Reproduction Steps

Use the quick click device to click on the anvil and set the name to "$#% y # # # $_% # yy # $_ # $_c # $_% _c% _% c% c% c% _% c% c% c% c"
After a series of errors, there is a probability that the item has been renamed, and similar usage restrictions are no longer in effect.
But for example, lightning can still be used.you can see the video

 https://www.bilibili.com/video/BV1Ei421i7B6/?share_source=copy_web&vd_source=0c579ca481e99907fda9d05eb4ec333b

### 💡 Expected Behavior

The item will no longer be renamed

### 📷 Screenshots / Videos

https://github.com/Slimefun/Slimefun4/assets/141195321/9caaa29a-5e4c-4057-9edc-8a132f1019bb

### 📜 Server Log

Only "You sent too many packets"

### 📂 `/error-reports/` folder

noting

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.19.x

### ⭐ Slimefun version

![QQ图片20240609230307](https://github.com/Slimefun/Slimefun4/assets/141195321/cc70bb6c-3715-4cd8-a51a-e9df003eff2f)

### 🧭 Other plugins

AntiBuild、BossShopPro、 Citizens、 *CommandNPC、
CoreProtect、Essentials、 EssentialsSpawn、 floodgate、
FluffyMachines、Geyser Spigot、GroupManager、 Hibernate、
LuckPerms、Multiverse Core、PlaceholderAPI、 PowerBoard、
ProtocolLib、SkinsRestorer、 Slimefun、 TrChat、
UltimateAutoRestart、VoidGen、 WorldEdit

**Comment by Boomer-1** [comment]
You are not using an official version. You need to talk to whomever made this one

**Comment by pingguomc** [comment]
I don't know who I should tell this to, maybe I can switch to the latest version

**Comment by Boomer-1** [comment]
this is the Chineese fork. it needs to be reported to them. https://github.com/SlimefunGuguProject/Slimefun4/issues

**Comment by pingguomc** [comment]
Thank you very much
