### ISSUE TITLE
Oil pumps not working and also scuba helmet recipe doesn't work

### ISSUE THREAD

**Issue by Istvan474** [Slimefun/Slimefun4#4210]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I am trying to craft a scuba helmet and it doesn't work. Oil pumps also do not work, they get stuck on 26s and don't do anything

### 📑 Reproduction Steps

Try crafting scuba helmet and try using oil pumps

### 💡 Expected Behavior

I was expecting for the recipe and for oil pumps to work properly.

### 📷 Screenshots / Videos

![image](https://github.com/Slimefun/Slimefun4/assets/55950760/ae560fe0-71fd-4c7a-9723-a09981335504)
![image](https://github.com/Slimefun/Slimefun4/assets/55950760/cc3dd6df-9164-40e0-8841-9077f1e512d2)

### 📜 Server Log

https://pastebin.com/jbsk13wU

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Build 1148

**Comment by ybw0014** [comment]
1. Wrong recipe.
2. Did u power it? this doesn't look like a bug but an user error.

**Comment by Istvan474** [comment]
what do you mean wrong recipe?

> 1. Wrong recipe.
> 2. Did u power it? this doesn't look like a bug but an user error.

**Comment by Istvan474** [comment]
thats literally the correct recipe and the recipe it shows in the guide

**Comment by Boomer-1** [comment]
the picture you provided says it isn't powered.if its stuck at zero that means no power.also for scuba helmet you're probably missing the glass pane im the recipe thats shown in the guide

**Comment by Istvan474** [comment]
i fixed the oil pump issue and ty for that but there is no glass shown in the scuba recipe guide?

**Comment by Istvan474** [comment]
nvm, just seen it. thanks!
