### ISSUE TITLE
Error stack and some incorrect use of variables in the code

### ISSUE THREAD

**Issue by mcchampions** [Slimefun/Slimefun4#4211]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

from [SlimefunGuguProject/Slimefun4#912](https://github.com/SlimefunGuguProject/Slimefun4/issues/912),This fork does not change the code related to this issue.
The following is machine translation:
Original content:For certain items, slimefun will directly make them stack, even if they have different slimefun IDs

Specific items: Same name, same lore, but different slimefun ID (i.e. NBT exists differently, you don't need to consider the full NBT to fix the bug, just consider the slimefun ID)

<details>
<summary>Problem tracing</summary>

https://github.com/Slimefun/Slimefun4/blob/226af9be61d1bfc582cbe235909579b9f4f605cd/src/main/java/me/mrCookieSlime/Slimefun/api/inventory/DirtyChestMenu.java#L178-L183

https://github.com/Slimefun/Slimefun4/blob/226af9be61d1bfc582cbe235909579b9f4f605cd/src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java#L306-L322

https://github.com/Slimefun/Slimefun4/blob/226af9be61d1bfc582cbe235909579b9f4f605cd/src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java#L348-L387

Herein lies the problem——`equalsItemMeta`method

https://github.com/Slimefun/Slimefun4/blob/226af9be61d1bfc582cbe235909579b9f4f605cd/src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java#L459-L501

**Here's a thing to say about the `checkCustomModelData` variable in this method called `bypassCustomModelCheck`, which actually ignores checking, so it should be reversed when it is passed in, but it is not reversed when it is passed in**

This code checks Lore & Name,The problem arises

https://github.com/Slimefun/Slimefun4/blob/226af9be61d1bfc582cbe235909579b9f4f605cd/src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java#L364-L386

Check here to see if you have overlooked a situation where it is a slimefun item and the two items are not the same slimefun item

https://github.com/Slimefun/Slimefun4/blob/226af9be61d1bfc582cbe235909579b9f4f605cd/src/main/java/io/github/thebusybiscuit/slimefun4/utils/SlimefunUtils.java#L358-L378

The variable name is `sfItem`, which means that `sfItem` is a slimefun item by default. In the case of `id==null` (i.e. the item is not a Slimefun item), it is't necessary to continue to determine if it is necessary to return false if one is a Slimefun item and the other is not.

Also, since `sfitem.hasItemMeta()` has been judged
Why should the variable of this ItemMeta be named `possibleSfItemMeta`, and the same goes for `possibleItemId`

In a word,maybe change like:
```java
if (id != null && id.equals(possibleItemId)) { 
                     Debug.log(TestCase.CARGO_INPUT_TESTING, "  Item IDs matched!"); 
  
                     /* 
                      * PR #3417 
                      * 
                      * Some items can't rely on just IDs matching and will implement Distinctive Item 
                      * in which case we want to use the method provided to compare 
                      */ 
                     Optional<DistinctiveItem> optionalDistinctive = getDistinctiveItem(id); 
                     if (optionalDistinctive.isPresent()) { 
                         return optionalDistinctive.get().canStack(possibleSfItemMeta, itemMeta); 
                     } 
                     return true; 
                 }
                 return false;
```
</details>

In a word,there is a wrong check and some incorrect use of variables(or wrong name?)

### 📑 Reproduction Steps

Put different slimefun items with the same lore and name into the charging bench
And then they stacks.

### 💡 Expected Behavior

they shouldn't stack

### 📷 Screenshots / Videos

https://github.com/Slimefun/Slimefun4/assets/95963344/2545a8bb-da13-4155-ae34-713b4e28a149

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

latest

**Comment by Boomer-1** [comment]
charging bench is a duplicate issue. also please report issues on seperate report. also we aren't responsible for any forks of slimefun.

**Comment by mcchampions** [comment]
> charging bench is a duplicate issue. also please report issues on seperate report. also we aren't responsible for any forks of slimefun.

No,Actually, I'm talking about the problem with the charging bench ,  but I found a lot of errors in this logic in the process.and the problem was found on this branch, but the branch doesn't change the code, so it's safe to assume that the problem works on the main branch as well

**Comment by mcchampions** [comment]
> charging bench is a duplicate issue. also please report issues on seperate report. also we aren't responsible for any forks of slimefun.

No,Actually, I'm talking about the problem with the charging bench , but I found a lot of errors in this logic in the process.and the problem was found on this branch, but the branch doesn't change the code, so it's safe to assume that the problem works on the main branch as well(In fact, it does)

**Comment by Boomer-1** [comment]
again, it's a duplicate issue. it's already been reported, and it's never safe to assume a fork doesn't affect code.

**Comment by mcchampions** [comment]
> again, it's a duplicate issue. it's already been reported, and it's never safe to assume a fork doesn't affect code.
Yes,It's reported in other fork,but it isn't reported in here.And,in fact,is does't affect code,this question exists

**Comment by mcchampions** [comment]
> > again, it's a duplicate issue. it's already been reported, and it's never safe to assume a fork doesn't affect code.
> 
> Yes,It's reported in other fork,but it isn't reported in here.And,in fact,is does't affect code,this question exists

In fact,this issue is not quite the same as that one

**Comment by Boomer-1** [comment]
it is reported here. #4183

**Comment by mcchampions** [comment]
> it is reported here. #4183

Emm.no same

**Comment by mcchampions** [comment]
> it is reported here. #4183

Emm.no same

**Comment by Boomer-1** [comment]
you said you have items stacking in the charging bench on the official version. that was already reported in 4183. this is closed. move on

**Comment by JustAHuman-xD** [comment]
Boomer he is meaning different issues, it sounds like some other menus/methods combine slimefun items that shouldn't combine like how cargo does

**Comment by balugaq** [comment]
It's completely different, and the charging bench is just a convenient demonstration machine, not just the charging bench with this issue.

**Comment by Boomer-1** [comment]
then as i said, open a seperate issue

**Comment by Boomer-1** [comment]
this doesn't have anything to do with cargo

**Comment by mcchampions** [comment]
> then as i said, open a seperate issue

If you read it carefully, you will see that this is not the same.

**Comment by Boomer-1** [comment]
if the cause of the other issue is what you identified then it's not. open a seperate issue not related to the charging bench

**Comment by mcchampions** [comment]
> 如果另一个问题的原因是您确定的，那么它是一样的。打开一个与充电台无关的单独问题
OK

**Comment by mcchampions** [comment]
> if the cause of the other issue is what you identified then it's the same. open a seperate issue not related to the charging bench

That's not the cause of the problem, it's talking about items that can't be stacked but stacked,but i will open a new issue

**Comment by Boomer-1** [comment]
there's already an open pr to fix it

**Comment by mcchampions** [comment]
> 已经有一个开放的 PR 来修复它

Not really

**Comment by mcchampions** [comment]
> 已经有一个开放的 PR 来修复它

This issue should have just been discovered by now

**Comment by balugaq** [comment]
That PR maybe just fix the charging bench. But it is SlimefunUtils's wrong in fact.

**Comment by Boomer-1** [comment]
as part of the review process the dev's can look into it to see if the root cause is addressed in the PR or if other changes need to be made to look at #4212

**Comment by mcchampions** [comment]
I am in China and it is 0 o'clock. I originally opened this issue for convenience, but it seems inconvenient. Also, this issue comes with a detailed solution and traceability process
