### ISSUE TITLE
Slimefun4 not working on aternos spiggot 1.21

### ISSUE THREAD

**Issue by wartuki** [Slimefun/Slimefun4#4215]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

when i tried using any of the items like the backpack it would just place and not open and the book didnt work nothing work so i tried commands and everytime i got an error and i tried reinstalling but that did nothing

### 📑 Reproduction Steps

1 have aternos spiggot 1.21
2 have slimefun4 [1448] installed
3 try using any commands/item

### 💡 Expected Behavior

a fixed version so i can play in 1.21

### 📷 Screenshots / Videos

![afbeelding_2024-06-28_135023428](https://github.com/Slimefun/Slimefun4/assets/73833110/5d08e024-4d6d-4836-acca-c14884677235)
i dont think thats supposed to happen

### 📜 Server Log

_An internal error occured while attempting to perform this command_

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Slimefun4 1448

**Comment by Boomer-1** [comment]
slimefun does not support 1.21 yet. we're waiting on an issue with spigot to be resolved for 1.20.5. once that is done, we will have a 1.21 version.
