### ISSUE TITLE
Support to Folia

### ISSUE THREAD

**Issue by StarSunSky** [Slimefun/Slimefun4#4217]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Hello! I'm a fan of Slimefun and have been enjoying its features on my Minecraft server. Recently, I've migrated my server to use the Folia server core, known for its efficient multithreading capabilities that help maintain low-cost server setups. I'm curious if there are any plans to support Folia with Slimefun. I couldn't find much information on compatible plugins for Folia, and I'm eager to know if there have been any updates from the Slimefun team regarding this. The project link for Folia is here: https://github.com/PaperMC/Folia. Looking forward to your response!

### 📑 Reproduction Steps

Nothing

### 💡 Expected Behavior

I hope that Slimefun can be compatible with Folia!

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Future versions

**Comment by Boomer-1** [comment]
Suggestions would go on discord. Core devs have said there won't be plans to support folia
