### ISSUE TITLE
how do i find the recipe files?

### ISSUE THREAD

**Issue by cybersteve547** [Slimefun/Slimefun4#4221]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I downloaded the official version from the new build site [Blob Builds](https://blob.build/).
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

i wanna make a game with sf stuff so if someone could tell me how to find the recipe files then thx

### 📑 Reproduction Steps

required

### 💡 Expected Behavior

required

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

required

**Comment by cybersteve547** [comment]
ah how do i change lables

**Comment by ybw0014** [comment]
Issues is a place to report bugs. To get help with using Slimefun, please join our discord server.
