### ISSUE TITLE
The plugin does not work in 1.21.1 on Aternos.

### ISSUE THREAD

**Issue by R3alo** [Slimefun/Slimefun4#4226]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I downloaded the official version from the new build site [Blob Builds](https://blob.build/).
- [x] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Your plugin on Aternos says it supports 1.21.1 but then it is red when i do /pl.

### 📑 Reproduction Steps

1. Make server with 1.21.1. Spigot/Bukkit
2. Then install Slimefun 4
3. Launch server
4. And then the plugin wont work

### 💡 Expected Behavior

I expected for it to work.

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Slimefun4-1149

**Comment by Lamby777** [comment]
> Your plugin on Aternos says it supports 1.21.1 but then it is red when i do /pl.

It doesn't support 1.20.5 or above yet from what I can tell. https://github.com/Slimefun/Slimefun4/pull/4186

**Comment by Mrs-Feathers** [comment]
i can confirm this bug.

here's hopeing for 1.20 and 1.21 support soon!

**Comment by Mrs-Feathers** [comment]
btw just wanted to let you know that you listed 1.20.x minecraft version on the bug info sheet when in the title you say 1.21! cheers.

**Comment by Boomer-1** [comment]
slimefun does not officially support 1.21 yet
