### ISSUE TITLE
1.21 support 

### ISSUE THREAD

**Issue by SomeTroller77** [Slimefun/Slimefun4#4254]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I downloaded the official version from the new build site [Blob Builds](https://blob.build/).
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

When will the plugin be updated for 1.21

### 📑 Reproduction Steps

the title

### 💡 Expected Behavior

title

### 💻 Server Software

Paper

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

4

**Comment by Erlspramana** [comment]
:( when

**Comment by Outfit8TSB** [comment]
is already going on rn. #4248 (Fix: #4251 & #4253)

**Comment by Boomer-1** [comment]
this does not belong here. this is for bug reports. you can see the status on discord or thru the pr's
