### ISSUE TITLE
Vanilla Enchaments?

### ISSUE THREAD

**Issue by Bard02** [Slimefun/Slimefun4#4257]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I downloaded the official version from the new build site [Blob Builds](https://blob.build/).
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

HELLO! so this isnt really an issue just more of a question

im wondering if there is an addon or a config thing i can change to allow vanilla enchantments to be used on the silmefun stuff 

### 📑 Reproduction Steps

just a question

### 💡 Expected Behavior

i dont know what to do 

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

![SLIME FUN](https://github.com/user-attachments/assets/aee22641-a1d1-4c95-b97d-4d7b3a362949)

**Comment by Boomer-1** [comment]
please ask questions on the discord. this is for reporting actual issues. thank you
