### ISSUE TITLE
Aternos 1.21.3 doesn't work

### ISSUE THREAD

**Issue by Adambuild** [Slimefun/Slimefun4#4269]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I downloaded the official version from the new build site [Blob Builds](https://blob.build/).
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

I have proble with Slimefun plug-in on Aternost on 1.21.3 minecraft java When i start server everything looks like it works byt when i join I didn't find book in inventory and /slimefun doesn't work. I tried it on Spingot/bukkit and Paper/bukkit. Do anyone know why?

### 📑 Reproduction Steps

1. start server
2. Join server
3. Look in inventory don't find book
4. Try comand /slimefun

### 💡 Expected Behavior

To find slimefun book or get it from comand.

### 📜 Server Log

https://pastebin.com/wwKy6XMN

### 💻 Server Software

Other (please specify in your description)

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Slimefun 4 1156 and 1157

### 🧭 Other plugins

nothing

**Comment by Boomer-1** [comment]
slimefun has not released an official version for 1.21. Aternos has mis marked that by mistake. closing this  as invalid.
