### ISSUE TITLE
Slimefun blocks going to vannila blocks

### ISSUE THREAD

**Issue by masood151117** [Slimefun/Slimefun4#4273]
### ❗ Checklist

- [X] I am using the official english version of Slimefun and did not modify the jar.
- [X] I downloaded the official version from the new build site [Blob Builds](https://blob.build/).
- [X] I am using an up to date "DEV" (not "RC") version of Slimefun.
- [X] I am aware that issues related to Slimefun addons need to be reported on their bug trackers and not here.
- [X] I searched for similar open issues and could not find an existing bug report on this.

### 📍 Description

Every day, many items on my server are converted to vanilla blocks. Don't you want to do something about this? This happens mostly when chunks are unloaded and reloaded Please do something, I can't wait for version 1.21 to be released, and then you will come up with an idea to fix the problem of blocks becoming vanilla.

### 📑 Reproduction Steps

.

### 💡 Expected Behavior

.

### 📜 Server Log

.

### 📂 `/error-reports/` folder

.

### 💻 Server Software

Spigot

### 🎮 Minecraft Version

1.20.x

### ⭐ Slimefun version

Latest Dev Build - Autoupdate

### 🧭 Other plugins

.

**Comment by masood151117** [comment]
At least introduce a way so that I can control these events or identify where the block slime fan was before. Every day, many players report and complain to me about Slimefun blocks becoming normal blocks

**Comment by masood151117** [comment]
I only started my server a week ago

**Comment by Boomer-1** [comment]
closing as this is a duplicate.
