### ISSUE TITLE
Grappling Hook turns into lead. 

### ISSUE THREAD

**Issue by paperbenni** [Slimefun/Slimefun4#677]
I have an issue with the grappling hook item. Since it's actually just a lead with a different name, it can still be used on animals. When I click on an animal and, the grappling hook just turns into a regular lead instead of the way more expensive hook. I hope the fact that I didn't include any screenshots doesn't matter in this case, because the problem is pretty simple. event.setCanceled(true) at the right spot should do it.

**Comment by paperbenni** [comment]
Why did you close this? So is it going to be fixed?

**Comment by VoidAngel** [comment]
TheBusyBiscuit usually closes reports that do not follow the correct format. It may not seem like it to the average person, but in plugin development the details are _crucial_. Plus, if you want people to put it the work to fix it, its only fair that you put in the work to report it correctly.
But really I'm not sure, it could have been closed for any number of reasons. If I were you I would simply resubmit using the correct format and see if it goes through.
