### ISSUE TITLE
Cargo Bug in 1.13

### ISSUE THREAD

**Issue by Ephilem** [Slimefun/Slimefun4#772]
## Description 
Cargo don't work with this version : https://github.com/TheBusyBiscuit/Slimefun4/pull/756 (pull update)

## Server Log
In the video

## Evidence / Proof (Required)
Video : https://youtu.be/ro-QnS9WeM4

## Environment (Required)
Video.

**Comment by MineCraftael** [comment]
And slimefun will be released one day officially?

**Comment by Poslovitch** [comment]
See https://github.com/TheBusyBiscuit/Slimefun4/issues/769

**Comment by PrzemoVi** [comment]
https://github.com/TheBusyBiscuit/Slimefun4/pull/756
